### ISSUE TITLE
Install logs don't account for mandatoryInstallMode

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/cordova-plugin-code-push#100]
The logs that are outputted by `sync` when an update is installed only takes into account the `installMode` property, and not the new `mandatoryInstallMode` property. For example, if you install an mandatory update using `InstallMode.ON_NEXT_RESUME`, but the `installMode` property was set to `InstallMode.ON_NEXT_RESTART`, the plugin would incorrectly log "Update is installed and will be run on the next app restart." after installing the mandatory update. The [install logic](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/www/codePush.ts#L304) makes it clear why this behavior exists.

This isn't a hugely critical bug, but these logs are pretty important for users to diagnose their update experience, so making it accurate is important. I actually got a bit confused by this when dogfooding the new `mandatoryInstallMode` property :)

**Comment by geof90** [comment]
Closed via #102
