### ISSUE TITLE
cordova-plugin-code-push@1.7.0-beta Cannot call "reportStatus" on undefined

### ISSUE THREAD

**Issue by chris-vaszauskas** [Microsoft/cordova-plugin-code-push#103]
When I try to upload a build to Android, the update downloads successfully and running `codePush.restartApplication()` loads from the new code. However, when I force kill the app and open it again, I get a console error that says `Uncaught TypeError: Cannot read property 'reportStatus' of undefined` before any of my app code runs. I'm assuming this is the `reportStatus` function on the `codePush` object. My hunch is that the reportStatus function is getting called before the Cordova `deviceready` event when the codePush object becomes available.

When I downgrade to `cordova-plugin-code-push@1.6.0-beta`, I don't get the error.

I'm using the Crosswalk plugin at version 1.6.0.

**Comment by lostintangent** [comment]
@chris-vaszauskas Interesting, we haven't seen this issue yet. Let me investigate this right now and get back to you. It's extremely helpful to know that downgrading to `v1.6.0` resolves it, and we'll make sure to try using CrossWalk in the app. Thanks for reporting the issue and sorry for the inconvenience.

**Comment by lostintangent** [comment]
This issue has been fixed and we'll be releasing it to NPM later this evening. Thanks so much for submitting this!

**Comment by chris-vaszauskas** [comment]
Thanks! That was fast!
