### ISSUE TITLE
Application Error: "The connection to the server was unsuccessful. (file:///android_asset/www/index.html)"

### ISSUE THREAD

**Issue by plougsgaard** [Microsoft/cordova-plugin-code-push#111]
> **Application Error**
> The connection to the server was unsuccessful. (file:///android_asset/www/index.html)

I'm getting this error *only* the first time the app runs after being installed. Subsequent runs are fine. 

I run 

`codePush.sync(null, { updateDialog: false, installMode: InstallMode.IMMEDIATE })` 

on `deviceready` and `resume`. 

### Environment

```
λ ~ → node -v
v5.7.0
λ ~ → code-push -v
1.10.0-beta
λ ~ → cordova -v
6.1.1
```

*Edit: I've only experienced this on Android - not on iOS.*

### Flavor screenshot

![screenshot_20160429-150449](https://cloud.githubusercontent.com/assets/487223/14917253/6cc48788-0e1e-11e6-8ac7-5c104919d6d4.png)

**Comment by lostintangent** [comment]
I believe that error usually indicates that the app took too long to startup and isn't using a splash screen. Are you already using a splash screen? If you remove the CodePush plugin, does this error go away? We try to make sure we have as little impact on app start as possible, but it's possible that something is going on here.

Also, could you list our the Cordova plugins you app is using and their versions? Thanks!

**Comment by plougsgaard** [comment]
@lostintangent 

### Plugins

```
→ cordova plugin ls
code-push 1.8.0-beta "CodePushAcquisition"
cordova-plugin-code-push 1.7.0-beta "CodePush"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-crosswalk-webview 1.6.1 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-device-motion 1.2.1 "Device Motion"
cordova-plugin-device-orientation 1.0.3 "Device Orientation"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
```

### Symptoms

- Error occurs after 3-4 seconds
- The app uses a splash screen
- Error goes away when removing the plugin

I'll try and see what happens if I don't call sync too

**Comment by lostintangent** [comment]
Yeah that definitely sounds like an app start timeout. If you could add the plugin back and just not call sync, and see if you get the error, that would be hugely helpful. In the meantime, we'll take a look at this and see if we can repro it with the same plugins. Thanks for reporting this!

**Comment by lostintangent** [comment]
Two other things:

1. Could you let us know the version of Cordova Android you're using by running `cordova platform ls`
2. Does your `config.xml` already contain the following element:

```xml
<preference name="SplashScreenDelay" value="3000" />
```

If so, what is the value? If you update it to a larger value (e.g. 7000, 10000), does this error go away?

**Comment by plougsgaard** [comment]
1. `cordova platform ls => android 5.1.1`
2. It does not contain the delay.

I'm now home without access to my previous testing device. My own device (Nexus 5) is a year or two quicker than the device I got the error on which (I think) supports the theory of the *app start timeout*.

When I get back to the office I'll try experimenting with adding a delay on the (slower) testing device. Supposing it is due to a timeout, is there (or will there be) a solid solution for that?

And thanks by the way for the very quick help/feedback!

**Comment by lostintangent** [comment]
If it's a timeout issue, we will definitely make sure to find a solution for that :) We haven't seen any perf issues on startup before, so I'm assuming that it may be due to some interop with another plugin or some other issue. We'll investigate this today and will hopefully be able to repro it. Stay tuned!

**Comment by lostintangent** [comment]
@plougsgaard Have you been able to continue reproing this issue? (I noticed your update and was just curious)

**Comment by plougsgaard** [comment]
@lostintangent I haven't been able to reproduce the issue at all, though not for lack of trying. The only change I did was set the mode to `InstallMode.ON_NEXT_RESUME`.

I'll close the issue seeing as it hasn't happened in a while. If I manage to get it failing again I'll try to see if I can provide some more details and maybe reopen this one. Cheers!

**Comment by plougsgaard** [comment]
@lostintangent 

I just managed to reproduce it again!

1. Publish APK v1.0.0 to (beta) Play Store 
2. Publish mandatory update targeting `"^1.0.0"`
3. Install the beta and run the app
4. Publish APK v1.0.1 to (beta) Play Store
5. Install the beta and run the app - it now breaks with the Application Error from above

I've included the log from my test device below or at least the parts pertaining to the process id **18103**:

```
05-04 13:23:36.930   777 10374 I ActivityManager: Start proc 18103:com.example.app/u0a184 for activity com.example.app/.MainActivity
05-04 13:23:36.939  1825  1825 I MicroDetector: Keeping mic open: false
05-04 13:23:36.939  1825  1825 I MicrophoneInputStream: mic_close com.google.android.apps.gsa.speech.audio.ah@7bd9d83
05-04 13:23:36.939  1825 18065 I DeviceStateChecker: DeviceStateChecker cancelled
05-04 13:23:36.939  1825 18018 E AudioRecord-JNI: Error -4 during AudioRecord native read
05-04 13:23:36.985   203 18068 D audio_hw_primary: disable_audio_route: reset and update mixer path: audio-record
05-04 13:23:36.985   203 18068 D audio_hw_primary: disable_snd_device: snd_device(61: voice-rec-mic)
05-04 13:23:36.991  1825 18066 I MicroRecognitionRunner: Detection finished
05-04 13:23:36.991  1825  7361 I MicroRecognitionRunner: Stopping hotword detection.
05-04 13:23:37.051 18103 18103 D XWalkLib: Pre init xwalk core in com.example.app.MainActivity
05-04 13:23:37.058 18103 18103 D XWalkLib: Reserve class class org.xwalk.core.XWalkPreferences to com.example.app.MainActivity
05-04 13:23:37.058 18103 18103 D XWalkLib: Reserve method setValue to com.example.app.MainActivity
05-04 13:23:37.059 18103 18103 D XWalkLib: Reserve class class org.xwalk.core.XWalkPreferences to com.example.app.MainActivity
05-04 13:23:37.059 18103 18103 D XWalkLib: Reserve method setValue to com.example.app.MainActivity
05-04 13:23:37.059 18103 18103 D XWalkLib: Reserve class class org.xwalk.core.XWalkPreferences to com.example.app.MainActivity
05-04 13:23:37.059 18103 18103 D XWalkLib: Reserve method setValue to com.example.app.MainActivity
05-04 13:23:37.063 18103 18103 D XWalkLib: Reserve object class org.crosswalk.engine.XWalkCordovaView to com.example.app.MainActivity
05-04 13:23:37.072 18103 18103 D XWalkLib: Reserve object class org.crosswalk.engine.XWalkCordovaResourceClient to com.example.app.MainActivity
05-04 13:23:37.072 18103 18103 D XWalkLib: Reserve method setResourceClient to com.example.app.MainActivity
05-04 13:23:37.073 18103 18103 D XWalkLib: Reserve object class org.crosswalk.engine.XWalkCordovaUiClient to com.example.app.MainActivity
05-04 13:23:37.073 18103 18103 D XWalkLib: Reserve method setUIClient to com.example.app.MainActivity
05-04 13:23:37.131 18103 18121 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
05-04 13:23:37.182 18103 18103 V StatusBar: StatusBar: initialization
05-04 13:23:37.290 18103 18103 D XWalkActivity: Initialize by XWalkActivity
05-04 13:23:37.290 18103 18103 D XWalkLib: DecompressTask started
05-04 13:23:37.291 18103 18103 W ResourceType: No package identifier when getting value for resource number 0x00000000
05-04 13:23:37.307 18103 18121 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
05-04 13:23:37.309 18103 18121 I OpenGLRenderer: Initialized EGL, version 1.4
05-04 13:23:37.375   777  1536 I WindowManager: Switching to real app window: Window{89ef657 u0 com.example.app/com.example.app.MainActivity}
05-04 13:23:37.377 18103 18103 D XWalkLib: DecompressTask finished, 0
05-04 13:23:37.378  1588  1588 I Keyboard.Facilitator: onFinishInput()
05-04 13:23:37.379 18103 18103 D XWalkLib: ActivateTask started
05-04 13:23:37.380 18103 18137 D XWalkLib: Attach xwalk core
05-04 13:23:37.389 18103 18137 D XWalkLib: lib version, api:5, min api:5
05-04 13:23:37.389 18103 18137 D XWalkLib: app version, api:5, min api:5
05-04 13:23:37.566   777   799 I ActivityManager: Displayed com.example.app/.MainActivity: +652ms (total +5m52s235ms)
05-04 13:23:37.602 18103 18137 I LibraryLoader: Time to load native libraries: 4 ms (timestamps 5108-5112)
05-04 13:23:37.602   777 10374 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@44c594f attribute=null, token = android.os.BinderProxy@e81910a
05-04 13:23:37.605 18103 18137 I LibraryLoader: Expected native library version number "",actual native library version number ""
05-04 13:23:37.605 18103 18137 D XWalkLib: Running in embedded mode
05-04 13:23:37.614 18103 18103 D XWalkLib: Dock xwalk core
05-04 13:23:37.614 18103 18103 D XWalkLib: Init core bridge
05-04 13:23:37.615 18103 18103 D XWalkLib: Init xwalk view
05-04 13:23:37.620   777   883 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 129]
05-04 13:23:37.639 18103 18103 I LibraryLoader: Expected native library version number "",actual native library version number ""
05-04 13:23:37.639 18103 18103 I chromium: [INFO:library_loader_hooks.cc(120)] Chromium logging enabled: level = 0, default verbosity = 0
05-04 13:23:37.641 18103 18103 I BrowserStartupController: Initializing chromium process, singleProcess=true
05-04 13:23:37.820 18103 18144 I ResourceExtractor: Extracting resource xwalk.pak
05-04 13:23:37.836 18103 18144 I ResourceExtractor: Extracting resource icudtl.dat
05-04 13:23:37.913 18103 18103 E SysUtils: ApplicationContext is null in ApplicationStatus
05-04 13:23:37.948 18103 18103 E libEGL  : validate_display:255 error 3008 (EGL_BAD_DISPLAY)
05-04 13:23:37.948 18103 18103 E libEGL  : validate_display:255 error 3008 (EGL_BAD_DISPLAY)
05-04 13:23:37.991 18103 18157 W AudioManagerAndroid: Requires BLUETOOTH permission
05-04 13:23:37.993 18103 18103 D XWalkLib: Post init xwalk core in com.example.app.MainActivity
05-04 13:23:37.993 18103 18103 D XWalkLib: Init reserved class: class org.xwalk.core.XWalkPreferences
05-04 13:23:37.993 18103 18103 D XWalkLib: Call reserved method: public static void org.xwalk.core.internal.XWalkPreferencesBridge.setValue(java.lang.String,boolean)
05-04 13:23:37.993 18103 18103 D XWalkLib: Init reserved class: class org.xwalk.core.XWalkPreferences
05-04 13:23:37.993 18103 18103 D XWalkLib: Call reserved method: public static void org.xwalk.core.internal.XWalkPreferencesBridge.setValue(java.lang.String,boolean)
05-04 13:23:37.993 18103 18103 D XWalkLib: Init reserved class: class org.xwalk.core.XWalkPreferences
05-04 13:23:37.994 18103 18103 D XWalkLib: Call reserved method: public static void org.xwalk.core.internal.XWalkPreferencesBridge.setValue(java.lang.String,boolean)
05-04 13:23:37.994 18103 18103 D XWalkLib: Init reserved object: class org.crosswalk.engine.XWalkCordovaView
05-04 13:23:38.018 18103 18103 E chromium: [ERROR:xwalk_platform_notification_service.cc(103)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersistentNotifications(content::BrowserContext*, std::set<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >*)
05-04 13:23:38.027 18103 18103 E chromium: [ERROR:xwalk_browser_context.cc(79)] Failed to read preference, error num: 0
05-04 13:23:38.091 18103 18103 W VideoCapabilities: Unrecognized profile 2130706433 for video/avc
05-04 13:23:38.114 18103 18103 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
05-04 13:23:38.149 18103 18103 D XWalkLib: Init reserved object: class org.crosswalk.engine.XWalkCordovaResourceClient
05-04 13:23:38.150 18103 18103 D XWalkLib: Call reserved method: public void org.xwalk.core.internal.XWalkViewBridge.setResourceClientSuper(org.xwalk.core.internal.XWalkResourceClientBridge)
05-04 13:23:38.150 18103 18103 D XWalkLib: Init reserved object: class org.crosswalk.engine.XWalkCordovaUiClient
05-04 13:23:38.152 18103 18103 D XWalkLib: Call reserved method: public void org.xwalk.core.internal.XWalkViewBridge.setUIClientSuper(org.xwalk.core.internal.XWalkUIClientBridge)
05-04 13:23:38.152 18103 18103 D XWalkLib: ActivateTask finished, 1
05-04 13:23:38.186 18103 18162 I chromium: [INFO:xwalk_extension_renderer_controller.cc(47)] EXTENSION PROCESS DISABLED.
05-04 13:23:38.196 18103 18103 I Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
05-04 13:23:38.359 18103 18103 I chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'reportStatus' of undefined", source:  (1)
05-04 13:23:39.319   777   958 I ActivityManager: Killing 17075:com.google.android.apps.docs/u0a35 (adj 15): empty #17
05-04 13:23:40.407  1588  1588 I Keyboard.Facilitator: onFinishInput()
05-04 13:23:43.669   777   883 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 129]
05-04 13:23:45.450   777 13212 D NetlinkSocketObserver: NeighborEvent{elapsedMs=93184715, 10.10.10.1, [E05FB9B2666D], RTM_NEWNEIGH, NUD_STALE}
05-04 13:23:49.745   777   883 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 129]
05-04 13:23:52.089   777 13212 D NetlinkSocketObserver: NeighborEvent{elapsedMs=93191355, 10.10.10.1, [E05FB9B2666D], RTM_NEWNEIGH, NUD_REACHABLE}
05-04 13:23:55.769   777 13212 D NetlinkSocketObserver: NeighborEvent{elapsedMs=93195034, 10.10.10.1, [E05FB9B2666D], RTM_NEWNEIGH, NUD_STALE}
05-04 13:23:57.187 18103 18103 E CordovaWebViewImpl: CordovaWebView: TIMEOUT ERROR!
```

Here is the alert with the **Application Error**. I wait a bunch before pressing ok and resuming the app. This is what it writes after resuming.

```
05-04 13:30:52.680 18103 18103 W ScreenOrientationListener: Removing an inexistent observer!
05-04 13:30:53.920   777   883 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 129]
05-04 13:30:54.391   777 10373 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.example.app/.MainActivity bnds=[804,573][1068,870] (has extras)} from uid 10019 on display 0
05-04 13:30:54.414  1825  1836 W SearchService: Abort, client detached.
05-04 13:30:54.458  1825 18993 I DeviceStateChecker: DeviceStateChecker cancelled
05-04 13:30:54.472  1825  1825 I MicroDetector: Keeping mic open: false
05-04 13:30:54.473  1825  1825 I MicrophoneInputStream: mic_close com.google.android.apps.gsa.speech.audio.ah@6b697d8
05-04 13:30:54.473  1825 18990 E AudioRecord-JNI: Error -4 during AudioRecord native read
05-04 13:30:54.508 18103 18103 V StatusBar: StatusBar: initialization
05-04 13:30:54.512 18103 18103 D XWalkActivity: Activate by XWalkActivity
05-04 13:30:54.512 18103 18103 D XWalkLib: ActivateTask started
05-04 13:30:54.518   203 18996 D audio_hw_primary: disable_audio_route: reset and update mixer path: audio-record
05-04 13:30:54.518   203 18996 D audio_hw_primary: disable_snd_device: snd_device(61: voice-rec-mic)
05-04 13:30:54.519 18103 18103 D XWalkLib: ActivateTask finished, -1
05-04 13:30:54.527  1825  7361 I MicroRecognitionRunner: Stopping hotword detection.
05-04 13:30:54.528  1825 18994 I MicroRecognitionRunner: Detection finished
05-04 13:30:54.592   777   799 I ActivityManager: Displayed com.example.app/.MainActivity: +173ms
05-04 13:30:54.598  1588  1588 I Keyboard.Facilitator: onFinishInput()
05-04 13:30:54.614 18103 18103 W BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 18103
05-04 13:30:54.852 18103 18103 D JsMessageQueue: Set native->JS mode to OnlineEventsBridgeMode
05-04 13:30:55.164 18103 18171 D CordovaNetworkManager: toLower : wifi
05-04 13:30:55.164 18103 18171 D CordovaNetworkManager: wifi : wifi
05-04 13:30:55.164 18103 18171 D CordovaNetworkManager: Connection Type: wifi
...
```

**Comment by plougsgaard** [comment]
I'm currently trying some of the suggested work arounds.

**Comment by lostintangent** [comment]
@plougsgaard Thanks for the thorough repro investigation! Just to make sure I fully understand, you're seeing this issue simply by having the CodePush plugin installed? Even if you're not calling sync at all, it occurs?

Also, can you confirm that you don't get this error when installing a CodePush update to a freshly installed binary? Your repro steps above seemed to indicate that this issue only occurs after updating the binary on the device?

**Comment by plougsgaard** [comment]
Yes, the issue occurs consistently just by having the CodePush plugin added to the binary. I've commented out the `sync` code as it doesn't influence the problem either way.

I can only reproduce by using the Play Store to update the binaries as indicated by the steps. This of course also limits the speed of the testing what with having to wait for the store to distribute out the binaries to the test devices.

### Notes on >>**Revert `cordova-plugin-file` to `4.1.1`**<< 

I got to test this on the Nexus 5 device but not on the other devices. This just entails building an APK with the CodePush plugin added and the `cordova-plugin-file` at `4.1.1` instead of `4.2.0`.

The observed behavior is that it seems to work, the only difference being it suddenly asking for a Storage/Media permission on launch. I wonder why that is and if that's somehow related.

**Comment by MarketAmericaMobile** [comment]
I am actually having the same issue after updating to cordova-plugin-code-push 1.7.0-beta "CodePush"

I can confirm that reverting these plugins to the last know good config seems to have solved the issue. 

cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.0 "File Transfer"

**Comment by lostintangent** [comment]
Yeah it seems like we might have been broken by an upgrade to the `cordova-plugin-file` plugin. We're still investigating this.

**Comment by MarketAmericaMobile** [comment]
Is this related to https://github.com/Microsoft/cordova-plugin-code-push/issues/99, or is it just a coincidence?

My test device is a Nexus 5X, in case you it is relevant.

**Comment by lostintangent** [comment]
@MarketAmericaMobile That bug was tracking a different issue with the `cordoba-plugin-file` plugin, but it's possible that we have another issue with it.

**Comment by MarketAmericaMobile** [comment]
If it helps any, this shows up in chrome://inspect before the error: Uncaught TypeError: Cannot read property 'reportStatus' of undefined

**Comment by plougsgaard** [comment]
I get that same TypeError as well (as seen in the log posted previously).

**Comment by lostintangent** [comment]
We just merged in the fix for this issue, and it's entirely possible this bug is a downstream issue as well. Any chance either of you could try installing the plugin from this GitHub repo and seeing if that resolves it for you? That would super helpful to know, and we could then release this to NPM ASAP.

**Comment by plougsgaard** [comment]
@lostintangent I just built a version with the GitHub **master** of this repo, and on my main test device it seems to work! I don't have access to the other devices currently so can't test on those.

**Comment by lostintangent** [comment]
@plougsgaard Awesome! I just released this fix to NPM (`v1.7.1-beta`), and in our tests, that seems to address this issue. Please let me know if you continue to see this resolved.

**Comment by plougsgaard** [comment]
Will do. Appreciate the responsiveness a lot - that's a nice change of pace! I'll be using the `1.7.1` and reopen with details if the issue isn't completely gone. Cheers!

**Comment by MarketAmericaMobile** [comment]
Confirmed - it seems to be working. Thanks a lot for your help!

**Comment by lostintangent** [comment]
Yay! Thanks for the patience everyone :)

**Comment by rkjhaw** [comment]
Add the next line into the config.xml in side the <platform name="android"> tag.

<preference name="loadUrlTimeoutValue" value="700000" />

**Comment by rkjhaw** [comment]
Add the next line into the config.xml in side the <platform name="android"> tag.

        <preference name="loadUrlTimeoutValue" value="700000" />

**Comment by kigh143** [comment]
add this <preference name="loadUrlTimeoutValue" value="700000" /> @rkjhaw it will not appear again.

**Comment by gjdownes** [comment]
Is there any way to disable the popup (and any other code-push popups) in general? I want to be in full control over what my users see. If there's already a working app bundle on the device, it should fail silently in my opinion.

The error message shown has no context for the user and will only cause confusion.

**Comment by lavanvickyneshwaran** [comment]
Add this line into the config.xml in side the tag. 

 <platform name="android"> // android or ios
 <preference name="loadUrlTimeoutValue" value="70000" />
 </platform>

this is working 
or try 

Add this line into the index.html file in side head

  <script>
    window.location='./main.html';
  </script>

**Comment by lavanvickyneshwaran** [comment]
Add this line into the config.xml in side the tag. 

`<platform name="android"> // android or ios`
`<preference name="loadUrlTimeoutValue" value="70000" />`
 `</platform>`

this is working 
or try 

Add this line into the index.html file in side head

  `<script>`
   ` window.location='./main.html';`
  `</script>`

**Comment by rezafree** [comment]
Is
