### ISSUE TITLE
minimumBackgroundDuration config not working on sync() 

### ISSUE THREAD

**Issue by MarketAmericaMobile** [Microsoft/cordova-plugin-code-push#114]
It seems that in spite of setting the minimumBackgroundDuration property on the syncOptions config in the sync() method, the update is installed immediately, regardless of time in background.

```javascript
codePush.sync(null, {
    deploymentKey: Config.codepush_key,
    minimumBackgroundDuration: 60,
    installMode: InstallMode.ON_NEXT_RESUME,
    mandatoryInstallMode: InstallMode.IMMEDIATE
});
```

This is occurring for both iOS and Android.

- cordova-android: 5.1.1
- cordova-ios: 3.9.2
- Cordova CLI: 5.3.3
- OS: Mac OS X El Capitan
- Node Version: v4.2.2
- Xcode version: Xcode 7.3 Build version 7D175 
- code-push 1.8.0-beta "CodePushAcquisition"
- cordova-plugin-code-push 1.5.1-beta "CodePush"
- cordova-plugin-file 4.1.1 "File"
- cordova-plugin-file-transfer 1.5.0 "File Transfer"
- cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

**Comment by lostintangent** [comment]
@MarketAmericaMobile Are these updates marked as mandatory? The minimumBackgroundDurarion property only takes affect if you're using a resume-based install, and in your case, your app will always use immediate if the update is marked as mandatory. Would that explain this behavior you're seeing?

**Comment by MarketAmericaMobile** [comment]
No, they aren't - 

Seems to be working as intended on cordova-plugin-code-push 1.7.0-beta "CodePush"

**Comment by lostintangent** [comment]
Ah apologies, I didn't see that you were on an older version of the plugin. Yeah we added that feature in 1.7.0. Sorry for the confusion!
