### ISSUE TITLE
Documentation for downloadProgress differs from implementation

### ISSUE THREAD

**Issue by mvanderlinde** [Microsoft/cordova-plugin-code-push#116]
Within the README/documentation, there is a code sample that defines `downloadProgress` (within `codePush.sync()`) as follows:

```
function downloadProgress(totalBytes, receivedBytes) {
    // Update "downloading" modal with current download %
}
```

However, the function actually expects a single object with two properties, so the actual implementation is more along the lines of:

```
function downloadProgress(progress) {
    // Update "downloading" modal using progress.totalBytes and progress.receivedBytes
}
```

**Comment by rub8n** [comment]
@mvanderlinde Were you calling out the Cordova readme? We have it correctly on the tutorial area but seems like we forgot to update the Cordova readme. I'll take a look and update accordingly.

**Comment by rub8n** [comment]
Closing as it should be fixed now. 

Thanks for letting us know!
