### ISSUE TITLE
checkForUpdate doesn't respond with already downloaded version

### ISSUE THREAD

**Issue by ikosta** [Microsoft/cordova-plugin-code-push#123]
1. I have checked for an update end synced it successfully but never restarted the app.
2. Now I check again for an update but didn't make a new version. Returns: null

Shouldn't there be an information that there is an update waiting for restart? Or a function like getCachedPackage?

**Comment by ikosta** [comment]
Just found in the sources getPendingPackage.

Maybe update the docs?

**Comment by lostintangent** [comment]
@ikosta Ah good call, I thought we had this method documented. I'll take care of hay this afternoon. Apologies for the confusion and thanks for the feedback.
