### ISSUE TITLE
getCurrentPackage returns to wrong label

### ISSUE THREAD

**Issue by ikosta** [Microsoft/cordova-plugin-code-push#124]
1. release v1
2. sync and restart
3. release v2
4. sync but don't restart
5. release v3
6. sync but don't restart
7. getCurrentPackage returns: v2 should be v1 because v2 was not installed

**Comment by lostintangent** [comment]
@ikosta Yeah you're right, this method should return v1 in your scenario. We haven't had anyone encounter this issue before, so thanks for reporting it.

**Comment by lostintangent** [comment]
*Random side note* I just tried reproing this on our React Native SDK, and the expected behavior occurs, so we seem to have a bug in the Cordova plugin here. We'll try to address this ASAP, since it should be straight forward to make sure we have consistent behavior between our two clients.

**Comment by geof90** [comment]
Yup, can confirm its a bug, have a fix out but working on adding test coverage now.
