### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by kenvunz** [Microsoft/cordova-plugin-code-push#131]
I got this error when run `codePush.sync()` on Android
```
Error in Success callbackId: CodePush967422951 : TypeError: Cannot read property 'code-push' of undefined
```
And the line causing that issue seems to be this
```js
xhr.setRequestHeader("X-CodePush-SDK-Version", cordova.require("cordova/plugin_list").metadata["code-push"]);
```

I'm running `cordova` version `6.1.1` and the `cordova-android` is at `5.1.1`

Let me know if you need any more information

Cheers
Ken

**Comment by slorber** [comment]
hey

Just to know, what is this cordova.require() call? Is this a new feature? I've never seen that before and after taking a look at fresh doc I don't see this being mentionned

**Comment by silhouettes** [comment]
@kenvunz: That's really strange. It seems like your plugins have not been loaded - does the `platforms/android/platform_www/cordova_plugins.js` file exist for you, and what does it contain? Does it persist if you run `cordova clean` and then `cordova build`?

@slorber: `cordova.require()` is a way to reference/import modules that have been populated in `cordova_plugins.js`, although it's not commonly needed. The modules in that file were in turn generated from `plugin.xml`, along with a few cordova-specific additions.

**Comment by kenvunz** [comment]
@silhouettes found the culprit, it's the new `--browserify` flag introduced in `cordova build` command which basically pack all plugins code in a single file. Looks to me that when it's doing the packaging, the `metadata` part of the `cordova/plugin_list` has been stripped out somehow.

Anyway, not `code-push` problem. Closing :)

**Comment by silhouettes** [comment]
Thanks for letting us know! Feel free to reach out anytime if you have any other issues :)

**Comment by slorber** [comment]
thanks @silhouettes maybe it's because I don't use browserify I never found this.

BTW thanks for CodePush, just installed it on a 2 years old Cordova project and it just works out of the box without any complication!

**Comment by silhouettes** [comment]
Glad we could help :)
