### ISSUE TITLE
Install optional updates only when user has Wifi?

### ISSUE THREAD

**Issue by slorber** [Microsoft/cordova-plugin-code-push#132]
Hi,

I don't know if it's possible nor worth it, but sometimes we want to reduce bandwidth usage when we don't have wifi

Can it be a good idea to choose to postpone an optional update in case the user is under a slow/expensive/roaming connection?

Is it something to implement in userland or can it be done in this plugin?

**Comment by lostintangent** [comment]
@slorber Thanks for the feedback! Our current recommendation is the use the [cordova-plugin-network-information](https://github.com/apache/cordova-plugin-network-information) plugin to check the network type, and only call sync if it's wifi. If you wanted to always do the update check, and then force a mandatory update regardless of the network type, then you'd need to use the checkForUpdate method first to see if there's an update, and if so, is it mandatory. 

We haven't had a ton of feedback for this, and we prefer not to add dependencies on our Cordova plugins unless it's broadly valuable for users, which is the only reason we don't support it out of the box. That said, I'd love to hear your feedback on this, and I'll use this issue as a reminder to add a sample of how this can be done in userland today.

**Comment by slorber** [comment]
Hey,

Thanks for the feedback. I understand that it's quite complicated to add dependencies in Cordova plugins (ooh god Intercom / PushPlugin conflicts I had...). I don't think I'll implement this for now but it's worth knowing it's possible :)

**Comment by lostintangent** [comment]
Sounds good!
