### ISSUE TITLE
sync / checkForUpdate hangs

### ISSUE THREAD

**Issue by sagikarni** [Microsoft/cordova-plugin-code-push#133]
Hi,
I'm trying to use the push plugin but when using the 
codePush.sync / codePush.checkForUpdate , it looks like something is hanging and the completed event is never returned.
 my code :

codePush.checkForUpdate(function (update) {      
            if (!update) {
               alert("The app is up to date.");
            } else {
                alert("An update is available! Should we download it?");
            }
        });

These are my configurations
1.  my config xml : 
<img width="565" alt="push1" src="https://cloud.githubusercontent.com/assets/16361670/15777135/ccfde526-2995-11e6-9f35-0ffc238db58a.png">
2. this is how the metadata looks in the push code server
  <plugin name="code-push" version="1.9.0-beta" />`
<img width="594" alt="push" src="https://cloud.githubusercontent.com/assets/16361670/15777011/c5f2174e-2994-11e6-8d2c-0380eedb04d9.png">

Am I missing something ?
Calls to sync and checkForUpdate just hand with no sucess or error response.
btw , 0fp8klF4oolC1_zIrjoL11vTL9LH4yvif4qQW is the key for the staging environment.

Thanks
Sagi

**Comment by lostintangent** [comment]
@sagikarni Are just seeing this on both iOS and Android? Also, could you let us know which platform versions you have installed (by running "cordova platform ls")? I just want to make sure I try to repro the exact conditions.

Additionally, could you try downgrading the CodePush plugin to 1.7.1-beta and see if that makes a difference? We'll investigate this on our end, so stay tuned. Thanks!

**Comment by sagikarni** [comment]
I'm currently testing it im my android device.

<img width="579" alt="cordova_ver" src="https://cloud.githubusercontent.com/assets/16361670/15787029/816a1d68-29c8-11e6-9e96-54f8a4e19b2b.png">
<img width="558" alt="cli" src="https://cloud.githubusercontent.com/assets/16361670/15787036/8aa23276-29c8-11e6-8ac6-6144eb8ab2e0.png">

I'll try to downgrade to 1.7.1 and update.
Thanks
Sagi

**Comment by sagikarni** [comment]
I have tried using 1.8.0-beta , but getting the same result (request is still hanging)
I will also try to 1.7.1 , but I do have a question :
When I try to run the command :  code-push release-cordova IListApp android
I get the following error : 

[Error]  Unable to prepare project. Please ensure that the CWD represents a Cordova project and that the "android" platform was added by running "cordova platform add android".

when I run "cordova platform add android". the command does runs succusfully (although , the hanging problem is still there...) 
I wonder if you have any idea why do I need to run this command , 
I'm working with VS 2015 (update 9) and the platforms/android is already there.. why do I have to install it  ? (and this command also installed unwanted additional plugins that I need to remove later on)

<img width="650" alt="codepush" src="https://cloud.githubusercontent.com/assets/16361670/15788891/489bf34e-29d2-11e6-9f16-3f2af4fe350b.png">

Thanks
Sagi

**Comment by lostintangent** [comment]
@sagikarni Can you try restarting your emulator and see if that helps? We've seen cases where the network connectivity in the emulator gets screwed up, and therefore, the call to `sync` and/or `checkForUpdate` hangs because the app can't actually reach the CodePush server. 

Regarding your question about the `release-cordova` command, you need to ensure that you CD into the root of your Cordova project (the directory that includes the `www`, `platforms`, etc. folders) before running this.

**Comment by sagikarni** [comment]
1. I'm not working with en emulator , I'm deploying and testing the app against my android device (ASUS)
2. release-cordova command :  i'm inside my cordova project's root.

you can take a look at these screen shots 
first one is the folder (C:\Users\sagi\Documents\Visual Studio 2015\Projects\IListApp\IListApp) structure including the platforms folder , and the command which is executed in the context of this directory (C:\Users\sagi\Documents\Visual Studio 2015\Projects\IListApp\IListApp)

<img width="650" alt="root" src="https://cloud.githubusercontent.com/assets/16361670/15789820/d48bfdaa-29d6-11e6-9fa4-551d47140639.png">
<img width="650" alt="cmd" src="https://cloud.githubusercontent.com/assets/16361670/15789902/33eb2a64-29d7-11e6-9429-c740dfb6864a.png">

**Comment by lostintangent** [comment]
@sagikarni If you simply run `cordova prepare android` in that same directory, does it work? That is all that CodePush is calling under the covers, so I'm curious if we have an issue, or if there is something up with Cordova in general.

**Comment by sagikarni** [comment]
Hi ,
I did not run cordova prepare android command yet since I have created a new Cordova project in VS 2015  and this time for some reason when executing : code-push release-cordova IListApp android the command did not throw any error (in my previouse project I had to "cordova platform add android" for some reson...) , 

Anyway , I'm still struggling with the hanging of the plugin calls which does not return.
I have added the error callback (dont know how I missed it...) , but again nothing , no callback is called nither to the succss nor to the error calbacks : 

   codePush.checkForUpdate(function (update) {
                     if (!update) {
                        console.log("The app is up to date.");
                    } else {
                        console.log("An update is available! Should we download it?");
                    }
                }, function (e) {
                    console.log("error");
                 })

btw ,
I'm developing web apps for quite some years now , but I do not have a lot of expirience with Cordova (although I'm using few plugins succusfully without any issue) 
So I have attached the cordova project i'm using , in case you you can detect anything that I have missed in the project setup.
One last thing , is there any way to check where the code is hanging ?
Is there any logs that I can use or install any kind of http network monitor in my device , to see if  the request to the code push server is even fired (when debugging my SPA web apps I usually use fiddler , so I wonder if there is something for android)
Or do you have other suggestions how can I debug my issue.


[pushcode.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/298443/pushcode.zip)


Thanks
Sagi

**Comment by lostintangent** [comment]
You can use the Chrome dev tools to view the network traffic of the app. If you go to `chrome://inspect` in Chrome, you can select the device/emulator you're running, and then view the network traffic as well as console logs. The CodePush plugin outputs a bunch of diagnostics information, so it would be great to know if you see any errors or what the network traffic looks like when you call `sync` or `checkForUpdate`.

**Comment by sagikarni** [comment]
thanks , I'll do it tomorrow (1 AM here (-:)
I did though step inside the code and find out the following :
Getting the following error in cordova.js file(I do not know yet , why the error callback was not invoked...):

<img width="666" alt="screen1" src="https://cloud.githubusercontent.com/assets/16361670/15794166/93c89baa-29f1-11e6-8baf-94e3f8c29552.png">


"Error: Failed to execute 'open' on 'XMLHttpRequest': Refused to connect to 'https://codepush.azurewebsites.net/updateCheck?deploymentKey=0fp8klF4oolC1_zIrjoL11vTL9LH4yvif4qQW&appVersion=1.6.0&packageHash=26c79c936b402bad4f656445e8af660075f77777d02e2144e3e2903cfab84a81&isCompanion=false&label=&clientUniqueId=7c6b09332943aff9' because it violates the document's Content Security Policy.
    at Error (native)
    at HttpRequester.request (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/httpRequester.js:34:13)
    at AcquisitionManager.queryUpdateWithCurrentPackage (file:///android_asset/www/plugins/code-push/script/acquisition-sdk.js:37:29)
    at file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePush.js:134:48
    at file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:358:21
    at binaryHashSuccess (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/nativeAppInfo.js:28:57)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:58)
    at processMessage (file:///android_asset/www/cordova.js:1081:17)
    at processMessages (file:///android_asset/www/cordova.js:1104:9)"

**Comment by lostintangent** [comment]
@sagikarni Ah OK, that explains it. The call to `sync` isn't hanging, it's failing because your CSP isn't configured correctly. Can you make sure to go through steps 2-5 in our [getting started](https://github.com/Microsoft/cordova-plugin-code-push#getting-started) docs to ensure you have the right access and CSP policies setup? If not, then this wouldn't just be a CodePush issue, you would have problems connecting to any remote URL in general.

**Comment by sagikarni** [comment]
That did the trick !!
2 questions though  : 
1.  if I have the following meta tag , the call to checkForUpdate works just fine,
`    <meta http-equiv="Content-Security-Policy" content="default-src https://codepush.azurewebsites.net 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *" />

 do you know how do I add another end point other than https://codepush.azurewebsites.net to the security policy (if you dont , never mind I'll google it...) so I could perform ajax calls to other servers other than code push server

2. Why the error callback was not called ?

Thanks
Sagi

**Comment by lostintangent** [comment]
It doesn't look like your example meta tag came through correctly.

Regarding your question about how to add other URLs to your CSP, I would recommend checking out the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Security/CSP) on CSP, which do a good job of explaining the syntax and how to use it.

The fact that the error callback isn't triggered is definitely odd, and if a bug we should investigate and fix.

**Comment by sagikarni** [comment]
Thanks very much for your help !!
This issue can be closed.

**Comment by lostintangent** [comment]
@sagikarni Thanks for working through this with us and for using CodePush!
