### ISSUE TITLE
App does not start when update is applied/checked for update

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#138]
This is my cordova start code in `index.js`

```es6
function startApp() {
  if (window.codePush) {
    const update = () => {
      window.codePush.sync(null, {
        deploymentKey: CONFIG.codepush,
      })
    }
    document.addEventListener("resume", update)
    update()
  }

  render(<Root/>,  document.getElementById("app"))
}

if (window.cordova) {
  document.addEventListener("deviceready", startApp)
} else {
  startApp()
}
```

Sometimes, the app will not start at all and not mount the react app. The index.html `app` element remains empty. I also do not see any `codePush` log entries in the console.

This is my configuration:

```
code-push 1.9.0-beta "CodePushAcquisition"
cordova-plugin-code-push 1.8.0-beta "CodePush"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-device-name 1.0.0 "Device-Name"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.1 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.0.11 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
phonegap-plugin-barcodescanner 4.1.0 "BarcodeScanner"
phonegap-plugin-push 1.6.0 "PushPlugin"

Installed platforms:
  android 5.1.1
  ios 4.1.1
  windows 4.3.1
```

Is there anything I can do to investigate further?

**Comment by lostintangent** [comment]
Can you confirm that sync is even being called in this circumstance? I can't think of a reason why it could be called but not result in any console logs. I'm also not sure whether or not you can guarantee that the DOM will be fully available when deviceready is fired, which may explain why your app element is null. Is the block of code that you paste being triggered after the DOM has loaded?

In order for us to try to repro this, could you share how you are currently running the app? In the simulator or device? Are you using live reload? Does this issue happen on both iOS and Android?

**Comment by pke** [comment]
It seems this weird issue came from me loading the scripts like this:

```
<script src="cordova.js" async></script>
<script src="scripts/platformOverrides.js" async></script>
<script src="bundle.js" async></script>
```

It seems the drop-in webview engine "CDVWKWebViewEngine" can't handle this properly. So a race condition between the script loads seemed to be the source of the issue.

I'll close for now and re-open if that was not the reason.

**Comment by lostintangent** [comment]
Thanks for letting us know, and we can definitely help investigate it further if the problem shows up again.
