### ISSUE TITLE
How does this work with beta store submits and propagating

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#144]
I understand that one can propagate a codepush version from one deployment channel to another. Mostly from "staging" to "production" (btw I renamed the default deployment names from uppercase first to all lowercase, as this matches our other env better).

So now I deploy a cordova app version to the beta play store to let testers test it. This version should of course not use the same deployment key as the production build. We want to update the beta version independent from the production version. Now its time to move this app from beta to production. But since it contains the beta deployment key, a new version has to be created/uploaded whos only change is the deployment key. So in the app store I cannot simply promote the app. I have to upload an app version that contains the production key. Since the app does not know that it was installed from the beta or production store. Or is there a ways the app could detect that?

So, to get the exact same version in both cases, one would have to compile & build the production version always alongside the beta version, so they both use the same assets/plugins/node modules but only different deployment keys.

Or is there something I'm missing in the deployment/update cycle?

**Comment by lostintangent** [comment]
> So, to get the exact same version in both cases, one would have to compile & build the production version always alongside the beta version, so they both use the same assets/plugins/node modules but only different deployment keys.

Yes, that is currently the "primary" way of doing this. On iOS, I'm aware of a solution to dynamically detect if your app was acquired via TestFlight or the App Store, which would allow you to swap out your deployment keys as appropriate. However, I'm not aware of how to do this on Android without using the Google Play REST APIs to detect if your APK version is currently in the beta or production track.

**Comment by pke** [comment]
aha interesting. Do you have any doc references for me maybe? Then we could develop a cordova plugin

**Comment by lostintangent** [comment]
@pke I just realized I didn't reply here after we spoke about this a little bit on Discord :) I definitely think it would be valuable to create a package for this and/or even add it directly to the CodePush plugin. Did you ever do anything here?

**Comment by pke** [comment]
no problem, Jonathan. It's unfortunate that google does not offer an easy way to figure out if a bundle was installed from the beta/alpha track.
But I think the functionality for iOS could indeed live in the `code-push` plugin itself. It could then have additional configuration preferences for the Apple appstore and testflight respectively.
I also think this needs a bit of testing for edge cases, if there are any. Like when you download an app update while the app is installed from Testflight and then the app gets updated via the store, while the codepush update is pending, would that picked up when the app is then started again (now being the store version) and the update for the testflight app version should not be installed. Or is that not even possible cause ios removes the testflights app folder completely?

**Comment by pke** [comment]
Close reason?
