### ISSUE TITLE
not able to see my deployment keys for the second time.

### ISSUE THREAD

**Issue by Suryanarayanamurthy** [Microsoft/cordova-plugin-code-push#151]
I would like to know if we can get the deployment keys for my app.

i recently started using Code-push for my cordova app.
I followed the initial setup of the app and everything looks good.
I am not able to see my app's production/staging deployment keys once again.

Thanks,
Surya.

**Comment by Suryanarayanamurthy** [comment]
sorry it was there in the documentation .
inCase if some1 else stumbles on this same issue here's the scoop:
`code-push deployment ls APP_NAME -k`

**Comment by silhouettes** [comment]
I'm glad you were able to work it out :) Feel free to ping us if you run into any other issues!
