### ISSUE TITLE
Splashscreen not displayed when using InstallMode.ON_NEXT_RESUME

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#152]
This install mode works just great, however during the update no splash screen is displayed just the apps blank background (I guess as defined in the `config.xml`).

I am using the cordova splashscreen plugin, so I could manually show the splashscreen on a certain sync event. Would that be possible?

**Comment by geof90** [comment]
I think we could do either of the following:

1. Simply check for the presence of the splashscreen plugin, and if it exists, show the splashscreen before restarting the app.
2. Expose a general "pre-restart" hook for devs to run any kind of code before a CodePush update is applied.

**Comment by pke** [comment]
The question is will the splashscreen stay during the update our will Cordova tear it down. To what extent is Cordova shut down during update? Or is only the web view reloaded?

**Comment by geof90** [comment]
The update happens when we call `install` on `the localPackage`. https://github.com/Microsoft/cordova-plugin-code-push/blob/master/www/localPackage.ts#L138

Internally, this goes into native code which calls `loadUrlIntoView` on the webview. https://github.com/Microsoft/cordova-plugin-code-push/blob/master/src/android/CodePush.java#L193

So, I have not tried it, but I would expect a solution would be to call `navigator.splashscreen.show();` before the webview navigates, and `navigator.splashscreen.hide();` in the `ready` event when the new update is loaded.

**Comment by pke** [comment]
Yes, thats exactly what I was about to  try out. I am listening to the `UPDATE_INSTALLED` sync event and set an internal "update installed" variable that my `resume` listener has access to. Now when the listener is called and this var is set, it displays the splash-screen. Upon `deviceready` the react app is mounted and at the end of the mount process the splashscreen is hidden.
I'll report back here if it works. Maybe we can add it as an **receipe** to the docs then.

**Comment by pke** [comment]
I have this code now and it seems to work:

```es6
function startApp() {
  navigator.splashscreen && navigator.splashscreen.show()
  render(
    <Root/>,
    document.getElementById("app"),
    () => {
      if (navigator.splashscreen) {
        setTimeout(() => {
          navigator.splashscreen.hide()
        }, 10)
      }
      if (window.codePush) {
        var updateReady = false
        const update = () => {
          // Make sure the splashscreenn is shown before codepush restarts the app
          updateReady && navigator.splashscreen && navigator.splashscreen.show()
          window.codePush.sync(status => {
            updateReady = status === window.SyncStatus.UPDATE_INSTALLED
          }, {
            deploymentKey: api.CONFIG.codepush,
            installMode: window.InstallMode.ON_NEXT_RESUME,
          })
        }
        document.addEventListener("resume", update)
        update()
      }
    }
  )
}

if (window.cordova) {
  document.addEventListener("deviceready", startApp)
} else {
  startApp()
}
```

However, it seems that in `InstallMode.ON_NEXT_RESUME` my `resume` document event listener is not always attached after app re-start. That might be a cordova problem though, as my other `resume` document listener installed in my telemetrics module does also not fire anymore after the app was restarted due to an update.

**Comment by pke** [comment]
> I think we could do either of the following:
Simply check for the presence of the splashscreen plugin, and if it exists, show the splashscreen before restarting the app.

I'd vote for that, its a one liner and helps a lot. The hook idea can wait until there is more demand. I wonder why no-one has complained about the blank screen during resume-update before :)

**Comment by alexhisen** [comment]
Hi, any progress on adding navigator.splashscreen.show() to the install process?

**Comment by brassier** [comment]
FYI - I got the splash screen to show after a successful install by doing below.  This seems to work from my minimal testing.  This syntax is using the Ionic Native version of CodePush.

    ...
    CodePush.sync(
      {
        installMode: InstallMode.IMMEDIATE,
        mandatoryInstallMode: InstallMode.IMMEDIATE
      },
      (progress) => { this.codePushDownloadProgress(progress); }).subscribe((syncStatus) => this.codePushSyncStatus(syncStatus));

    }

    codePushSyncStatus(status) {
        switch (status) {
          case SyncStatus.UPDATE_INSTALLED:
            this.loggingService.info("Code push sync complete: success");

            // Hide updating modal
            this.loggingService.info("Showing splash, hiding update screen");
            this.splashScreen.show();
            this.updatingScreen.dismiss();
            break;
        }
      }

**Comment by pke** [comment]
So whats the solution MS proposes here by closing the issue comment-less?

**Comment by pniko** [comment]
Hi @pke, we are working to narrow our priorities as much as possible and clean house a bit on issues open for over a year in preparation for the next wave of CodePush enhancements (better rollback, crash, brownfield support, analytics, distribution options and code-signing for Cordova). We are very open to external contributors to the CodePush service and its various SDK's, but do not presently have any bandwidth to apply to this directly. If you would like to issue PR's containing better support for this and other features we will be happy to review them asap.
