### ISSUE TITLE
InstallMode.ON_NEXT_RESUME only works on time, then the resume listener never triggers again

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#153]
It seems that in InstallMode.ON_NEXT_RESUME neither `resume` `document` event listener nor codepush's own `resume` listener for update checks is not attached (anymore) to `document` after app re-start.
That might be a cordova problem though.

I can confirm now after several codepush updates my event handlers are no longer triggered after the update was performed. And codepush also does not check for new updates. 
I have to close the app and start it again. Then all `resume` listeners react properly again of course.

mainWebView.loadUrlIntoView should just load the app as it would be on a real restart and attach all "document" listeners properly, shouldn't it?

**Comment by geof90** [comment]
@pke is this on Android or iOS?

**Comment by geof90** [comment]
@pke I cannot repro this, I tried installing an two update ON_NEXT_RESUME one after the other consecutively. Each time after the update is applied I still see resume listeners being fired.

Are you on Android? Are u using a custom webview implementation?

**Comment by geof90** [comment]
Did you only see this happening after you did the work to show the splashscreen when an update gets applied?

**Comment by pke** [comment]
That is happening on `Android`. Haven't tested iOS. I am using the [wkwebview cordova plugin](https://github.com/apache/cordova-plugin-wkwebview-engine).

It has nothing to do with the splashscreen handling.

**Comment by pke** [comment]
On Android I am using crosswalk as the browser. Maybe that's the reason?

**Comment by geof90** [comment]
Hmm no.. after adding the crosswalk plugin, still unable to repro..

**Comment by geof90** [comment]
What version of cordova are you on?

**Comment by pke** [comment]
6.2 and the latest ios & Android cordova versions. The device is running Android 5.1

````xml
<engine name="ios" spec="~4.1.1" />
<engine name="windows" spec="~4.3.1" />
<engine name="android" spec="~5.1.1" />
<plugin name="cordova-plugin-code-push" spec="~1.8.0-beta" />
<plugin name="cordova-plugin-splashscreen" spec="~3.2.2" />
<plugin name="cordova-plugin-appinfo" spec="~2.0.3" />
<plugin name="cordova-plugin-crosswalk-webview" spec="~1.7.2" />
<plugin name="cordova-plugin-wkwebview-engine" spec="~1.0.3" />
```

**Comment by sergey-akhalkov** [comment]
@pke, sorry for the late reply, do you still experiencing the issue? Please let me know if you see any issues or have any questions.

**Comment by pke** [comment]
No, we are not using code-push at all anymore atm. So if there has been no update on that part, I assume its still happening.

**Comment by sergey-akhalkov** [comment]
Got it, closing this for now, please feel to reopen in case it happens again.
