### ISSUE TITLE
Where I should find the declaration files for typescript?

### ISSUE THREAD

**Issue by elranu** [Microsoft/cordova-plugin-code-push#154]
Hi
Where I should find the declaration files for typescript?
Is there a small example how to import/use codepush in typescript?

are this the typings: https://github.com/Microsoft/cordova-plugin-code-push/tree/master/typings

why are not automatically installed when I do `cordova plugin add cordova-plugin-code-push@latest` ?

Regards

**Comment by silhouettes** [comment]
Hi @elranu, yes, those are the typings, although they are not automatically imported. They should work if you do something like the following:

```
/// <reference path="path/to/typing.d.ts" />

import * as codePush from "code-push";

...

onDeviceReady(): void {
    codePush.sync();
}
```

When you mention 'automatic install', do you mean intellisense in your editor, or something else? And if so, which editor are you using?

**Comment by elranu** [comment]
@silhouettes thanks for your reply.  when I say automatically is that when I do 'cordova plugin add cordova-plugin-code-push@latest' the typings.d.ts is not downloaded on the plugins folder.

**Comment by sergey-akhalkov** [comment]
Hi @elranu, I've merged PR in master that should fix it https://github.com/Microsoft/cordova-plugin-code-push/pull/252, could you please have a chance to look at this and verify if it works as expected.
I'm closing this for now, please feel free to reopen if needed.

**Comment by mredbishop** [comment]
This still seems like it's wrong to me as in most recent packages that have typings, npm installing the package makes the typings available to an import command. I would expect to be able to do something similar to the following:
```
import 'cordova-plugin-code-push';

codePush.sync();

```

and have it recognise the codePush types?

**Comment by ruslan-bikkinin** [comment]
@mredbishop thanks for the question, does it relates to https://github.com/Microsoft/cordova-plugin-code-push/issues/23#issuecomment-223148238?
