### ISSUE TITLE
Apparent memory leak when run in a timer loop

### ISSUE THREAD

**Issue by hilkeheremans** [Microsoft/cordova-plugin-code-push#158]
We are running a "long lived" app that is intended to be shown on screen nearly 24/7. To be able to update rather seamlessly, we would like to use Code Push. To that end, we are running `sync` (or rather: `checkForUpdate`) function in a loop every few minutes.

Unfortunately, this seems to result in continuously increasing memory usage, eventually freezing or crashing the app [Xcode mem usage chart below]:

![](http://image.prntscr.com/image/b270173e4e8e4bc28d3c74868f94483b.png)

Try this `onDeviceReady` function for a quick repro:

```
function onDeviceReady() {
    check()
    function check() {
        console.log('Checking')
        window.codePush && window.codePush.sync()
        setTimeout(check, 5e3)
    }
}

```

This occurs both when using `sync` or `checkForUpdate`.

Aside from any silly errors we might have made (which I would personally prefer), there appears to be something causing memory usage to systematically increase. It does not get GC'd over time either.

Any ideas?

**Comment by silhouettes** [comment]
@hilkeheremans - I will try to repro this. Just to double check, what version of Cordova and cordova-plugin-code-push are you using?

**Comment by hilkeheremans** [comment]
@silhouettes: `cordova-plugin-code-push v1.8.2-beta`, `phonegap CLI v6.2.9` which (I believe) runs on `cordova v6.1.1` under the hood. All this combined with `cordova-ios v.4.1.0`.

Thanks!

**Comment by hilkeheremans** [comment]
By the way, when replicating this on a 'virgin' phonegap application, the effect still seems to be there but is much less pronounced. I also tested on `cordova-ios v4.2.0` without result.

Not sure if this is some kind of interaction with plugins, dependent on code base size, ... FWIW, our app is a React web app which is built with webpack.

**Comment by geof90** [comment]
> I also tested on cordova-ios v4.2.0 without result.

Just to clarify, you mean you still see the same memory problem when using cordova-ios v4.2.0? 

I do know that cordova-ios has a bunch of memory related issues that are outstanding.
https://issues.apache.org/jira/browse/CB-7873
https://issues.apache.org/jira/browse/CB-11249

It is certainly strange that using React would have any impact.

We will try to get a repro scan our codebase for any stale global state being left around.

**Comment by hilkeheremans** [comment]
Yes -- the memory problem is still there on `cordova-ios v4.2.0`, sorry for the lack of clarity.

The issue is there regardless of calling `sync` from inside React or outside, and doesn't seem to affect the "size" of the memory leak.

I've been playing with `Instruments` a bit to find out a bit more, but it seems the memory is being allocated as `transient` and despite this, it is not getting released (despite that the allocations are transient..). I don't think we can actually dig into the transient allocations using Instruments, but I'm not an expert on that.

Thanks for looking into this! It's very puzzling to me as well.

**Comment by geof90** [comment]
So I can confirm that the Cordova bridge itself is leaking memory. I set up a simple `setInterval` loop to call into native Obj-C code that simply returns a result.

```javascript
setInterval(function() {
    cordova.exec(function() { console.log("notify succeeded");}, function() { console.log("notify failed");}, "CodePush", "doNothing", []);
}, 1000);
```

The corresponding native code:
```objectivec
- (void)doNothing:(CDVInvokedUrlCommand *)command {
    [self.commandDelegate sendPluginResult:[CDVPluginResult resultWithStatus:CDVCommandStatus_OK]
                                callbackId:command.callbackId];
}
```

I saw the same increase in memory. If I don't call into native code, but just do something stupid like a `console.log`, I don't see any increase in memory.

I will try to work with the Cordova runtime team to get this resolved.

**Comment by hilkeheremans** [comment]
That's interesting (and surprising). I will check again if using the classic WebView works around the issue. I don't like reverting to it, but we can probably live with it.

Is this a known issue at Cordova's end? Shouldn't we log this at their end if not?

**Comment by geof90** [comment]
Classic webview seems to also leak memory when I call sync in an interval, but in the classic webview case it seems it's not the bridge that's responsible.

**Comment by geof90** [comment]
So from my investigation it really seems that the WKWebView is definitely having a memory leak on the bridge, but when I reverted to the UIWebView, the memory increase is much slower. Both were tested by calling `sync` in an interval. I think you should file this on WKWebView. I was using `cordova-plugin-wkwebview-engine@1.0.3`.

**WKWebView**
![screen shot 2016-07-30 at 5 57 31 pm](https://cloud.githubusercontent.com/assets/8598682/17273964/2928b28e-567f-11e6-959a-e460ca082a0a.png)

**UIWebView**
![screen shot 2016-07-30 at 5 55 37 pm](https://cloud.githubusercontent.com/assets/8598682/17273965/2e026eda-567f-11e6-82df-5423e367371e.png)

**Comment by max-mironov** [comment]
So the issue appeared to be correlated to WKWebView and has nothing related with code-push side.
Will close this out, if you do see any problems on the code-push side please reopen or file a new issue, thanks!
