### ISSUE TITLE
how to display the current version to the user?

### ISSUE THREAD

**Issue by PierBover** [Microsoft/cordova-plugin-code-push#161]
According to the docs the object `LocalPackage` does not contain any info on the installed version.

https://github.com/Microsoft/cordova-plugin-code-push#localpackage

Is there any way to display a human version number such as `v5`?

**Comment by silhouettes** [comment]
It's a little bit strange, but I believe the field you're looking for is `label`. Does that help?

**Comment by PierBover** [comment]
Oh right. It wasn't clear from the docs that `label` represents the version.

> label: The internal label automatically given to the update by the CodePush server. This value uniquely identifies the update within it's deployment.

Thanks for the help @silhouettes 👍

**Comment by silhouettes** [comment]
That's a really good point, I've updated the docs:

 > label: The internal label automatically given to the update by the CodePush server, **such as `v5`**. This value uniquely identifies the update within it's deployment.

Glad to be of help :)
