### ISSUE TITLE
Loading error after code-push update using WKWebView plugin

### ISSUE THREAD

**Issue by seriouscircus** [Microsoft/cordova-plugin-code-push#163]
In my iOS app I want to make use of the better performance of the WKWebView. I am using the official `cordova-plugin-wkwebview-engine` plugin. But after a new code-push update package has been downloaded the restart mechanism can't open the new index.html file. It seems that the app has not the permission to read files from the new package folder.

the location of the current index.html file is
```
file:///var/mobile/Containers/Data/Application/F1C...52C/Library/NoCloud/codepush/deploy/versions/523...571/index.html
```

the location of the new index.html file which can't be loaded is
```
file:///var/mobile/Containers/Data/Application/F1C...52C/Library/NoCloud/codepush/deploy/versions/123...AF7/index.html
```

Everything is working again when I completely stop the app and restart it. Then the new index.html file can be served. (Using the UIWebView instead of WKWebView there are no problems replacing the code-push packages.)

Is there a solution for this problem?

I found a discussion about the `cordova-hot-code-push` plugin which seems to address the same problem: https://github.com/nordnet/cordova-hot-code-push/issues/85
There the issue ("By default, wkwebview doesn't allow to switch to another folder. WK plugin set's readAccessURL to the folder, that is 1 level up to the index.html. ") is resolved by setting the `readAccessURL` from inside the plugin. Is this is also a possible solution for the `cordova-plugin-code-push` plugin?

**Comment by seriouscircus** [comment]
problem solved by updating all plugins to latest version

**Comment by silhouettes** [comment]
Thank you for the update @seriouscircus!
