### ISSUE TITLE
Issue with iOS 10?

### ISSUE THREAD

**Issue by ingageco** [Microsoft/cordova-plugin-code-push#164]
Hey guys - I've been using this successfully in the simulator and in physical testing on iOS. Friday, pre-iOS 10 - my phone received the update fine. After updating, the simulator still works and receives the update - but my phone, now updated, isn't receiving the same update. 

Any advice? Is there a bug with iOS10 pushes?

**Comment by silhouettes** [comment]
Hi @ingageco - we have never had any issues with iOS updates before. Is it possible you ran into this issue? https://github.com/Microsoft/code-push/issues/319

If you don't mind, could you run the `code-push deployment history` CLI command and post the output here?

**Comment by ingageco** [comment]
Could the Content Security Policy meta tag setting also affect this? If so, why would the push work on android and the iOS sim, but not iOS production devices?

**Comment by silhouettes** [comment]
Sorry about the slow response - we will investigate this over the next two days.

**Comment by ingageco** [comment]
Continues to be an issue. Updates work fine in the simulator, but not on the device after pushing through the App Store.

**Comment by Muji86** [comment]
Hi, I'm having an issue where the iOS device (v 10) is nit updating.
Emulator(pre v10) works just fine.
Has this been resolved?

**Comment by max-mironov** [comment]
Hi @Muji86, @ingageco, do you still see the issue with the latest code-push plugin?
If yes then can you be more specific about the symptoms? Specific iOS version, the way you deploy the app, list of used plugins, is it repro on basic sample or not etc would be valuable.

**Comment by Muji86** [comment]
@max-mironov it's working fine now.
Can't really remember what I changed to resolve it.

Thanks

**Comment by max-mironov** [comment]
Thank you for quick reply @Muji86. I'm closing the issue for now, feel free to create a new one in case you have any questions.
