### ISSUE TITLE
Bug when closing and opening app

### ISSUE THREAD

**Issue by alissonlinneker** [Microsoft/cordova-plugin-code-push#168]
Whenever I make updates to the app using the code-push, it redirects to a page:

file:///data/user/0/com.myapp/files/codepush/deploy/versions/e6cb4cdsc5e36226a7a3047dc217cafcc871a132f1c86b59c5fcdbd511b73802/www/index.html

But if I finalize the app and open it again, it returns to display the old version:

file:///android_asset/www/index.html

Why? How to fix?

**Comment by silhouettes** [comment]
Is this on a simulator or a real device? Is it possible that your app is being rolled back? What does the `code-push deployment history` command show?

**Comment by pke** [comment]
I described a similar problem in #171

**Comment by wssss** [comment]
i'm facing the same problem .

and use 
```
code-push deployment ls myApp
```
avtive:0% (0 of 0);
Total: 0 ( 8 pending )

**Comment by wssss** [comment]
i'm facing the same problem ,
@silhouettes  
on real device ,  maybe app is rolled back .
use code-push deployment history
```
Active: 0% (0 of 0) 
Total: 0 (5 pending) 
```
like this , 

On android 4.4.2

**Comment by wssss** [comment]
sr , i didn't use these code.
```
codePush.async().
```
and add these code in my project it worked。

**Comment by max-mironov** [comment]
@wssss - thanks for posting it back, closing the issue for now, create a new one in case of any problems.
