### ISSUE TITLE
problem in updating the app (the update rolls back alternately!)

### ISSUE THREAD

**Issue by vahidreza** [Microsoft/cordova-plugin-code-push#170]
hi
i have installed the plugin on my cordova app and had released some updates. after releasing the update, and running my app, the app detects the update and logs a message stating that it has installed the update and this will affect at the next run. 
I restart the app and the update applies. but when I close and restart the app again, the update's gone and my app is in it's initial version.
if you check logs now you'll see it says again that an update is available and is installed and it'll be run after restarting the app.

what could possibly be wrong?

**Comment by silhouettes** [comment]
@vahidreza - we have an automatic rollback feature that is intended to shield you from bad updates. The way it works, is that if an update is considered 'bad' during its first run, it will be reverted once the app is restarted. You can use the `code-push deployment history` command to see how many rollbacks occurred on each release.

Assuming that your update is not crashing, my guess is that you're not calling `sync()` on app start, and hence need to call `notifyApplicationReady()` - see here: https://github.com/Microsoft/cordova-plugin-code-push#codepushnotifyapplicationready.

Does this help?

**Comment by vahidreza** [comment]
hi
thanks for the reply
I have put the sync function inside the checkforupdate function and that
seems to be a problem. why? don't know exactly but when I put the sync
function outside the mentioned update checking process it worked.

thanks again.
as a new question, is there any API so i can manage code-push server-side
tasks automatically?

**Comment by silhouettes** [comment]
I'm not sure what you mean by `checkforupdate` function here. Are you calling `sync()` inside `onDeviceReady()`? If not, you should call `notifyApplicationReady()` inside `onDeviceReady()`.

As for automated deployments, you can either write scripts against our CLI, or use our management SDK: https://github.com/Microsoft/code-push/tree/master/sdk.

Does this help?

**Comment by silhouettes** [comment]
I'm going to close this for now seeing as there is no response, but please feel free to follow up!
