### ISSUE TITLE
After code-push update is applied, cordova `deviceready` event is not respected

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#173]
I just had some rogue codepush deployment that was targeted at `^2.0.0` to crash my (beta) app.
The crash happened at a faulty check:
`export const canScan = () => window.cordova && !!window.cordova.plugins.barcodeScanner`

Apparently the function was called (from a react component `componentDidMount` callback) before cordova had been completely initialised.
The check works on app start, because it could only ever been called after the cordova `deviceready` event has been fired. Because upon that event I mount my react-app to the DOM.

So when this (yes, faulty) code crashes after an app restart (and codepush update applied) then it seems codepush is not respecting the cordova `deviceready` event.

That's my codepush handling code:

``` es6
function startApp() {
  navigator.splashscreen && navigator.splashscreen.show()
  render(
    <Root/>,
    document.getElementById("app"),
    () => {
      if (navigator.splashscreen) {
        setTimeout(() => {
          navigator.splashscreen.hide()
        }, 10)
      }
      if (window.codePush) {
        var updateReady = false
        const update = () => {
          // Make sure the splashscreen is shown before codepush restarts the app
          updateReady && navigator.splashscreen && navigator.splashscreen.show()
          window.codePush.sync(status => {
            updateReady = status === window.SyncStatus.UPDATE_INSTALLED
          }, {
            deploymentKey: api.CONFIG.codepush,
            installMode: window.InstallMode.ON_NEXT_RESUME,
          })
        }
        document.addEventListener("resume", update)
        update()
      }
    }
  )
}

if (window.cordova) {
  document.addEventListener("deviceready", startApp)
} else {
  startApp()
}
```

And my Scanner.jsx that crashes when `canScan()` is called and `window.cordova.plugins` is not defined

``` es6
import React from "react"

import Div from "components/Div"

const PROPTYPES = {
  // cancelled scans are reported as onScan(undefined)
  onScan: React.PropTypes.func.isRequired,
  onError: React.PropTypes.func.isRequired,
}

export const canScan = () => window.cordova && !!window.cordova.plugins.barcodeScanner

class Scanner extends React.Component {

  componentDidMount() {
    const { onError } = this.props
    if (!canScan()) {
      return onError(new Error("Keine Kamera vorhanden?"))
    }
    const androidPermissions = window.cordova && window.cordova.plugins.permissions
    if (androidPermissions) {
      androidPermissions.requestPermission(androidPermissions.CAMERA, ({ hasPermission }) => {
        if (hasPermission) {
          this.scan()
        } else {
          onError(new Error("Keine Berechtigung zur Benutzung der Kamera"))
        }
      })
    } else {
      this.scan()
    }
  }

  scan() {
    const { onScan, onError } = this.props
    window.cordova.plugins.barcodeScanner.scan(result => {
      if (result.cancelled) {
        onScan()
      } else {
        window.navigator.vibrate && window.navigator.vibrate(200)
        onScan(result.text)
      }
    },
    onError)
  }

  render() {
    return <Div/>
  }
}
Scanner.propTypes = PROPTYPES
export default Scanner
```

**Comment by TheBosZ** [comment]
This this happens to me as well. I've found that I have to reload the page in this case. That way the event gets fired correctly.

In my startup script, I check that window['codePush'] is defined, if not, I do a `window.location.reload()`

**Comment by max-mironov** [comment]
Hey @TheBosZ, thanks for letting us know. At that moment could you please share with us the sample code (with exact repro steps) where and how we could reproduce the issue? Do you see that the issue could be reproducible within our [sample app](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic)?

**Comment by max-mironov** [comment]
@TheBosZ, just a friendly ping on this :)

**Comment by TheBosZ** [comment]
@max-mironov I'll see if I can make a minimal code that reproduces this, but I'm not the original bug reporter. The original guy has repro code in his message.

**Comment by max-mironov** [comment]
@TheBosZ thanks, got it. If you could reproduce the issue and share your minimal code example with us -
 that would be awesome.

**Comment by max-mironov** [comment]
@TheBosZ - hi, did you get a chance to try to make a minimal code that reproduces this issue?

**Comment by TheBosZ** [comment]
I haven't been able to, so I think my problem was unrelated.

**Comment by max-mironov** [comment]
@TheBosZ  got it and thanks for looking at it!
