### ISSUE TITLE
Android compilation fails after adding the plugin (Java version compatibility)

### ISSUE THREAD

**Issue by dchekanov** [Microsoft/cordova-plugin-code-push#174]
After adding this plugin, `cordova run android` fails to compile the code saying that some of the code is not compatible with Java 1.6. Please see the attached log for details. I had to use [another plugin](https://github.com/cvuser0/cordova-plugin-java7) to forcefully set Java compatibility to 1.7 for the app to build.

Cordova 6.3.1, plugin 1.8.2-beta, JDK 1.8, macOS Sierra.

[log.txt](https://github.com/Microsoft/cordova-plugin-code-push/files/529320/log.txt)

**Comment by dchekanov** [comment]
The issue was not related to this plugin.

**Comment by silhouettes** [comment]
Thanks for the update!
