### ISSUE TITLE
App freezes on update - waiting for fixed version

### ISSUE THREAD

**Issue by galsch** [Microsoft/cordova-plugin-code-push#175]
Hi guys,

Following this thread:

https://github.com/Microsoft/cordova-plugin-code-push/issues/156#issuecomment-235649494

A fixed version to the problem was supposed to be released already. 

Is there an updated ETA for this release?

Thanks

**Comment by silhouettes** [comment]
I'm so sorry we didn't end up publishing it - this has now been published in `1.9.0-beta` ([release notes](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.9.0-beta)). Thanks so much for your patience.

**Comment by galsch** [comment]
@silhouettes Awesome, thanks for all the help. We will integrate the new version now and if there will be any issue we'll update. Have a great day!

**Comment by galsch** [comment]
@silhouettes hi, we are trying to get the latest version with

`cordova plugin add cordova-plugin-code-push@latest`

or

`cordova plugin add cordova-plugin-code-push@1.9.0-beta`

but when running `cordova plugins ls` I see:

`cordova-plugin-code-push 1.8.2-beta "CodePush"`

How can we get the new version?

Thanks

**Comment by silhouettes** [comment]
Hi @galsch, thanks so much for pointing this out. We had bumped the `package.json` version but not the `plugin.xml` of our project. You would have gotten the right package, but the version you were displayed (`1.8.2-beta`) was incorrect. I've fixed this small issue and made another release, `1.9.1-beta`.

**Comment by galsch** [comment]
@silhouettes thanks for the quick reply & fix. I've verified and indeed now it's `1.9.1-beta`.

Thanks!
