### ISSUE TITLE
Could not delete file

### ISSUE THREAD

**Issue by ingageco** [Microsoft/cordova-plugin-code-push#180]
Hey guys - I am having a problem after the update is downloaded. Here's my logs: 

`6     550937   log      [CodePush] Installing update
7     551291   log      Could not delete file: www/scripts/app-714b86ed3d.js
8     551344   error    [CodePush] Preinstall failure.
9     551345   error    [CodePush]  An error has occured while installing the package. Could not find start page in package.
10    551346   error    [CodePush] An error occurred during sync.`

Any idea why I would be receiving this error? The www folder is fairly standard, and I'm releasing the same way I have with other apps successfully.

**Comment by ingageco** [comment]
Note - the app-*.js file is generated by gulp in gulp -b. So that file differs by name each time I believe, and is injected to index.html . Could that be causing issues with codePush?

**Comment by ingageco** [comment]
Anyone? @silhouettes ?

**Comment by max-mironov** [comment]
Hi @ingageco ,
I've tried to repro the issue on both ios/android devices. I've added an app to code push, then released the app with modified index.js file name to index-12345.js and updated the reference to this js file in index.html accordingly. No issue occurred, update was downloaded and installed successfully..

Can you please provide us with exact repro steps or maybe you have small example you can share?

**Comment by ingageco** [comment]
Thanks for the info @max-mironov . I've put the code push functionality on hold for now since I couldn't get it to work in this project, but I'll revisit it in the next few weeks and report back.

**Comment by max-mironov** [comment]
Hello @ingageco, just a friendly ping :) Do you have a chance to verify if you are still experience this issue?

**Comment by max-mironov** [comment]
@ingageco - we are closing this issue for now, please feel free to reopen or create a new one if you needed.
