### ISSUE TITLE
Phonegap Build, CodePush has some problems. 

### ISSUE THREAD

**Issue by oleksiy-nesterov** [Microsoft/cordova-plugin-code-push#182]
Basically, it works fine, but here is two problems.

1) In case, if app asks Location Permission, the permission dialog shows full path for new index.html (should show App's name only, like "**MyApp** would like to use your current location")   

2) After app restart, app rolls back to previous content. Code-push log is: "[CodePush] An update is available, but it is being ignored due to have been previously rolled back."

`code-push release MyApp ./www 2.7.3 --des "Test. Again!"`

Anybody know how i can get around this problems?
thx

**Comment by oleksiy-nesterov** [comment]
anybody here?

**Comment by silhouettes** [comment]
Hi @oleksiy-nesterov, the CodePush run-time depends on a call to `CodePush.notifyApplicationReady()` on `deviceready` to 'rubber stamp' an update as successful - the absence of this will cause a rollback. This is why we prescribe calling `CodePush.sync()` on app start at minimum (which calls this under the covers), but if you don't call it there you should just call `CodePush.notifyApplicationReady()` directly. Does this solve the rollback problem for you?

Regarding your first point, we'll have to investigate it, but as we are currently at capacity on a number of our projects it may be a while before we are able to get back to you. If anybody else from the community would like to investigate or has ideas here, we would love your input!

**Comment by oleksiy-nesterov** [comment]
Hi, @silhouettes 

1) It looks like: 
![wp_20161117_12_51_16_pro](https://cloud.githubusercontent.com/assets/765086/20387891/09544598-accb-11e6-93c1-20fa0a37ea97.jpg)

2) My code is: (pretty simple, seems like **notifyApplicationReady** does not help)

```javascript
<script>
    window.checkHotUpdates = function(){
        if(window.codePush){
            window.codePush.notifyApplicationReady(); // added just for testing
            window.codePush.sync( // works, but after app restart, app rolls back to previous content.
                null ,{
                    updateDialog: {
                         appendReleaseDescription:true,
                         descriptionPrefix:'\n\nChange log:\n'
                    },
                    installMode: InstallMode.IMMEDIATE
                }
            );
        }
    };
    document.addEventListener('deviceready', window.checkHotUpdates, false);
</script>
```

**Comment by once** [comment]
I'm facing the same issue as @oleksiy-nesterov  : 
An android app, built with Phonegap Build, **rolls back to previous version** after first "install" of code-push-served update. 
The command  `code-push deployment history Appname Staging`  for example always says that there are **Pending installs (but NOT complete).**

To prove it, here I peresent details of my experiment:

1. I took your [sample application](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic) .
2. I created empty Cordova CLI project (named App3) and placed www-contents from your sample app in it.
3. I **built it using Cordova CLI** , then installed APK to Android emulator.
4. I made some change to index.html, and released an update:
`code-push release-cordova App3 android`
5. I launched app on emulator, it successfuly found that an upadte is available and promised to install it on next restart
6. I killed the app process, restarted the app again.
7. The new version was successfully installed and `code-push deployment history App3 Staging` command suggested that 1 Active install was succesfully completed.
8. Then I made a build using PhoneGap Build  ( I  have <preference name="android-build-tool" value="gradle" />	in my config.xml - as it's said that we need to use Gradle in phonegap build case)

9. I cleaned my Android emulator of the previous crodova-cli-built version of an app.
10. I installed the new phonegap-built version of an app to an emulator
11. I launched it on emulator and got message that app is up-to-date - that's correct.
12. I again made some change to index.html, and released an update:
`code-push release-cordova App3 android`
13. I killed app process on emulator and then launched it again.
14. The app succesfully discovered update available and promised to install it on next restart.
15. I restarted the app.
16. The new version of app seems to be active.
17. I check command `code-push deployment history App3 Staging` . It still says that there are NO active installs ! The install is PENDING !
18. I restart the app on emulator
19. App rolls back to previous version :(

**Comment by once** [comment]
To add to the previous :  I face this problem **only with Android builds** made with PhonegapBuild.   

**iOS builds**, made with PhonegapBuild **are OK** - they succesfully apply further code-push updates and do not roll back.

**Comment by max-mironov** [comment]
Hello @once - I'm sorry for so late reply.
Is it possible that you have the same issue as here - https://github.com/Microsoft/cordova-plugin-code-push/issues/232?
Can you please verify and let us know if you still have an issue here.

**Comment by max-mironov** [comment]
@once, just a friendly ping :)

**Comment by max-mironov** [comment]
Guys - I'm closing the issue currently as of no response, feel free to revisit it when you have time and let us know if any questions.
