### ISSUE TITLE
Update Many App with different Config.xml

### ISSUE THREAD

**Issue by TechGuyVN** [Microsoft/cordova-plugin-code-push#185]
Hi,

I use this plugin to my ionic app. 
In my app i have one source code and build many app, each app have a different config.xml exp: bundleid, name ...
I try with single application work perfect, but when i use to update code for 2 app with different id , it's failed, app turn to black nothing show.

My question: how to update one souce, one code-push key for many cordova app. Can we config some file not tobe replace when code-push update !

Many thanks

**Comment by sergey-akhalkov** [comment]
@TechGuyVN, sorry for the slow response. Have you resolved your question? Please let me know if you need any help.

**Comment by sergey-akhalkov** [comment]
@TechGuyVN, just a friendly ping.

**Comment by sergey-akhalkov** [comment]
Closing this, please feel free to reopen.
