### ISSUE TITLE
build error iOS: Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_SSZipArchive"

### ISSUE THREAD

**Issue by Zvika88** [Microsoft/cordova-plugin-code-push#186]
hi codePush team,
It works fine for me on Android, but when building for iOS via XCode I am getting the following error:

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SSZipArchive", referenced from:
      objc-class-ref in ZipPlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

or, if I use command line "cordova build ios" I am getting:

`The following build commands failed:
	CompileC build/PettingClub.build/Debug-iphonesimulator/PettingClub.build/Objects-normal/i386/ZipPlugin.o PettingClub/Plugins/cordova-plugin-zip/ZipPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
`

Any suggestions or ideas how to solve that?

**Comment by Zvika88** [comment]
problem solved: had tor (forcefully) remove the zip plugin, then add it:

`cordova plugin rm cordova-plugin-zip --force`

then:

`cordova plugin add cordova-plugin-zip --save`

Cheers,
Z.

**Comment by silhouettes** [comment]
Thanks for the update!
