### ISSUE TITLE
Unable to connect to the CodePush server. Are you offline, or behind a firewall or proxy?

### ISSUE THREAD

**Issue by thebasix** [Microsoft/cordova-plugin-code-push#191]
I want to release an update but I get this error:

`[Error]  Unable to connect to the CodePush server. Are you offline, or behind a firewall or proxy?
  (getaddrinfo EAI_AGAIN codepush-management.azurewebsites.net:443)`

Why is this happening?

**Comment by vladimir-kotikov** [comment]
Closing this, as it has been resolved. @thebasix, feel free to reopen if you run into this again

**Comment by hanishs17** [comment]
I am also getting the same error.
