### ISSUE TITLE
Content Security Policy Question

### ISSUE THREAD

**Issue by yoavpa** [Microsoft/cordova-plugin-code-push#194]
Hi,

We have a question regarding how to alter our current CSP in our project.

Currently our CSP looks like this:
< meta http-equiv="Content-Security-Policy"
          content="default-src 'self' 'unsafe-eval' 'unsafe-inline' ourdomain:* data: *.ourdomain.com ams.ourdomain.com cdn.mxpnl.com candle.ourdomain.com billing-pci.ourdomain.com ourdomain-cdn.ourdomainstatic.com file:* * gap://ready wss://* ws://*" >

In your documentation it specifies to add
https://codepush.azurewebsites.net to the Content-Security-Policy meta tag in your index.html file in the following way:

Here’s the doc’s example:
< meta http-equiv="Content-Security-Policy" content="default-src https://codepush.azurewebsites.net 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *" / >

So, in order to support code push, we changed the CSP to looks like this:

 < meta http-equiv="Content-Security-Policy"
          content="default-src 'self' 'unsafe-eval' 'unsafe-inline' ourdomain:* data: *.ourdomain.com ams.ourdomain.com cdn.mxpnl.com candle.ourdomain.com billing-pci.ourdomain.com ourdomain-cdn.ourdomainstatic.com file:* * https://codepush.azurewebsites.net gap: https://ssl.gstatic.com https://codepushupdates.azureedge.net ; style-src 'self' 'unsafe-inline'; media-src *  gap://ready wss://* ws://*" >

Unfortunately, This change caused issue in accessing sources in other domain.

Could you please tell us how to update correctly the CSP so it will be the minimal changes from our current CSP while still supporting CodePush?

Thanks,
Yoav

**Comment by vladimir-kotikov** [comment]
@yoavpa, there is no need to add neither `style-src` nor `media-src` directives to your CSP.  You need to add _only_ `https://codepush.azurewebsites.net` entry. I.e. `content` attribute of your CSP would look like this (note that line breaks are only for readability purposes):
```
default-src
    'self'
    'unsafe-eval'
    'unsafe-inline'
    ourdomain:*
    data:
    https://codepush.azurewebsites.net
    .ourdomain.com
    ams.ourdomain.com
    cdn.mxpnl.com
    candle.ourdomain.com
    billing-pci.ourdomain.com
    ourdomain-cdn.ourdomainstatic.com
    file:
    *
    gap://ready
    wss://*
    ws://*
```

**Comment by yoavpa** [comment]
Great, thanks Vladimir!

**Comment by vladimir-kotikov** [comment]
No problem :) Did that fix issues with accessing to other addresses?

**Comment by yoavpa** [comment]
Actually, it works fine now also without adding  https://codepush.
azurewebsites.net

Is it really needed?

Thanks,
Yoav

On Tue, Dec 20, 2016 at 10:41 AM, Vladimir Kotikov <notifications@github.com

**Comment by vladimir-kotikov** [comment]
Hmm.. I didn't notice it first time but it looks like your `default-src` already has a `*` which basically allows access to everything - using it you don't need to add codepush hosts to CSP of course :)

If you still have any other issues with whitelist and CSP you might want to check [Cordova whitelist and Content Security Policy guide from VS TACO docs](https://taco.visualstudio.com/en-us/docs/cordova-security-whitlists/#the-w3c-content-security-policy-csp)

**Comment by yoavpa** [comment]
Great, thanks Vladimir!

On Tue, Dec 20, 2016 at 12:04 PM, Vladimir Kotikov <notifications@github.com
