### ISSUE TITLE
Ability To Clear Older Versions?

### ISSUE THREAD

**Issue by TombolaShepless** [Microsoft/cordova-plugin-code-push#195]
I have looked through the docs, issues and the source code but I'm still non-the-wiser!

How many deployments does CP hold onto on the device? Obviously this builds up a lot over time and eats storage up. If CP does hold onto all deployments locally then is there anything on the roadmap to allow the client to "tidy up" whether that be automatic or in the developers hands?

Many Thanks.

**Comment by silhouettes** [comment]
Hi @TombolaShepless, the CodePush SDK will hold onto at most two updates at any time (the old one being there as long as a rollback is possible). You can see where the old package is being cleared [here](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/src/ios/CodePush.m#L101). Hope that helps!

**Comment by TombolaShepless** [comment]
@silhouettes brilliant - thank you
