### ISSUE TITLE
Updating from store doesn't update www/ path

### ISSUE THREAD

**Issue by scopsy** [Microsoft/cordova-plugin-code-push#198]
I'm using codepush on a cordova application, And I published a codepush version for v0.6.0.

I had add extra SDK's and uploaded new binaries to app store, When the user downloads the update from the appstore the codepush plugin still points the user to the old version location.

Is there a way that when the app is update from the store it will be used as the latest version? (In the case that codepush doesn't know a newer version).

I want to avoid the situation which will cause my users to download 2 updates, one from the store and than again from codepush.

**Comment by silhouettes** [comment]
Hi @scopsy, we expect that, when you push a version to the store, you will also push it to CodePush. This is useful not only for the reason you mentioned, but also to allow us to generate diffs against your subsequent updates. The SDK should be intelligent enough not to install the update if its hash matches the one that was shipped to the store.

In future, we can also consider a timestamp-based approach that prevents an older update from being applied to a binary, but there are some technical questions here that we're still working out.

Hope this helps!

**Comment by chineseneo** [comment]
Hi @silhouettes , the thing is, even if we publish a store app and codepush at the same time, the user always have to experience a "nothing changed" update until the codepush update is downloaded and installed and reloaded. I think this could be a very bad user experience. What do you think?
