### ISSUE TITLE
Ionic angularjs: getDeploymentKey error

### ISSUE THREAD

**Issue by wengseng300** [Microsoft/cordova-plugin-code-push#203]
I've created a thread in Stackoverflow but no respond so far:
http://stackoverflow.com/questions/41501172/ionic-code-push-error-codepush-getdeploymentkey

Basically, I had done the following:
1. Add deployment key to config.xml
2. I have <access origin="*" /> in config.xml
3. Insert into index.html header:<meta http-equiv="Content-Security-Policy" content="default-src https://codepush.azurewebsites.net 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *" />
4. cordova-plugin-whitelist is installed

When I call `codePush.sync()` in app.js, I hit error with "CodePush.getDeploymentKey". It seems that my deployment key could not be found. 

I tried hard-code the deployment key in codePush.js (which I know it's a bad idea) just to give it a try. And then I face the error "CodePush.getServerURL" this time. 

I have no idea what's missing or what did I do wrong. 

Please help. Thanks

**Comment by vladimir-kotikov** [comment]
@wengseng300, it's not possible to run the app in Ripple, as you're trying to do. Ripple provides a basic support for core Cordova plugins like Geolocation and Device Orientation, while CodePush heavily relies on functionality, implemented using native code, which can't be simulated in the Ripple.

To test the app with CodePush plugin you'll need to run it either on device or in Android emulator.

**Comment by wengseng300** [comment]
@vladimir-kotikov Hello. Thank you very much for your reply. 

As suggested, I had deploy my app into an android device and inserted the code below to test if code push is working:

```
codePush.checkForUpdate(function (update) {
            if (!update) {
                var alertUpdated = $ionicPopup.alert({
                    title: 'Updated',
                    template: 'The app is up to date!'
                })
            } else {
                var alertUpdated = $ionicPopup.alert({
                    title: 'New Release',
                    template: 'An update is available! Should we download it?'
                })
            }
        });
```

But there is no pop up at all. Am I using the right way to check if code push is initialized or any other better way?

Thanks

**Comment by vladimir-kotikov** [comment]
@wengseng300, are there any errors in Javascript console? Could you please also run `code-push debug android` in console to see if there any code-push issues?

**Comment by sergey-akhalkov** [comment]
@wengseng300, are you still experiencing the issue? Please let me know if I could help you.

**Comment by max-mironov** [comment]
Closing for now, please reopen if you still experience the issue.
