### ISSUE TITLE
Question about plugins

### ISSUE THREAD

**Issue by epicfaace** [Microsoft/cordova-plugin-code-push#204]
Since code-push doesn't update native code like plugins, then, if you release a new version of an app with a new plugin, and then code-push some changes to Production, is there a way to make sure that it only reaches only the new version?

Otherwise it seems like if you use any plugin code, it will break all older versions of the app.

**Comment by vladimir-kotikov** [comment]
@epicfaace, `code-push release-cordova` by default publish updates that are only applicable to the current binary version of the app (see `targetBinaryVersion` documentation [here](http://microsoft.github.io/code-push/docs/cli.html#target-binary-version-parameter)), so if you have published a new version of the app, all new code pushes will be installed to that new version only.

**Comment by epicfaace** [comment]
Great, thanks!
