### ISSUE TITLE
How do I register on a second computer?

### ISSUE THREAD

**Issue by MichaelApproved** [Microsoft/cordova-plugin-code-push#205]
How would I login on a second or multiple computers? When I ran the `code-push register` command and logged in, I go the following error:

"You are already registered with the service using this authentication provider.
Please cancel the registration process (Ctrl-C) on the CLI and login with your account."

So, how would I get the access key on a second computer?

I'm doing this because I develop Android on my Windows machine and iOS on my Mac.

Thanks!

**Comment by vladimir-kotikov** [comment]
@MichaelApproved, you need to use `code-push login` on the second machine to log into existing code-push account

**Comment by MichaelApproved** [comment]
Thanks. I'm exploring the command line more and see these options now.
