### ISSUE TITLE
CodePush logic

### ISSUE THREAD

**Issue by Muji86** [Microsoft/cordova-plugin-code-push#206]
Will CodePush sync if the apk/ipa is built after the last code push?
If I have built my app with code different to the latest version in codepush I wouldn't want it to sync, is there any logic for this or will I always get the latest version from the CodePush servers?

**Comment by max-mironov** [comment]
Hi @Muji86, if you rebuild your ipa/apk and do not increase your build version then your app will be updated with latest code-push release targeting your app version. 
So for major changes that can potentially break your app/can have compatibility issues it would be better to always bump current version of the app in android manifest or iOS plist file. 
Also you can have more granular control over how the updates will be distributed to your app via _target binary version_ parameter. Please refer to https://microsoft.github.io/code-push/docs/cli.html#link-4 -> **Target Binary Version Parameter** section for more details.
