### ISSUE TITLE
can't show the newest www folder's content after app is updated fully 

### ISSUE THREAD

**Issue by magude** [Microsoft/cordova-plugin-code-push#213]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
after app is  updated by code-push, app will not show the new www's content when users update app fully.
I know how the question is caused,that is code-push has changed the location of index.html, but the newest www's content is contained in assets folder.
I want to know how to change index location to the original path.

* cordova-plugin-code-push version: 1.9
* List of installed plugins:
code-push 1.9.0-beta "CodePushAcquisition"
com.qdc.plugins.wxpay 1.0.0 "WeixinPay"
com.qinsilk.updateapp 1.1.0 "UpdateApp"
com.rd11.remote-controls 1.0.1 "RemoteControls"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-plugin-alipay 0.10.0 "AlipayPlugin"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-background-download 0.0.2 "Background Download"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-code-push 1.9.2-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-media 2.4.0 "Media"
cordova-plugin-nativeclicksound 0.0.3 "Native Click Sound"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 1.5.1 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.background-mode 0.6.4 "BackgroundMode"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
* Cordova version:6.2
* iOS/Android/Windows version:android 7
* Does this reproduce on a debug build or release build?
release build
* Does this reproduce on a simulator, or only on a physical device?
all tested
* Repro steps and/or stack trace:

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
@magude, thanks for posting this. Do I get it right that by "users update app fully" you mean situation when the app version was bumped? If so than the issue might be fixed with the following changes: 
https://github.com/Microsoft/cordova-plugin-code-push/pull/201/files and
https://github.com/Microsoft/cordova-plugin-code-push/pull/202/files.
Please let us know if we are correct in our assumptions.

**Comment by magude** [comment]
I mean that my app can't read "file:///android_asset/www/" when users setup a newest app version(e.g v2.1.3, current version is v2.1.2) in overwrite mode(not only update www folder, but also update java code,res folder,etc.)
In other words, all of the app is replaced by the newest builded one. In this time, app should show the newest "file:///android_asset/www/" folder, but in fact, the app  is still showing the old www's folder,like "file:///data/user/0/cn.ivoix.app/files/codepush/deploy/versions/ab3670f1d921c71cda492331eec60905ef4e38c4d1a8e539a41feb5d06bee6fc/www/".
current:
![v0](https://cloud.githubusercontent.com/assets/18024116/22766147/cc9f6da0-eeae-11e6-8ae0-790593af108c.jpg)
newest:![v1](https://cloud.githubusercontent.com/assets/18024116/22766123/aac1caca-eeae-11e6-83b3-5272c6ff2ecd.jpg)

**Comment by magude** [comment]
I have solve this problem in my way. This method is  a little rude , that is checking current version code vs. new version code and delete code-push folder if it is necessary.
please provide a better solution offically, thanks.
By the way, this plugin's ios version is very well.

**Comment by max-mironov** [comment]
@magude, thank you for this, we appreciate your feedback! We are going to include those pull requests when new version of cordova-plugin-code-push will be released. If you don't mind I'm closing the issue for now, feel free to open new one if you have any troubles with code-push.
