### ISSUE TITLE
Does reducing the js size help load the app faster if done through CodePush

### ISSUE THREAD

**Issue by Muji86** [Microsoft/cordova-plugin-code-push#214]
Reducing the js size on a hybrid app will help speed up the initial load. My question is will this also be true if the js codepushed is reduced or will the original js always try to load first?

**Comment by sergey-akhalkov** [comment]
@Muji86, sorry for slow response, could you please clarify what you mean by "if the js codepushed is reduced or will the original js always try to load first"?

**Comment by Muji86** [comment]
@sergey-akhalkov 
I am using Ionic 2 and they have changed their compiler so that the final js file for the app is smaller than before. The main gain for this is performance where the initial load of the app is meant to be a couple of seconds quicker.
So when I use the new compiler I will have a smaller js which I will then release using code push.
The question is, will I benefit from the performance gain of the smaller js file? bearing in mind the initial apk was released with the older compiler and has a larger js file.
As I understand it, anything released via code push doesn't physically replace the original file released in the apk (for android) so I'm not sure if the loading process bypases the original files or if they still need load first.

**Comment by sergey-akhalkov** [comment]
@Muji86, oh, sorry, I've totally missed it. 
>will the original js always try to load first

I think reducing the js files size will help you to load the app faster, because CodePush uses [new package location](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/www/localPackage.ts#L67) where all app assets will persist. 

Please let me know if it helps.

**Comment by Muji86** [comment]
@sergey-akhalkov Thanks. That answers my question

**Comment by sergey-akhalkov** [comment]
Closing this, please feel free to reopen if needed.
