### ISSUE TITLE
Unable to get app to update content

### ISSUE THREAD

**Issue by djsimanton** [Microsoft/cordova-plugin-code-push#217]
I've create a number of basic Cordova apps. No problem there. I love the concept that the code-push plugin provides. I just haven't been able to make a test app work. I've followed the through the "Getting Started" guide. I've followed the Cordova Client SDK guidelines.  I even found a step by step guide (https://www.sitepoint.com/push-code-updates-to-apps-instantly-with-codepush/) that I was able to follow through step by step to see if I might be missing something. I can't see that I'm missing anything.

I have the latest code-push plugin version - 1.9.2-beta
Plugins include: compat 1.1.0; device 1.1.4; notification 1.3.1; file 4.3.1; file-transfer 1.6.1; whitelist 1.3.1; and cordova-plugin-zip 3.1.0

Cordova version 6.5.0
Windows 7.0
I'm experiencing this when I run the app on my Android 6.0.1 Samsung phone. The app builds and runs fine. It updates onto the code-push server fine. It just appears that the app does not recognize that there is an update that needs to be downloaded. I believe I have all the necessary edits made in the config.xml file to specify my deployment key and to allow access to code-push servers. I believe I have the necessary edits in the index.html file related to content security in the meta line. This is the file that i make changes to and then update them through the CLI to the code push server. But the changes are not recognized and downloaded to the app. I believe I have the necessary edits in the index.js file so that when the device is ready it will check for and update to download new content. 
After I update the content on the code-push server. I end the app on my phone. I then restart it expecting it to load new content or to recognize that there is new content to download to then make available on the next restart. But even the next restart of the app shows the old content.

I've uploaded a doc file with the content of my index.html, config.xml, and index.js files. I appreciate any help to get this working.

[code push file content.docx](https://github.com/Microsoft/cordova-plugin-code-push/files/776961/code.push.file.content.docx)

**Comment by max-mironov** [comment]
Hi @djsimanton. On the first sight your code looks good, Can you please provide us what
` code-push deployment history` or `code-push deployment ls `
commands show for your application and your deployment? Do you have any pending/failed install records in install metrics column?

**Comment by max-mironov** [comment]
@djsimanton - Hi again, please let us know if you still have the issue above or if we could close the current one?

**Comment by djsimanton** [comment]
Nothing has changed. I'll get the logs requested and post them.

**Comment by djsimanton** [comment]
When I run the command "code-push deployment ls" I get as seen in the attached image. It shows no installs recorded. But I can see that my updates to the code-push server are happening. They are are not getting installed on my app when I refresh or restart it.
![image](https://cloud.githubusercontent.com/assets/7088662/23149151/a19cb53c-f81c-11e6-86a7-58bed54fd57a.png)
When I run the command "code-push deployment history APPNAME staging" I get as seen in the attached image.
![image](https://cloud.githubusercontent.com/assets/7088662/23149491/cf570174-f81e-11e6-8f8f-ff84fffe7c48.png)
In order to get this to not return an error or unfound deployment message I had to run the command "code-push deployment add APPNAME staging"
After this I ran the app on my phone. Then I made a change to the index.html file and saved it. Then I ran the update command again - "code-push release-cordova APPNAME android"
After I closed the app and restarted it there is no update. You can see in the attached image the screen printout from this command.
![image](https://cloud.githubusercontent.com/assets/7088662/23149562/5223f008-f81f-11e6-9fb2-97a21b5fadb5.png)
I've tried running "code-push debug android" and it just sits "listening for android debug logs" even though I have my phone connected which I just installed the app onto.
To me it appears that I'm getting it onto the code-push server but there is something not happening correctly between my app and the code-push server to recognize that an update needs to be downloaded. This is where I need help.

**Comment by max-mironov** [comment]
Hi @djsimanton, thanks for reply. 'no install records' means that no updates were even downloaded to any devices,
The command "code-push deployment add APPNAME staging" is showing nothing, because it is case-sensitive, so you should use 'Staging", not "staging".

As for case where you are not able to dl any updates - is it possible for you to attach to device via e,g, chrome debugger to see if any exceptions are showing in the console?
Especially to see what codePush.js -> checkForUpdate function is doing actually. 
Also have you tried to reproduce this on e.g. simulator?

**Comment by djsimanton** [comment]
Thanks for the pointer about case-sensitive. I've run the command again and you can see the history now in the screen shot I've attached.
![image](https://cloud.githubusercontent.com/assets/7088662/23159366/19464048-f855-11e6-9ccd-d0ef474fe306.png)
I've been able to get the content running in Chrome and the debugger as you have suggested. I'm not sure how to check to see what codePush.js is doing or where to look for it. See my screenshot.
![image](https://cloud.githubusercontent.com/assets/7088662/23159876/06453d9e-f857-11e6-8b86-8d1058b12987.png)
It appears that it is failing to load some resources.  And I don't see the codePush.js resource if it should be there. Is there somewhere else I should be looking to find out what codePush.js is doing? See Screenshot.
![image](https://cloud.githubusercontent.com/assets/7088662/23160087/b911855e-f857-11e6-93bf-17b404640f10.png)
I've not tried to do this on a simulator as it's just easier and faster to plug my phone in. A Samsung J7Prime.

**Comment by djsimanton** [comment]
Oh. I realize now when I'm looking in the Chrome debug I've loaded my the website but it's not the app content so it's not showing anything about the codePush.js. Can you give me further hints of where to go to get the correct content loading into Chrome debugger?

**Comment by djsimanton** [comment]
I've been able to access through Chrome Debug the app on my phone. See Screenshot.
![image](https://cloud.githubusercontent.com/assets/7088662/23161058/435adbc2-f85b-11e6-8bbb-08cb310a15fc.png)
But when I click on the file link then I get this:
![image](https://cloud.githubusercontent.com/assets/7088662/23161075/4feccdd2-f85b-11e6-98e5-fbc06bcab925.png)
If I click on the inspect link. I get this: There is no reference to codePush.js
![image](https://cloud.githubusercontent.com/assets/7088662/23161127/76862574-f85b-11e6-89c3-83baf0188d7f.png)

Does this help you to be able to tell me how to fix my problem? Am I missing a reference to codePush.js?

**Comment by max-mironov** [comment]
@djsimanton, is it possible for you to reach me via slack/skype/discord IM? So this way we can try to faster identify the issue? Do you have any contacts I can connect to you?

**Comment by djsimanton** [comment]
skype dsimanton

**Comment by djsimanton** [comment]
Thanks for the help! Problem solved now!

**Comment by roalts** [comment]
Can you please explain how was the problem resolved, I am also facing a similar problem. Any leads would be appreciated! Thanks.

**Comment by ruslan-bikkinin** [comment]
@roalts thanks for reaching us. Please fill new issue with more detailed information about your codepush configuration, environment so we be able to provide you help quicker.
