### ISSUE TITLE
Xcode warnings

### ISSUE THREAD

**Issue by dchekanov** [Microsoft/cordova-plugin-code-push#218]
I receive a number of warnings from this plugin during the build in Xcode:

1. CodePushReportingManager.m:35:42: Undeclared selector 'evaluateJavaScript:completionHandler:'
2. CodePushReportingManager.m:36:39: Undeclared selector 'evaluateJavaScript:completionHandler:'
3. InstallOptions.m:15:38: Implicit conversion loses integer precision: 'NSInteger' (aka 'long') to 'int'
4. UpdateHashUtils.m:66:32: Implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'CC_LONG' (aka 'unsigned int')

* cordova-plugin-code-push version: 1.9.2-beta

**Comment by max-mironov** [comment]
Closed due to https://github.com/Microsoft/cordova-plugin-code-push/pull/235 has been merged, @dchekanov thanks for pointing at this!
