### ISSUE TITLE
App Start up time increases after any code push update in the App

### ISSUE THREAD

**Issue by PrithiviRajG** [Microsoft/cordova-plugin-code-push#221]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* cordova-plugin-code-push version: latest version
* Cordova version:6.4.0
* iOS/Android/Windows version: Android 5.1
* Does this reproduce on a debug build or release build? Release Build and debug build
* Does this reproduce on a simulator, or only on a physical device? Physical Device
* Repro steps and/or stack trace:

1. installed the App without code push changes, App started at 5 seconds
2. deployed the code changes with code push and reopened the App. code push updated the changes at background and I am able to see it in console.
3. opened the app again and it took more 14 seconds and it's fetching values like this data/data/io.ionic.vocabBrawl/files/codepush/deploy/versions/8c9fc792fe88ef77cdafc3b2f15f735a4e10122315d48ab2661fc87ad307b6ad/www/index.html
4. After code push update, App takes more than 14 seconds at every instance.

Thanks

**Comment by napcat** [comment]
I think I have the same problem...

I'm testing CodePush and it works great, but here's an issue. After an update the app starts slow, it takes more time to boot.

For exemple, install the app... takes 1/2 secs to boot and be in the main screen.
Release an update and install it and restart the app.
The app now (with the new update) takes about 5/6 seconds to boot (on a OnePlus 3T).
Go to Android settings and clean the cache.
The update is removed and the app boots again with a 1/2 seconds delay.

Is this suposed to happen?

What is happning when a update is done? Does it try to install it again? Is just file checking every file?

**Comment by pniko** [comment]
@napcat please refer to #275 for a suggestion on how to improve performance.

> In that case you can bundle bower libraries and you app code separately, because bower packages are changing not so often as app.
