### ISSUE TITLE
TypeError: Cannot read property 'is' of undefined 

### ISSUE THREAD

**Issue by ThibaultLesuisse** [Microsoft/cordova-plugin-code-push#223]
When trying out Code-Push I noticed this promise issue in an Ionic 2 app. Maybe it's because code-push is not available. 

Error
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'is' of undefined
TypeError: Cannot read property 'is' of undefined

**Comment by max-mironov** [comment]
Hi @ThibaultLesuisse,
I've tried the following:
1) Create new blank Ionic2 project 
  $ ionic start MyIonic2Project blank --v2
2) Added Android platform to test with 
  $ cordova platform add android
3) Added code push plugin
 $ cordova plugin add cordova-plugin-code-push@latest
4) Configured code-push plugin as it is described here: 
https://microsoft.github.io/code-push/docs/cordova.html#link-2
5) Add codePush.sync to sync the app at platform.ready event
5) Successfully run ionic app with emulator and was able to check for updates
  $ ionic run android

Please can you be more specific about how to reproduce this?

**Comment by ThibaultLesuisse** [comment]
It resolved itself when i added the Ionic plugin for code-push and imported it
`ionic` plugin add cordova-plugin-code-push`

Maybe specify in the Docs that this plugin exists! :)
