### ISSUE TITLE
Apple App Store Review rejections?

### ISSUE THREAD

**Issue by chendo** [Microsoft/cordova-plugin-code-push#227]
Someone reported that Apple have begun rejecting apps for having the ability to remotely update app functionality on https://forums.developer.apple.com/thread/73640. Do we know if this applies to this plugin? Has anyone been rejected for using the Cordova plugin?

**Comment by awebdeveloper** [comment]
I have also been wondering the same

**Comment by BretJohnson** [comment]
We believe the rejections only affect apps that use native code update technologies, like Rollout and JSPatch.  Those tools can allow your app to call new native APIs (even private APIs) after an update, beyond native APIs Apple detects in its initial code scan at app store submission time.  CodePush only allows JavaScript code to be updated, but doesn't allow new native APIs to be called.  So we believe we're fine here, but we're continuing to monitor the situation.

**Comment by n0mer** [comment]
Our app was rejected due to pop-up 'new version is available'. Apple recommended to use app store update mechanism

**Comment by awebdeveloper** [comment]
Cant you just update and not show the popup. Why not instead say "New features" and list down new features with a continue button 

PS: Not used code-push but wanted to try it out

**Comment by silhouettes** [comment]
Hi @n0mer, we recommend silent updates for this exact reason (the App Store does not like an update dialog that can be misconstrued as the App Store dialog). This is called out in our docs here: https://github.com/Microsoft/cordova-plugin-code-push#plugin-usage.

**Comment by sergey-akhalkov** [comment]
I'm closing the issue now as it turns out that code-push is valid for using with app store. Will reopen this one if any changes.

**Comment by Borisboky** [comment]
Any new experiences with code-push and apple?

I use it as follows:

- First check if there are updates available in `componentDidMount` with `codePush.checkForUpdate().then(....)`

- Then depending on that I show an button

- On button click a call an function where I manipulate the state and use sync. I use sync as follows:  `codePush.sync({updateDialog: false, installMode: codePush.InstallMode.ON_NEXT_RESTART}, checkUpdateStatus, downloadProgress)`

- Then I'm showing an _downloading modal_ and after the downloading is finished I show an _alert_ to restart the app to apply changes. I do it as follows:

```
if (this.state.downloadingUpdate) {
            return (
                <Modal animationType={"none"} transparent={true} visible={this.state.downloadingUpdate}>
                    <View style={{backgroundColor:'#000', opacity: .7, flex: 1, flexDirection: 'column', alignItems:'center', justifyContent:'center'}}>
                        <View style={{backgroundColor:'#000', opacity: 1}}>
                            <Spinner isVisible={true} size={100} type={'ThreeBounce'} color={"#ffffff"}/>
                        </View>
                        <View>
                            <Text style={{color: '#fff', marginTop: 30, fontSize:24}}>{gettext("Downloaded")}: {this.state.downloadProgress} %</Text>
                        </View>
                    </View>
                </Modal>
            )
        }


        if(!this.state.downloadingUpdate && this.state.updateInstalled){
            return (
                <Modal animationType={"none"} transparent={false} visible={!this.state.downloadingUpdate && this.state.updateInstalled}>
                    <View style={{backgroundColor:'#000', opacity: .7, flex: 1, flexDirection: 'column', alignItems:'center', justifyContent:'center'}}>
                        {
                            Alert.alert(
                                gettext('Upgraded').toString().replace(/^,/, ''),
                                gettext('Update installed successfully').toString().replace(/^,/, ''),
                                [
                                    {text: gettext('Apply update').toString().replace(/^,/, ''), onPress: () => codePush.restartApp()}
                                ],
                                { cancelable: false }
                            )
                        }
                    </View>
                </Modal>
            )
        }
```

Do you guys think that that code would be rejected?

**Comment by andyscraven** [comment]
@Borisboky Was it rejected?

**Comment by dann95** [comment]
@Borisboky it was rejected? 2
