### ISSUE TITLE
Provide status bar progress bar

### ISSUE THREAD

**Issue by aaronorosen** [Microsoft/cordova-plugin-code-push#228]
It would be nice if when passing {updateDialog: true} that the dialog shown would also show a status bar of the progress if the update was mandatory. 

Currently, it just shows a message that the app is being updated user clicks "okay" then then app automatically restarts on them sometime after the update has finished.  It would be nice to let the user know the progress and when it's done/going to be restarted.

**Comment by max-mironov** [comment]
Hello @aaronorosen, may be is it possible to use [CodePush.Sync](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/README.md#codepushsync) *downloadProgress* method and create/show progress bar within this method?
It seems that showing progress bar every time may be not required by all users. 
Please let us know what do you think about this?

**Comment by aaronorosen** [comment]
@max-mironov  yup, one could definitely build the progress bar using that method.  

If someone does a mandatory update though it would be nice if a progress bar was shown rather than just restarting the app on the user after the update has completed.

**Comment by max-mironov** [comment]
Tagging @silhouettes as he may advise if we are interesting in having this feature now.

**Comment by max-mironov** [comment]
@aaronorosen  we have discussed this a little bit more - seeing as there is a way for user to do it himself and because there's not many requests for it we are not going to implement this at that moment. You can submit a PR implementing this if you likes or if we get more requests we will consider it. Thank you for your understanding.
