### ISSUE TITLE
codePush with phonegap build is undefined after one update

### ISSUE THREAD

**Issue by talavidan4** [Microsoft/cordova-plugin-code-push#232]
Hello everyone,

I'm using PGB for install the app to my device (in this case android).
the plugin work like a chram at the first time, i get all the messages from the sync function
for each step, and it reach till the "UPDATE_INSTALLED" stage smoothly.
once i close the app and re-launch it, i can see the changes in the app,
but when the sync function get called again it raise "codePush is not defined" inside
catch block (javascript error message).
when i close the app and strat it again it rollback to the first version
and codePush is recognized and the same process start all over.

i will appreciate any clue that will make my google search to be effective again :)

tnx,
Avidan

**Comment by max-mironov** [comment]
Hello @talavidan4, thank you for your question.
I've tried to use PGB with [my android test app](https://build.phonegap.com/apps/2531988/share) and it works for code-push updates successfully. 
At what time you are calling code-push `sync` method? Is it possible for you to try to reproduce this case on our [code-push sample app](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples)? If not may be you can share the minimal code for us so we can see how you apply code-push logic? 
Also btw what changes are in the update? Is it possible that they somehow crash code-push?

**Comment by talavidan4** [comment]
Hi @max-mironov thank you for your quick reply.
I tried the plugin in the basic hello world project of the cordova examples - just pack it
with PGB, i want to check it as clean as possible before merging it to my main project.

The call to sync method is on the device ready event, i set 
github repo with the relevant files [here](https://github.com/talavidan4/codePush-test).

For sure i will try your basic example with PGB and will update here later.

**Comment by max-mironov** [comment]
@talavidan4 - just checked [my app with the code](https://build.phonegap.com/apps/2531988/share) you provided and it is working good for me. 
So seems nothing wrong with your code. Is it possible that your update is broken?

**Comment by talavidan4** [comment]
@max-mironov  - i am not an expert, but i can't see how it's broken.
the update is install successfully and the cordova ready event is invoke,
it seems like the plugin for code push is missing after the update.
you can check it in my [PGB](https://build.phonegap.com/apps/2532085/share).

after updating the version, the text is change and the cordova ready is invoked.
if my code work for you, for sure i'm not doing it correctly. 

please name the files, screenshot, commands etc.. that you want me to share here for
figure it out.

**Comment by max-mironov** [comment]
@talavidan4 thanks I'll look at. In the meantime - do you release the update with `code-push release-cordova AppName android` command?

**Comment by max-mironov** [comment]
@talavidan4 - I have looked at your update and it looks broken -> this is not a diff update but it doesn't have e.g. plugins folder inside or cordova_plugins.js file etc. That is why code push is undefined on `deviceready`. So can you please try to release new update and then check if it is working?

**Comment by talavidan4** [comment]
@max-mironov - i am running the release with the command:
code-push release-cordova MyApp android.

I believe that i'm not running the command from the right directory according to your
reply. the cordova project got the follwing structure:
![cordova structure](https://cloud.githubusercontent.com/assets/6347078/24107888/abebf542-0d94-11e7-8b37-6133cf4abb0a.png)


all the above are inside directory called myApp.
I'm running the release command from that dir:


![cordova structure](https://cloud.githubusercontent.com/assets/6347078/24108002/fcc45b76-0d94-11e7-87e9-a8e597bbcf3b.png)

what are you saying?

**Comment by talavidan4** [comment]
@max-mironov - code-push release-cordova MyApp-Android android of course.
MyApp-Android is the name of the app i registered where myApp is the root folder

**Comment by max-mironov** [comment]
@talavidan4 - yes, that should work! Have you tried to release new update and verify if it helps?

**Comment by talavidan4** [comment]
@max-mironov - still the same.
any idea? at which folder i need to look for the files you mention above?
tomorrow i'll test the same app on ios - trying to cross if the problem is in the platform...

**Comment by max-mironov** [comment]
@talavidan4 ok - can you run `cordova prepare android` command and your package path then should be in ./platforms/android/assets/www directory (relative to the project root). What is the content of that folder?

**Comment by talavidan4** [comment]
@max-mironov - after running `phonegap prepare android`
this is the folder content:
![phonegap prepare](https://cloud.githubusercontent.com/assets/6347078/24111086/01b45f56-0d9e-11e7-8bb9-9638e5f55b39.png)

**Comment by max-mironov** [comment]
@talavidan4 and also and you run `cordova plugins ls` command to verify if we have code-push plugin here?

**Comment by talavidan4** [comment]
@max-mironov - just name it:
![phonegap prepare](https://cloud.githubusercontent.com/assets/6347078/24111538/6bc9b12e-0d9f-11e7-82b6-afc3abd934b6.png)

**Comment by max-mironov** [comment]
@talavidan4 looks strange :)
I've tried to google it a little, so may be something related to this: http://stackoverflow.com/questions/18301518/phonegap-3-doesnt-copy-plugins-to-platforms-folder

Can you try to `"cordova platform remove android"
"cordova platform add android" ` and again run `corodva prepare android` and see if we have plugins folder added?

**Comment by talavidan4** [comment]
@max-mironov  - thank you for the google **bingo** search!!
the problem was the missing file cordova_plugins.js that cause the broken update,
apparently due to add plugin before add platform as mention in stackoverflow.
it's now work as expected!

great plugin and easy to use!!

**Comment by max-mironov** [comment]
@talavidan4 - I'm glad to hear that everything is working now :)
If you currently have no more questions is it ok if we close the issue?

**Comment by talavidan4** [comment]
@max-mironov - absoulotly.
thanx again for your time and help.
