### ISSUE TITLE
Ionic 2 errors: Cannot read property 'is' of undefinded and Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by max-mironov** [Microsoft/cordova-plugin-code-push#237]
Moved to separate issue from https://github.com/Microsoft/code-push/issues/297#issuecomment-289379623

@lukasrein97 - feel free to edit/add more info if needed.
So im working on Ionic 2 and I'm faceing 2 Problems!

**First Problem**: If you run "ionic build android --prod" instead of "ionic build android" the Plugin wont work anymore because you get Typestript: Cannot read property 'is' of undefinded.
Notice: if you run the exactly same code with ionic build android the Code-Push works perfect!

**Second Problem**: The Method with onResume dont work in my Project. If my App gets out back of the Background and on Resume gets called i get this Error: Typescript Error: Cannot read property 'sync' of undefined
Notice: Normal startup works fine here only the Resume Method dont work.

This is my Code in my app.component.ts:

 this.platform.ready().then(() => { 

      this.codePushService.sync().subscribe((syncStatus) => {

        console.log('Sync Status: ', syncStatus);

        if (syncStatus === SyncStatus.UP_TO_DATE) {

          // facing some zoning problems here !!
          // why ??

          // forcing to run in the ngzone
          this._zone.run(() => {
            this.messageText = 'App is up to date !';
            console.log("App is up to date");
          });
        }

        switch (syncStatus) {
          case SyncStatus.IN_PROGRESS:
            this.messageText = 'An update is in progress ..';
            break;

          case SyncStatus.CHECKING_FOR_UPDATE:
            this.messageText = 'Checking for update ..';
            break;

          case SyncStatus.DOWNLOADING_PACKAGE:
            this.messageText = 'Downloading package ..';
            break;

          case SyncStatus.INSTALLING_UPDATE:
            this.messageText = 'Installing update ..';
            break;

          case SyncStatus.UPDATE_INSTALLED:
            this.messageText = 'Installed the update ..';
            const alert = this.alertCtrl.create({
              title: 'Update',
              message: 'A new update was installed and will be available on next app restart',
              buttons: ['OK']
            });
            alert.present();
            alert.onDidDismiss(() => {
            });
            break;

          case SyncStatus.ERROR:
            this.messageText = 'An error occurred :( ...';
            break;

          default:
            this.messageText = 'An unhandled sync status ..';
            break;
        }

      }) && document.addEventListener("resume", function () {
        this.codePushService.sync();
      });

**Comment by lukasrein97** [comment]
well i cant edit it. There is also a third Problem in here. 

With my code the  Update gets rolled back. Failed to install is set to true. 
I think thats because   ```
}) && document.addEventListener("resume", function () {
    this.codePushService.sync();
  });
```
dont work. I dont know. 
This is console output:
![unbenanntasdf](https://cloud.githubusercontent.com/assets/24311260/24347788/d51327de-12d9-11e7-8a20-b77f8484bd56.png)

**Comment by lukasrein97** [comment]
any update on this?

**Comment by max-mironov** [comment]
@lukasrein97 - sorry, we are going to look at this in the nearest days.
At the meantime, could you please look at several questions below:
1) You said: 
> If you run "ionic build android --prod" 

I've looked at [ionic cli ](http://ionicframework.com/docs/v2/cli/build/)docs and [cordova docs ](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#cordova-build-command)and was unable to find any documentaion about `--prod` parameter. Could you please point me to docs with some description about it.

2) Also where and how do you initialize `this.codePushService` variable?

**Comment by lukasrein97** [comment]
> I've looked at ionic cli docs and cordova docs and was unable to find any documentaion about --prod  parameter. Could you please point me to docs with some description about it.

Sadly there isnt any official documentation about it. I wrote about that with one of the CEOs of Ionic in Twitter and he said that they will update the documentation about it in the future. 

> Also where and how do you initialize this.codePushService variable?

`import { CodePushService } from 'ionic2-code-push';`

And in constructor:

```
  constructor( ...........  ,  private codePushService: CodePushService) 
  {   
    this.initializeApp();
  }
```
And now i cant use it:
```
initializeApp(){
    this.platform.ready().then(() => { 

      this.codePushService.sync().subscribe((syncStatus) => {
.............................
```

**Comment by lukasrein97** [comment]
> Hi @lukasrein97 , so as far as I get - your app is based on this example.
Also I see that your 1st question was resolved here, please let us know if you still have any issues with it.

Well this Solution you have mentioned here is my Solution i posted in the Ionic 2 Forum. And the Problem here is that this solution only works for  `"ionic android build" ` . If you release an application with `"ionic android build --prod"` this solution doesnt work anymore and we get the same Error. BUT it seems that with: `"ionic plugin add cordova-plugin-code-push"` sometimes the error is gone. Well I know its a weird behavior because you only install the plugin new again and again but well you get a 50% chance it works. But it definatly have something to do with that --prod flag. 

I changed my app.component.ts to this:
```
    this.platform.ready().then(() => {
      document.addEventListener('resume', () => { this.codePushService.sync(); });
........................
```
and it seems that the rollback error is mostly of the time gone.

> Regarding your 3rd question about rollbacks - I believe that we need to use general form of releasing updates, that is something like code-push release ionic-android ./platforms/android/assets/www 0.2.0 because ionic bundles the package to app.bundle.js wheres cordova build don't. So that may be the reason for rollback.

How do you mean that? At this time Im publishing it with this: 
`code-push release-cordova talents-android android -d Production`
So you mean i should publish it know with:
`code-push release talents-android android ./platforms/android/assets/www `?
And my app should get the update as well?

**Comment by max-mironov** [comment]
@lukasrein97 - regarding `ionic build android --prod` command. Do I get it right that the app won't work only when you apply code-push update? Or you receive this error immediately after you install the app on device (if yes - which command do you use to install the app on device after you do `ionic build android`?).

You said:

>and it seems that the rollback error is mostly of the time gone

Do I get it right that it fixes your issue?

As for releasing updates: when you use `code-push release-cordova telents-android android -d Producation` be sure that your app is bundled correctly. 
Internally this command calls `cordova prepare` command which is not packaging your js in one bundle by default. Please verify that `ionic hooks add` was executed to add ionic specific behavior and just be sure that your `./platforms/android/assets/www` contains valid files here.

**Comment by max-mironov** [comment]
@lukasrein97 - hi, please let us know if you havea chance to look at this.

**Comment by lukasrein97** [comment]
>  regarding ionic build android --prod command. Do I get it right that the app won't work only when you apply code-push update? Or you receive this error immediately after you install the app on device

Well if i use `ionic build android --prod` the app doesnt work on the first start up. If i use `ionic build android` all works fine for now. With` ionic build android `the whole app and also the updates works like a charm.

> Do I get it right that it fixes your issue?

Yeah adding an event listener for resume sloved this issue with ionic android build (but not for android build --prod)
```
    this.platform.ready().then(() => {
      document.addEventListener('resume', () => { this.codePushService.sync(); });
```

**Comment by max-mironov** [comment]
Hey @lukasrein97, thanks for answering.
I've just tried to use `ionic build android --prod` and seems it is working for me. Interesting thing is that I do not see any differences in the output folder `"./platforms/android/assets/www"` regardless if I use `--prod` flag or not. Can you look at to see if you have different generated output content when using `ionic build android` and `ionic build android --prod` or you see no differences here?

I'm on on ionic `2.2.1` version.

**Comment by lukasrein97** [comment]
I dont know much details about --prod the only things I know are that with --prod flag the android apk package isnt as big as the apk file without the --prod flag. And the most important thing with --prod is that --prod speed up the boot time of the app by the HALF. Thats why everyone use --prod. I dont know how ionic do that but it has something to do with the ionic build scripts.

**Comment by max-mironov** [comment]
@lukasrein97 thanks, got it. As far as the issue is not reproducing on our side and besides this is not an "officially documented" ionic build parameter I believe we can close the issue for now. We should reopen it if we get more stable repro steps or we get more users who claim similar issue.
