### ISSUE TITLE
Android app won't start after update

### ISSUE THREAD

**Issue by PierBover** [Microsoft/cordova-plugin-code-push#238]
I have updated the Android platform in my Cordova project. After that, any update I have sent to `code-push` has resulted in my app not starting or the update not being accepted by my users.

This morning everything worked fine. Hours later, after updating Android SDK tools Google changed the location of `graddle` and I had to update the android platform to be able to compile my app. The only thing I have changed since this morning is the Android platform and I have also removed and reinstalled the `cordova-plugin-code-push`.

When I compile a debug version locally the app starts fine, although of course it does not update. The problem happens with the `.apk` that my users have installed which was compiled months ago.

From what I've seen in `adb logcat` the new update is detected and downloaded fine. But afterwards the cordova app does not start.

[Here is the adb logcat output.](https://gist.github.com/PierBover/a510b526f898fcfdde88640eb65a6d24) I've cleaned it a bit.

After downloading I see this:
`[CodePush] Install succeeded.`

The app restarts and then this:
```
PluginManager: THREAD WARNING: exec() call to CodePush.install blocked the main thread for 25ms. Plugin should use CordovaInterface.getThreadPool().
...
JsMessageQueue: Set native->JS mode to null
cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 7757
JsMessageQueue: Invalid NativeToJsBridgeMode: 3
CordovaBridge: Ignoring exec() from previous page load.
chromium: [INFO:CONSOLE(1223)] "deviceready has not fired after 5 seconds."
chromium: [INFO:CONSOLE(1216)] "Channel not fired: onFileSystemPathsReady"
chromium: [INFO:CONSOLE(1216)] "Channel not fired: onCordovaInfoReady"
chromium: [INFO:CONSOLE(1216)] "Channel not fired: onCordovaConnectionReady"
```

And after that there's nothing else. The app is frozen and doesn't start since the `deviceready` event is not fired.

Here is the list of plugins I'm using. Like I said I haven't updated any plugin today except for `cordova-plugin-code-push`:
```
code-push 1.9.0-beta "CodePushAcquisition"
cordova-plugin-code-push 1.9.3-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-nativestorage 2.0.2 "NativeStorage"
cordova-plugin-network-information 1.3.0 "Network Information"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
```

Here are my platforms:
```
Installed platforms:
  android 6.2.0-dev
  browser 4.1.0
  ios 4.2.1
```

I have reported the problem in a `cordova-android` PR since I suspect it's related to this.

Any ideas as to what I could try?

**Comment by PierBover** [comment]
Sorry it was something else.

**Comment by Nashorn** [comment]
after installing code push plugin the 'deviceready' event never fires. I remove code push, my app work. Good ol' crappy microsoft programmers
