### ISSUE TITLE
Incompatible with cordova-plugin-settings-hook

### ISSUE THREAD

**Issue by jnordstrom1983** [Microsoft/cordova-plugin-code-push#241]
If the cordova plugin cordova-plugin-settings-hook is installed and used cordova-plugin-code-push breaks and seams to fail to create the currentpackage.json file when building the app causing .sync() to fail with the "Cannot perform diff-update." message.

I'm not sure if this is a problem with cordova-plugin-settings-hook or with cordova-plugin-code-push.

Best regards
Johan

**Comment by max-mironov** [comment]
Hello @jnordstrom1983, just have tried to reproduce your issue but with no luck.

My cordova plugin ls output:
```code-push 1.9.0-beta "CodePushAcquisition"
cordova-plugin-code-push 1.9.3-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-dialogs 1.3.2 "Notification"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-file-transfer 1.6.2 "File Transfer"
cordova-plugin-settings-hook 0.2.4 "Cordova Settings Hooks"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
```
and I was able to successfully release/sync update with code-push.

Could you please be more specific about rerpo steps (can you reproduce it on our [Basic Sample App?](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic))
What platform your are on? Is it possible for you to share with us your `cordova info` output?

**Comment by max-mironov** [comment]
Hey @jnordstrom1983, do you have any chance to look at this?

**Comment by jnordstrom1983** [comment]
Hi Max, 

Sorry for not getting back, I have been trying to create a reproducible project. However, now I seams to be unable to reproduce this. I successfully reproduced it multiple times before submitting the issue here, however the day after I wasn't able reproduce it any more with new projects, and after re installing the cordova-plugin-code-push plugin in my initial app the problem seams to have solved it self.

Really sorry for taking your time.

**Comment by max-mironov** [comment]
@jnordstrom1983 no problem, thanks for getting back :) Feel free to reach us if you have any issues with code-push in future.
