### ISSUE TITLE
Code-push can't install with cordova 7.0.0

### ISSUE THREAD

**Issue by huytran0605** [Microsoft/cordova-plugin-code-push#243]
### Description

i got this message when run command `cordova platform add android`

`Failed to restore plugin "cordova-plugin-code-push" from config.xml. You might need to try adding it again. Error: Version of installed plugin: "code-push@1.9.0-beta" does not satisfy dependency plugin requirement "code-push@>=1.8.0-beta". Try --force to use installed plugin as dependency.`

In my config.xml, i have config <plugin name="cordova-plugin-code-push" spec="~1.9.2-beta" />
The error only come when i upgrade cordova version to 7.0.0

### Additional Information

* cordova-plugin-code-push version: 
* List of installed plugins:
* Cordova version: 7.0.0
* iOS/Android/Windows version: ios 4.3.1, android 6.2.2

**Comment by sergey-akhalkov** [comment]
Hi @huytran0605, thanks for reaching us. I've published PR that should fix it #244, please verify (remove plugin and platform, then add them again) and let me know if it helps.

**Comment by BigFoppa** [comment]
@sergey-akhalkov I face the same problem. Have never installed a plugin from a PR before. Please tell me how to do it.

**Comment by sergey-akhalkov** [comment]
Hi @BigFoppa, no problem! To install plugin that contains the fix you can use [my fork](https://github.com/sergey-akhalkov/cordova-plugin-code-push):
```bash
cordova plugin add https://github.com/sergey-akhalkov/cordova-plugin-code-push.git
```
Please let me know if you have any issues.

**Comment by huytran0605** [comment]
@sergey-akhalkov  Your plugin fixed that issues. Thank you a lot

**Comment by sergey-akhalkov** [comment]
@huytran0605, thanks for the response, hoping this fix will be merged and released soon.

**Comment by sergey-akhalkov** [comment]
Closing this due to [v.1.9.4-beta](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.9.4-beta) has been released.

**Comment by tavojavi** [comment]
Hello, I´m trying to install the plugin, and have a similar issue, tried to install using sergey-akhalkov fork  but it did not work.

Error: Version of installed plugin: "code-push@2.0.1-beta" does not satisfy dependency plugin requirement "code-push@>=1.9.0-beta". Try --force to use installed plugin as dependency.

Cordova  version 7.00, installed platforms: android 6.2.3, ios 4.4.0

Thanks!

**Comment by huytran0605** [comment]
Please install code push plugin  v.1.9.4-beta  and try again.

**Comment by walfro** [comment]
@tavojavi, I don't know if you are still facing this issue...

I was having the same issue, fixed it by removing plugin code-push and then adding the plugin again, just like this: 

`cordova plugin rm code-push`
`cordova plugin add cordova-plugin-code-push@latest`

Hope it helps,
Thanks!
