### ISSUE TITLE
Comatible with HockeyApp?

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/cordova-plugin-code-push#245]
Hi,
Does this work for pushing updates to HockeyApp for testing?

Thanks

**Comment by sergey-akhalkov** [comment]
Hi @jrmcdona, I don't sure if I quite understand your question, but this should work for each app that have been configured to use CodePush service. 

Please let me know if you have any questions.

**Comment by max-mironov** [comment]
@jrmcdona we close the issue currently, please reopen this one or create a new item if you face any issues with this.

**Comment by jrmcdona** [comment]
Thanks I will be trying it soon.  Just hadn't quite gotten there but seems like it is supported for CodePush to HockeyApp in a Cordova/Ionic app.
