### ISSUE TITLE
Android App crashes after CodePush update

### ISSUE THREAD

**Issue by gubyy** [Microsoft/cordova-plugin-code-push#246]
We have just added CodePush to our Cordova App. It works fine on iOS but not on Android. After the CodePush update install (codePush.sync()), we restart the App but it only crashes.

We added codePush.sync() to the onResume method and the update seems to install fine. We do get one error during the install though. Here is the output during the CodePush update:

![screen shot 2017-05-15 at 32](https://cloud.githubusercontent.com/assets/11578073/26074911/7f497ece-3981-11e7-8606-368e419a5c3f.png)

After this finishes, I kill the App and attempt to restart it but it immediately crashes saying "App Name has stopped".

### Additional Information

* cordova-plugin-code-push version: 1.9.3-beta
* List of installed plugins:
CodePushAcquisition@1.9.0-beta
PushPlugin@2.5.0
Native Page Transitions@0.6.5
Compat@1.1.0
DatePicker@0.9.2
Device@1.1.1
Notification@1.2.1
File@4.2.0
File Transfer@1.5.1
Geolocation@2.1.0
Globalization@1.0.4
Google Universal Analytics Plugin@1.7.4
InAppBrowser@1.5.0
Splashscreen@4.0.0
Whitelist@1.3.0
cordova-plugin-zip@3.1.0
Keyboard@2.2.1
* Cordova version: 5.4.1
* iOS/Android/Windows version: Android@4.1.1
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Only tested on physical device

**Comment by soenneker** [comment]
You might want to try updating Cordova (6.5/7.0.1) as well as your Android engine (6.2.3). Some of those plugins are out of date too. Make sure you also have cordova-plugin-code-push 1.9.3-beta and code-push 1.9.0-beta installed (cmd: cordova plugin list)

**Comment by max-mironov** [comment]
@gubyy in addition of what was said by@soenneker please verify that you have different deployment keys for iOS and Android app just to be sure that this is not the root cause of the issue.

**Comment by gubyy** [comment]
@soenneker thanks updating our cordova and plugins fixed the issue.
