### ISSUE TITLE
Empty RemotePackage

### ISSUE THREAD

**Issue by kaiukdevelopment** [Microsoft/cordova-plugin-code-push#247]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

We have two version of our product (currently in beta) v1.0.14 (in house testing) and v1.0.15 (to be released to app stores). We have used codepush to push out an update to 1.0.14, but 1.0.15 now also shows that there is an update. Upon further investigation, the RemotePackage that is retrieved on the app for 1.0.15 only has the deploymentKey filled in.

![image](https://cloud.githubusercontent.com/assets/13997981/26163938/0d121250-3b23-11e7-8b73-fb603864e310.png)

We have a work around which checks that the appVersion in RemotePackage is filled in for us to then call codepush.sync(), but this seems like a bit of a hack.

Should codepush not be checking the version of the app against the version in the RemotePackage?

### Additional Information

* cordova-plugin-code-push version: 1.9.4 beta
* List of installed plugins:
* Cordova version: 7.0.1
* iOS/Android/Windows version: Android 6.0.1
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device? Physical only

**Comment by sergey-akhalkov** [comment]
Hi @kaiukdevelopment, thanks for reaching us. Could you please try to release another update and verify if the issue still reproduces? Also please share with me the way you've released CodePush update (i.e. `code-push release-cordova ...` command)?

**Comment by kaiukdevelopment** [comment]
I've just pushed out a new update to version 1.0.14 and am still getting the issue. The command I ran was

`code-push release *APPNAME* platforms/android/assets/www/ 1.0.14 --deploymentName Production --description Test14`

We have also tried with the `code-push release-cordova *APPNAME* --deploymentName Production` (on the 1.0.14 version) and get the same results

**Comment by sergey-akhalkov** [comment]
Hi @kaiukdevelopment, we've tried to reproduce it but with no luck. So could you please try to reproduce the issue using our [sample app](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples) (or share with us minimum version of your source code where the issue reproduces). Could you also please share with us your deployment history (perform `code-push deployment history <appName> <deploymentName>` command)?

**Comment by trebor678** [comment]
I believe we have figured out the issue. For some reason although we are using cordova-plugin-code-push 1.9.4beta, code-push is 1.9.0beta. When I created a new app it downloaded 1.11.2beta; this version doesn't seem to have the issue.

Not sure why our app has an older version, but we will update it to the latest and see if this fixes it

**Comment by kaiukdevelopment** [comment]
I believe we have figured out the issue. For some reason although we are using cordova-plugin-code-push 1.9.4beta, code-push is 1.9.0beta. When I created a new app it downloaded 1.11.2beta; this version doesn't seem to have the issue.

Not sure why our app has an older version, but we will update it to the latest and see if this fixes it

**Comment by sergey-akhalkov** [comment]
@kaiukdevelopment, got it, let us know if any updates.

**Comment by kaiukdevelopment** [comment]
OK, all sorted! It was that it was using the older 1.9.0-beta for code-push; not sure how that happened!

The only minor thing that I am seeing, is that when I run the command `cordova plugin`, code-push is showing as 1.9.0-beta. It seems like this is coming from the 'plugin.xml' file which hasn't been updated to show the latest version

**Comment by max-mironov** [comment]
@kaiukdevelopment good catch, thank you so much for pointing at this! We've [updated CodePushAcquisition plugin](https://github.com/Microsoft/code-push/pull/447) version to latest.
