### ISSUE TITLE
Weird Prompt Shows on Mandatory Push

### ISSUE THREAD

**Issue by andrewoodleyjr** [Microsoft/cordova-plugin-code-push#248]
![img_8915](https://cloud.githubusercontent.com/assets/4668369/26180029/bc7fbbbe-3b1b-11e7-8e7c-8581868e1caf.png)

### Description

I am releasing mandatory updates and I'm coming across this message when releasing the update

### Error Messages on iOS

gap:[null,"File","requestAllPaths","File961069884"]
gap:[null,"Device","getDeviceInfo","Device961069883"]
gap:[null,"CoreAndroid","show","CoreAndroid260306808"] 

### Reproduction

Here are the two separate codes I use to reproduce this behavior.

`code-push release-cordova intheroom ios -d Production -t "*" --mandatory`

#### Code Push Version
code-push 1.9.0-beta "CodePushAcquisition"

#### Installed Plugins
code-push 1.9.0-beta "CodePushAcquisition"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-background-geolocation-lt 2.7.0 "BackgroundGeolocation"
cordova-custom-config 2.0.3 "cordova-custom-config"
cordova-instagram-plugin 0.5.4 "Instagram"
cordova-plugin-actionsheet 2.2.2 "ActionSheet"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appsee 2.2.1 "Appsee"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-calendar 4.5.5 "Calendar"
cordova-plugin-calendars-usage-description 0.0.3 "PhoneGap Calendar Usage Description plugin"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-code-push 1.9.3-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-contacts 2.1.0 "Contacts"
cordova-plugin-customurlscheme 4.2.0 "Custom URL scheme"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-fcm 1.1.5 "FCMPlugin"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-whitelist 1.3.3-dev "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-uxcam 2.3.6 "UXCam"
ionic-plugin-keyboard 2.2.1 "Keyboard"

#### Cordova Version 
6.5.0

#### iOS version
10+

Happens on a physical device and simulator!

**Comment by sergey-akhalkov** [comment]
Hi @andrewoodleyjr, thanks for reaching us. To fix the issue you have to use different deployment keys both for Android and iOS due to you iOS app is receiving cordova js files that have been built for Android.

Please let me know if it helps or if you have any questions.

**Comment by andrewoodleyjr** [comment]
@sergey-akhalkov Thanks for your help.
Is there a way to update the config.xml via code-push?

**Comment by max-mironov** [comment]
@andrewoodleyjr, CodePush allows you to update just client -side code (i.e. js files, images, html and etc.). So native-side things such as java, objective-c, configs files should be updated via app store only. Please let me know if you have any questions.

**Comment by max-mironov** [comment]
@andrewoodleyjr, I believe the issue could be closed for now. Please feel free to reopen or create a new one if you have more questions about this.

**Comment by JoeMadhan** [comment]
I am trying to run the android index.html on the browser and I am getting the above error 

> gap:[null,"File","requestAllPaths","File961069884"]
> gap:[null,"Device","getDeviceInfo","Device961069883"]
> gap:[null,"CoreAndroid","show","CoreAndroid260306808"]
