### ISSUE TITLE
LocalPackage object the getPendingPackage method return  has no isMandatory property

### ISSUE THREAD

**Issue by fenglu09** [Microsoft/cordova-plugin-code-push#250]
### Description
The  result of `codePush.getPendingPackage()` not has `isMandatory` property on my iOS.
![image](https://cloud.githubusercontent.com/assets/12250129/26274579/6a20a4a8-3d7f-11e7-8a8e-906010f436cd.png)

But the document  [here](https://microsoft.github.io/code-push/docs/cordova.html#codepushgetpendingpackage) write that the  LocalPackage has `isMandatory`  property.

### Reproduction
My code: 
```js
codePush.getPendingPackage(function (update) {
    if (update) {
        console.log(update);
    }
});
```

### Additional Information

* cordova-plugin-code-push version:  1.9.4-beta
* List of installed plugins: 
code-push 1.9.0-beta "CodePushAcquisition"
cordova-plugin-android-movetasktoback 0.1.3 "cordova-android-movetasktoback"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-mode 0.6.6-dev "BackgroundMode"
cordova-plugin-badge 0.7.2 "Badges"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-code-push 1.9.4-beta "CodePush"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-contacts 2.3.0 "Contacts"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-opener2 2.0.2 "File Opener2"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-getuisdk 1.0.0 "GeTuiSdk"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-qqsdk 0.4.0 "YCQQ"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-screenshot-detect 0.0.1 "cordova-plugin-screenshot-detect"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-wechat 1.2.0 "Wechat"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-save-image-gallery 0.0.26 "saveImageGallery"
cordova.plugins.diagnostic 3.4.2 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"

* Cordova version:  6.4.0
* iOS/Android/Windows version:  iOS 10.3.1
* Does this reproduce on a debug build or release build?  
debug build
* Does this reproduce on a simulator, or only on a physical device?
physical device

**Comment by max-mironov** [comment]
Hello @fenglu09 - thanks for good catch! Seems that we are missing this property when returning `localPackage` from getPendingUpdate method. 
I've added [PR](https://github.com/Microsoft/cordova-plugin-code-push/pull/251) to fix it, could you please verify if it works for you?

**Comment by fenglu09** [comment]
Thanks for you apply!
After add ` localPackage.isMandatory = metadata.isMandatory;` to the `localPackage.js`, it solved my issue.

**Comment by max-mironov** [comment]
@fenglu09 you are welcome! Please let us know if you consider the issue could be closed as resolved.

**Comment by fenglu09** [comment]
@max-mironov  you can close this issue after your pull request is merged.

**Comment by max-mironov** [comment]
Closing the issue due to [PR](https://github.com/Microsoft/cordova-plugin-code-push/pull/251) has been merged to Master. Let us know if you see any issues.
