### ISSUE TITLE
Update available

### ISSUE THREAD

**Issue by aboveo** [Microsoft/cordova-plugin-code-push#256]
### Description

_I have added new code push key to the project and when I deploy it to mobile it popups an alert saying update available, without releasing any updates

From my console
[Log] [CodePush] Downloading update (codePushUtil.js, line 36)
[Log] An error occured while checking for updates (, line 487)

The app only works after I release any update using code push 

Is this a bug or am I doing anything wrong_

### Additional Information

* cordova-plugin-code-push version: 1.9.4-beta
* List of installed plugins:
* Cordova version: 7.0.1
* iOS/Android/Windows version: iso10.3.2 & android7
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

(The more info the faster we will be able to address it!)

**Comment by aboveo** [comment]
# this is my code

```
document.addEventListener('deviceready', function () {
    //codePush.sync();

    window.codePush.sync(
        function (syncStatus) {
            switch (syncStatus) {
                // Result (final) statuses
                case SyncStatus.UPDATE_INSTALLED:
                    codePush.restartApplication();
                    break;
                case SyncStatus.UP_TO_DATE:
                    console.log("The application is up to date.");
                    break;
                case SyncStatus.UPDATE_IGNORED:
                    console.log("The user decided not to install the optional update.");
                    break;
                case SyncStatus.ERROR:
                    console.log("An error occured while checking for updates");
                    break;

                // Intermediate (non final) statuses
                case SyncStatus.CHECKING_FOR_UPDATE:
                    console.log("Checking for update.");
                    break;
                case SyncStatus.AWAITING_USER_ACTION:
                    console.log("Alerting user.");
                    break;
                case SyncStatus.DOWNLOADING_PACKAGE:
                    UpdatesShow();
                    break;
                case SyncStatus.INSTALLING_UPDATE:
                    InstallsShow();
                    break;
            }
        },
        {
            installMode: InstallMode.ON_NEXT_RESTART, updateDialog: true
        },
        function (downloadProgress) {
            console.log("Downloading " + downloadProgress.receivedBytes + " of " + downloadProgress.totalBytes + " bytes.");
        });
}, false);
```

**Comment by aboveo** [comment]
![img_3983](https://user-images.githubusercontent.com/19563398/27113541-60cf6e24-508b-11e7-9529-7d2daaa27b6a.jpg)

**Comment by aboveo** [comment]
![screen shot 2017-06-13 at 10 58 06 pm](https://user-images.githubusercontent.com/19563398/27113716-93021e68-508c-11e7-9c55-03557c69a4f3.jpg)

**Comment by sergey-akhalkov** [comment]
Hi @aboveo, thanks for reaching us. The issue looks weird, could you please figure out what deployment key you are currently using and share us with an output of the following command: `code-push deployment history <appName> <deploymentName>`

Also could you please clarify what do you mean by `I have added new code push key`? Have you created new deployment?

**Comment by aboveo** [comment]
for testing I'm using Staging and for production I'm using production

![screen shot 2017-06-14 at 8 46 46 am](https://user-images.githubusercontent.com/19563398/27132924-82780218-50de-11e7-995a-8f5c9b5e9fd0.jpg)

> Yes, I have created a new deployment key

**Comment by aboveo** [comment]
even I tried increasing version number it still shows up update available

**Comment by max-mironov** [comment]
Hey @aboveo - thank you for posting the issue and sorry for delay in responses. 
Finally we have found out that the issue was introduced with Cordova 7 failed to properly resolve the dependency to  `code-push` package thus using old 1.9.0-beta instead of latest 2.0.1-beta version. 
The issue was fixed by modifying `plugin.xml` `<dependency id="code-push" version="2.0.1-beta" />` line. So we went ahead and released new version of cordova-plugin-code-push [1.9.5-beta](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.9.5-beta). Please update to verify if it works good for you.

With all that said I'm going to close the issue for now, please feel free to reopen if you notice any problems with it.
