### ISSUE TITLE
images not always rendering after code-push update

### ISSUE THREAD

**Issue by gulullu** [Microsoft/cordova-plugin-code-push#259]
- ionic version: 2.2.0
- cordova version: 7.0.1
- code-push version: code-push 1.9.0-beta "CodePushAcquisition"

Hi, I am using code-push for an ionic application.  I noticed that sometimes some images are not rendering when an update package has download but app not restart. When restart it, then everything is fine.

This is my check update code:

```javascript
    checkUpdate() {
        if (this.platform.is('ios') || this.platform.is('android')) {
            const downloadProgress = (progress) => {
                console.debug(`Downloaded ${progress.receivedBytes} of ${progress.totalBytes}`);
                if (!ConfigService.isProdEnv) {
                    if (progress.receivedBytes === progress.totalBytes) {
                        this.hudService.getAlert('更新成功', '新版本更新成功，请关闭应用并重新打开使用新版本.该提示只会在测试期间出现，请勿依赖。', [
                            {
                                text: '确定',
                                handler: () => {
                                }
                            }
                        ]).present();
                    }
                }
            }
            this.codePush.sync({}, downloadProgress).subscribe((syncStatus) => console.log(syncStatus));
        }
    }
```

Do you have any idea what could be the problem? I tried various things as a workaround but so far nothing helped.

Thanks a lot.

**Comment by max-mironov** [comment]
Hello @gulullu, thank you for your question. Although I'm not sure that this is the same problem (and the issue was initially created for react app, not a cordova one) but anyway - do you have a chance to look for [this thread](https://github.com/Microsoft/react-native-code-push/issues/699) to see if this could be useful for you.

**Comment by max-mironov** [comment]
Hey @gulullu, do you have a chance to look at this?

**Comment by max-mironov** [comment]
Closing this for now, please feel free to reopen when you get a chance t revisit it.
