### ISSUE TITLE
CheckForUpdate and determine if there is a new binary version

### ISSUE THREAD

**Issue by jgkinnear** [Microsoft/cordova-plugin-code-push#260]
### Description
Is there a public method to determine if there is a new Binary version available? When checking for an update, the console logs 
` An update is available, but it is targeting a newer binary version than you are currently running.`
but the calls internally 
`appUpToDate();`

I would like to send the user to a URL to download the new binary version

### Additional Information

* cordova-plugin-code-push version: 2.0.1-beta
* Cordova version: 6.4.0
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by max-mironov** [comment]
Hi @jgkinnear, that a good question. Currently we do not have an API method to verify this.
So probably you could try to do one of the following things to get your requirements:
1) Add an additional callback function to `checkForUpdate` method and rise this callback e.g. after [this LOC](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/www/codePush.ts#L167). If you could create a PR that implements this and  update docs - that would be much appreciated. 
2) You could try to import some stuff from cordova-plugin-code-push, say you need to import 
`class Sdk` and `class LocalPackage` and try to write you custom function [reflecting the same logic](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/www/codePush.ts#L195) we do in `checkForUpdate` method. So this way you should be available to implement your custom handling there.

Please let us know if you have any questions regarding this.

**Comment by sergey-akhalkov** [comment]
Hi @jgkinnear, please also take a look at the similar PR here https://github.com/Microsoft/react-native-code-push/pull/888 - it can help you. And especially pay attantion on https://github.com/Microsoft/react-native-code-push/pull/888#issuecomment-309805588

**Comment by max-mironov** [comment]
@jgkinnear - we believe that we can close the issue if you do not have any questions at that moment. Do not hesitate to reopen the ticket if needed.

**Comment by jgkinnear** [comment]
Thanks for the information @sergey-akhalkov and @max-mironov, appreciated!
