### ISSUE TITLE
Plugin reports "unable to find start page" if start page is not a local path

### ISSUE THREAD

**Issue by bradzacher** [Microsoft/cordova-plugin-code-push#263]
If you have the config.xml's start page set to a remote address, codepush will throw an error and say the update was unsuccessful. However when you trigger the install (restart app..), it installs fine, and further calls to `sync` report no updates available.

Found this bug because I was running the app off a dev server on my laptop, so config startpage was set to a xip.io address.

Specifically occurs with the check here:
ios: https://github.com/Microsoft/cordova-plugin-code-push/blob/master/src/ios/CodePush.m#L360
That check fails so the function returns null and it fails.

I'd assume the same check would exist on android, but I haven't investigated.

**Comment by max-mironov** [comment]
Hey @bradzacher unfortunately this is not something that our plugin supports at that moment (using remote address as a start page), seems related to https://github.com/Microsoft/cordova-plugin-code-push/issues/188.
