### ISSUE TITLE
Supports additional args passed to cordova prepare/build

### ISSUE THREAD

**Issue by tedliang-aa** [Microsoft/cordova-plugin-code-push#266]
### Description

The  `release-cordova` command will run `cordova prepare android/ios --verbose`, which triggers custom hooks with the options inside the [context](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/#javascript) as `options: { verbose: true, argv: [], fetch: true }`

The `cordova prepare` supports custom args, which are accessible via the `options`

e.g. running `cordova prepare android --verbose --customarg1 --customarg2` would results the options in the context to be `options: { verbose: true, customarg1: true, customarg2: true, argv: [], fetch: true }`

Is it possible to pass custom args to the `cordova prepare/build`? It would be of great help to customize the custom hook to perform specific tasks based on the args

For example, `code-push release-cordova app-android android --args customarg` would trigger `cordova prepare android --verbose --customarg`

Thanks!

### Additional Information

* cordova-plugin-code-push version:  1.9.5-beta
* Cordova version: 7.0.1

**Comment by pniko** [comment]
Hi @tedliang-aa, we are migrating our CLI commands over to the new Mobile Center CLI where additional functionality will be made available towards the end of this year. I would recommend looking out for that announcement and opening up this request if you feel it hasn't been implemented in that solution. Thanks!
