### ISSUE TITLE
Any setup suggestions on how to use staging and production environments for Android Play store's open beta and prod releases

### ISSUE THREAD

**Issue by mohamedsharaf** [Microsoft/cordova-plugin-code-push#273]
Any setup suggestions on how to use staging and production environments for Android Play store's open beta and prod releases

look at below we can specify both key staging and production and the run will determine which one to use 

https://github.com/Microsoft/react-native-code-push#android
https://github.com/Microsoft/react-native-code-push#ios

can I do a similar thing in Cordova 

or i have to manually modify the staging key 
        <preference name="CodePushDeploymentKey" value="staging  key" />
with production key every time i buikd for release 
        <preference name="CodePushDeploymentKey" value="production  key" />

any suggestion much appreciated

**Comment by iageoghe** [comment]
Hi, you can do the same sort of dynamic deployment run-time check with Cordova that you can do with React Native.

Instructions for including deployment keys in Cordova [here.](https://github.com/Microsoft/cordova-plugin-code-push#getting-started) 

Instructions for overriding the configured deployment key are [here.](https://github.com/Microsoft/cordova-plugin-code-push#api-reference) Check out the deploymentKey parameter of the checkForUpdate method. 

Does that help?

**Comment by max-mironov** [comment]
@mohamedsharaf - hi, please let us know if you have a chance to look at this

**Comment by mohamedsharaf** [comment]
i so your link it seems as an option but I haven't tried it 

i will give it a try and update question with solution as i finished 

thx alot for your support
