### ISSUE TITLE
Application keeps showing old index.html out of cache

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/cordova-plugin-code-push#282]
### Description

I installed my application (APK) on my device. After that, I released a update of my application and changed only one small thing. I looked at the logs and the application updates through codepush. However, the old application is still shown. I think this has something to do with caching. Because it just requests `index.html`, it still takes the old one out of the cache and serves that one. The reason I believe this is caching is because when I deploy my JavaScript files with a hash (random per build), the `index.html` file still keeps looking for the old files. One thing to note is that I use [CrossWalk](https://crosswalk-project.org/) to make sure my webview is consistant.

### Reproduction

I didn't try out the reproduction case. I will try it tomorrow.

### Additional Information

* cordova-plugin-code-push version: 1.9.6-beta
* List of installed plugins:
  - cordova-plugin-camera@2.3.0
  - cordova-plugin-media-capture@1.4.1
  - cordova-plugin-media@2.4.1
  - cordova-plugin-file@4.3.1
  - cordova-plugin-device@1.1.4
  - cordova-plugin-network-information@1.3.1
  - cordova-plugin-crosswalk-webview@2.1.0
  - cordova-plugin-splashscreen@3.1.0
  - cordova-plugin-statusbar@2.1.0
  - phonegap-nfc@0.6.4
  - cordova-plugin-code-push@latest
  - https://github.com/tomloprod/cordova-plugin-appminimize.git
* Cordova version: 6.x
* iOS/Android/Windows version: Android 6.x
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Physical (simulator untested)

**Comment by max-mironov** [comment]
Thanks for reporting @SamVerschueren, that looks strange. When you will try to find out reproduction steps is it possible for you to reproduce it within our [basic sample](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic) so we could also debug it on our side?

**Comment by max-mironov** [comment]
Hey @SamVerschueren, just a friendly ping on this.

**Comment by SamVerschueren** [comment]
Sorry for the late reply, working on this issue today so will keep you posted. One thing to clear up though as I don't use `code-push release-cordova` command, just the normal `code-push release` as I have a separate build process for my cordova application.

This is the command I use

```
$ code-push release AppName ./.cordova/platforms/android/assets/www ">0.16.0" --mandatory --deploymentName=Staging
```

I should point to the `www` directory, right? Not to `android` or something else? As I'm not sure it's a caching thing. I cleared my cache of the application and still shows the old app.

**Comment by max-mironov** [comment]
Thanks for update @SamVerschueren 
Yes, you should point to `./platforms/android/assets/www ` directory. Please see the reference in our docs [here](https://github.com/Microsoft/code-push/tree/master/cli#update-contents-parameter).

**Comment by SamVerschueren** [comment]
Apparently I can't reproduce this with the basic example. How does codepush work? Dus it overwrite the files in `android_asset/www` or does it create a new directory? The reason is because I use a base href which points to `file:///android_asset/www/`.

**Comment by max-mironov** [comment]
@SamVerschueren 
CodePush creates new directory based on packageHash ([code](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/www/localPackage.ts#L67)).
I believe your base href shouldn't be hardcoded as `file:///android_asset/www/`.

**Comment by SamVerschueren** [comment]
That was the issue! I'm using Angular 2 and in the beginning I had to set the base href to `file:///android_asset/www/`. I changed it to `.` and it works as well so 👌. Learned something new today :).

**Comment by max-mironov** [comment]
I'm glad to hear that it is working! Thanks for reply @SamVerschueren and for letting us know the reason of the issue :)
