### ISSUE TITLE
window.codePush undefined

### ISSUE THREAD

**Issue by AgDude** [Microsoft/cordova-plugin-code-push#283]
### Description

After installing an update using codepush `window.codePush` is undefined.  Since it is undefined, I can't call `notifyApplicationReady`, and thus the application rolls back on the next restart.

* I am using the manual/advanced workflow to install the plugin, with the ON_RESUME install mode and a 15 second delay for testing purposes. The install is performed by pressing a button in the app which checks, downloads and installs the update.  
* The update in question has only a change to the text on the index page.
*  After pressing this button and seeing the success message, I press the android home button (to pause the app).
* Wait 20 seconds and reopen the app. I can see the content change from the update at this point, At this point `window.codePush` is undefined

As a related question, where is the advised place to call `notifyApplicationReady` when using the ON_RESUME action? Will the app be forcefully restarted, causing deviceReady to fire after the update is installed?

### Additional Information

* cordova-plugin-code-push version: 1.9.7-beta
* List of installed plugins: only code-push and depencies
* Cordova version: 6.5.0
* iOS/Android/Windows version: android 6.0.1
* Does this reproduce on a debug build or release build? debug

**Comment by AgDude** [comment]
Closing this issue, as this was user error on my part. I had not correctly defined `updateContentsPath`, which needs to be `./platforms/android/assets/www` for android.

**Comment by max-mironov** [comment]
Hello @AgDude, thanks for asking.
Is it possible for you to reproduce your issue on sample app and share code with us of what you are doing? (this way it would be much easier for us to address this issue).

As for your 2nd question - I believe the best place to call `notifyAppReady` should be `onDeviceReady` event.
Please take a look at our [advanced sample logic](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/samples/advanced/www/js/index.js#L55) of using manual installation of the update and let us know if this works for you.
As for `deviceReady` event - I've verified that it is called also after update is installed via `ON_NEXT_RESUME`, see screenshot below:

![image](https://user-images.githubusercontent.com/24542698/29774458-51d9c34a-8bb6-11e7-98bf-c0b8759ce07d.png)

**Comment by AgDude** [comment]
@max-mironov Thanks for the response and for investigating.
