### ISSUE TITLE
Is it possible to install in background when triggering from cordova 'pause' event?

### ISSUE THREAD

**Issue by alexstanbury** [Microsoft/cordova-plugin-code-push#286]
If I add a listener like so: 

```
document.addEventListener("pause", function () {
        codePush.sync(null, {
            deploymentKey: 'MY_KEY_HERE',
            installMode: InstallMode.IMMEDIATE,
            mandatoryInstallMode: InstallMode.IMMEDIATE,
            minimumBackgroundDuration: 0
        });
        }, false);
```

Is it possible to have the app install immediately in the background  so it will be updated when the end user resumes the app?

I've tried on iOS simulator running 10.3 and it just seems to get stuck with this output:

```
[Log] [CodePush] Checking for update.
[Log] [CodePush] An update is available. {"appVersion":"1.0.0","deploymentKey":"my-key-here","description":"desc-here","downloadUrl":"url-here","isMandatory":false,"label":"v13","packageHash":"hash-here","packageSize":1769,"failedInstall":false} 
[Log] [CodePush] Downloading update
[Log] [CodePush] Sync already in progress.
```
Upon resuming the app the update is never installed, if I run the sync using the 'resume' event the console continually shows:

`[Log] [CodePush] Sync already in progress.`

every time I resume, and without using the 'resume' event nothing happens.

I have to force close it, then when opening it again it is then installed correctly using the 'deviceReady' hook.

**Comment by max-mironov** [comment]
Hi @alexstanbury, I'm afraid its not possible with cordova plugin at that moment. You are speaking about the same functionality as we have for `react-native-code-push` plugin - [ON_NEXT_SUSPEND](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#installmode)
 am I correct?

For `cordova-code-push-plugin` only the following [install modes](https://github.com/Microsoft/cordova-plugin-code-push#installmode) are available:
- IMMEDIATE
- ON_NEXT_RESTART
- ON_NEXT_RESUME

**Comment by max-mironov** [comment]
I'm closing the issue at that moment, please reach us if you have questions or have any considerations.
