### ISSUE TITLE
App crashing after download and run install

### ISSUE THREAD

**Issue by lanstudios** [Microsoft/cordova-plugin-code-push#288]
Hi Guys,

When the app first loads it connects to the code-push server and downloads the update.zip file. All that works fine, soon as i run the localPackage.install(onInstallSuccess, onError); part the app closes, then when you open it back up, it closes immediately. Is the app meant to close by itself once installed and not automatically open back up? 

I got a feeling the problem is when i commit the release to code-push something isn't going wrong there, because im using PGB and not the CLI so there isn't any cordova.js files or plugins being sent over, could that have something to do with it, or is it smart enough to only copy the HTML and JS files?

**Comment by lanstudios** [comment]
Actually technically that should be okay cause in the documentation and CLI it shows them upload only 1 file :/ any other ideas

**Comment by lanstudios** [comment]
I've tried changing all the options on the localPackage.install(onInstallSuccess, onError); but still the same. I've copied the example just to make sure its all 100% correct and till does the same thing. 

### Code
var onInstallSuccess = function () {
			    alert("Installation succeeded.");
			};

			var onError = function (error) {
			   	alert("An error occurred. " + error);
			};

			var onPackageDownloaded = function (localPackage) {
			    //alert("Package downloaded at: " + localPackage.localPath);


			    // you can now update your application to the downloaded version by calling localPackage.install()
			    localPackage.install(onInstallSuccess, onError);
			};

			var onProgress = function (downloadProgress) {
			    //console.log("Downloading " + downloadProgress.receivedBytes + " of " + downloadProgress.totalBytes + " bytes.");
			};

			var onUpdateCheck = function (remotePackage) {
			    if (!remotePackage) {
			        alert("The application is up to date.");
			    } else {
			        //alert("A CodePush update is available. Package hash: " + remotePackage.packageHash);
			        remotePackage.download(onPackageDownloaded, onError, onProgress);
			    }
			};

			window.codePush.checkForUpdate(onUpdateCheck, onError);

**Comment by lanstudios** [comment]
Publish code: code-push release com.hashlike .\www\ "*"
I've tried putting one js file, and the whole project in the www file, still the same crash.

**Comment by lanstudios** [comment]
I've rebuilt the app with CLI on a mac, and run in the emulator, still got the same issue

### System Log
Sep 14 15:09:26 Daniels-MBP Swipa[3830]: [CodePush] Installing update
Sep 14 15:09:29 Daniels-MBP Swipa[3830]: THREAD WARNING: ['File'] took '2414.200684' ms. Plugin should use a background thread.
Sep 14 15:09:30 Daniels-MBP Swipa[3830]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[4]'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x00000001105f334b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x000000011002b21e objc_exception_throw + 48
		2   CoreFoundation                      0x00000001105033b3 -[__NSPlaceholderArray initWithObjects:count:] + 275
		3   CoreFoundation                      0x000000011050a5c4 +[NSArray arrayWithObjects:count:] + 52
		4   Swipa                               0x000000010f241ef1 -[CodePush getStartPageURLForLocalPackage:] + 257
		5   Swipa                               0x000000010f240900 __23-[CodePush preInstall:]_block_invoke + 208
		6   libdispatch.dylib                   0x0000000112c35810 _dispatch_call_block_and_release + 12
		7   libdispatch.dylib                   0x0000000112c5712e _dispatch_client_callout + 8
		8   libdispatch.dylib                   0x0000000112c3d24c _dispatch_queue_override_invoke + 809
		9   libdispatch.dylib                   0x0000000112c3ea0e _dispatch_root_queue_drain + 506
		10  libdispatch.dylib                   0x0000000112c3e7b4 _dispatch_worker_thread3 + 113
		11  libsystem_pthread.dylib             0x00000001130e6746 _pthread_wqthread + 1299
		12  libsystem_pthread.dylib             0x00000001130e6221 start_wqthread + 13
	)
Sep 14 15:09:30 Daniels-MBP com.apple.CoreSimulator.SimDevice.3CC7F17F-761D-4187-839B-D4806F81FDA2.launchd_sim[3431] (UIKitApplication:com.swipa[0xcb7e][3830]): Service exited due to Abort trap: 6
Sep 14 15:09:30 Daniels-MBP backboardd[3453]: [Common] Unable to get short BSD proc info for 3830: No such process
Sep 14 15:09:30 Daniels-MBP backboardd[3453]: [Common] Unable to get proc info for 3830: No such process
Sep 14 15:09:30 Daniels-MBP assertiond[3456]: notify_suspend_pid() failed with error 7
Sep 14 15:09:30 Daniels-MBP SpringBoard[3452]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus

**Comment by max-mironov** [comment]
Hello @lanstudios, sorry for a delay in response :) 
So just to sum it up - you are still unable to get this working with cordova and you are using PGB for building the app, correct? 
You have tried it both on mac/win on emulator and on real device (btw it is not working for both iOS and android?)?
You are using [general](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-general) release command for uploading codepush releases?
Have you tried to use code-push with our [demo](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic) app, is it working correctly for you?

Could you also share the  output of `code-push deployment history AppName DeploymentName --format json` with us?

**Comment by lanstudios** [comment]
Hi Max,

Thanks for the reply, The original app is built with PGB and tried using the code push plugin on that, but kept crashing. The app keeps crashing after i run the install function. I bought a mac, set the app up fresh with cordova cli and tested it on the emulator and it still crashing except now i can see the error log, which is what i posted a few comments up. I've only tested on ios and not android since this is the main platform i want it on. I've tried general release and release-cordova both giving the same error. I havent tried your demo app yet. My next plan was to build a demo app with only the code push plugin in it to see if it works. I've also tried building with an older version of code-push to see what happens and, if found the update, but didnt download it, returned an error (ill post that here tomorrow, i have to rebuild).  

### Output
code-push deployment history com.swipa Staging --format json
[
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": null,
    "appVersion": "*",
    "packageHash": "0831d32ee8dd3a537ae6cb30e2db0748ffb7a19b57f78fd4195eea34fa2f6c1f",
    "blobUrl": "https://codepush.blob.core.windows.net/storagev2/QRTlYiyvva6wvDSaeVARLVPRWX1v73adb4a9-96fc-4227-bc95-dcec4511ae52",
    "size": 9103189,
    "manifestBlobUrl": "https://codepush.blob.core.windows.net/storagev2/jQHHHu-CdaDWfh96vm85b5Juzp1n73adb4a9-96fc-4227-bc95-dcec4511ae52",
    "releaseMethod": "Upload",
    "uploadTime": 1505360723994,
    "label": "v1",
    "releasedBy": "daniel132@live.com.au",
    "metrics": {
      "active": 0,
      "downloaded": 1,
      "failed": 0,
      "installed": 0,
      "totalActive": 0
    }
  },
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.1.4",
    "packageHash": "51b9578897e426160901379e1d4ddaf4f40942e64d09da47a15dc46e1abc2688",
    "blobUrl": "https://codepush.blob.core.windows.net/storagev2/zdfhje5EENgjhRi7StJAcEZJdPcU73adb4a9-96fc-4227-bc95-dcec4511ae52",
    "size": 9103289,
    "manifestBlobUrl": "https://codepush.blob.core.windows.net/storagev2/aKjYFtNC5x_evhLUh_GlExpfyMyU73adb4a9-96fc-4227-bc95-dcec4511ae52",
    "releaseMethod": "Upload",
    "uploadTime": 1505364427100,
    "label": "v2",
    "releasedBy": "daniel132@live.com.au",
    "diffPackageMap": {
      "0831d32ee8dd3a537ae6cb30e2db0748ffb7a19b57f78fd4195eea34fa2f6c1f": {
        "size": 21313,
        "url": "https://codepush.blob.core.windows.net/storagev2/Ygo_yJFiZI_R0c76-GMDVx7X28ZC73adb4a9-96fc-4227-bc95-dcec4511ae52"
      }
    },
    "metrics": {
      "active": 0,
      "downloaded": 2,
      "failed": 0,
      "installed": 0,
      "totalActive": 0
    }
  }
]

**Comment by max-mironov** [comment]
Hi there again @lanstudios, so AFAIK phonegap should work with code-push as I have verified it previously by myself :)
Is it possible that you have the same issue as we have discussed previously here: https://github.com/Microsoft/cordova-plugin-code-push/issues/232#issuecomment-287830575

Please let me know what you find out!

**Comment by lanstudios** [comment]
So it turns out if you don't have this <content src="index.html" /> in the config.xml, the code push wont work. I put it in and now it works.

**Comment by lanstudios** [comment]
`<content src="index.html" />`
