### ISSUE TITLE
Failed to load resource: Preflight response is not successful

### ISSUE THREAD

**Issue by seme1** [Microsoft/cordova-plugin-code-push#292]
### Description

I'm using this plugin in combination with Ionic-team's WKWebivew https://github.com/ionic-team/cordova-plugin-wkwebview-engine

Only when both plugins are installed, local links in my app cease to work with the following error reported in the console:
XMLHTTPRequest cannot load file://var/containers/Bundle/Application/APP-ID/www/..../somefile.html?par1=1&parameter2=somethingElse

It seems like WKWebview is rewriting all urls to load from http://localhost but cordova-plugin-code-push is also interfering with its update logic in order to load files locally ?

I used to use another push-code plugin https://github.com/nordnet/cordova-hot-code-push
for the same purpose but it is no longer maintained. I would love to try and use the Microsoft version of the plugin, but the above problem is still an obstacle preventing me from using it.

### Additional Information

* cordova-plugin-code-push version: latest
* Cordova version: latest
* iOS/Android/Windows version: IOS

**Comment by seme1** [comment]
This issue is related https://github.com/nordnet/cordova-hot-code-push/issues/264 and possible solution was posted by @chriswep . However, implementing the solution he posted requires major changes on the application side from my end.
It would be nice if the code-push plugin can detect the presence of WKWebview and re-write URLs if needed to start with http://localhost:8080 in order to support both plugins.

**Comment by max-mironov** [comment]
Hi there @seme1, thanks for reporting, we've such feature request previously, please see https://github.com/Microsoft/cordova-plugin-code-push/issues/188 for details. Unfortunately at that moment that is not something that we are going to work on in the nearest future but it would be awesome if someone can pick up this item and contribute, We would be happy to review and merge this going further.
