### ISSUE TITLE
iOS tests don't work

### ISSUE THREAD

**Issue by afoo** [Microsoft/cordova-plugin-code-push#296]
### Description

I tried running the tests for the iOS platform but couldn't get them to run. Steps to reproduce below, full output attached: [test-ios.txt](https://github.com/Microsoft/cordova-plugin-code-push/files/1320988/test-ios.txt)

### Reproduction

* clone the repository
* fix the TS compile error (see pull request #293)
* comment out the tslint task (see Issue #294)
* change the version number of code-push in plugin.xml to `2.0.2-beta` (leaving it as is produces another error even earlier)
* run `gulp test-ios --clean`

### Additional Information

* cordova-plugin-code-push version: 726d6ffe6b91e27ca04da3b350b828f8a8be9508 (latest from master)
* List of installed plugins: N/A
* Cordova version: 7.0.1
* iOS/Android/Windows version: latest iOS 11 SDK / Xcode 9 / macOS 10.12.6

**Comment by sergey-akhalkov** [comment]
Hi @afoo, thanks for pointing to this, tests are probably out of dated and should be fixed, unfortunately, the fix probably could take a lot of time and currently we have no resources to handle it and I believe we'll fix it in the future. Please also feel free to contribute and fix tests - we'll be very grateful.

**Comment by iTOYS** [comment]
Hi @afoo 
I've fixed `gulp test-ios --clean` so you can try it #367 
Unfortunately we still have 3 failed tests(

Thanks!
