### ISSUE TITLE
My code-push did't work well

### ISSUE THREAD

**Issue by code-coder** [Microsoft/cordova-plugin-code-push#297]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description
I had two problems.
My usage :  `this.codePush.checkForUpdate().then((IRemotePackage)=>{console.log(IRemotePackage.appVersion);})`
the result is not the latest version.
And
I use `this.codePush.sync({installMode: 0}, this.downloadProgress).subscribe((syncStatus) => {})`
It download the package but it did not restart the APP.
[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.]

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

XCODE had this information, but the APP did not restart

2017-09-22 16:38:40.034429+0800 Lark[16625:7515160] Resetting plugins due to page load.
2017-09-22 16:38:40.342990+0800 Lark[16625:7515160] Finished load of: file:///var/mobile/Containers/Data/Application/0A6B40C6-940D-4C5B-8D69-C99FD0A6FD9B/Library/NoCloud/codepush/deploy/versions/f0a990d876b0965e0aa9bd26aebed8e855143c5b1cace330da46c9e420e9557c/www/index.html

### Additional Information

* cordova-plugin-code-push version: 1.9.8-beta
* List of installed plugins:
"cordova": {
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-dialogs": {},
      "cordova-plugin-camera": {
        "CAMERA_USAGE_DESCRIPTION": " ",
        "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
      },
      "cordova-plugin-app-version": {},
      "cordova-plugin-file": {},
      "cordova-plugin-appminimize": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-touch-id": {},
      "cordova-sqlite-storage": {},
      "com.kit.cordova.amaplocation": {},
      "com.kit.cordova.amapnavigation": {},
      "cordova-plugin-http": {},
      "cordova-plugin-qqsdk": {
        "QQ_APP_ID": "1106296181"
      },
      "cordova-plugin-wechat": {
        "WECHATAPPID": "wxe90d4bf91187f744"
      },
      "jpush-phonegap-plugin": {
        "APP_KEY": "b2fe6441aa6f4534ebb9a4c7"
      },
      "cordova-plugin-secure-storage": {},
      "phonegap-plugin-barcodescanner": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-code-push": {},
      "com.synconset.imagepicker": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": " "
      }
    }
* Cordova version:7.0.1
* iOS/Android/Windows version:IOS 10.3.3
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by code-coder** [comment]
I resolved my problems. I should not change the app version in config.xml. And the version should stay the same, or else codePush dose not work well.

**Comment by sergey-akhalkov** [comment]
Hi @code-coder, yes, you should not increment your app version after releasing an CodePush update, because all CodePush updates are targeting to specific app binary version, please see https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter

Let us know if you have any questions or see any issues.
