### ISSUE TITLE
iOS release always rolling back

### ISSUE THREAD

**Issue by MattHoneycutt** [Microsoft/cordova-plugin-code-push#298]
### Description

I'm using v1.9.7-beta of the plugin. 

The plugin works fine for Android versions of my app.  However, it seems to fail on iOS.  Updates are applied, but they are rolled back on the next app restart, even though the app was updated correctly.

### Reproduction

Run the following command: 

code-push release-cordova <app name> ios -d Production

I'm running the following code on both deviceready and on resume:

        codePush.sync(status => {
            console.log('CodePush sync status changed: ' + status);
        }, {installMode: InstallMode.IMMEDIATE});

Again, I can see the new update being installed, but it then rolls back.

Looking at the release history, I see this:

![image](https://user-images.githubusercontent.com/156878/30775020-83c68924-a051-11e7-994f-a886c5c282d2.png)

### Additional Information

* cordova-plugin-code-push version: 1.9.7-beta
* List of installed plugins: 
cordova-plugin-app-event
cordova-plugin-code-push
cordova-plugin-compat
cordova-plugin-device
cordova-plugin-dialogs
cordova-plugin-file
cordova-plugin-file-transfer
cordova-plugin-network-information
cordova-plugin-splashscreen
cordova-plugin-statusbar
cordova-plugin-whitelist
cordova-plugin-zip
phonegap-plugin-push

* Cordova version:
iOS Platform version: 4.4.0
Cordova version: 7.0.1

* iOS Version: 10.2.1

* Does this reproduce on a debug build or release build?  Both 

* Does this reproduce on a simulator, or only on a physical device?  Physical device

**Comment by MattHoneycutt** [comment]
To add even more fuel to the fire: it looks like it isn't even trying to install the latest release that I've published.  If I "patch" the older releases and disable them, leaving only the most recent release enabled, it does not try to apply any updates.  

I did test this out on the simulator, and everything works fine.

**Comment by max-mironov** [comment]
Hello @MattHoneycutt and thanks for asking.
Do you use separate deployment keys for each platform?

**Comment by MattHoneycutt** [comment]
I do, I followed the tutorial, so I actually made separate "apps" for each platform.  I've double-checked my keys, and they are correct.

**Comment by max-mironov** [comment]
@MattHoneycutt looks odd :) 
Can you share the minimum app with us so we can try it on our side?
Or probably you could debug the app and see if you have something suspicious in developers console?

**Comment by MattHoneycutt** [comment]
I'm unable to debug the final, signed version of the app that was released through the app store, but rebuilding and deploying locally or to the simulator works just fine.  No errors, no warnings, it correctly installs the latest upgrade that's available.

**Comment by max-mironov** [comment]
@MattHoneycutt sorry, initially I suppose that both debug and release builds are not working because of this:
>Does this reproduce on a debug build or release build? Both

Anyway is it possible for you to produce new release on prod to verify if it will be also rolled back or not?

**Comment by max-mironov** [comment]
@MattHoneycutt please let us know if you have a chance to look at this.

**Comment by MattHoneycutt** [comment]
I will, but it will probably be sometime Friday before I can get back to this.

**Comment by max-mironov** [comment]
@MattHoneycutt ok got it, please let us know the results.

**Comment by max-mironov** [comment]
I'm closing this item for now, please reopen or let us know when you get a chance to revisit it.
