### ISSUE TITLE
Code push issue started again

### ISSUE THREAD

**Issue by Wallethub** [Microsoft/cordova-plugin-code-push#300]
This issue #272 and #281 and #287 has started coming up again. Same scenario and has started since 1:24:47 AM EDT today and has increased in values since then.

Please check if there is an issue on your side.

Thanks,
Wallethub Team

**Comment by max-mironov** [comment]
Closing this as it is mitigated at that moment, please refer to this comment for more details regarding the this: https://github.com/Microsoft/react-native-code-push/issues/1028#issuecomment-335560805
