### ISSUE TITLE
Push code "Production" deployment

### ISSUE THREAD

**Issue by pallaviMN** [Microsoft/cordova-plugin-code-push#302]
Unable to push the code to production.

I ran the command - code-push release-cordova InsightApp android.

Later it showed below success message. I want to push the code to production. I have used production key in the config.xml

Successfully released an update containing the "D:\InsightApp3rdMarch\platforms\android\assets\www" directory to the "Staging" deployment of the "InsightApp" app.

* cordova-plugin-code-push version: 1.9.8

* Cordova version: 6.5.0
* Android version: 4.3
* Does this reproduce on a simulator, or only on a physical device? - Physical device

**Comment by ruslan-bikkinin** [comment]
Hi @pallaviMN and thanks for submitting the issue. You can push update to production using `promote` command. Please refer to documentation [section](https://github.com/Microsoft/code-push/tree/master/cli#promoting-updates). 

Let us know if this information was helpful for you or you need any more assistance from our side.

**Comment by ruslan-bikkinin** [comment]
@pallaviMN could you please let us know whether you need more help with issue?

**Comment by pallaviMN** [comment]
@ruslan-bikkinin , no thanks for the information
