### ISSUE TITLE
Codepush issue started again

### ISSUE THREAD

**Issue by Wallethub** [Microsoft/cordova-plugin-code-push#304]
Hi, 
This issue #272 and #281 and #287 and #300 has started coming up again. Same scenario and has started since 11:03:05 AM EDT today and has increased in values since then.

Please check if there is an issue on your side.

Thanks,
Wallethub Team

**Comment by ruslan-bikkinin** [comment]
Hi @Wallethub 
This seems like duplicate to this issue, so could you please refer to the exisiting [one](https://github.com/Microsoft/react-native-code-push/issues/1028) in future. 
So, I am closing this for now.
