### ISSUE TITLE
How to use the plugin with build.phonegap.com

### ISSUE THREAD

**Issue by Rajesh71983** [Microsoft/cordova-plugin-code-push#308]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I am new to phonegap development.  We are using build.phonegap.com to build and release new version. We are sending the build url to install latest app update. 

We need to make this process automated. We are not going upload the app in ios app store as the app is specific for limited number of devices.  

When i searched i have got the this code push solution, but it looks like it is completely CLI based. 

Can you please help me using code push at build.phonegap.com. Please provide step by step process if it is possible to use at online build tool

**Comment by sergey-akhalkov** [comment]
Hi @Rajesh71983, thanks for reaching us and sorry for the delayed response. Unfortunately, we do not have step by step guides, but please take a look at the following: https://github.com/Microsoft/cordova-plugin-code-push#phonegap-build

Please let me know if you see any issues or have any questions.

**Comment by ruslan-bikkinin** [comment]
I am closing this for now, please feel free to reopen if needed.
