### ISSUE TITLE
Alert user on application rollback

### ISSUE THREAD

**Issue by dlebu** [Microsoft/cordova-plugin-code-push#31]
We are thinking about adding an aditional parameter to apply(), such that the user can optionally be alerted when their application is rolled back to the previous version in case of a bad update. We are also thinking about adding a new flag (potentially to LocalPackage) such that developers can react to the rollback.

**Comment by ryanlin1986** [comment]
I think this is good.

**Comment by dlebu** [comment]
@ryanlin1986 Thanks for your feedback. Can you share more details about your scenario?

**Comment by lostintangent** [comment]
I'm going to close this since I no longer think we would pursue displaying any UI to the end user before performing a rollback. We also haven't heard any feedback here from either the Cordova or React Native side, so I'm comfortable closing this until we hear more instead of keeping it around.
