### ISSUE TITLE
How to use CodePush from Ionic2 Typescrit app?

### ISSUE THREAD

**Issue by flaviomedeiros** [Microsoft/cordova-plugin-code-push#311]
Just created a new _Ionic2_ application using the [Super Starter](https://github.com/ionic-team/ionic-starter-super) template and tried to use _CodePush_ following _Cordova_ instructions from [https://github.com/Microsoft/cordova-plugin-code-push#getting-started](https://github.com/Microsoft/cordova-plugin-code-push#getting-started).

How to inject _CodePush_ to call `codePush.sync()` on `deviceready` event?

The `deviceready` event is declared on file `src\app\app.component.ts` as `platform.ready()`.

Environment:

OS: Windows 10 version 1703  
Ionic v3.15.2  
Node v6.11.4  
Cordova v7.1.0

**Comment by max-mironov** [comment]
Hello @flaviomedeiros, you probably should declare codePush before calling this. 
I believe something like this should work in app.component.ts:
```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';

import { HomePage } from '../pages/home/home';


declare const codePush:any


@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage = HomePage;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();
      codePush.sync();
      console.log('12 - sync call above');
    });
  }
}

```

**Comment by max-mironov** [comment]
@flaviomedeiros please let us know if you have a chance to look at this

**Comment by max-mironov** [comment]
Closing this, please let us know if any further help heeded.
