### ISSUE TITLE
Code push not compatible with Ionic WkWebview

### ISSUE THREAD

**Issue by robobobo** [Microsoft/cordova-plugin-code-push#315]
### Description
After upgrading my ionic application to support iOS11 I also updated the WkWebview to the new ionic optimised [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview) I discovered the I can no longer build my iOS app with Code-push 1.9.8-beta

I get the below error in Xcode
`Undefined symbols for architecture arm64: "_OBJC_CLASS_$_CDVWKWebViewEngine", referenced from: l_OBJC_$_CATEGORY_CDVWKWebViewEngine_$_CodePush in CDVWKWebViewEngine+CodePush.o`

If I remove code-push then it works perfectly fine

## Reproduction

Setup a new ionic project with the new ionic optimised [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview) 

App will compile fine for iOS

Install code-push
`cordova plugin add cordova-plugin-code-push@latest`

Try and build app 
`ionic cordova build ios`

Build will fail when attempting to run on a device with below error
`Undefined symbols for architecture arm64: "_OBJC_CLASS_$_CDVWKWebViewEngine", referenced from: l_OBJC_$_CATEGORY_CDVWKWebViewEngine_$_CodePush in CDVWKWebViewEngine+CodePush.o`

### Additional Information
* conflicting plugin
[cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview)
* cordova-plugin-code-push version: 
Code-push 1.9.8-beta
* Cordova version:
Cordova Platforms  : ios 4.5.3
 ionic (Ionic CLI) : 3.16.0

* iOS/Android/Windows version:
iOS 11
 Xcode      : Xcode 9.1 Build version 9B55
* Does this reproduce on a debug build or release build?
Only tried debug build for now
* Does this reproduce on a simulator, or only on a physical device?
Both

**Comment by sergey-akhalkov** [comment]
Hi @robobobo, thanks for reaching us, please take a look at the following https://github.com/Microsoft/cordova-plugin-code-push/issues/188#issuecomment-330625235

I'm closing this, please let me know if you have any questions.

**Comment by saschwarz** [comment]
This appears to be the solution: https://github.com/Microsoft/cordova-plugin-code-push/issues/371
