### ISSUE TITLE
Getting a white screen of death for Ionic app 

### ISSUE THREAD

**Issue by veti-io** [Microsoft/cordova-plugin-code-push#317]
### Description

Usingi Ionic  4.3.1 (angular 4.4.4) when I tried to use CodePush upon first download of an app update I would get a splash screen and then a blank white screen. This happened on my iPhone 5S and on the simulator for an iPhone 5S

### Reproduction

This is a rough list of steps to reproduce
1. create a project with the current ionic conference app template
2. add the code push plugin
3. build app, deploy to device or emulator
4. make a deployment, add the deployment keys to preferences 
5. close app, open app, see white screen of death

### Additional Information

* cordova-plugin-code-push version: 1.9.8-beta
* List of installed plugins:
"plugins": {
            "cordova-plugin-crosswalk-webview": {
              "XWALK_VERSION": "22+",
              "XWALK_LITEVERSION": "xwalk_core_library_canary:17+",
              "XWALK_COMMANDLINE": "--disable-pull-to-refresh-effect",
              "XWALK_MODE": "embedded",
              "XWALK_MULTIPLEAPK": "true"
            },
            "cordova-plugin-device": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-whitelist": {},
            "cordova-plugin-ionic-webview": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-ionic-keyboard": {},
            "com.microblink.BlinkIdScanner": {
              "CAMERA_USAGE_DESCRIPTION": "Scan"
            }
        }
* Cordova version: 7.0.1
* iOS/Android/Windows version: 11
* Does this reproduce on a debug build or release build? not sure
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by ruslan-bikkinin** [comment]
Hi @veti-io and thanks for submitting the issue. I don't see `cordova-plugin-code-push` in installed plugins list you provided. Please could you provide us whole config file for the project you are using?

**Comment by veti-io** [comment]
This was an issue with my code, not with code push. thanks for your help!
