### ISSUE TITLE
 Can't compile

### ISSUE THREAD

**Issue by zhangzhaojun** [Microsoft/cordova-plugin-code-push#318]
I used cordova-plugin-code-push@1.10 in my ionic3 app,the plugin require cordova-android >=6.3.0,but i used the cordova-android =6.1.2，I don't want to update,so what can i do?

**Comment by max-mironov** [comment]
Hi @zhangzhaojun, I believe that you should upgrade to 6.3.0 or later because if this issue: https://github.com/Microsoft/cordova-plugin-code-push/issues/319

**Comment by ruslan-bikkinin** [comment]
Closing this as duplicate #319
