### ISSUE TITLE
Increased number of rolledback events

### ISSUE THREAD

**Issue by Wallethub** [Microsoft/cordova-plugin-code-push#323]
Hi,
We've been seeing an increased number of rolledback events since yesterday at 17:00 PM EST.
Please check if there's an issue on your side.

**Comment by max-mironov** [comment]
Hello @Wallethub, sorry for late response. Do you still face the issue? Probably that could be a service blip or something else, currently that looks like things are going well.

**Comment by max-mironov** [comment]
Closing this, let us know if the issue still persist for you.
