### ISSUE TITLE
IOS (wkwebview) not support Code push on first launch 

### ISSUE THREAD

**Issue by hugoblanc** [Microsoft/cordova-plugin-code-push#324]
After update to WkWebview with ionic cordova there is an error on first launch(if I try again then it works fine)

I call the following code into my first component => app.component

`        
    this.platform.ready().then(() => {
      if (!this.platform.is("mobileweb")) {

        this.codePush.sync().subscribe((syncStatus) => console.log(syncStatus));

        const downloadProgress = (progress) => { console.log(`Downloaded ${progress.receivedBytes} of ${progress.totalBytes}`); }
        this.codePush.sync({}, downloadProgress).subscribe((syncStatus) => console.log(syncStatus));
      }
`

When I build with xcode, the first launch is stuck because of this: 
`
-[WKWebView evaluateJavaScript:completionHandler:] must be used from main thread only
`

screenshot 
https://imagebin.ca/v/3hqO9jTowS5O

### Reproduction
I think this issue is related to the new Wkwebview of IOS which will be the futur main webview of IOS. 
Then In my case the problem happend after the installation of cordova-plugin-ionic-webview on app launch

**Comment by max-mironov** [comment]
Hello @hugoblanc unfortunately I believe that CodePush is not compatible with Ionic WKWebView at all. Please see e.g. this thread for details: https://github.com/Microsoft/cordova-plugin-code-push/issues/315

**Comment by max-mironov** [comment]
Closing this as currently we are are not going to support and fix issues with 3rd party plugins due to other priorities.
