### ISSUE TITLE
Cordova FileTransfer/FileUtils Error

### ISSUE THREAD

**Issue by itshu** [Microsoft/cordova-plugin-code-push#326]
### Description

Android build fails after installing cordova-plugin-code-push.
 

### Additional Information

cli packages: (C:\Users\Administrator\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.1.2
    npm               : 5.0.3
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : E:\androidsdk\android-sdk-windows

Misc:

    backend : legacy

plugin list:
code-push 2.0.1-beta "CodePushAcquisition"
cordova-plugin-code-push 1.10.0-beta "CodePush"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-ionic-webview 1.1.11 "Ionic's WKWebView Engine"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-keyboard 2.2.1 "Keyboard"

### ERROR Information

:compileDebugJavaWithJavac

:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no p
revious execution, etc.).
E:\cordova\ionic3\tmc\platforms\android\src\org\apache\cordova\filetransfer\File
Transfer.java:49: ����: �����org.apache.cordova.file������
import org.apache.cordova.file.FileUtils;
                              ^
E:\cordova\ionic3\tmc\platforms\android\src\org\apache\cordova\filetransfer\File
Transfer.java:851: ����: �Ҳ�������
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");

                        ^
  ����: �� FileUtils
E:\cordova\ionic3\tmc\platforms\android\src\org\apache\cordova\filetransfer\File
Transfer.java:851: ����: �Ҳ�������
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");

                                                ^
  ����: �� FileUtils
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�������ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
3 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
:compileDebugJavaWithJavac FAILED

BUILD FAILED

Total time: 7.58 secs
Error: cmd: Command failed with exit code 1 Error output:
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
E:\cordova\ionic3\tmc\platforms\android\src\org\apache\cordova\filetransfer\File
Transfer.java:49: ����: �����org.apache.cordova.file������
import org.apache.cordova.file.FileUtils;
                              ^
E:\cordova\ionic3\tmc\platforms\android\src\org\apache\cordova\filetransfer\File
Transfer.java:851: ����: �Ҳ�������
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");

                        ^
  ����: �� FileUtils
E:\cordova\ionic3\tmc\platforms\android\src\org\apache\cordova\filetransfer\File
Transfer.java:851: ����: �Ҳ�������
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");

                                                ^
  ����: �� FileUtils
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�������ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
3 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

[ERROR] An error occurred while running cordova build android (exit code 1).

WHY???

**Comment by andrefa** [comment]
I have the same problem, but only on BuddyBuild automated build tool.

**Comment by ruslan-bikkinin** [comment]
Hi @itshu and thanks for submitting the issue. Please take a look at these comments: https://github.com/Microsoft/cordova-plugin-code-push/issues/322#issuecomment-346301825 https://github.com/Microsoft/cordova-plugin-code-push/issues/320#issuecomment-344873279 and try solutions provided there (if they fits your case). Let us know whether it helps you or not.

**Comment by ruslan-bikkinin** [comment]
Hi @itshu did you have a chance to look at this?

**Comment by itshu** [comment]
@ruslan-bikkinin   
I did like this  but it's not work
uninstall code push plugin
uninstall file & file-transfer plugins
update my cordova-android platform to 6.3.0
install file 4.3.2
install code-push 1.9.3-beta
remove & re-add Android platform
#320

**Comment by caritasverein** [comment]
Any updates here :)?

**Comment by ruslan-bikkinin** [comment]
@itshu @caritasverein sorry for delated response. I tried to reproduce this issue but after upgrading `cordova-android` from `6.2.3` to `6.3.0` build errors have gone. Please take a look at my [working demo project](https://github.com/ruslan-bikkinin/co326-demo) and let me know if I missed something while configuring it.

**Comment by ruslan-bikkinin** [comment]
@itshu @caritasverein huys, did you have a chance to look at this?

**Comment by ruslan-bikkinin** [comment]
I am closing this for now, feel free to re-open it in case if your issue will be still existing.
