### ISSUE TITLE
Thread warning on IOS

### ISSUE THREAD

**Issue by tux240** [Microsoft/cordova-plugin-code-push#329]
Hi,

A use the sync on a resume state and I get this error message from the console on IOS 11 :
- THREAD WARNING: ['CodePush'] took '1082.812988' ms. Plugin should use a background thread.

Did you already have this king of issue ?

thanks

**Comment by karlbohlmark** [comment]
I just got this as well. I do sync on deviceready.
```
THREAD WARNING: ['CodePush'] took '26.326172' ms. Plugin should use a background thread.
```

**Comment by sergey-akhalkov** [comment]
Hey guys, my apologies for the delayed response as we are a little under-resourced, especially as the holiday season is coming up. Does this warning somehow block you now? If so, I believe we'll have a chance to take a look at it soon, but If there is anybody from the community who has input or would like to submit PR's, we will gladly accept them!

**Comment by karlbohlmark** [comment]
Hi! Nope, it's not blocking me right now at least. Just want to know what's going on. I'll update you if it seems serious.
