### ISSUE TITLE
Unclear Version Information

### ISSUE THREAD

**Issue by F1LT3R** [Microsoft/cordova-plugin-code-push#331]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

Version information in documentation is unclear.

### Reproduction

The README.md states:

> Note: In order to use `CodePush` along with the `cordova-plugin-wkwebview-engine` plugin, you need to install `v1.5.1-beta+`, which includes full support for apps using either WebView.

Is this referring to version 1.5.1-beta of the `code-push` codebase or the `cordova-plugin-wkwebview-engine`?

**Comment by sergey-akhalkov** [comment]
Hi @F1LT3R, thanks for reaching us! `v1.5.1-beta+` relates to the code-push, please see https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/1.5.1-beta

I've fixed the docs, thanks for the feedback!

So I'm closing the issue, please feel free to create a new one in case you have any questions or see any issues.

**Comment by F1LT3R** [comment]
That's great to know thanks @sergey-akhalkov !
