### ISSUE TITLE
window.codePush not available

### ISSUE THREAD

**Issue by jpike88** [Microsoft/cordova-plugin-code-push#332]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

window.codePush never gets loaded, so I'm using var codePush = cordova.require("cordova-plugin-code-push.codePush")

### Reproduction

fresh Cordova install.

### Additional Information

* cordova-plugin-code-push version: latest
* List of installed plugins:latest
* Cordova version: latest
* iOS/Android/Windows version:latest
* Does this reproduce on a debug build or release build?both
* Does this reproduce on a simulator, or only on a physical device?both

(The more info the faster we will be able to address it!)

**Comment by ruslan-bikkinin** [comment]
Hi @jpike88 and sorry for late response. Please double check that you accurately followed our [Getting Started](https://github.com/Microsoft/cordova-plugin-code-push#getting-started) and [Plugin usage](https://github.com/Microsoft/cordova-plugin-code-push#plugin-usage) docs sections. Also please share with us your application code samples and provide more detailed information about you environment  (**Additional Information** section of your first message) in case if you correctly configured your app.

**Comment by ruslan-bikkinin** [comment]
I am closing this for now, feel free tore-open it if needed.
