### ISSUE TITLE
Error when updating: Unable to verify signature for package: Error occurred while creating the a public

### ISSUE THREAD

**Issue by eduboxgithub** [Microsoft/cordova-plugin-code-push#333]
### Description

Unable to make an update. The app starts, detects and update, downloads the update and then the app crashes. Here is the logo:

```
[CodePush] Checking for update.
codePushUtil.js:36 [CodePush] An update is available. {"appVersion":"1.6.8","deploymentKey":"79Ucd8sJVuQ1NlVmW1568cXNj2--14483cab-29b0-4415-94d8-d11f5fdf6060","description":"lorem test 2","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/CwY8FWP0MP2EegjeWHmQGNzDcEMH14483cab-29b0-4415-94d8-d11f5fdf6060","isMandatory":false,"label":"v8","packageHash":"6c1dc1efac0d4882c4971bb4163593e5e5c327c57e7ddf42462394cdc5686ebe","packageSize":2991637,"failedInstall":false}
codePushUtil.js:36 [CodePush] Awaiting user action.
app.min.js:163085 7
codePushUtil.js:36 [CodePush] Downloading update
app.min.js:163025 Downloading 1612 of 2991637
app.min.js:163025 Downloading 9804 of 2991637
...
app.min.js:163025 Downloading 2989644 of 2991637
app.min.js:163025 Downloading 2991637 of 2991637
app.min.js:163025 Downloading 1613388 of 2991637
codePushUtil.js:36 [CodePush] Package download success: {"deploymentKey":"79Ucd8sJVuQ1NlVmW1568cXNj2--14483cab-29b0-4415-94d8-d11f5fdf6060","description":"lorem test 2","label":"v8","appVersion":"1.6.8","isMandatory":false,"packageHash":"6c1dc1efac0d4882c4971bb4163593e5e5c327c57e7ddf42462394cdc5686ebe","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
app.min.js:163091 8
codePushUtil.js:36 [CodePush] Installing update
codePushUtil.js:36 [CodePush] Applying full update
codePushUtil.js:36 [CodePush] Verifying hash for folder path: /codepush/deploy/versions/6c1dc1efac0d4882c4971bb4163593e5e5c327c57e7ddf42462394cdc5686ebe/
codePushUtil.js:36 [CodePush] The update contents succeeded the data integrity check.
codePushUtil.js:36 [CodePush] Verifying signature for folder path: /codepush/deploy/versions/6c1dc1efac0d4882c4971bb4163593e5e5c327c57e7ddf42462394cdc5686ebe/
codePushUtil.js:40 [CodePush]  Unable to verify signature for package: Error occurred while creating the a public keyjava.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c074079:ASN.1 encoding routines:ASN1_get_object:HEADER_TOO_LONGCodePushUtil.logError @ codePushUtil.js:40CodePushUtil.invokeErrorCallback @ codePushUtil.js:44installError @ localPackage.js:43verificationFail @ localPackage.js:94decodeSignatureFail @ localPackage.js:202callbackFromNative @ cordova.js:295(anonymous function) @ VM660:1
codePushUtil.js:40 [CodePush] An error occurred during sync.
```

### Additional Information

* cordova-plugin-code-push version:  1.10.1

* List of installed plugins:
code-push 2.0.5 "CodePushAcquisition"
com.lampa.startapp 0.1.4 "startApp"
com.transistorsoft.cordova.background-geolocation 1.5.0 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appmunicipios 0.0.1 "Plugin App Municipios"
cordova-plugin-badge 0.7.3 "Badges"
cordova-plugin-calendar 4.5.5 "Calendar"
cordova-plugin-camera 2.4.0 "Camera"
cordova-plugin-code-push 1.10.1 "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-dialogs 1.3.2 "Notification"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-globalization 1.0.6 "Globalization"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-network-information 1.3.2 "Network Information"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
phonegap-plugin-push 1.10.5 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.0 "Launch Navigator"

* Cordova version: 6.5.0

* iOS/Android/Windows version: Android 6.1.2

* Does this reproduce on a debug build or release build? Build

* Does this reproduce on a simulator, or only on a physical device? Physical device

**Comment by ruslan-bikkinin** [comment]
Hi @eduboxgithub and thanks for submitting the issue. Could you please share with us how did you create private/public key pair for code signing? Also, please, make sure that `CodePushPublicKey` preference value is in correct format in your `config.xml`.

**Comment by eduboxgithub** [comment]
Hi @ruslan-bikkinin,

I follow the documentation steps.

First I start with code-push cli and  follow the command below:
$  code-push app add [appName] [os] [platform]

And then, the keys generated I paste on the config.xml:
preference name="CodePushPublicKey" value="YOUR-PUBLIC-KEY" 

I generate private  and public key with openssl:
$ openssl genrsa -out privatekey.pem
$ openssl rsa -pubout -in privatekey.pem -out publickey.pem

And create the update:
$ code-push release-cordova nameApp --description "test" --targetBinaryVersion "1.6.8" --deploymentName Staging -b -k ./privatekey.pem

Thanks

**Comment by ruslan-bikkinin** [comment]
@eduboxgithub 

>First I start with code-push cli and follow the command below:
>$ code-push app add [appName] [os] [platform]
> And then, the keys generated I paste on the config.xml:
> preference name="CodePushPublicKey" value="YOUR-PUBLIC-KEY"

Those keys are deployment keys and you should place one of them (for example for `Staging` environment) into `CodePushDeploymentKey` preference value. For example:

```xml
<preference name="CodePushDeploymentKey" value="rHwiZQKWRSRZ0svGPNh-gZZmhzlta4c23a71-4e6c-4f9b-8f95-4fb15b6dd8b5" />
```

Public key generated for code signing via openssl should be placed into `CodePushPublicKey` preference value. For example:

```xml
<preference name="CodePushPublicKey" value="-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApzHq0A4DajW/nY0/Hi7V
3btfyyT2ibbvNQNpTTRZYXB/Q66IOWkvH+dIESOUxQPY+aeSZedgxxj+ynL0+jGc
c9t9+XIzmQIK7OH/YZCpBtVEE+BVUiyWKJVFISpgekh5ZWbfcIhAVF0CcWpfSBsC
/ArgvezKhBr6LsAI3v5TSV0qXSvSGVXJgbxNVR5u8Mv3KfUutxs8TjAu6/JBWhSi
7cAfR7b3J424MN+aCZjaUgOA4B2UshgosmuTjMyJX0UDWaahxTL1stlzMaO8q3nT
U162ayr4ctw/tMF8WqpcbITSvE8AMqXAA3nfduFGmmN+s8zYOFPQSQJ0JbEifjI/
+QIDAQAB
-----END PUBLIC KEY-----" />
```

Please refer to [Getting Started](https://github.com/Microsoft/cordova-plugin-code-push#getting-started) and [Deployment Management](https://github.com/Microsoft/code-push/tree/master/cli#deployment-management) sections for more information.

Let us know if it helps or you'll need more assistance from our side.

**Comment by ruslan-bikkinin** [comment]
I am closing this for now, feel free to re-open if needed.
