### ISSUE TITLE
[ERROR] Uploaded File is greater than 400 Mb

### ISSUE THREAD

**Issue by zersys** [Microsoft/cordova-plugin-code-push#334]
Description
I have an app that has is 500Mb, I am unable to release content updates to the app anymore as I get the following error

"[Error]  The uploaded file is larger than the size limit of 400 megabytes."

Additional Information

* cordova-plugin-code-push version: 1.10.0-beta
* List of installed plugins:
cordova-plugin-whitelist
"cordova-plugin-device
"cordova-plugin-dialogs
"cordova-plugin-network-information"
"cordova-plugin-splashscreen"
"cordova-plugin-statusbar"
"cordova-plugin-fullscreen"
"cordova-plugin-file"
"cordova-plugin-file-transfer"
"cordova-plugin-code-push"
"cordova-plugin-crosswalk-webview"
* Cordova CLI version:7.1.0

How can I resolve this ?

**Comment by sergey-akhalkov** [comment]
Hi @zersys, thanks for reaching us and sorry for the inconvenience, do I get it right if you have not experienced this issue before and your update size was more than 400mb?

**Comment by zersys** [comment]
@sergey-akhalkov : This is the first time our app size has exceeded 400mb and also the first time we are seeing this issue. All our previous updates were lesser than 400mb and we did not have any issues with them whatsoever.

**Comment by sergey-akhalkov** [comment]
@zersys, got it, thanks for the clarification. I'm going to share this issue w/ right person and let you know if any updates.

**Comment by sergey-akhalkov** [comment]
Hi @zersys, we've discussed this limitation internally and to resolve your issue we've increased file upload size limitation to 500mb - it's a maximum size that we have the ability to allow now.

Please note that some time is required to apply new limitation value, so I believe you should be able to release an update in several hours - let us know if you'll see _"[Error] The uploaded file is larger than the size limit of 400 megabytes."_ error again.

**Comment by zersys** [comment]
Hi @sergey, Thank you so much for the fix ! we will try and update by EOD and revert incase of any issues.

We can live with this for now, but is there anyway around this in future ? , as we foresee that our app would exceed 500MB soon. Is there is a paid subscription that we can avail to increase the limit ?

**Comment by sergey-akhalkov** [comment]
@zersys, right now we have the ability to customize it per customer, but I think it probably could be good improvement for CodePush - so we'll discuss it internally and let you know the result.

**Comment by zersys** [comment]
@sergey-akhalkov, Eagerly awaiting the result.

**Comment by sergey-akhalkov** [comment]
Hi @zersys, we've discussed this internally and we have the following plan:
1. Complete Implementation of new file-upload-service for CodePush backend
2. Integrate related changes to the AppCenter CLI
3. Switch from CodePush CLI to AppCenter CLI
4. New upload service should have a high limit of file upload size - I could be wrong but if I get it right it should be ~ 4GB.

Another words we are going to complete new upload service integration soon next year so you'll be able to make uploads without any problems.

I'm closing this for now, please feel free reopen or ping us if you have any questions or see any issues.

**Comment by zersys** [comment]
Hi Sergey,  As mentioned we have hit the 500mb limit today. I get an error message saying "Error: The uploaded file is larger than the size limit of 500 megabytes."
