### ISSUE TITLE
An error occurred during sync. Deployment key not found

### ISSUE THREAD

**Issue by Basavaraj-Tanikedar** [Microsoft/cordova-plugin-code-push#340]
An error occurred during sync. Deployment key not found

**Comment by ruslan-bikkinin** [comment]
Hi @Basavaraj-Tanikedar and thanks for reaching us. Please update using issue template so we could help you quicker with your problem.

**Comment by ruslan-bikkinin** [comment]
So I am closing this for now. Feel free to create the new one using our issue template.
