### ISSUE TITLE
Include multi-deployment keys in config.xml

### ISSUE THREAD

**Issue by jpike88** [Microsoft/cordova-plugin-code-push#342]
Instead of me having to fish out keys all the time, it would be good to just put my Staging and Production keys in config.xml for each platform once and be done with it, using a STAGING=1 flag or something similar.

**Comment by max-mironov** [comment]
Hey @jpike88 that could be useful however I can argue here that Staging/Production are not the only possible values. In fact it is just a convention most people are using but there is nothing that could stop you by changing that names to something like `MyCustomDeployment` `Test1` and so on or having three, four and more deployments, this way resolving this situation would be not so smooth. 
From the other hand current approach should work in all cases. 

Would be happy to hear other thoughts about this.

**Comment by jpike88** [comment]
That would be better... would be also ideal to bake some TestFlight detection as the most common scenario would be having a staging key for the beta, and a production key for the final product

**Comment by ruslan-bikkinin** [comment]
@jpike88 you can customize this behavior by passing `deploymentKey` option directly to `sync` command ignoring `CodePushDeploymentKey` preference at all. Please refer to relevant documentation [section](https://github.com/Microsoft/cordova-plugin-code-push#syncoptions) for more details.

**Comment by sergey-akhalkov** [comment]
Hi @jpike88, just a friendly ping.

**Comment by jpike88** [comment]
I think passing the deployment key isn't so bad, but it means that some will be lazy and hardcode that key in JS instead of fetching it via a plugin call

**Comment by sergey-akhalkov** [comment]
@jpike88, please also take a look at [dynamic-deployment-assignment](https://github.com/Microsoft/react-native-code-push#dynamic-deployment-assignment) chapter that also can be upload to the Cordova Plugin. 

>Not sure how important that is from a security perspective

Deployment key is used to check for updates only, it doesn't allow to release new updates, remove existing updates and etc. So please feel free to use it.

In terms of multiple deployment keys in the config.xml or info.plist - we'll watch for this feature in the future and will add it to our backlog in case of a lot of similar requests.

I'm closing this for now, please feel free to reopen if you have any questions or see any issues.
