### ISSUE TITLE
Query about disaster recovery

### ISSUE THREAD

**Issue by jpike88** [Microsoft/cordova-plugin-code-push#343]
Let's say I push a totally messed up deployment where cordova.js etc are broken.

Does that break the user's app permanently? Is sync called without having to call it from JS?

**Comment by jpike88** [comment]
Anyone?

**Comment by sergey-akhalkov** [comment]
Hi @jpike88, thanks for your question.

From the official docs:
>notifyApplicationReady: Notifies the CodePush runtime that an installed update is considered successful. If you are manually checking for and installing updates (i.e. not using the sync method to handle it all for you), then this method MUST be called; otherwise CodePush will treat the update as failed and rollback to the previous version when the app next restarts.

Please also take a look at https://github.com/Microsoft/cordova-plugin-code-push#codepushnotifyapplicationready

Another word CodePush has rollbacks mechanism that allows to revert broken updates.

**Comment by jpike88** [comment]
thanks heaps, good news
