### ISSUE TITLE
White screen appears and app breaks after second update from code-push [Ionic APP]

### ISSUE THREAD

**Issue by DLopezOpentix** [Microsoft/cordova-plugin-code-push#344]
Hello,

### Description

I'm trying to use the plugin on an Ionic APP, following the steps indicated here (https://ionicframework.com/docs/native/code-push/).

Everything seems to work well, I have installed the plugin and it seems to be working. Then, I have released an update using the code-push CLI, and when I open the app again, I receive the update in the alert.

The first update seems to work well, the app restarts and code changes seem to have applied successfully.

However, when I update again, and send a new release, I receive the update in the app, but when the plugin tries to restart the app, a **white screen** appears and the **app breaks**. When I restart the app manually, **code changes are not applied**, and the update does not trigger again. If I check the updates in the devices with the code-push cli, it says **Rollbacks: 1**.

### Reproduction

`ionic start codepushtest blank`

`cd codepushtest`

`ionic cordova plugin add cordova-plugin-code-push`

`sudo npm install --save @ionic-native/code-push`

`ionic cordova platform add ios`

**This is how I release the update**:
`code-push release-cordova --description "Release 1" codepush-test ios`

In **src/app/app.module.ts**, in order to set up the CodePush service as a provider:

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';

import { CodePush } from '@ionic-native/code-push';

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    CodePush,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

```
In **src/app.component.ts**:

```typescript
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { HomePage } from '../pages/home/home';

import { CodePush, InstallMode, SyncStatus } from '@ionic-native/code-push';
import { AlertController } from 'ionic-angular/components/alert/alert-controller';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen,
              private codePush: CodePush,  private alertCtrl: AlertController) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();
      this.checkCodePush();
    });
  }

  checkCodePush() {
    let alert1 = this.alertCtrl.create({
      title: 'CODE PUSH',
      subTitle: 'Hello!',
      buttons: ['Dismiss']
    });
    alert1.present();
     this.codePush.sync({
      updateDialog: {
       appendReleaseDescription: true,
       descriptionPrefix: "\n\nChange log:\n"   
      },
      installMode: InstallMode.IMMEDIATE
   }).subscribe(
     (data) => { },
     (err) => { }
   );
  }

}

```
In the **config.xml**, set up the deployment key preference for **ios platform**:

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.ionic.starter" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MyApp</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        <allow-intent href="market:*" />
         <!-- I'M JUST HIDDEN A LOT OF IRRELEVANT INFO HERE -->
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <!-- I'M JUST HIDDEN A LOT OF IRRELEVANT INFO HERE -->
        <preference name="CodePushDeploymentKey" value="<staging_deployment_key_willfully_hidden" />
    </platform>
    <engine name="ios" spec="^4.4.0" />
    <plugin name="cordova-plugin-code-push" spec="^1.11.0" />
    <plugin name="cordova-plugin-device" spec="1.1.4" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.16" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.1" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
</widget>
```
`ionic cordova build ios`

**Run APP in device from XCode**

### Additional Information

* cordova-plugin-code-push version: **1.11.0**
* List of installed plugins:
```
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-code-push 1.11.0 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
* Cordova version: **7.0.0**
* iOS/Android/Windows version: **iOS 11.2.1**
* Does this reproduce on a debug build or release build?  **debug**
* Does this reproduce on a simulator, or only on a physical device? **physical device & simulator**

- I'm testing directly on my iPhone 7

**Comment by ruslan-bikkinin** [comment]
Hi @DLopezOpentix I tried to reproduce your issue on iPhone 7 simulator but my demo app works just fine. Could you please clarify:
1. What code parts did you change between updates? It will be perfect if you will share diffs between updates.
2. Please share with us your app logs.
3. Are you sure this behavior could be reproduced on simulator too?

**Comment by DLopezOpentix** [comment]
Hello @ruslan-bikkinin,

Thank you for the response!

Actually, it seems I was doing something wrong.

Right now I've been able to set up the plugin with my Ionic app and seems to be working allright! It's working fine in the simulator and in real device.

However, I think that the `code-push release-cordova` command is not the most recommendable with an Ionic app. I guess all my issues came because I was trying to use that command in order to release my updates (or maybe I was not using it correctly, but didn't find my way).

Right now I feel more comfortable using the `code-push release` command instead of the `code-push release-cordova` one.

I guess it's because ionic needs to build the app before performing the `cordova prepare`.

This is how I do it currently:

`ionic cordova prepare ios`

`code-push release codepush-ionic-test-ios ./platforms/ios/www/ 0.0.1 --description "Your awesome change description"`

For those who get stuck also with this, I have uploaded an example of an **ionic app** using this plugin at this repo: https://github.com/DLopezOpentix/example-cordova-code-push-plugin

Thank you very much!

Regards,

David.

**Comment by ruslan-bikkinin** [comment]
Thanks @DLopezOpentix for the answer, glad to hear your problem is resolved. Yes, currently `code-push cordova-release` works with every app just like it cordova app, e.g. looking for assets in `platforms/<platform>/www`. In case of ionic app you need manually build your assets from .ts/.scss to .js/.css using `ionic build` then run `code-push cordova-release` or `code-push release`. I believe, we should add note about this in docs. 

 I am closing this issue, feel free to re-open if needed.
