### ISSUE TITLE
Error de compilacion firebase2 

### ISSUE THREAD

**Issue by SHEMOLOPZ** [Microsoft/cordova-plugin-code-push#347]
Agradezco la ayuda, tengo una aplicación que estoy actualizando de ionic 2 a Ionic 3, se presentan errores con firebase, adjunto informacion

D:>ionic info
cli packages: (C:\Users\USER\AppData\Roaming\npm\node_modules)
@ionic/cli-utils  : 1.19.0
ionic (Ionic CLI) : 3.19.0
global packages:

cordova (Cordova CLI) : not installed
local packages:

@ionic/app-scripts : 3.1.6
Cordova Platforms  : android 7.0.0
Ionic Framework    : ionic-angular 3.9.2
System:

Node : v8.9.3
npm  : 5.6.0
OS   : Windows 10
Environment Variables:

ANDROID_HOME : not set
Misc:

backend : pro

informacion de package.json
{
“name”: “spxgo”,
“version”: “0.0.1”,
“author”: “Ionic Framework”,
“homepage”: “http://ionicframework.com/”,
“private”: true,
“scripts”: {
“clean”: “ionic-app-scripts clean”,
“build”: “ionic-app-scripts build”,
“lint”: “ionic-app-scripts lint”,
“ionic:build”: “ionic-app-scripts build”,
“ionic:serve”: “ionic-app-scripts serve”
},
“dependencies”: {
“angular2-signaturepad”: “^2.6.1”,
“angularfire2”: “^5.0.0-rc.4”,
“angularfire2-offline”: “^4.3.1”,
“cordova-android”: “7.0.0”,
“cordova-plugin-add-swift-support”: “^1.6.0”,
“cordova-plugin-advanced-http”: “^1.9.0”,
“cordova-plugin-android-permissions”: “^1.0.0”,
“cordova-plugin-battery-status”: “^2.0.1”,
“cordova-plugin-camera”: “^4.0.1”,
“cordova-plugin-compat”: “^1.2.0”,
“cordova-plugin-console”: “^1.1.0”,
“cordova-plugin-device”: “^1.1.4”,
“cordova-plugin-file”: “^6.0.1”,
“cordova-plugin-file-opener2”: “^2.0.19”,
“cordova-plugin-file-transfer”: “^1.7.0”,
“cordova-plugin-geofence”: “^0.7.0”,
“cordova-plugin-geolocation”: “^4.0.1”,
“cordova-plugin-ionic-webview”: “^1.1.16”,
“cordova-plugin-mauron85-background-geolocation”: “^2.3.3”,
“cordova-plugin-network-information”: “^2.0.1”,
“cordova-plugin-splashscreen”: “^4.0.3”,
“cordova-plugin-statusbar”: “^2.4.1”,
“cordova-plugin-whitelist”: “^1.3.1”,
“cordova-sms-plugin”: “^0.1.11”,
“cordova-sqlite-storage”: “^2.2.0”,
“es6-promise-plugin”: “^4.2.2”,
“firebase”: “^4.8.1”,
“ionic-angular”: “3.9.2”,
“ionic-plugin-keyboard”: “^2.2.1”,
“ionicons”: “3.0.0”,
“onesignal-cordova-plugin”: “^2.2.5”,
“phonegap-plugin-barcodescanner”: “^7.0.0”,
“promise-polyfill”: “^7.0.0”,
“rxjs”: “5.5.2”,
“sw-toolbox”: “3.6.0”,
“zone.js”: “0.8.18”
},
“devDependencies”: {
“@ionic/app-scripts“: “3.1.6”,
“typescript”: “2.4.2”
},
“description”: “An Ionic project”,
“cordova”: {
“plugins”: {
“ionic-plugin-keyboard”: {},
“cordova-plugin-whitelist”: {},
“cordova-plugin-device”: {},
“cordova-plugin-splashscreen”: {},
“cordova-plugin-ionic-webview”: {},
“cordova-plugin-battery-status”: {},
“phonegap-plugin-barcodescanner”: {},
“cordova-plugin-camera”: {},
“cordova-plugin-android-permissions”: {},
“cordova-plugin-file”: {},
“cordova-plugin-file-opener2”: {},
“cordova-plugin-advanced-http”: {},
“cordova-plugin-network-information”: {},
“onesignal-cordova-plugin”: {},
“cordova-sms-plugin”: {},
“cordova-sqlite-storage”: {},
“cordova-plugin-console”: {},
“cordova-plugin-statusbar”: {},
“cordova-plugin-geolocation”: {
“GEOLOCATION_USAGE_DESCRIPTION”: “To locate you”
},
“cordova-plugin-geofence”: {},
“cordova-plugin-mauron85-background-geolocation”: {
“GOOGLE_PLAY_SERVICES_VERSION”: “+”,
“ICON”: “@mipmap/icon”,
“SMALL_ICON”: “@mipmap/icon”,
“ACCOUNT_NAME”: “@string/app_name”,
“ACCOUNT_LABEL”: “@string/app_name”,
“ACCOUNT_TYPE”: “$PACKAGE_NAME.account”,
“CONTENT_AUTHORITY”: “$PACKAGE_NAME”
}
},
“platforms”: [
“android”
]
}
}
Error que se reproduce

[17:27:08] ngc started …
[17:27:25] typescript: D://node_modules/angularfire2/firebase.app.module.d.ts, line: 5
Cannot find namespace ‘firebase’.

   L4:  export declare const FirebaseAppConfigToken: InjectionToken<FirebaseAppConfig>;
   L5:  export declare class FirebaseApp implements firebase.app.App {
   L6:      name: string;

Agradezco la ayuda y quedo atento.

**Comment by ruslan-bikkinin** [comment]
Hi @SHEMOLOPZ and thanks for submitting the issue. Could you please rephrase your question in english, so we could help you much quicker?

**Comment by max-mironov** [comment]
Closing the issue, please create new one with our [issue_template](https://github.com/Microsoft/cordova-plugin-code-push/issues/new) and in english, thanks!
