### ISSUE TITLE
Android app does not run after codepush update successfully

### ISSUE THREAD

**Issue by toantd90** [Microsoft/cordova-plugin-code-push#348]
### Description

I have used cordova-plugin-codepush for my cordova application. But it only works for iOS.  It shows grey screen after codepus update successfully.

### Reproduction

I tried to run application to a real device from Android Studio. Here is what I got from Logcat. It means 

```
01-11 10:37:16.480 18951-19148/works.kinkan.kinkan W/PluginManager: THREAD WARNING: exec() call to CodePush.notifyApplicationReady blocked the main thread for 18ms. Plugin should use CordovaInterface.getThreadPool().
01-11 10:37:17.154 18951-18951/works.kinkan.kinkan D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js: Line 36 : [CodePush] Checking for update.
01-11 10:37:17.154 18951-18951/works.kinkan.kinkan I/chromium: [INFO:CONSOLE(36)] "[CodePush] Checking for update.", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (36)
01-11 10:37:18.637 18951-18951/works.kinkan.kinkan D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js: Line 36 : [CodePush] An update is available. {"appVersion":"0.5.0","deploymentKey":"nc4v3lvsiMWfvJvoaUr9pKdYMn35EJi6kSVSM","description":"","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/b0Ukc6nUwrW7iXmTR8zuHynqFpKda591e682-d4ef-4b4d-b5c4-9daf95fe88ad","isMandatory":false,"label":"v59","packageHash":"9964f858a720573d01b12ea80fb883ecf32d204c9a7f5b7583d54f8022c70f71","packageSize":2523709,"failedInstall":false}
01-11 10:37:18.637 18951-18951/works.kinkan.kinkan I/chromium: [INFO:CONSOLE(36)] "[CodePush] An update is available. {"appVersion":"0.5.0","deploymentKey":"nc4v3lvsiMWfvJvoaUr9pKdYMn35EJi6kSVSM","description":"","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/b0Ukc6nUwrW7iXmTR8zuHynqFpKda591e682-d4ef-4b4d-b5c4-9daf95fe88ad","isMandatory":false,"label":"v59","packageHash":"9964f858a720573d01b12ea80fb883ecf32d204c9a7f5b7583d54f8022c70f71","packageSize":2523709,"failedInstall":false}", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (36)
01-11 10:37:18.640 18951-18951/works.kinkan.kinkan D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js: Line 36 : [CodePush] Downloading update
01-11 10:37:18.640 18951-18951/works.kinkan.kinkan I/chromium: [INFO:CONSOLE(36)] "[CodePush] Downloading update", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (36)
01-11 10:37:36.051 18951-18951/works.kinkan.kinkan D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js: Line 36 : [CodePush] Package download success: {"deploymentKey":"nc4v3lvsiMWfvJvoaUr9pKdYMn35EJi6kSVSM","description":"","label":"v59","appVersion":"0.5.0","isMandatory":false,"packageHash":"9964f858a720573d01b12ea80fb883ecf32d204c9a7f5b7583d54f8022c70f71","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
01-11 10:37:36.051 18951-18951/works.kinkan.kinkan I/chromium: [INFO:CONSOLE(36)] "[CodePush] Package download success: {"deploymentKey":"nc4v3lvsiMWfvJvoaUr9pKdYMn35EJi6kSVSM","description":"","label":"v59","appVersion":"0.5.0","isMandatory":false,"packageHash":"9964f858a720573d01b12ea80fb883ecf32d204c9a7f5b7583d54f8022c70f71","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (36)
01-11 10:37:36.052 18951-18951/works.kinkan.kinkan D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js: Line 36 : [CodePush] Installing update
01-11 10:37:36.052 18951-18951/works.kinkan.kinkan I/chromium: [INFO:CONSOLE(36)] "[CodePush] Installing update", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (36)
01-11 10:37:37.408 18951-18951/works.kinkan.kinkan D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js: Line 36 : [CodePush] Install succeeded.
01-11 10:37:37.408 18951-18951/works.kinkan.kinkan I/chromium: [INFO:CONSOLE(36)] "[CodePush] Install succeeded.", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (36)
```

### Additional Information

* cordova-plugin-code-push version:  1.9.2-beta / 1.9.7-beta / 1.11.0
* List of installed plugins:
code-push 2.0.5 "CodePushAcquisition"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-code-push 1.9.7-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4 "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
* Cordova version: 6.5.0
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by max-mironov** [comment]
Hello @toantd90, thanks for reaching us, several questions:
1) Is it the 1st time you run into the issue or it doesn't work previously at all for android (seeing that update label is v59 I guess it is not the 1st time you try codepush update?)
2) Do you use separate apps for iOS and android with different deployment keys?
3) Please share with us the commands you use to make code push release and also would be great if you could share with us the output for the deployment history
4) Could you try to repro this issue on our [sample app](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic)?

Looking forward for your replies.

**Comment by toantd90** [comment]
Hi @max-mironov, thanks for replying me, 

1. Yes, it is not the first time I try codepush update. I was such a long time I did not check code push update on Android. I only checked on iOS. Since I updated *cordova-plugin-code-push* from 1.9.2-beta to *1.9.7-beta* to support VKWebview on xCode 9 then I have time to check on Android devices  ( both simular and real devices ).
2. No, I dont have seperate apps. I used a same source code and build with cordova.
3. Here is code push release command:

TARGET_PLATFROM could be `android` or `ios`
DEPLOYMENT_NAME is code push channel ( `Production`, `Staging`, `Integration` or `Development` )

```
code-push release-cordova "${APP_NAME}" "${TARGET_PLATFORM}" -d "${DEPLOYMENT_NAME}"
```
Sorry Max, but I do not really what do you want for deveplopment history.
4. Yes, Let me try your simple app. I will get back to you soon.

Thank you for your supporting again.

**Comment by max-mironov** [comment]
@toantd90 thanks for looking at, yeah just be sure that you use different deployment keys for iOS/Android to avoid unexpected issues. 
If you could try it on sample app that would be great, keep us updated with the results.

**Comment by max-mironov** [comment]
I'm going to close the issue as of now, please let us know when you get a chance to look at this and if you have any updates (e.g. with sample app) so we could reopen it (or create a new issue if needed).
