### ISSUE TITLE
Plugin prevents ionic livereload from working.

### ISSUE THREAD

**Issue by jdeanwaite** [Microsoft/cordova-plugin-code-push#349]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

Using the plugin breaks the usage of ionic's built-in `livereload` capabilities when running a project on a device.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'http://10.0.1.8:8101 is not a file URL'
```

### Reproduction

1. `ionic start breakme blank` to create a sample project.
2. `ionic cordova platform add ios` to add iOS
3. `ionic cordova plugin add cordova-plugin-code-push@latest`
3. Take necessary steps to sign your app in order to run it on a device.
4. `ionic cordova run ios --device --livereload` to **attempt** to run the app on a plugged in device with `livereload` enabled from ionic. At this point the app will start up and crash immediately. 
5. Open the project in XCode and try running from there to get the aforementioned error message. 
Remove the CodePush plugin and everything works as normal. 

### Additional Information

* cordova-plugin-code-push version: **1.11.1**
* List of installed plugins:
```
> cordova plugin ls
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-code-push 1.11.1 "CodePush"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
* Cordova version: **8.0.0**
* iOS/Android/Windows version: **iOS 11.2** `<engine name="ios" spec="~4.5.4" />`
* Does this reproduce on a debug build or release build? **Debug**
* Does this reproduce on a simulator, or only on a physical device? **Device**

(The more info the faster we will be able to address it!)

**Comment by sergey-akhalkov** [comment]
Hi @jdeanwaite, thanks for reaching us.

By using `livereload ` you've got exactly the same issue as the other devs have while using `react-native-code-push` module, please take a look at this https://github.com/Microsoft/react-native-code-push/issues/682

Another words, in case you have `live update / reload` you should test CodePush update in modes other than debug, because CodePush thinks that an update has been installed, but actually we are using live update server and as result we have runtime exceptions.

Please let me know if you have any questions or considerations about this issue that would help us to improve code quality and stability.

**Comment by jdeanwaite** [comment]
Hey @sergey-akhalkov 

I remain a little confused here. My goal in running my application with `--livereload` enabled is not to test CodePush, but rather develop my application without having to restart the app on every little change. It just so happens that I have the CodePush plugin installed for production purposes.

Are you saying that when I have the CodePush plugin installed, I will not be able to run my apps in development mode? Do you want me to run with the `--release` flag? **Is there a way to disable CodePush when I am developing without uninstalling the whole thing?** At least that way CodePush cannot crash my app.

**Comment by moshik008** [comment]
i am also facing the exact same issue, any solution for that?

**Comment by jdeanwaite** [comment]
@moshik008 
The best solution I can come up with is to write a deployment script that will reinstall CodePush when you are ready to deploy, and to simply remove the plugin during development.

**Comment by thetylerholden** [comment]
same issue

**Comment by alexandergoncharov** [comment]
Hi all,

I opened PR for fixing this issue: https://github.com/Microsoft/cordova-plugin-code-push/pull/396
Could you please test it?


Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi all,

As fix already released I'll close this bug.
Please feel free to reopen bug if you have questions or issues.

Thanks,
Alexander
