### ISSUE TITLE
Failed to hash Thumbs.db and .git files

### ISSUE THREAD

**Issue by zafiredevelopment** [Microsoft/cordova-plugin-code-push#350]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I am using the cordova codePush to sync an app and I get this error 

cordova.callbackFromNative('CodePush35326482',false,9,["An error occurred when trying to get the hash of the binary contents. www\/images\/icons\/Thumbs.db"],false);

cordova.callbackFromNative('CodePush35326482',false,9,["An error occurred when trying to get the hash of the binary contents. www\/.git"],false);

I know i shouldn't have a Thumbs.db or a .git in the project, but this might be happening with other file types too.

### Reproduction

Create a .git folder or copy a windows Thumbs.db to the www/ folder and try to sync a new package

### Additional Information

* cordova-plugin-code-push version: cordova-plugin-appcenter-push 0.1.3
* List of installed plugins: 
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-appcenter-push 0.1.3 "App Center Push for Cordova"
cordova-plugin-appcenter-shared 0.1.2 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.1 "Camera"
cordova-plugin-code-push 1.11.1 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.1.1 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 7.0.1 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"

* Cordova version: 7.1.0
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? Release and debug
* Does this reproduce on a simulator, or only on a physical device? Both
[Thumbs.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/1635560/Thumbs.zip)

(The more info the faster we will be able to address it!)

**Comment by ruslan-bikkinin** [comment]
Hi @zafiredevelopment and thanks for reaching us. I tried to reproduce your issue using the following steps:

1. Create cordova application using our [sample app](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/advanced).
2. Add all plugins you specified to application.
3. Run application.
4. Release update with new `Thumbs.db` file.
5. Install full update on app (*installation was successful*).
6. Release few more updates including adding `.git` directory with `some.file` and `Thumb.db` file within it.
7. Install diff update on app (*installation was successful*).

Everything was worked without a problem for me. In this case, please, to clarify a few more things:

* on what machine did you release updates: windows, mac, linux?
* is it `phonegap` application? If it is, what version of phonegap it uses?

**Comment by zafiredevelopment** [comment]
Hello @ruslan-bikkinin,

The machine where we generate the releases is a mac, the application is a Cordova version 7.1.0 (not phonegap)

I had this error again today, here is the stacktrace

`
[CodePush]  Unable to compute hash for package: An error occurred when trying to get the hash of the binary contents. invalid directory path /data/user/0/com.zafire.mobiletest/files/codepush/deploy/versions/2f8a31a993d34bdd9b5087db120f1540498741b258add62f40faff0cd2890f58/www/.git/hooks. StackTrace: Error: Unable to compute hash for package: An error occurred when trying to get the hash of the binary contents. invalid directory path /data/user/0/com.zafire.mobiletest/files/codepush/deploy/versions/2f8a31a993d34bdd9b5087db120f1540498741b258add62f40faff0cd2890f58/www/.git/hooks
    at packageHashFail (file:///data/user/0/com.zafire.mobiletest/files/codepush/deploy/versions/12cf18d6cc88d9e8730566325fa88f62fab235160e70988a5497a9d121d2ca40/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:187:27)
    at Object.callbackFromNative (file:///data/user/0/com.zafire.mobiletest/files/codepush/deploy/versions/12cf18d6cc88d9e8730566325fa88f62fab235160e70988a5497a9d121d2ca40/www/cordova.js:296:52)
    at <anonymous>:1:9
`
Our www doesn't have the .git folder, but still that is on the mobile, after I uninstalled and installed the application, the error is gone

We will report back if we get a standar way to replicate

**Comment by ruslan-bikkinin** [comment]
@zafiredevelopment got it, I believe we have similar issue here #327, but unfortunately, we can't reproduce it by ourselves. Just in case, could you please clarify, which version of `cordova-android` you are using and which version of android is installed on your simulator?

**Comment by ruslan-bikkinin** [comment]
@zafiredevelopment just a friendly ping on this.

**Comment by max-mironov** [comment]
Closing this as of no response, please feel free to reopen/create new one if the issue still persist.

**Comment by slorber** [comment]
I'm having a similar issue on Android with latest release 1.11.3

> Error: Could not get binary hash.

This makes the hot update unusable as on restart the app does not find the new JS and rollbacks to former release.

Cordova 6.5.0, Android 6.4.0

**Comment by slorber** [comment]
don't know if this happens to others but it looks like the bundle very often refuses to download due to network errors when using the browser in the app center.

![image](https://user-images.githubusercontent.com/749374/35638162-b152df16-06b6-11e8-991d-9cce978186a7.png)

The download is often interrupted after like 5mb.
It seems to work better for older releases.

**Comment by zafiredevelopment** [comment]
Hello, the cordova-android version is `android 6.3.0` and the device is a `huawei honor 7` with Android 6.0
