### ISSUE TITLE
beforeInstall hook is not launched 

### ISSUE THREAD

**Issue by sambegin** [Microsoft/cordova-plugin-code-push#351]
### Description

Installing cordova plugin code push from zero (no platforms, no plugins folder) does not run the beforeInstall hook. 

What I did : run ``` cordova prepare ios ```

What I expected to happen : Having cordova code push plugin with all its dependencies installed correctly

What actually happened: cordova plugin file and cordova plugin file transfer were missing. When I tried to do a sync() on the client, I get an undefined FileTransfer error. I also get this warning when installing the plugins : ``` Script file does't exist and will be skipped: .../plugins/cordova-plugin-code-push/scripts/beforeInstall.js``` 

My 2 cents : 
I think that the link to the script file is just wrong in the plugin.xml. When the cordova-plugin-code-push is installing, the warning seems to be a correct one since the beforeInstall.js script is in fact in the /hooks folder inside the /cordova-plugin-code-push folder and not in the /scripts folder like it is requested by the plugin.xml

### Reproduction

From a scratch cordova project
- run ``` cordova plugin add cordova-plugin-code-push@latest ````
- run ``` cordova prepare ios ``` (or android)

See the warning and the missing file plugins 

### Additional Information
* cordova-plugin-code-push version: 1.11.1
* List of installed plugins: Can be none
* Cordova version: 7.1.0
* iOS/Android/Windows version: 4.5.4 (ios)

**Comment by sambegin** [comment]
For your information, I just tested it by forking this project and renaming the hooks folder for scripts 
(or maybe just change the src tag in the plugin.xml file for ``` src="hooks/beforeInstall.js" ``` should do the same) and we see that now the beforeInstall script is run : 
<img width="629" alt="screen shot 2018-01-16 at 7 42 38 pm" src="https://user-images.githubusercontent.com/6645382/35019561-7a85a47c-faf5-11e7-83b9-15b43086788f.png">

**Comment by max-mironov** [comment]
@sambegin Thank you so much for pointing at this and sorry for inconvenience! Will check it out today and release patch if needed. Again - thanks a lot for letting us know.

**Comment by max-mironov** [comment]
@sambegin we have released patch for cordova-plugin-code-push https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.11.2

I believe the issue could be closed for now - feel free to reach us if any questions or you see any issues.
