### ISSUE TITLE
Unable to complete update process

### ISSUE THREAD

**Issue by zersys** [Microsoft/cordova-plugin-code-push#352]
Description
We are using codepush via appcenter cli to release updates to our app, We have maintained two separate apps for android and iOS as suggested. 

As of today, we are facing the following issue

Android : the screen gets stuck at "checking for Update"  and does not move forward.
iOS : package is downloaded but gets stuck at "Installing Update".

The releases are going through the appcenter cli without any issues. 

### Additional Information

* cordova-plugin-code-push version: 1.11.2

* List of installed plugins:
cordova-plugin-whitelist" spec="^1.3.3" 
cordova-plugin-camera" spec="^3.0.0" 
cordova-plugin-media-capture" spec="^2.0.0" 
cordova-plugin-console" spec="^1.1.0" 
cordova-plugin-contacts" spec="^3.0.0" 
cordova-plugin-device" spec="^1.1.7" 
cordova-plugin-device-orientation" spec="^1.0.7" 
cordova-plugin-dialogs" spec="^1.3.4" 
cordova-plugin-geolocation" spec="^3.0.0" 
cordova-plugin-globalization" spec="^1.0.8" 
cordova-plugin-inappbrowser" spec="^1.7.2" 
cordova-plugin-media" spec="^4.0.0" 
cordova-plugin-network-information" spec="^1.3.4" 
cordova-plugin-splashscreen" spec="^4.1.0" 
cordova-plugin-statusbar" spec="^2.3.0" 
cordova-plugin-vibration" spec="^2.1.6" 
cordova-plugin-device-motion" spec="^1.2.5" 
cordova-plugin-code-push" spec="^1.10.0-beta" 
phonegap-plugin-push" spec="^1.7.0"

* Cordova version: 8.0.0
* iOS/Android/Windows version: 4.3.1,6.1.2,4.4.3
* Does this reproduce on a debug build or release build? - Debug build
* Does this reproduce on a simulator, or only on a physical device? - Physical Device, haven't tried on a simulator.

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hello @zersys - that really looks weird! 

So it was working previously but suddenly you have started to see such kind of issues?
If so could you please confirm that the issue is still reproducible for you (another words it was not a service blip/something wrong with device). 
Any other specific information about this(e.g. integration logic, do you see this issue on demo app etc) would also be much appreciated.

**Comment by zersys** [comment]
Hello @max-mironov, thank you for the response. It does look weird, more so since I was happily pushing updates for more than a month. 

I have disabled code push for the time being as we are about to take our app to production and we were making a few last minute changes, hence I couldn't spend more time digging into the issue. I was wondering if there was a version conflict of some sort. 

I will revert back with more info when I pull back into test mode. Will close this issue until then.

**Comment by max-mironov** [comment]
Thanks @zersys, keep us posted is possible!
