### ISSUE TITLE
Android app cannot read property 'stack' of undefined"

### ISSUE THREAD

**Issue by toantd90** [Microsoft/cordova-plugin-code-push#355]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I have used cordova-plugin-codepush for my cordova application. But it only works for iOS. It can not get the latest version via codepush

### Reproduction

I tried to run application to a real device from Android Studio. Here is what I got from Logcat.

```
01-23 05:25:22.976 14830-14830/? D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js: Line 36 : [CodePush] Sync already in progress.
01-23 05:25:22.976 14830-14830/? I/chromium: [INFO:CONSOLE(36)] "[CodePush] Sync already in progress.", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (36)
01-23 05:25:41.632 15106-15106/? D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 309 : Error in Error callbackId: CodePush626295676 : TypeError: Cannot read property 'stack' of undefined
01-23 05:25:41.632 15106-15106/? I/chromium: [INFO:CONSOLE(309)] "Error in Error callbackId: CodePush626295676 : TypeError: Cannot read property 'stack' of undefined", source: file:///android_asset/www/cordova.js (309)
01-23 05:26:25.821 15309-15309/? D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 309 : Error in Error callbackId: CodePush524401210 : TypeError: Cannot read property 'stack' of undefined
01-23 05:26:25.821 15309-15309/? I/chromium: [INFO:CONSOLE(309)] "Error in Error callbackId: CodePush524401210 : TypeError: Cannot read property 'stack' of undefined", source: file:///android_asset/www/cordova.js (309)
01-23 06:15:26.824 17213-17213/? D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 309 : Error in Error callbackId: CodePush1282999560 : TypeError: Cannot read property 'stack' of undefined
01-23 06:15:26.824 17213-17213/? I/chromium: [INFO:CONSOLE(309)] "Error in Error callbackId: CodePush1282999560 : TypeError: Cannot read property 'stack' of undefined", source: file:///android_asset/www/cordova.js (309)
01-23 06:19:58.265 20302-20302/? D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 309 : Error in Error callbackId: CodePush1167929484 : TypeError: Cannot read property 'stack' of undefined
01-23 06:19:58.265 20302-20302/? I/chromium: [INFO:CONSOLE(309)] "Error in Error callbackId: CodePush1167929484 : TypeError: Cannot read property 'stack' of undefined", source: file:///android_asset/www/cordova.js (309)
01-23 06:21:46.654 20613-20613/ D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 309 : Error in Error callbackId: CodePush1419442286 : TypeError: Cannot read property 'stack' of undefined
01-23 06:21:46.654 20613-20613/ I/chromium: [INFO:CONSOLE(309)] "Error in Error callbackId: CodePush1419442286 : TypeError: Cannot read property 'stack' of undefined", source: file:///android_asset/www/cordova.js (309)
01-23 06:52:58.127 21811-21811/ D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 309 : Error in Error callbackId: CodePush1418509048 : TypeError: Cannot read property 'stack' of undefined
01-23 06:52:58.128 21811-21811/ I/chromium: [INFO:CONSOLE(309)] "Error in Error callbackId: CodePush1418509048 : TypeError: Cannot read property 'stack' of undefined", source: file:///android_asset/www/cordova.js (309)
```

### Additional Information

* cordova-plugin-code-push version: 1.11.2
* List of installed plugins:
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-code-push 1.11.2 "CodePush"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1-dev "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 2.0.1 "InAppBrowser"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4 "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
* Cordova version: 8.0.0
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by max-mironov** [comment]
Hi there @toantd90, your problem should be fixed in this PR: https://github.com/Microsoft/cordova-plugin-code-push/pull/353

Could you please update from master and let us know if it helps?

**Comment by max-mironov** [comment]
Hey @toantd90, just in case - we have released new version of the plugin which include this fix - https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.11.3. 

I think we can close the issue at that moment, please let us know if you see any problems though.
