### ISSUE TITLE
Failed to install 'cordova-plugin-code-push':TypeError: plugins.includes is not a function

### ISSUE THREAD

**Issue by byjoshi008** [Microsoft/cordova-plugin-code-push#358]
### Description
I am using visual studio to create an android app using cordova. I have added cordova-plugin-code-push to the project and is added fine. But when I try to build the project it fails with an error - Failed to install 'cordova-plugin-code-push':TypeError: plugins.includes is not a function.

This happens every time I try to build the solution in visual studio (both debug and release modes).
Here is the error log:

`MSBUILD : cordova-build warning : Warning: Failed to install 'cordova-plugin-code-push':TypeError: plugins.includes is not a function
Failed to install 'cordova-plugin-code-push':TypeError plugins.includes is not a function
    at module.exports (<My Project Path>\plugins\cordova-plugin-code-push\hooks\beforeInstall.js:26:18)`

When I removed the hook from plugin.xml and changed dependencies as below (same as version 1.11.0), it worked fine.

`<dependency id="code-push" version="2.0.4" />
 <dependency id="cordova-plugin-file-transfer" version="1.6.3" />
 <dependency id="cordova-plugin-zip" version=">=3.0.0" />
 <dependency id="cordova-plugin-dialogs" version=">=1.1.1" />
 <dependency id="cordova-plugin-device" version=">=1.1.0" />`

I am not sure whether I am missing anything to use version 1.11.3 or it is a real bug.

### Additional Information

* cordova-plugin-code-push version: 1.11.3
* Cordova version: 6.3.1

**Comment by annakocheshkova** [comment]
Hi @byjoshi008, `Array.prototype.includes` requires node 6 to be installed, please upgrade your node version.

**Comment by byjoshi008** [comment]
Hi @annakocheshkova. Thanks for your reply. 
My node version is 9.2.0. So doesn't look like the issue is related to node version.

**Comment by annakocheshkova** [comment]
Hi @byjoshi008, could you please modify the code of the hook to use `indexOf` instead on `includes` and see if it works.

F. e., replace `if(! plugins.includes('cordova-plugin-zip')` with `if(plugins.indexOf('cordova-plugin-zip') < 0)`.
Running this script instead of just specifying plugins in `plugin.xml` allows us to maintain backwards compatibility, so it's quite important for us to make it work for everybody.

Also, could you please paste the following lines of code after `var plugins = ...`:
```
for (var property in plugins) {
   console.log(property);
}
```
and share the output with us.
Thank you for your assistance!

**Comment by byjoshi008** [comment]
Hi @annakocheshkova,
I tried with your suggestion and it worked fine. 
Attaching logs and my code for reference.

**Log and code with !plugins.includes** (Error)
[plugins.includes log.txt](https://github.com/Microsoft/cordova-plugin-code-push/files/1671015/plugins.includes.log.txt)
[plugins.includes code.txt](https://github.com/Microsoft/cordova-plugin-code-push/files/1671020/plugins.includes.code.txt)

**Log and code with plugins.indexOf** (Working)
[plugins.indexOf log.txt](https://github.com/Microsoft/cordova-plugin-code-push/files/1671022/plugins.indexOf.log.txt)
[plugins.indexOf code.txt](https://github.com/Microsoft/cordova-plugin-code-push/files/1671023/plugins.indexOf.code.txt)

Conclusion:
I have changed all instance of `if(!plugins.includes("<plugin name>"))` to `if(plugins.indexOf("<plugin name>"))` in the hook _beforeIntall.js_

**Comment by annakocheshkova** [comment]
HI @byjoshi008 , thank you for the effort! Looks like `exexSync` returns an object of type [Buffer](https://nodejs.org/api/buffer.html), which is very strange then that it worked fine with `contains` function for others. 
Anyway, it seems that we need to rewrite the code of the hook to use `indexOf`, then.

**Comment by byjoshi008** [comment]
@annakocheshkova - thanks for your help. Closing this issue now.
