### ISSUE TITLE
Codepush: Get failed sync error details

### ISSUE THREAD

**Issue by saifeer** [Microsoft/cordova-plugin-code-push#359]
### Description

As of now, when the sync method is called and the SyncStatus get an ERROR value, there is no way to get the actual error. The documentation states the error details are in the console log but in live production, there should be a way to get the error details in the SyncCallback as an argument so they can be used for troubleshooting (like for eg. sending them out as error report to developers).

### Reproduction

Not relevant as this is an enhancement.

### Additional Information

* cordova-plugin-code-push version: All versions
* List of installed plugins: NA
* Cordova version: NA
* iOS/Android/Windows version: NA
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by slorber** [comment]
agreed, currently it's really hard to know when codepush deployments don't work. We get in sentry errors related to codepush that we can't really qualify
