### ISSUE TITLE
codePush.sync() fails to update release, rolls back to last install, and ignores all future releases

### ISSUE THREAD

**Issue by BbFGE** [Microsoft/cordova-plugin-code-push#362]
Problem:

Using the code-push plugin with Cordova apps fails on codePush.sync() intermittently  on Android. 

Step 1) What I have done is compile and  release an app  using (`appcenter codepush release-cordova -a mynam/appname -d Staging`)

Step 2) I then launch the app and then close.

Step 3) I then change the app slightly by simply modifying one line of javascript in the js
version='16.07'; 
(ie each release, I increment the variable version above (eg the next release would be '16.08'). Note this is *not* the actuall app version from config.xml- this never changes, the above is used simply as a number that the app displays on screen when launched so I can make sure it has updated the new release.

Step 4) I then launch the app, allowing codePush.sync() to download the new release.

Step 5) I close and re-open the app to see the new release in action

However, if I repeat this sequence (steps 3 to 5) after a number of iterations - and the number of iterations can be as little as 1 or up to 6 or 7) the download fails in codePush.sync() and the app reverts to the latest version actually installed on the device. Further releases will not fix this - nothing seems to get the app to update on the device other than manually reinstalling it.

I have spent some time trying to debug this, as it is a major issue for us as it will prevent us from using AppCenter and codePush if we can't make it work reliably) and have created text log files by overwriting the function of console.log so it writes to a text file, and puting new console.log commands in the fileUtil.js and 
localPackage.js (I amended them by editing local copies of the plugin's .ts files and using gulp to install into the app).

In the accompanying zip file, you can see these files, which are named 
CodepushTest_yyyy-mm-dd_hh-mm-ss.txt basied on the time the app launched.

I have added console.log commands throughout the code, trying to spot where the error occurs - I first increment a counter and then ouput the log with time and date. I also added an identifier for each one eg gD01 to this can help pinpoint in the javascript where this log comes from.

Example

[05/02/2018 14:55:27:307]
--> fileUtil gD01 (3), createIfNotExists=false, path=codepush, rootUri=file:///data/user/0/com.phonegap.codepushtest/files/
 
ie
[date logged]
--> jsfile identifer (counter) key parameters at this point in the code.

Where does the error happen?
The log file when it goes wrong shows something like this

[05/02/2018 14:55:29:389]
--> fileUtil gD03 (132),path=/codepush/deploy/versions/6faaecb038767b71f69c11b25f16113b7b7d42bb940af47b12fa1f1faacb70f0/, appDir={"isFile":false,"isDirectory":true,"name":"","fullPath":"/","filesystem":"<FileSystem: files>","nativeURL":"file:///data/user/0/com.phonegap.codepushtest/files/"}

[05/02/2018 14:55:29:394]
--> fileUtil gD09 (133)

[05/02/2018 14:55:29:430]
--> fileUtil gD10 (134) *ERROR* Error.code=1

This comes from the following code in fileUtil.js: 
```

var appDirErrorTemp1 = function (error) {
            
	FileUtil.fuLogCounter += 1;
            
	console.log('--> fileUtil gD10 (' + FileUtil.fuLogCounter + ') *ERROR* Error.code=' + error.code);
            
	callback(new Error("Could not get application subdirectory. Error code: " + error.code), null);
        
};
var rootDirSuccess = function (appDir) {
            
	FileUtil.fuLogCounter += 1;
            
	console.log('--> fileUtil gD11 (' + FileUtil.fuLogCounter + '),path =' + path + ', appDir=' + JSON.stringify(appDir));
            
	if (!createIfNotExists) {
                
		FileUtil.fuLogCounter += 1;
                
		console.log('--> fileUtil gD03 (' + FileUtil.fuLogCounter + '),path=' + path + ', appDir=' + JSON.stringify(appDir));

		appDir.getDirectory(path, { create: false, exclusive: false }, function (directoryEntry) {
                    callback(null, directoryEntry);
                }, appDirErrorTemp1);
           		FileUtil.fuLogCounter += 1;
                
		console.log('--> fileUtil gD09 (' + FileUtil.fuLogCounter + ')');
            
	}...
```
which is part of

`FileUtil.getDirectory = function (rootUri, path, createIfNotExists, callback) {`

From the log file, it looks like the error happens in this line
```
appDir.getDirectory(path, { create: false, exclusive: false }, function (directoryEntry) {
                    callback(null, directoryEntry);
                }, appDirErrorTemp1);
```
           

(One odd thing : the log files shows the following code 'gD03' 'gD09' and 'gD10' which I don't understand - I would expect 'gD10' to come between 'gD03' and 'gD09' as appDir.getDirectory which causes the callback appDireTemp1 to be called happens between those two - unless it is somehow calling the callback asynchronously. I even incremented to counter to prove the sequence of steps)

I can't spot why this is happening as I am only chnajging one character in the javascript for each release.

It looks like a problem in fileUtil somehow with the path of the download. Could it be a timing issue with the underlying file management system? At one point I thought it might be that the path sometimes ended in '/' and others not, but I don't think that's it now.

If you have any ideas, please let me know.

Exanple log files 

Successful release
CodepushTest_2018-02-05_14-54-59.txt

Failed release
CodepushTest_2018-02-05_14-55-27.txt

Note I have tried this on various different Android devices and different versions of Android (6,7.0, 7.0) for a week now, and all have the same problem.

I attcha a zip file with the output logs from the last sequence (from intial relase until it going wrong) and relevant files invcuding amended plugin javascript.
[Debugging.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/1695749/Debugging.zip)

**Comment by BbFGE** [comment]
Follow up : 
I have now tested it with two different Android devices simultaneously, one on Adnroid 6 and the other on Android 7.

I went through the cycle of releasing new updates and launching the apps.

One one device, the update failed on the second cycle, on the other , it went wrong after 6.

Looks like it is not an issue from the AppCenter end, but with the device and the plug in, Could it be a timing issue eg codeSync running too quickly for the fileUtil plugin?

**Comment by svekl** [comment]
Hi @BbFGE, thanks for reporting! I finally found the root of your issue, please, try to update plugin in your project. But this will require app update on users devices, because CodePush is not able to update plugin version.

**Comment by BbFGE** [comment]
Plan to test in the next few days - thanks for that. What was the problem?

**Comment by svekl** [comment]
There was an issue in update process that could corrupt current version package during update, so diff update couldn't be applied. That's why an app update via market is required to fix this issue.

**Comment by BbFGE** [comment]
In the java or in the javascript .TS files?

Thanks for your help... I hope to report success after testing!
