### ISSUE TITLE
Could not get binary hash on Android. Does CodePush work anyway?

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Microsoft/cordova-plugin-code-push#374]
I'm having this same problem that other people reported in other issues.

I'm going to add details that can help you evaluate and solve but, first of all, I'd like to ask you if CodePush works anyway. **Does it work? Even when it fails to get that binary hash?**

Here are the details

macOS High Sierra 10.13.3
cordova 8.0.0
cordova-android 6.4.0
cordova-plugin-code-push 1.11.5
cordova-plugin-file 6.0.1
cordova-plugin-file-transfer 1.7.1

`cdvasset.manifest`file is in the assets folder

Thanks,
Adriano

**Comment by decadX** [comment]
Seems to work, meaning  that it replaces the www contents no matter the error, but it fails to get bin hash or validate data integrity checks. There seems to be an issue with those 2 functions randomly, I can't find a way to replicate. Maybe it doesn't happen with using the codepush.sync? I am using a custom workflow for the deployment keys per git branch

**Comment by zafiredevelopment** [comment]
![image](https://user-images.githubusercontent.com/23500292/36374163-4e4eba92-1562-11e8-8d56-60850f5aac3e.png)
This is what we get too.
I debugged the issue and it seems to be caused by files that have the '.' in front of them

![image](https://user-images.githubusercontent.com/23500292/36383357-ce957ef4-1583-11e8-9875-41912bde4497.png)

**Comment by iTOYS** [comment]
Thanks for investigation!
Seems like that `android.content.res.AssetManager.open` can't open files starting with "."(dot)
We'll think about this.
While you can move files like `.eslintignore` outside `www` folder.

Thanks!

**Comment by zafiredevelopment** [comment]
Similar issue with the Thumbs.db from #350 
![image](https://user-images.githubusercontent.com/23500292/36480749-5dd06700-1705-11e8-9add-b3f3527c65a8.png)

We will remove those prior to the cordova prepare action but what if this is caused with other files too?

**Comment by zafiredevelopment** [comment]
![image](https://user-images.githubusercontent.com/23500292/36481529-084e3304-1708-11e8-9c6e-278f28fb8d1f.png)

I have tried some other filetypes, it seems that .tar.gz files cause the issue too.

**Comment by iTOYS** [comment]
Hi guys, sorry for delay.
I've found that AAPT ignore assets by this pattern([default](https://stackoverflow.com/questions/28934333/how-can-i-use-android-aaptoptions/28977617#28977617)):
`!.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~`

I'm working on it.
As a workaround you can change `aaptOptions` in your `<path_to_app>/platforms/android/app/build.gradle`:
```
...
android {
   aaptOptions {
        ignoreAssetsPattern ''
    }
}
...
```
