### ISSUE TITLE
docs: TypeScript usage

### ISSUE THREAD

**Issue by dylanvdmerwe** [Microsoft/cordova-plugin-code-push#375]
### Description

There should be a section on the docs that explain how to use this plugin in a TypeScript environment. What needs to be setup to get the sample code to work correctly.

**Comment by iTOYS** [comment]
Hi @dylanvdmerwe 
Do you mean [TACO](http://taco.visualstudio.com/) and/or [Ionic](https://ionicframework.com/) projects?

Thanks!

**Comment by dylanvdmerwe** [comment]
I was mainly talking about it from an ionic or plain cordova project point of view. Without having to us the [ionic native wrapper](https://ionicframework.com/docs/native/code-push/) for Codepush, getting the TypeScript to compile properly with the docs as they are is incredibly hard.

**Comment by Zakeelm** [comment]
Hey there,

Just wanted to let you know we're going to be going to be doing a complete overhaul of our docs in the near future. I'm going to go ahead and close this, but I have noted the suggestion as a point as improvement for our doc changes!

**Comment by gregor-srdic** [comment]
any news? :)
