### ISSUE TITLE
Documentation: Clarify CSP requirements

### ISSUE THREAD

**Issue by marfire** [Microsoft/cordova-plugin-code-push#376]
The documentation for this repository as well as the CLI is generally excellent.

One place where it could be improved is in the discussion the Content Security Policy. The text says: "To ensure that your app can access the CodePush server on CSP-compliant platforms, add `https://codepush.azurewebsites.net` to the `Content-Security-Policy` `meta` tag in your `index.html` file". But then it shows some code that includes all sorts of unrelated stuff (`https://ssl.gstatic.com`, `style-src`, etc.).

This seems to have been [added](https://github.com/Microsoft/cordova-plugin-code-push/issues/49#issuecomment-169386269) in a good-faith attempt to address one user's confusion. I hope it's obvious, though, that you cannot provide a CSP example that is going to work for all users since a CSP is global to the entire application. All the example does is create ambiguity and confusion over what the actual requirements are. This can be seen in #194.

Please just remove the example and state explicitly what the requirements are for this project.

**Comment by Zakeelm** [comment]
Thanks for the feedback on this, i'm going to take a look at it and update it as necessary. I'll follow up in this thread once action has been taken 😄

**Comment by Zakeelm** [comment]
Hey, i'm going to go ahead and close this. We will be working on a re-design of our docs in the near future and this has been noted to update!
