### ISSUE TITLE
[ERROR] Uploaded File is greater than 500 Mb

### ISSUE THREAD

**Issue by zersys** [Microsoft/cordova-plugin-code-push#379]
In Continuation to Issue #334 , We have hit this limit as well. (It doesn't seem to be a 4GB Limit as mentioned).

Kindly let us know how we can continue to push updates of this size or larger.

Additional Information

cordova-plugin-code-push version: 1.10.0-beta
List of installed plugins:
cordova-plugin-whitelist
"cordova-plugin-device
"cordova-plugin-dialogs
"cordova-plugin-network-information"
"cordova-plugin-splashscreen"
"cordova-plugin-statusbar"
"cordova-plugin-fullscreen"
"cordova-plugin-file"
"cordova-plugin-file-transfer"
"cordova-plugin-code-push"
"cordova-plugin-crosswalk-webview"
Cordova CLI version:7.1.0

**Comment by Zakeelm** [comment]
Hey there! 

We're working on and investigating this with the team and I will follow up with you soon

**Comment by Zakeelm** [comment]
Shot you guys an email. Your upload limit is now 1500MB. We hope this helps!
