### ISSUE TITLE
Cannot do 'cordova run android' after installing cordova codepush plugin

### ISSUE THREAD

**Issue by dannysindra** [Microsoft/cordova-plugin-code-push#38]
Successfully installed cordova codepush plugin ("cordova plugin add cordova-plugin-code-push"), but after that I cannot run the usual command "cordova run android" to test my app on the phone. Error on the CodePush.java.

My cordova version is 5.4.0

![capture](https://cloud.githubusercontent.com/assets/10548708/11021705/b1de76fa-8618-11e5-8ac2-c490e5b68e0e.JPG)

**Comment by lostintangent** [comment]
Hmm, that's no good. Could you check the version of the Android platform you're running by calling "cordova platform version android"? I'm assuming there was a breaking change at some point and our plugin doesn't comply. 

Does the app work fine for iOS?

**Comment by dannysindra** [comment]
Thanks @lostintangent, it fixes the issue. My android platform was 3.7.1, and after updating to 4.1.1 it ran just fine.

**Comment by lostintangent** [comment]
Awesome, thanks @dannysindra! Sorry for the inconvenience, and thanks for helping up diagnose this.
