### ISSUE TITLE
How can we obtain all available remote packages?

### ISSUE THREAD

**Issue by jmlopez-rod** [Microsoft/cordova-plugin-code-push#380]
I would like to be able to switch versions of the application. In this case this is more for developing and testing purposes. Take the scenario in which several developers are working on a particular feature or bug fixes for the application. Each developer can build their own patch to the staging deployment and a version will be assigned to it.

Then the person who is assigned to test it can simply go to the app settings and select the version that they wish to test.

I'm not interesting on letting our customers switch versions so a production build will retain the flow that is documented in your docs.

I read in your docs:

> downloadUrl: The URL at which the package is available for download. This property is only needed for advanced usage, since the download method will automatically handle the acquisition of updates for you. (String)

The question is, how can we obtain all the packages available for download?

I did some digging around and we can see the package latest package by using:

https://codepush.azurewebsites.net/updateCheck?deploymentKey=[your-key]&appVersion=[app-version]

and we get a response that looks like this:

```
{
updateInfo: {
  downloadURL: "https://codepush.blob.core.windows.net/storagev2/<some-hash>",
  description: "some description",
  isAvailable: true,
  isMandatory: true,
  appVersion: "app-version",
  packageHash: "the-hash",
  label: "v38",
  packageSize: 1395646,
  updateAppVersion: false,
  shouldRunBinaryVersion: false,
}
}
```

I was wondering if there is an endpoint in the API where I can request for all the available remote packages so that I can we let the tester decide which version to switch to.

**Comment by Zakeelm** [comment]
This is definitely something we can look into the future. I'm not sure it's something we can currently prioritize at the moment though. I'm going to close this for now, but we can re-open it in the future if more people are interested in this.
