### ISSUE TITLE
Build failing in Android with the latest version

### ISSUE THREAD

**Issue by pitAlex** [Microsoft/cordova-plugin-code-push#382]
Hello,

I've just updated the plugin to the latest version and now I am getting:

FAILURE: Build failed with an exception.

* Where:
Script 'platforms/android/cordova-plugin-code-push/mywalletdev-build-extras.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':app'.
> ******_build_extras_1bnhy1igraeiljpajsn1b2iy7$_run_closure1$_closure4

This started happened after I tried to update cordova-android to 7.1.0 then reverting back to 7.0.0

After reverting to 1.11.3 and re-adding the platform 7.0.0 the problem went away.

**Comment by Zakeelm** [comment]
Hey there! 

Sorry for the delayed response. We've been doing some internal re-structuring in regard to our repo support. Are you still having this issue?

**Comment by pitAlex** [comment]
Hi,

I don't have issues anymore
