### ISSUE TITLE
Uncaught TypeError: Cannot read property 'messageHandlers' of undefined

### ISSUE THREAD

**Issue by JohnD0580** [Microsoft/cordova-plugin-code-push#386]
When i debug in Android Studio 3 with Chrome Dev Tools i get this JS error:

Uncaught TypeError: Cannot read property 'messageHandlers' of undefined
    at iOSExec (ios-wkwebview-exec.js:122)
    at Object.execProxy [as exec] (ios-wkwebview-exec.js:151)
    at CodePush.notifyApplicationReady (codePush.js:22)
    at CodePush.syncInternal (codePush.js:207)
    at CodePush.sync (codePush.js:187)
    at hcp (cordova.js?nc=20:200)
    at HTMLDocument.<anonymous> (cordova.js?nc=20:183)
    at cordova_android.js:227

Why is iOS-wkwebview called on Android? And how can i fix this this Error?

Cordova Version:
cordova --version
8.0.0

Platforms:
Installed platforms:
  android 7.0.0
  ios 4.5.4

These are my plugins:
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-code-push 1.11.7 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-inappbrowser-wkwebview 1.0.7 "InAppBrowser (WKWebView)"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.3.2 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
es6-promise-plugin 4.2.2 "Promise"
pushwoosh-cordova-plugin 7.3 "Pushwoosh"

I works fine on Android by the way

**Comment by PaynPlan** [comment]
When i remove the wk webview plugin it works, but i need it, any way to get this to work?

**Comment by iTOYS** [comment]
Hi @JohnD0580,
Thanks for reporting. We'll take a look on this ASAP.

**Comment by iTOYS** [comment]
Hi @JohnD0580,

How I can reproduce your issues?
I've created new ionic app($ ionic start myApp tabs) with code push and all works fine.
I can get and install updates on simulator and device(iOS/Android), without any errors.
Would be great if you can create little app that i can use to reproduce

Thanks!

**Comment by alexandergoncharov** [comment]
Hi @JohnD0580,

Just friendly ping.
Are still having this issue?

**Comment by alexandergoncharov** [comment]
Hi @JohnD0580,

I'm going to close this issue as I haven't heard in a while. Please feel free to reopen this issue if you will have questions or considerations.

Thanks,
Alexander
