### ISSUE TITLE
Cordova app built with PhoneGap build using CodePush now crashes

### ISSUE THREAD

**Issue by BbFGE** [Microsoft/cordova-plugin-code-push#392]
I have been creating apps using PhoneGap Build Online (iOS and Android) and they have installed correctly. I was also using CodePush and the cordova-plugin-code-push to roll out content updates.

There was a problem with that plugin, but it was recently fixed.

However, I tried to work on these apps again today, and they are now crashing when codepush.sync() tries to download and install any updates. 

I have tried 

1. building online with PhoneGap Build Online iOS
2. building online with PhoneGap Build Online Android
3. building locally with cordova command line (Android)
4. manually adding the code-push plugin and even the file/file-transferplugins

I don't think I have changed anything since it was last working, so has something changed in the the plugins?

The error is below (grabbed by using remote debugging with Chrome), underneath is an example config.xml when building with PhoneGap Build Online.

```
codePushUtil.js:41 [CodePush]  FileTransfer is not defined. StackTrace: Error: FileTransfer is not defined
    at RemotePackage.download (file:///data/user/0/com.phonegap.rwtAndroid/files/codepush/deploy/versions/8ec0b377f7e5fb296a08f04bd602471390b2adb3595663493d03aee23267e9e7/www/plugins/cordova-plugin-code-push/bin/www/remotePackage.js:77:46)
    at downloadAndInstallUpdate (file:///data/user/0/com.phonegap.rwtAndroid/files/codepush/deploy/versions/8ec0b377f7e5fb296a08f04bd602471390b2adb3595663493d03aee23267e9e7/www/plugins/cordova-plugin-code-push/bin/www/codePush.js:234:27)
    at onUpdate (file:///data/user/0/com.phonegap.rwtAndroid/files/codepush/deploy/versions/8ec0b377f7e5fb296a08f04bd602471390b2adb3595663493d03aee23267e9e7/www/plugins/cordova-plugin-code-push/bin/www/codePush.js:275:21)
    at file:///data/user/0/com.phonegap.rwtAndroid/files/codepush/deploy/versions/8ec0b377f7e5fb296a08f04bd602471390b2adb3595663493d03aee23267e9e7/www/plugins/cordova-plugin-code-push/bin/www/codePush.js:116:49
    at win (file:///data/user/0/com.phonegap.rwtAndroid/files/codepush/deploy/versions/8ec0b377f7e5fb296a08f04bd602471390b2adb3595663493d03aee23267e9e7/www/plugins/cordova-plugin-code-push/bin/www/nativeAppInfo.js:43:30)
    at Object.callbackFromNative (file:///data/user/0/com.phonegap.rwtAndroid/files/codepush/deploy/versions/8ec0b377f7e5fb296a08f04bd602471390b2adb3595663493d03aee23267e9e7/www/cordova.js:291:58)
    at processMessage (file:///data/user/0/com.phonegap.rwtAndroid/files/codepush/deploy/versions/8ec0b377f7e5fb296a08f04bd602471390b2adb3595663493d03aee23267e9e7/www/cordova.js:1114:17)
    at processMessages (file:///data/user/0/com.phonegap.rwtAndroid/files/codepush/deploy/versions/8ec0b377f7e5fb296a08f04bd602471390b2adb3595663493d03aee23267e9e7/www/cordova.js:1137:9)
```

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.phonegap.rwtAndroid" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>RealWorldTestAndroid</name>
    <description>
        A blank PhoneGap app.
    </description>
    <author email="support@phonegap.com" href="http://phonegap.com">
        PhoneGap Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <platform name="android">
        <preference name="APP_SECRET" value="...redacted..." />
        <preference name="CodePushDeploymentKey" value="...redacted..." />
        <preference name="android-build-tool" value="gradle" />
    </platform>
    <engine name="android" spec="^7.0.0" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-inappbrowser" spec="1.5.0" />
    <plugin name="cordova-plugin-code-push" spec="^1.11.9" />
</widget>
```
Any help would be much appreciated as I have a deadline to finish this project, and thought it would be ok now the bug has been fixed, but some new problem has arisen (or I am doing something wrong!0

Thanks

**Comment by MrRobWad** [comment]
The most recent release fixed my issues with file/file-transfer plugins. I now have those plugins installed like any other, using the following versions. What versions are you using when you've tried adding those plugins manually? Did you try adding them with this code-push plugin present or with it removed from the project first?

config.xml
	<plugin name="cordova-plugin-file" spec="4.3.3"/>
	<plugin name="cordova-plugin-file-transfer" spec="1.6.3"/>

package.json
        "cordova-plugin-file": "4.3.3",
        "cordova-plugin-file-transfer": "1.6.3"

**Comment by BbFGE** [comment]
Hi

I have tried making absolutely sure these versions are installed. 
I first removed all plugins and the Android platform then adding back.

I then built the app and the same error happened - please see
[tests.txt](https://github.com/Microsoft/cordova-plugin-code-push/files/1867837/tests.txt)

Note, there was a warning when adding plugin 'file' ie
```
c:>cordova plugin add cordova-plugin-file@4.3.3
[RESPONSE...]
cordova plugin add cordova-plugin-file@4.3.3
Installing "cordova-plugin-file" for android
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement:
      <6.3.0
Skipping 'cordova-plugin-compat' for android
Android Studio project detected

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.

Adding cordova-plugin-file to package.json
Saved plugin info for "cordova-plugin-file" to config.xml
```
However, it has worked before on Android 7 devices.

I have tried recompiling an older test app that worked - I changed no code, but it failed in the same way.

Please advise!

Thanks

**Comment by iTOYS** [comment]
@alexandergoncharov 
Please take a look

**Comment by alexandergoncharov** [comment]
Hi @BbFGE,

Thanks for reporting!
I tried to reproduce your issue but attempts were unsuccessful.
Also. I tried to install old version of cordova-plugin-code-push(version before adding fix for file and file-transfer plugin) and then update. Not found any issues.
I checked your tests.txt file and note that you try to add `file ` and `file-transfer` before adding `code-push` plugin. 

**Could you please clarify have you tried to just add cordova-plugin-code-push without manually installation of `file ` and `file-transfer`?** 
It should add all necessary plugins. 

Also, about warning in your last comment: It is OK. It just deprecated plugin which functional already included in cordova-android 6.3.0 and newer. You can find more info on plugin repo page: https://github.com/apache/cordova-plugin-compat


Thanks,
Alexander

**Comment by BbFGE** [comment]
Hi 
I have managed to get it working again - I don't know what I changed as I tried so many things!
I was waiting to do a full test before closing this issue, which I hope to do shortly.

I definitely did encounter a problem, but I wonder if specifying the exact version number of the file/file-transfer plugins rather than just 'anything above' ie ~? Could that be it.

Thanks for your help.

**Comment by alexandergoncharov** [comment]
Hi,

Good news. Waiting for finish of test.

About versions:
It was made like so because file plugin doesn't support android older than 6.3.0 since 4.3.3 version. 
Please check this: https://github.com/apache/cordova-plugin-file/blob/master/plugin.xml#L33
And we use exactly 4.3.3 version of file plugin which support Android older than 6.3.0.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @BbFGE ,

Just a friendly ping about result of your testing. =)

**Comment by alexandergoncharov** [comment]
Hi @BbFGE, 

I'm going to close this issue as I haven't heard in a while. Please feel free to reopen this issue if you will have questions or considerations.

Thanks,
Alexander

**Comment by Aihabam** [comment]
I have been facing the same issue, I have solved it by adding `cordova-plugin-file-transfer`
