### ISSUE TITLE
Error Could not get application subdirectory. Errorcode:1 on iOS while call sync()

### ISSUE THREAD

**Issue by Xpedigo** [Microsoft/cordova-plugin-code-push#394]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

Hi there,

After installing the code push plugin, I try to perform a silent update on iOS with sync method, it works to download and install the version, but fail at the end, create a blank page, and rollback the update...

### Reproduction

- Installed last version of code push 
- Call that : `  document.addEventListener('deviceready', function () {

            codePush.sync(function (status) {
                switch (status) {
                    case SyncStatus.DOWNLOADING_PACKAGE:
                        app.alert("Downloading");
                        break;
                    case SyncStatus.INSTALLING_UPDATE:
                        app.alert("Installing");
                        break;
                    case SyncStatus.UPDATE_INSTALLED:
                        app.alert("Insalled wit successs!", function () { location.replace('./index.html'); }, "☂", "Relancer l'application");
                        break;
                }
            }, null);`

Downloading is OK, Installing is, I got the installed with success message but in the console, I got an error and in Microsoft App Center, it's tagged as rolled back : 

Here is the console error : 

`
[CodePush] Package download success: {"deploymentKey":"xxxx","label":"v17","appVersion":"1.0.0","isMandatory":true,"packageHash":"bf15b414cf949f889ac40c586c0f5217c247b1eb27d13e8ea322aa3f9ca07fcd","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/library-nosync/codepush/download/update.zip"}
[CodePush] Installing update
Couldnotgetapplicationsubdirectory.Errorcode:1
Anerrorhasoccurredwhileperformingtheoperation.Errorcode:1
`

### Additional Information

* cordova-plugin-code-push version: 1.11.9
* List of installed plugins:

com.telerik.plugins.nativepagetransitions   	npm	~0.6.5	0.6.5	n/a	android,ios,winphone
cordova-background-geolocation   	pgb	2.8.0	2.8.0	2.8.0	android,ios
cordova-plugin-code-push   	npm	1.11.9	1.11.7	n/a	android,ios,winphone
cordova-plugin-device   	npm	~2.0.1	2.0.1	n/a	android,ios,winphone
cordova-plugin-dialogs   	npm	~2.0.1	2.0.1	n/a	android,ios,winphone
cordova-plugin-file-transfer   	npm	~1.7.1	1.7.1	n/a	ios
cordova-plugin-file-transfer   	npm	~1.6.1	1.6.3	n/a	android
cordova-plugin-geolocation   	npm	~4.0.1	4.0.1	n/a	android,ios,winphone
cordova-plugin-globalization   	npm	~1.0.9	1.0.9	n/a	android,ios,winphone
cordova-plugin-googlemaps   	npm	1.4.5	1.4.5	n/a	android,ios,winphone
cordova-plugin-ionic-keyboard   	npm	~2.0.5	2.0.5	n/a	android,ios,winphone
cordova-plugin-ios-disableshaketoedit   	npm	~1.0.0	1.0.0	n/a	android,ios,winphone
cordova-plugin-splashscreen   	npm	~5.0.2	5.0.2	n/a	android,ios,winphone
cordova-plugin-statusbar   	npm	~2.4.1	2.4.1	n/a	android,ios,winphone
cordova-plugin-whitelist   	npm	1.2.2	1.2.2	n/a	android,ios,winphone
cordova-plugin-zip   	npm	~3.1.0	3.1.0	n/a	android,ios,winphone

* Cordova version: 6.3.1
* iOS/Android/Windows version: iOS 11.2.6
* Does this reproduce on a debug build or release build? :; Debug
* Does this reproduce on a simulator, or only on a physical device? : Real device Iphone SE

Thank you!

**Comment by Xpedigo** [comment]
No Idea anybody?

**Comment by iTOYS** [comment]
Hi @Xpedigo 
Sorry for delay, we'll see your issue as soon as possible!

Thanks for reaching us!

**Comment by alexandergoncharov** [comment]
Hi @Xpedigo,

I note that you don't have cordova-plugin-file. It is necessary for cordova-plugin-file-transfer, cordova-plugin-zip and working with files on devices. You can find more info on https://github.com/apache/cordova-plugin-file

I think that the reason of your issue is in this plugin. Try to add cordova-plugin-file to your project.
Please let me know if it was useful or not.


Thanks,
Alexander

**Comment by Xpedigo** [comment]
Hi,

Did you have chance to look at this? We want to use https://appcenter.ms/ but we are just not able to use the code push feature as the plugin for iOS is not working.

Moreover, is their a way we can have a business support from Microsoft for the appcenter and all the ecosystem around, as we migrate all our platform here and we want this to be reliable anytime.

Thank you for your answer. 

Regards.

**Comment by alexandergoncharov** [comment]
Hi @Xpedigo,

I tried to reproduce your issue but my attempts were unsuccessful. Every time I got require page.
I created `test.html` near to index.html just for testing `location.replace`.
Here is my code(I removed all unnecessary lines):

```
    bindEvents: function () {
        document.addEventListener('deviceready', this.onDeviceReady, false);
        
    },
    onDeviceReady: function () {
        window.codePush.sync(
            function (syncStatus) {
                switch (syncStatus) {
                    case SyncStatus.UPDATE_INSTALLED:
                        navigator.notification.alert("UPDATE_INSTALLED", window.location.replace('./test.html'), 'CodePush', 'OK');
                        break;
                }
            },
            null);
        
        app.receivedEvent('deviceready');
    },
```

Please let me know if it was helpful for you or I did something wrong.

Thanks,
Alexander

**Comment by Xpedigo** [comment]
Hi @alexandergoncharov Thank you for your help!
Let me try your code and I'll come back to you ASAP.

Simple question, are you using Visual Studio Enterprise 2017 with the cordova app environnement to develop that? Maybe there is a configuration that interfers with this code-push plugin and the default config.xml file generating by visual studio?

Regards.

**Comment by alexandergoncharov** [comment]
@Xpedigo , 
I use just Visual Studio Code for development.
I'm not sure about that, but I created cordova project with command-line and config.xml was automatically added in project.
We don't need special config.xml file for working with code-push. We need just one tag element like so: `<preference name="CodePushDeploymentKey" value="YOUR_DEVELOP_KEY" />` in neccessery platform tag. That's all that we need to change for successfully working with code-push.

I hope this helps you.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @Xpedigo ,

Just a friendly ping. Did my code was helpful and are you still having this issue?

**Comment by alexandergoncharov** [comment]
Hi @Xpedigo,

I'm going to close this issue as I haven't heard in a while. Please feel free to reopen this issue if you will have questions or considerations.

Thanks,
Alexander

**Comment by Xpedigo** [comment]
Hi,

After hundred of tests, there is nothing I can do to make this work... This error just popup for ever.
We update the cordova project, platform, plugins without any success.

Delete the app in appcenter, recreate, create a new cordova project from scratch, copy files, still nothing...

We have another project with same configuration, and code push is working well (with the same plugin), I just don't know why the same error is poping up....

I don't know where to investigate more. If you have any idea I will take it.

Here are the plugins installed : 


Plugin | Source | Version | Installed | Latest | Platforms
-- | -- | -- | -- | -- | --
com.telerik.plugins.nativepagetransitions | npm | ~0.6.5 | 0.6.5 | n/a | android,ios,winphone
cordova-plugin-badge | npm | ~0.8.7 | 0.8.7 | n/a | android,ios,winphone
cordova-plugin-code-push | npm | ~1.11.11 | 1.11.11 | n/a | android,ios,winphone
cordova-plugin-device | npm | ~2.0.2 | 2.0.2 | n/a | android,ios,winphone
cordova-plugin-dialogs | npm | ~2.0.1 | 2.0.1 | n/a | android,ios,winphone
cordova-plugin-file | npm | ~6.0.1 | 6.0.1 | n/a | android,ios,winphone
cordova-plugin-file-transfer | npm | ~1.7.1 | 1.7.1 | n/a | android,ios,winphone
cordova-plugin-geolocation | npm | ~4.0.1 | 4.0.1 | n/a | android,ios,winphone
cordova-plugin-globalization | npm | ~1.11.0 | 1.11.0 | n/a | android,ios,winphone
cordova-plugin-googlemaps | npm | 1.4.5 | 1.4.5 | n/a | android,ios,winphone
cordova-plugin-ionic-keyboard | npm | ~2.1.2 | 2.1.2 | n/a | android,ios,winphone
cordova-plugin-ios-disableshaketoedit | npm | ~1.0.0 | 1.0.0 | n/a | android,ios,winphone
cordova-plugin-local-notification | npm | ~0.9.0-beta.3 | 0.9.0-beta.3 | n/a | android,ios,winphone
cordova-plugin-splashscreen | npm | ~5.0.2 | 5.0.2 | n/a | android,ios,winphone
cordova-plugin-statusbar | npm | ~2.4.2 | 2.4.2 | n/a | android,ios,winphone
cordova-plugin-whitelist | npm | 1.3.3 | 1.3.3 | n/a | android,ios,winphone
cordova-plugin-zip | npm | ~3.1.0 | 3.1.0 | n/a | android,ios,winphone

Build with phonegap  : 

PhoneGap (iOS / Android / Windows)
cli-8.0.0 (4.5.4 / 7.0.0 / 5.0.0)

------------------------

Here are the config.xml : 

`<?xml version="1.0" encoding="utf-8"?>
<widget android-versionCode="10000" defaultlocale="fr-FR" id="xpedigo.com" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:vs="http://schemas.microsoft.com/appx/2014/htmlapps">
    <name>NONAME</name>
    <description>NONAME</description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">NONAME</author>
    <vs:template-name></vs:template-name>
    <content src="index.html" />
    <access origin="*" />
    <preference name="SplashScreen" value="screen" />
    <preference name="windows-target-version" value="10.0" />
    <preference name="phonegap-version" value="cli-8.0.0" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <platform name="android">
        <icon density="ldpi" src="res/icons/android/icon-36-ldpi.png" />
        <icon density="mdpi" src="res/icons/android/icon-48-mdpi.png" />
        <icon density="hdpi" src="res/icons/android/icon-72-hdpi.png" />
        <icon density="xhdpi" src="res/icons/android/icon-96-xhdpi.png" />
    </platform>
    <platform name="ios">
        <icon height="180" src="res/icons/ios/icon-60-3x.png" width="180" />
        <icon height="60" src="res/icons/ios/icon-60.png" width="60" />
        <icon height="120" src="res/icons/ios/icon-60-2x.png" width="120" />
        <icon height="76" src="res/icons/ios/icon-76.png" width="76" />
        <icon height="152" src="res/icons/ios/icon-76-2x.png" width="152" />
        <icon height="40" src="res/icons/ios/icon-40.png" width="40" />
        <icon height="80" src="res/icons/ios/icon-40-2x.png" width="80" />
        <icon height="57" src="res/icons/ios/icon-57.png" width="57" />
        <icon height="114" src="res/icons/ios/icon-57-2x.png" width="114" />
        <icon height="72" src="res/icons/ios/icon-72.png" width="72" />
        <icon height="144" src="res/icons/ios/icon-72-2x.png" width="144" />
        <icon height="29" src="res/icons/ios/icon-small.png" width="29" />
        <icon height="58" src="res/icons/ios/icon-small-2x.png" width="58" />
        <icon height="50" src="res/icons/ios/icon-50.png" width="50" />
        <icon height="100" src="res/icons/ios/icon-50-2x.png" width="100" />
    </platform>
    <platform name="windows">
        <icon height="150" src="res/icons/windows/Square150x150Logo.scale-100.png" width="150" />
        <icon height="360" src="res/icons/windows/Square150x150Logo.scale-240.png" width="360" />
        <icon height="30" src="res/icons/windows/Square30x30Logo.scale-100.png" width="30" />
        <icon height="310" src="res/icons/windows/Square310x310Logo.scale-100.png" width="310" />
        <icon height="44" src="res/icons/windows/Square44x44Logo.scale-100.png" width="44" />
        <icon height="106" src="res/icons/windows/Square44x44Logo.scale-240.png" width="106" />
        <icon height="70" src="res/icons/windows/Square70x70Logo.scale-100.png" width="70" />
        <icon height="71" src="res/icons/windows/Square71x71Logo.scale-100.png" width="71" />
        <icon height="170" src="res/icons/windows/Square71x71Logo.scale-240.png" width="170" />
        <icon height="50" src="res/icons/windows/StoreLogo.scale-100.png" width="50" />
        <icon height="120" src="res/icons/windows/StoreLogo.scale-240.png" width="120" />
        <icon height="150" src="res/icons/windows/Wide310x150Logo.scale-100.png" width="310" />
        <icon height="360" src="res/icons/windows/Wide310x150Logo.scale-240.png" width="744" />
    </platform>
    <platform name="android">
        <splash density="land-hdpi" src="res/screens/android/screen-hdpi-landscape.png" />
        <splash density="land-ldpi" src="res/screens/android/screen-ldpi-landscape.png" />
        <splash density="land-mdpi" src="res/screens/android/screen-mdpi-landscape.png" />
        <splash density="land-xhdpi" src="res/screens/android/screen-xhdpi-landscape.png" />
        <splash density="port-hdpi" src="res/screens/android/screen-hdpi-portrait.png" />
        <splash density="port-ldpi" src="res/screens/android/screen-ldpi-portrait.png" />
        <splash density="port-mdpi" src="res/screens/android/screen-mdpi-portrait.png" />
        <splash density="port-xhdpi" src="res/screens/android/screen-xhdpi-portrait.png" />
    </platform>
    <platform name="ios">
        <splash height="480" src="res/screens/ios/screen-iphone-portrait.png" width="320" />
        <splash height="960" src="res/screens/ios/screen-iphone-portrait-2x.png" width="640" />
        <splash height="1024" src="res/screens/ios/screen-ipad-portrait.png" width="768" />
        <splash height="2048" src="res/screens/ios/screen-ipad-portrait-2x.png" width="1536" />
        <splash height="768" src="res/screens/ios/screen-ipad-landscape.png" width="1024" />
        <splash height="1536" src="res/screens/ios/screen-ipad-landscape-2x.png" width="2048" />
        <splash height="1136" src="res/screens/ios/screen-iphone-568h-2x.png" width="640" />
        <splash height="1334" src="res/screens/ios/screen-iphone-portrait-667h.png" width="750" />
        <splash height="2208" src="res/screens/ios/screen-iphone-portrait-736h.png" width="1242" />
        <splash height="1242" src="res/screens/ios/screen-iphone-landscape-736h.png" width="2208" />
    </platform>
    <platform name="windows">
        <splash height="300" src="res/screens/windows/SplashScreen.scale-100.png" width="620" />
        <splash height="1920" src="res/screens/windows/SplashScreen.scale-240.png" width="1152" />
        <splash height="1920" src="res/screens/windows/SplashScreenPhone.scale-240.png" width="1152" />
    </platform>
    <preference name="Fullscreen" value="False" />
    <preference name="Orientation" value="portrait" />
    <preference name="target-device" value="handset" />
    <preference name="deployment-target" value="9.0" />
    <preference name="android-minSdkVersion" value="23" />
    <preference name="android-maxSdkVersion" value="27" />
    <preference name="android-targetSdkVersion" value="23" />
    <platform name="ios">
      <preference name="CodePushDeploymentKey" value="OURKEY" />
    </platform>
    <preference name="BackupWebStorage" value="cloud" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="~2.0.2" />
    <plugin name="cordova-plugin-globalization" spec="~1.11.0" />
    <plugin name="cordova-plugin-splashscreen" spec="~5.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="~2.4.2" />
    <plugin name="cordova-plugin-ios-disableshaketoedit" spec="~1.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="~2.1.2" />
    <plugin name="com.telerik.plugins.nativepagetransitions" spec="~0.6.5" />
    <plugin name="cordova-plugin-dialogs" spec="~2.0.1" />
    <plugin name="cordova-plugin-badge" spec="~0.8.7" />
    <plugin name="cordova-plugin-geolocation" spec="~4.0.1" />
    <plugin name="cordova-plugin-local-notification" spec="~0.9.0-beta.3" src="https://github.com/katzer/cordova-plugin-local-notifications" />
    <plugin name="cordova-plugin-googlemaps" spec="1.4.5">
        <variable name="API_KEY_FOR_ANDROID" value="OURKEY" />
        <variable name="API_KEY_FOR_IOS" value="OURKEY" />
    </plugin>
    <plugin name="cordova-plugin-file" spec="~6.0.1" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.7.1" />
    <plugin name="cordova-plugin-zip" spec="~3.1.0" />
    <plugin name="cordova-plugin-code-push" spec="~1.11.11" />
  <engine name="android" spec="7.1.0" />
  <engine name="ios" spec="4.5.4" />
  <engine name="windows" spec="4.4.2" />
</widget>`

We release the code to appcenter, I see the version, after that we connect to the app running 
`codePush.sync()`, and here is the output : 

`[CodePush] Checking for update.
[CodePush] An update is available. {"appVersion":"1.0.0","deploymentKey":"9R8YjK58ZXWSa7iPIQb6Ps_o8JwjHkDanfllX","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/c3kkxKsRJFKlHog55q0hXeUCRpXy746cc031-e56b-4460-818d-e852e69613f8","isMandatory":true,"label":"v3","packageHash":"88402324d2b6316abfec5534ef532fb0fc9b577b0dc082428046ad9254bc7921","packageSize":9003208,"failedInstall":false}
[CodePush] Downloading update
[CodePush] Package download success: {"deploymentKey":"9R8YjK58ZXWSa7iPIQb6Ps_o8JwjHkDanfllX","label":"v3","appVersion":"1.0.0","isMandatory":true,"packageHash":"88402324d2b6316abfec5534ef532fb0fc9b577b0dc082428046ad9254bc7921","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/library-nosync/codepush/download/update.zip"}
[CodePush] Installing update
Couldnotgetapplicationsubdirectory.Errorcode:1
Anerrorhasoccurredwhileperformingtheoperation.Errorcode:1`

And the app restart with a blank screen.

Any idea please? I'm kind of desperate... And the weirdest thing, I do not understand why it's working with another project with the same configuration.... This is the only which is not working!

Thank you.

**Comment by alexandergoncharov** [comment]
Hi @Xpedigo ,

Could you please share test project with reproducing issue and detailed repro steps? 
It can help me reproduce your issue and found the reason.

Thanks,
Alexander

**Comment by Anopetia** [comment]
Hi @alexandergoncharov thank you for your answer.

I'll try to do a test project for you. However after another batch of test, this is becoming interesting.
I'll copy all the "www" files of the project where codePush works into the www directory of the project where codePush failed (there are nearly similar). 

So i kept all the config.xml and cordova configuration of the failed project, but with the source of the working project, I try codePush... And it works.

So, I suppose there is somewhere in my code into the failing project (into a js file?), a block that cause an error and stop the installation of the the update.

Do you know what exactly trigger a rollback of an installation with codePush? Is that possible a javascript error trigger the rollback. (For example if we put a handler when the app restart, I know that codePush restart the app, and maybe it's conflicted with our code?).

Thank you!

**Comment by alexandergoncharov** [comment]
Hi @Anopetia ,

A RollBack is triggered if there is any error during installation.  And yes, JS error can trigger a RollBack. Possible during installation there is any error with getting subdirectory(no idea why it is only on update) and it trigger RollBack. Waiting test project for investigate it.
Also, as you said:
> I'll copy all the "www" files of the project where codePush works into the www directory of the project where codePush failed (there are nearly similar). 

Could you please check diff between this "www" versions. Possible there will be a reason of issue.  

Thanks,
Alexander

**Comment by Xpedigo** [comment]
Hi @alexandergoncharov , finally I created a blank cordova project from VS 2017 entreprise .

I copy the source from www and the config.xml into the brand new cordova project.

I ran after these commandes : 

`cordova platform add ios`
`cordova platform add android`

I recompile with the new cordova projects folders and the former config.xml and www files.

I codePush.sync()... And tada it works!

I have absolutely no idea what happened. One thing i'm sure. There is something wrong on the structure of the cordova project, and I suspect this is the reason codepush crashed...

Thank you for your help^.

**Comment by Xpedigo** [comment]
Hi @alexandergoncharov for your information, now it's working (Updates seems to be ok), but we still have the error.... I really don't get it : 

![image](https://user-images.githubusercontent.com/37959565/40933913-0b75ba4e-6801-11e8-9dee-9e18efed79dc.png)

**Comment by alexandergoncharov** [comment]
Hi @Xpedigo ,

So, it was worked and than again broken?
The same way: could you please share test project? I would like to take a look at the Cordova configuration if you are sure that the reason of issue in configuration.

Thanks,
Alexander

**Comment by Anopetia** [comment]
No its not broken, codePush is working but still this error.
I'll prepapre you a share project if you want to take a closer look? Thank you.

**Comment by alexandergoncharov** [comment]
@Anopetia , so, at now you can successfully release updates -> successfully download it on device -> but got issue during installation. Do I understand you correct? =)

Yeah, I would like. Because I can't find the reason of issue by error massage. I would like to debug CodePush logic in your case and check what can work incorrect. I hope this can help me to find the reason of issue.

**Comment by Anopetia** [comment]
@alexandergoncharov , yes absolutely, I can release updates, it's successfully downloaded, It successfully installed, the app restart, not rollback is trigerred, however during the update process I still have the subdirectory error, but it seems not to affect the update process, it's very strange.

I sent to you a private repository codepush-test, you will be able to see my environnement.

However, to clarify the exact bug, after many tests, the bug was poping up, even with a simple index.html file with only one line.

So what I decided was to recreate a cordova project from scratch with VS studio 2017, run the cordova command line to add ios and android platform on the new project, and after copy the files from the "buggy" project to the brand new one. And it's only after this, I was able to release update, however even if it's working, I still had the "subdirectory error".

In the repo I invited you, you will find the master branch, which is the clone of the project with codePush working, and I created another branch call issue-394 which is a clone of the buggy codePush project. 

Thank you for your time and help!

**Comment by alexandergoncharov** [comment]
@Anopetia Thanks, I got invite. I'll invetigate it and respone to you ASAP.

**Comment by Anopetia** [comment]
@alexandergoncharov You are very welcome, thank you for your help. I compare with the project where codePush is completely working (without any error) I notice that if I compare to the one where codePush is working but the error is trigerred, it seems the error is trigerred on this operation : 

![image](https://user-images.githubusercontent.com/7024320/40977880-2b625714-68a0-11e8-88cc-eccaaa1d1a0a.png)

On the failing project, even if the update is processed well and installed, I don't have this notification in the console.... instead I have the directory read error.

Regards.

**Comment by Anopetia** [comment]
@alexandergoncharov More and more tests leads to randoms result... Finally, even on the app where it was perfectly working without any error, sometimes I do get the "Update content scceeded" message, and sometimes not... It's random... It might be something wrong somewhere.

**Comment by alexandergoncharov** [comment]
@Anopetia Could you please also provide detailed repro steps which you used?

**Comment by Anopetia** [comment]
@alexandergoncharov Sorry for the delay.

So here what I'm doing : 

- Compile the app with phonegap build
- Launch the app
- Connect to the console with VORLON or WEINRE on iphone
- Type in the console : codePush.sync()

When I typing codePush.sync(), in weinre, codePush stops at "Verifying hash", (I don't get "data integrity succeed), and in Vorlon I got the subdirectory error....

But the process seems to work.

**Comment by alexandergoncharov** [comment]
Hi @Xpedigo , @Anopetia ,

I'm really sorry for this long delay.
Could you please clarify is this issue still actual for you?

**Comment by alexandergoncharov** [comment]
Hi @Xpedigo and @Anopetia,

I'm going to close this issue as I haven't heard from you in a while unfortunately. Please feel free to reopen it if you have any questions. And I'm really sorry for this delay.

Thanks,
Alexander

**Comment by Anopetia** [comment]
Hi!

Si sorry for the delay.

Actually, everything looks find in our side. Updates are working, we just have this error which appears in the console, very randomly, but in any case, update still to performed...

Thank you.

Regards.
