### ISSUE TITLE
Broken "Apple's developer agreement" Link in README

### ISSUE THREAD

**Issue by ddoria921** [Microsoft/cordova-plugin-code-push#397]
I'm looking for the section in Apple's agreement that says they allow delivering over the air updates. It appears that "Apple's developer agreement" link in the README points to a file that does not exist anymore.

**Comment by alexandergoncharov** [comment]
Hi @ddoria921,

Thanks for reporting!
Good catch! Fixed in this PR: https://github.com/Microsoft/cordova-plugin-code-push/pull/399


Thanks,
Alexander
