### ISSUE TITLE
Control Access-Origin on checking for updates

### ISSUE THREAD

**Issue by Wallethub** [Microsoft/cordova-plugin-code-push#400]
Hi,
We've been seeing the problem of access control origin come from time to time where it seems the cordova app is being blocked due to origin being null as this is a cordova ios running on wkwebview. The app has been in stores for a couple of months now and this thing only started recently.

**Comment by Wallethub** [comment]
For CSP we have https://codepush.azurewebsites.net and I don't see that being the problem, otherwise, it wouldn't have ever worked. This happened during some days and it was random. Only for ios, which is 4.5.4, running on the wkwebview plugin (cordova-plugin-wkwebview-engine 1.1.4) and with Cordova 8.0.0.
I don't have the error sample with me right now and couldn't manage to reproduce it anymore. However, it gave an error that is pretty standard when it comes to cross-origin requests, like this one:
https://user-images.githubusercontent.com/34209603/34109880-f9f340de-e42a-11e7-852e-6a10d704b042.png

**Comment by iTOYS** [comment]
@Wallethub 
The best way it's check url in error and if it's `valid` url then set up CSP for it.
If you will find url, please let me know!

Thanks!

**Comment by alexandergoncharov** [comment]
Hi @Wallethub ,

Are you still having this issue?

**Comment by alexandergoncharov** [comment]
@Wallethub unfortunately, I didn't get response from you in a while. Close this issue for now. Please feel free to reopen it if you have questions or still have issue.

Thanks,
Alexander

**Comment by Cui-y** [comment]
This problem is also encountered today.  
This happened during some days and it was random. Only for ios, which is 4.5.5, running on the wkwebview plugin (cordova-plugin-wkwebview-engine 1.1.4) and with Cordova 8.1.2.

like this one:https://ws4.sinaimg.cn/large/006tNbRwly1fx7e4p624dj30rj06bmzz.jpg

**Comment by Cui-y** [comment]
> For CSP we have https://codepush.azurewebsites.net and I don't see that being the problem, otherwise, it wouldn't have ever worked. This happened during some days and it was random. Only for ios, which is 4.5.4, running on the wkwebview plugin (cordova-plugin-wkwebview-engine 1.1.4) and with Cordova 8.0.0.
> I don't have the error sample with me right now and couldn't manage to reproduce it anymore. However, it gave an error that is pretty standard when it comes to cross-origin requests, like this one:
> https://user-images.githubusercontent.com/34209603/34109880-f9f340de-e42a-11e7-852e-6a10d704b042.png

How do you solve this problem?

**Comment by alexandergoncharov** [comment]
Hi @Cui-y,

It looks like you have your own server. Possible this server was not added for your Access-Origin configuration.
Could you please share info from this comment https://github.com/Microsoft/cordova-plugin-code-push/issues/400#issuecomment-381643959?

Also, we have issue with CodePush and `cordova-plugin-wkwebview-engine` plugin. Please check this issue: https://github.com/Microsoft/cordova-plugin-code-push/issues/424
