### ISSUE TITLE
iOS Update only once

### ISSUE THREAD

**Issue by vale95ntino** [Microsoft/cordova-plugin-code-push#401]
### Description

We can only update an iOS app via CodePush once. 
If we upload a new version to Production, it updates the app once. Once we upload a newer version to Production nothing happens. If we reinstall the app, the newest version from CodePush is installed.
We had the same problem for Android but we solved it by loading polyfills.js before cordova.js in index.html

### Reproduction

We used a version of the app that was installed via the App Store so to recreate it you would have to use a production build.

### Additional Information

* cordova-plugin-code-push version: 1.11.7
* List of installed plugins:
code-push 2.0.5 "CodePushAcquisition"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-apprate 1.3.0 "AppRate"
cordova-plugin-code-push 1.11.7 "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova.plugins.diagnostic 3.7.0 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
* Cordova version: cordova (Cordova CLI) : 6.4.0

Thank you in advance

**Comment by vale95ntino** [comment]
Hi @alexandergoncharov ,

I use this function:
`
//update/check for updates
  updateApp(){
    
    // note - mostly error & completed methods of observable will not fire
    // as syncStatus will contain the current state of the update
    this.codePush.sync().subscribe((syncStatus) => console.log(syncStatus));

    const downloadProgress = (progress) => { console.log(`Downloaded ${progress.receivedBytes} of ${progress.totalBytes}`); }
    this.codePush.sync({}, downloadProgress).subscribe((syncStatus) => console.log(syncStatus));
    
  }

`
and in my app.component.ts I use:
`
platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      //check for updates for the app
      backend.updateApp()
      //check if the user is logged in
      let navCtrl = this.navCtrl
      //initiate the push provider
      push.initiatePush()
      //check which maps app to use
      gps.checkFavMapsApp()

    })
`

**Comment by alexandergoncharov** [comment]
Hi @vale95ntino 
Sorry for long replay.

Also, Do you have any logs? 
And what can you see in statistics monitor for CodePush in appcenter.ms? Is there all successful installing? 

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @vale95ntino ,

Unfortunately I haven't hear from you in a while. I'll close this bug for now but please feel free to reopen it if you'll have any questions or you'll provide logs for issue.

Thanks,
Alexander
