### ISSUE TITLE
Code push depended plugins are not installed on platform add

### ISSUE THREAD

**Issue by arnoldsi** [Microsoft/cordova-plugin-code-push#402]
### Description

We are using this plugin in our application. Part of our build processes is to remove the platform and add again.
We noticed that if you remove the platform and add again, only code push plugin installed, without the depended plugins like file, device and etc. 
The hook is not running

### Reproduction

Create new cordova platform.
Add plugin
remove platform
add platform again

### Additional Information

* cordova-plugin-code-push version:  1.11.10
* List of installed plugins:
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-googleplus 5.2.1 "Google SignIn"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-qrscanner 2.5.0 "QRScanner"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.3.2 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
* Cordova version: 6.5
* iOS/Android/Windows version: windows 10 or Mac 10.13.4 or Linux 
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by arnoldsi** [comment]
Hi @alexandergoncharov ,
Thank you for your response. I must say that we're not committing plugins folder into git, The issue occurred when other developer is taking the code and running `cordova platform add [platform]`.
In build logs we see that the platform was added and only code-push plugin restored because the plugin configured in config.xml. It's not restoring the plugin dependencies.

I hope it will help you

**Comment by alexandergoncharov** [comment]
Thanks for information.
Yeah, it was helpful. I found the reason of your issue.
As hot workaround for now I can suggest you the next approach:
Add codePush dependency in your config.xml. This is 

> cordova-plugin-file@4.3.3
> cordova-plugin-file-transfer@1.6.3
> cordova-plugin-zip@3.1.0

This recommended version which work with all android version.
We are trying to support old and new versions of cordova and android, so, this can be inconvenience here at now. Sorry for that.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
@arnoldsi , Could you please let me know if my workaround fix your issue or not?

**Comment by arnoldsi** [comment]
Hi @alexandergoncharov,
I saw that there are some more dependencies like dialog and other, when I add all of them to config.xml it's working, the issue with it is once you will update the versions of the plugins, we won't know about it and it might create application issues

**Comment by alexandergoncharov** [comment]
Hi @arnoldsi,

Yeah, `cordova-plugin-code-push` has dependency `dialog` and `device`. But this dependencies aren't issue and installing automatically as this dependencies are in `plugin.xml` file of plugin.

About updating: You can set a version which you prefer to use(like so: `spec="1.11.7"`) or you can set latest version of plugin(like so: `spec=">=1.11.7"`).  For example, I successfully tested update scenario with setting strong version in `config.xml` file of project: 

>     <plugin name="cordova-plugin-code-push" spec="1.11.7" />
>     <plugin name="cordova-plugin-file" spec="4.3.3" />
>     <plugin name="cordova-plugin-file-transfer" spec="1.6.3" />
>     <plugin name="cordova-plugin-zip" spec="3.1.0" />

Please, let me know if it was helpful or I understand you issue incorrect.

Thanks,
Alexander

**Comment by hobzcalvin** [comment]
I think this happens because the dependencies are only installed if `cordova-plugin-code-push` was used in the command that installed the plugin: https://github.com/Microsoft/cordova-plugin-code-push/blob/master/hooks/afterPluginAdd.js#L2
So, nothing is installed if `cordova platform add` or `cordova prepare` are used to add the plugin. Both seem like perfectly fine workflows to me. Why, @alexandergoncharov?

**Comment by alexandergoncharov** [comment]
Hi @hobzcalvin ,
Sorry for long replay.

Yeah, I implemented this logic because I'm using after_plugin_add hook type which is called after all plugin added. So, this logic prevent unnecessary calling of this hook.
Unfortunately, I can't use after_plugin_install because there is cordova bug which affect adding new plugins in this hook type. 

I'm working on workaround for this and trying to support all use cases.
I will keep you updated on the development of this fix.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi all,
I implemented workaround for this:
https://github.com/Microsoft/cordova-plugin-code-push/pull/411
This approach should fix issue with adding plugin by using config.xml file.  

Could someone please test it?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi all,

Fix in Master branch and it will be released in next release.
So, I'll close this issue for now, but please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi all,

Changes are published. Please try the latest version of plugin.
Feel free to reopen it if you have any questions.

Thanks,
Alexander
