### ISSUE TITLE
The ionic cordova app doesnt get update after successfully pusses the code to thecode-push

### ISSUE THREAD

**Issue by developuser** [Microsoft/cordova-plugin-code-push#404]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

While am using the cordova-plugin-code-push in new app it works fine. the app updated after every successful code push to the code-push plugin.If i added the the cordova-plugin-code-push to my existing app the code are successfully pushes to the code-push plugin .but the apk file doesnt get any update.it just simply checking for the update and shows the app is up-to-date. my existing app configuration is as follows.
cordova-android=6.2.3
cordova-plugin-code-push=1.11.10
cordova-plugin-device=2.0.2
ionic version =1

list of plugins already installed
cordova-plugin-whitelist=1.3.3
cordova-plugin-splashscreen=5.0.2
cordova-plugin-ionic-webview=1.1.16
cordova-plugin-ionic-keyboard=2.0.5
cordova-sqlite-storage=2.2.1
cordova-plugin-device=2.0.2
cordova-plugin-code-push=1.11.10
cordova-plugin-file=4.3.3
cordova-plugin-file-transfer=1.6.3
cordova-plugin-zip=3.1.0

**Comment by joao-gsneto** [comment]
Same for me =/

**Comment by Zakeelm** [comment]
Hey! 

Can you let me know where you're calling `sync()` and tell me what your sync options are?

**Comment by alexandergoncharov** [comment]
Hi @developuser and @joao-gsneto,

Thanks for reporting!
I tested this issue but my attempts for reproduce it were unsuccessful.
I generated apk file of app, installed it on device and release new versions to CodePush. All my releases was successfully installed on device.

As Zakeelm said logs and info about using `sync()` would be helpful.

Also, could you please provide info how exactly you generated apk, code sample or test project with reproducing issue with detailed repro steps?

Thanks,
Alexander

**Comment by joao-gsneto** [comment]
@alexandergoncharov what log would be useful and what is the best way to do it?

So, my app is an ionic 3 based and all compilation is generated by the ionic cli command (ionic cordova run android or ionic cordova run ios ).

On IOS 11 (On Iphone X and Iphone 7) although on the dashboard of appcenter show all devices as successfully installed on the device has no code changes.
Its like an compilation cache that compiles an old version and send to codepush or something like that.

**Comment by alexandergoncharov** [comment]
Hi @joao-gsneto ,
Sorry for long delay.

You can use androidStudio/Xcode/VS Code debugger for getting logs.
Or if you would like get logs from release build you can use services like .bugsnag.
In most cases it is enough but if you will find some more approach for getting logs please feel free to share it =)

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @developuser,

Are you still having this issue?

**Comment by frahmantamala** [comment]
i using sync() like belows but still not work

 this.codePush.sync({
      updateDialog: {
        appendReleaseDescription: true,
        descriptionPrefix: "\n\nChange log:\n"
      },
      installMode: InstallMode.IMMEDIATE
    }).subscribe(
      (data) => {
        console.log('CODE PUSH SUCCESSFULL2: ' + data);

      },
      (err) => {
        console.log('CODE PUSH ERROR: ' + err);

      }
    );

**Comment by huytran0605** [comment]
Could you try to use version 1.10.1?

**Comment by frahmantamala** [comment]
i've try <plugin name="cordova-plugin-code-push" spec="^1.11.10" /> but still same.

**Comment by alexandergoncharov** [comment]
Hi @frahmantamala ,
Thanks for reporting!

Could you please also provide any logs, screen of metrics from https://appcenter.ms/apps?
Also, please double check that your `CodePushDeploymentKey` is correct and you released updates in correct app.

Thanks,
Alexander

**Comment by frahmantamala** [comment]
Hi @alexandergoncharov

**Comment by alexandergoncharov** [comment]
@frahmantamala  Cool. 

So, I'll close this issue for now as issue form @frahmantamala is resolved and I haven't heard in a while form @developuser. But please feel free to reopen if you will have any questions.

Thanks,
Alexander
