### ISSUE TITLE
Code-push does not work with Android 5.2.1

### ISSUE THREAD

**Issue by quintonn** [Microsoft/cordova-plugin-code-push#405]
### Description

I'm using Visual Studio 2017 to create a new Cordova (TACO) project and using the highest available versions of Cordova, Node, Android, etc.
When I try and run codePush.sync i get errors.
When I run "adb logcat" i can see the following errors:

> E/Vold    (  143): Failed to find mounted volume for /storage/extsd/Android/data/com.bcis.stanlibadvisor/cache/
> W/Vold    (  143): Returning OperationFailed - no handler for errno 0
> W/ContextImpl(16938): Failed to ensure directory: /storage/extsd/Android/data/com.bcis.stanlibadvisor/cache
> E/Vold    (  143): Failed to find mounted volume for /storage/extsd/Android/data/com.bcis.stanlibadvisor/files/
> W/Vold    (  143): Returning OperationFailed - no handler for errno 0
> W/ContextImpl(16938): Failed to ensure directory: /storage/extsd/Android/data/com.bcis.stanlibadvisor/files
> E/Vold    (  143): Failed to find mounted volume for /storage/extsd/Android/data/com.bcis.stanlibadvisor/files/
> W/Vold    (  143): Returning OperationFailed - no handler for errno 0
> W/ContextImpl(16938): Failed to ensure directory: /storage/extsd/Android/data/com.bcis.stanlibadvisor/files
> E/Vold    (  143): Failed to find mounted volume for /storage/extsd/Android/data/com.bcis.stanlibadvisor/cache/
> W/Vold    (  143): Returning OperationFailed - no handler for errno 0
> W/ContextImpl(16938): Failed to ensure directory: /storage/extsd/Android/data/com.bcis.stanlibadvisor/cache
> E/Vold    (  143): Failed to find mounted volume for /storage/extsd/Android/data/com.bcis.stanlibadvisor/files/
> W/Vold    (  143): Returning OperationFailed - no handler for errno 0
> W/ContextImpl(16938): Failed to ensure directory: /storage/extsd/Android/data/com.bcis.stanlibadvisor/files
> E/Vold    (  143): Failed to find mounted volume for /storage/extsd/Android/data/com.bcis.stanlibadvisor/files/
> W/Vold    (  143): Returning OperationFailed - no handler for errno 0
> W/ContextImpl(16938): Failed to ensure directory: /storage/extsd/Android/data/com.bcis.stanlibadvisor/files
> E/Vold    (  143): Failed to find mounted volume for /storage/extsd/Android/data/com.bcis.stanlibadvisor/cache/
> W/Vold    (  143): Returning OperationFailed - no handler for errno 0
> W/ContextImpl(16938): Failed to ensure directory: /storage/extsd/Android/data/com.bcis.stanlibadvisor/cache
> D/ContentSync(16938): unzipSync called
> D/ContentSync(16938): zip = /cdvfile:/localhost/files/codepush/download/update.zip
> E/ContentSync(16938): An error occurred while unzipping.

> E/ContentSync(14644): An error occurred while unzipping.
> E/ContentSync(14644): java.io.FileNotFoundException: cdvfile:/localhost/files/codepush/download/update.zip: open failed: ENOENT (No such file or directory)
> E/ContentSync(14644): 	at libcore.io.IoBridge.open(IoBridge.java:456)
> E/ContentSync(14644): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
> E/ContentSync(14644): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
> E/ContentSync(14644): 	at java.util.zip.ZipFile.<init>(ZipFile.java:158)
> E/ContentSync(14644): 	at java.util.zip.ZipFile.<init>(ZipFile.java:119)
> E/ContentSync(14644): 	at com.adobe.phonegap.contentsync.Sync.unzipSync(Sync.java:783)
> E/ContentSync(14644): 	at com.adobe.phonegap.contentsync.Sync.access$200(Sync.java:57)
> E/ContentSync(14644): 	at com.adobe.phonegap.contentsync.Sync$2.run(Sync.java:124)
> E/ContentSync(14644): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> E/ContentSync(14644): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> E/ContentSync(14644): 	at java.lang.Thread.run(Thread.java:818)
> E/ContentSync(14644): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
> E/ContentSync(14644): 	at libcore.io.Posix.open(Native Method)
> E/ContentSync(14644): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
> E/ContentSync(14644): 	at libcore.io.IoBridge.open(IoBridge.java:442)
> E/ContentSync(14644): 	... 10 more
> W/CordovaPlugin(14644): Attempted to send a second callback for ID: Zip1294452191
> W/CordovaPlugin(14644): Result was: "OK"
> I/chromium(14644): [INFO:CONSOLE(41)] "[CodePush]  Could not unzip package-1. StackTrace: Error: Could not unzip package-1
> I/chromium(14644):     at newPackageUnzipped (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:49:50)
> I/chromium(14644):     at fail (file:///android_asset/www/plugins/cordova-plugin-zip/zip.js:24:13)
> I/chromium(14644):     at Object.callbackFromNative (file:///android_asset/www/cordova.js:295:52)
> I/chromium(14644):     at processMessage (file:///android_asset/www/cordova.js:1081:17)
> I/chromium(14644):     at processMessages (file:///android_asset/www/cordova.js:1104:9)
> I/chromium(14644):     at pollOnce (file:///android_asset/www/cordova.js:973:9)
> I/chromium(14644):     at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:960:5)", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (41)
> I/chromium(14644): [INFO:CONSOLE(41)] "[CodePush] An error occurred during sync. Could not unzip package-1. StackTrace: Error: Could not unzip package-1
> I/chromium(14644):     at newPackageUnzipped (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:49:50)
> I/chromium(14644):     at fail (file:///android_asset/www/plugins/cordova-plugin-zip/zip.js:24:13)
> I/chromium(14644):     at Object.callbackFromNative (file:///android_asset/www/cordova.js:295:52)
> I/chromium(14644):     at processMessage (file:///android_asset/www/cordova.js:1081:17)
> I/chromium(14644):     at processMessages (file:///android_asset/www/cordova.js:1104:9)
> I/chromium(14644):     at pollOnce (file:///android_asset/www/cordova.js:973:9)
> I/chromium(14644):     at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:960:5)", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (41)

Also in the logcat output is the result from the package download success. And it has the following in it:

> **"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}"**

If I compare those 2 paths:
cdvfile://localhost/files/codepush/download/update.zip  --> Code Push Path
cdvfile:/localhost/files/codepush/download/update.zip   --> Zip.Unzip Path

It looks like maybe it's the extra **"/"** in the code push plugin?

### Reproduction

Create a new Cordova project in Visual Studio 2017.
Set up code push using App Center.
Publish 1 release.
Try and run codePush.sync();

### Additional Information

* cordova-plugin-code-push version:  

> ~1.11.10

* List of installed plugins:
> <plugin name="cordova-plugin-inappbrowser" spec="~2.0.2" />
>   <plugin name="cordova-plugin-whitelist" spec="~1.3.3" />
>   <plugin name="cordova-plugin-youtube-video-player" spec="~1.0.6" />
>   <plugin name="cordova-plugin-calendar" spec="^4.6.0">
>     <variable name="CALENDAR_USAGE_DESCRIPTION" value="This app may access your system calendar to create events" />
>   </plugin>
>   <plugin name="cordova-plugin-datepicker" spec="~0.9.3" />
>   <plugin name="cordova-plugin-fcm" spec="~2.1.2" />
>   <plugin name="cordova-plugin-device" spec="~2.0.2" />
>   <plugin name="cordova-plugin-appcenter-crashes" spec="~0.1.4" />
>   <plugin name="code-push" spec="~2.0.5" />
>   <plugin name="cordova-plugin-appcenter-shared" spec="~0.1.4" />
>   <plugin name="cordova-plugin-dialogs" spec="~2.0.1" />
>   <plugin name="cordova-plugin-code-push" spec="~1.11.10" src="D:\Projects\CordovaPlugins\cordova-plugin-code-push" />
>   <engine name="android" spec="5.2.1" />
>   <engine name="ios" spec="4.3.0" />
>   <engine name="windows" spec="4.4.2" />
>   <plugin name="cordova-plugin-file" spec="~4.3.3" />
>   <plugin name="cordova-plugin-file-transfer" spec="~1.6.3" />
>   <plugin name="cordova-plugin-zip" spec="~3.1.0" />

* Cordova version: 

> 6.3.1 (max allowed by Visual Studio)

* iOS/Android/Windows version: 

> 4.3.0/5.2.1/4.4.2

* Does this reproduce on a debug build or release build? 

> Both

* Does this reproduce on a simulator, or only on a physical device? 

> Physical Device

(The more info the faster we will be able to address it!)

**Comment by quintonn** [comment]
**Note**
As a test, i cloned my same project and upgraded to Cordova 8, and Android 6.4.0 and i re-installed all the plugins and the plugin worked and installed my update nicely.

**Comment by alexandergoncharov** [comment]
Hi @quintonn ,

Thanks for reporting!
I need some time for investigate specialty of creating cordova app throw VisualStudio. Possibly the issue can be related of it.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @quintonn ,
Sorry for long replay.

I tried to reproduce your issue but my attempts were unsuccessful. Successfully got update using codePush. I created proj as described in MS doc: https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/?view=toolsforcordova-2017
But I got issue with `includes()` method which we already fixed in: https://github.com/Microsoft/cordova-plugin-code-push/pull/408. Next release will contain it.

Could you please share test project with reproducing issue with detailed repro steps? 
It can help me to reproduce it and investigate.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @quintonn ,

I'll close this issue for now as I haven't heard from you in a while unfortunately. But please, feel free to reopen it if you will have any questions or you will provide test project with reproducing issue.


Thanks,
Alexander

**Comment by wambele** [comment]
am also getting the same error in my project on downloading app through an error
downloading undefined of error: could not unzip package-1 codepush error
