### ISSUE TITLE
New Releases of Ionic App does not change the app after deployment

### ISSUE THREAD

**Issue by joao-gsneto** [Microsoft/cordova-plugin-code-push#407]
### Description

When i release a new codepush version for Cordova IOS everything works fine.
But when the device Open the App, download the update and then reload, nothing happens. The version of installed application (and every change maded to the code) does not apply to the device - even in the appcenter appearing as installed and active.

### Reproduction

-> # IOnic 3 application.
-> # Codepush enabled
-> # New release (Staging)
-> # Open the application and try to download and apply the update.

### Additional Information

* cordova-plugin-code-push version: 
1.11.10

* List of installed plugins:
branch-cordova-sdk 2.6.24 "branch-cordova-sdk"
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-code-push 1.11.10 "CodePush"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

* Cordova version:
8.0.0

* iOS/Android/Windows version:
iOS - 11
Android - 7
Windows 10 - build 16299.371

* Does this reproduce on a debug build or release build?
Release build with staging codepush

* Does this reproduce on a simulator, or only on a physical device?
On simulator or physical devices

I aready made 7 versions of the application but no one has applied to the physical devices - still on a old version.
Thanks for the support

**Comment by Zakeelm** [comment]
Hey!

do you have any logs?

**Comment by alexandergoncharov** [comment]
Hi @joao-gsneto ,
Thanks for reporting.

I haven't faced this issue for me. `appcenter codepush release-cordova` should run `cordova prepare` internally. So, this should guaranty that you release your actual code.
Please check docs for more information: https://github.com/Microsoft/code-push/tree/master/cli#releasing-app-updates
 
Anyway, If you will get stable repro of this you can open issue in code-push-cli repo: https://github.com/Microsoft/code-push/tree/master/cli#releasing-app-updates

As issue is gone I'll close this issue for now but please feel free to reopen it if you will have questions.


Thanks,
Alexander

**Comment by camaragit** [comment]
I all i'm faced to the same issue.The update correcty (it dowload and apply the modification) but when i restart the app it go always to the first version before making any change. Can someone help me to fix it?

**Comment by alexandergoncharov** [comment]
Hi @camaragit ,

Could you please share your logs and CodePush configuration?
Also, Have tried to do steps from here: https://github.com/Microsoft/cordova-plugin-code-push/issues/407#issuecomment-389538058 ?

**Comment by camaragit** [comment]
Hi @alexandergoncharov ,
thanks you for your reply 
Yes i have try theses @joao-gsneto 's steps but i still have always the same issue. here is my codepush configuration :
` <platform name="android">
        <preference name="CodePushDeploymentKey" value="asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ" />
		</platform>`
theses are my plugins : `	    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^2.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-code-push" spec="^1.11.12" />
    <plugin name="cordova-plugin-file" spec="^4.3.3" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.6.3" />
    <plugin name="cordova-plugin-zip" spec="^3.1.0" />
    <engine name="android" spec="7.0.0" />`
here is the logs that i have when an update is available: 
`	
[CodePush] Checking for update.
codePushUtil.js:36 [CodePush] An update is available.
{"appVersion":"0.0.1","deploymentKey":"asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/bx6NRCOef_mctmhrsD3HfEl2Lk3W39084bbb-4369-4a3a-ac6a-bb21dc659d03","isMandatory":true,"label":"v6","packageHash":"852f10571ffc4f91b569382b407f6940c55d590d1405e1607507c1b4ed3929f0","packageSize":2474,"failedInstall":false}


[CodePush] Downloading update
codePushUtil.js:36 [CodePush] Package download success:
 {"deploymentKey":"asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ","label":"v6","appVersion":"0.0.1","isMandatory":true,"packageHash":"852f10571ffc4f91b569382b407f6940c55d590d1405e1607507c1b4ed3929f0","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
 
 
 [CodePush] Installing update
codePushUtil.js:36 [CodePush] Applying diff update
codePushUtil.js:36 [CodePush] Verifying hash for folder path: /codepush/deploy/versions/852f10571ffc4f91b569382b407f6940c55d590d1405e1607507c1b4ed3929f0/
codePushUtil.js:36 [CodePush] The update contents succeeded the data integrity check.
codePushUtil.js:36 [CodePush] Install succeeded.

[CodePush] Reported status: {"status":1,"label":"v6","appVersion":"0.0.1","deploymentKey":"asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ","previousLabelOrAppVersion":"v5","previousDeploymentKey":"asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ"}`
When an update is available it download and apply it correctly after restarting the app. After if a restart the app my self. The app return to its first version.

**Comment by lperezb** [comment]
> Hi @alexandergoncharov ,
> thanks you for your reply
> Yes i have try theses @joao-gsneto 's steps but i still have always the same issue. here is my codepush configuration :
> `<platform name="android"> <preference name="CodePushDeploymentKey" value="asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ" /> </platform>`
> theses are my plugins : `<plugin name="cordova-plugin-whitelist" spec="1.3.3" /> <plugin name="cordova-plugin-device" spec="2.0.2" /> <plugin name="cordova-plugin-splashscreen" spec="5.0.2" /> <plugin name="cordova-plugin-ionic-webview" spec="^2.0.0" /> <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" /> <plugin name="cordova-plugin-code-push" spec="^1.11.12" /> <plugin name="cordova-plugin-file" spec="^4.3.3" /> <plugin name="cordova-plugin-file-transfer" spec="^1.6.3" /> <plugin name="cordova-plugin-zip" spec="^3.1.0" /> <engine name="android" spec="7.0.0" />`
> here is the logs that i have when an update is available:
> `
> [CodePush] Checking for update.
> codePushUtil.js:36 [CodePush] An update is available.
> {"appVersion":"0.0.1","deploymentKey":"asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ","downloadUrl":"[https://codepushupdates.azureedge.net/storagev2/bx6NRCOef_mctmhrsD3HfEl2Lk3W39084bbb-4369-4a3a-ac6a-bb21dc659d03","isMandatory":true,"label":"v6","packageHash":"852f10571ffc4f91b569382b407f6940c55d590d1405e1607507c1b4ed3929f0","packageSize":2474,"failedInstall":false}](https://codepushupdates.azureedge.net/storagev2/bx6NRCOef_mctmhrsD3HfEl2Lk3W39084bbb-4369-4a3a-ac6a-bb21dc659d03%22,%22isMandatory%22:true,%22label%22:%22v6%22,%22packageHash%22:%22852f10571ffc4f91b569382b407f6940c55d590d1405e1607507c1b4ed3929f0%22,%22packageSize%22:2474,%22failedInstall%22:false%7D)
> 
> [CodePush] Downloading update
> codePushUtil.js:36 [CodePush] Package download success:
> {"deploymentKey":"asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ","label":"v6","appVersion":"0.0.1","isMandatory":true,"packageHash":"852f10571ffc4f91b569382b407f6940c55d590d1405e1607507c1b4ed3929f0","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
> 
> [CodePush] Installing update
> codePushUtil.js:36 [CodePush] Applying diff update
> codePushUtil.js:36 [CodePush] Verifying hash for folder path: /codepush/deploy/versions/852f10571ffc4f91b569382b407f6940c55d590d1405e1607507c1b4ed3929f0/
> codePushUtil.js:36 [CodePush] The update contents succeeded the data integrity check.
> codePushUtil.js:36 [CodePush] Install succeeded.
> 
> [CodePush] Reported status: {"status":1,"label":"v6","appVersion":"0.0.1","deploymentKey":"asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ","previousLabelOrAppVersion":"v5","previousDeploymentKey":"asB1TYrAcB_PgKkakWFykFXVPn67rJfFWCtUQ"}`
> When an update is available it download and apply it correctly after restarting the app. After if a restart the app my self. The app return to its first version.

Having the same issue here.... Anybody?!
