### ISSUE TITLE
i'm use code-push ,found a error,is not update

### ISSUE THREAD

**Issue by mengxiaof** [Microsoft/cordova-plugin-code-push#410]
An update is available,but it is being ignored due to have been previously rolled back;i want to update to next version,how can i do?
![image](https://user-images.githubusercontent.com/19354837/39976918-074431f6-5769-11e8-83c2-4656336d0f92.png)

**Comment by alexandergoncharov** [comment]
Hi @mengxiaof ,
Thanks for reporting.

It is mean that last update got error on other device. To prevent other user for getting broken update it was rollbacked. New updates will be available for you when developer release it until it also got error on some devices.
Please check this for more info:  https://github.com/Microsoft/cordova-plugin-code-push#how-does-it-work


Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
@mengxiaof Please let me know if it was helpful or you have any other questions?

Thanks,
Alexander

**Comment by huytran0605** [comment]
i'm using version 1.11.10 and have same issues with cordova ios version 4.5.4, 
It happens only in IOS, Android is still ok so i think code logic is no problem...:(

**Comment by huytran0605** [comment]
One more thing, when i used version 1.10.1, it's okay.

**Comment by alexandergoncharov** [comment]
Hi @huytran0605 ,
Thanks for reporting!

Could you place provide any logs, code example of your using codePush, screen from metrics in https://appcenter.ms/apps?

Thanks,
Alexander

**Comment by mengxiaof** [comment]
ok,thank you
