### ISSUE TITLE
App size increases with each new update

### ISSUE THREAD

**Issue by geneoes** [Microsoft/cordova-plugin-code-push#416]
### Description

I did a few deploys for testing, and notice that my android APP SIZE is incrementing considerably, like +20MB per any downloaded update comming from code-push. 

I tried to uninstall the app, and installing it again, so it could download ONLY the latest bundle. But it downloaded the whole 80mb of the four deploys I had done.

I tried: generating another binary APK, with same APP id (*com.myapp.myapp*) but pointing to another *code-push* app and *deploymentKey*.  The crazy thing is that even with that new DEPLOYMENT KEY and new APP, I got again the 80mb app size on the first code-push download

### Reproduction

Having an app and keys set on an android cordova aplication:

1- Push changes within *cordova-release* command on the *code-push* cli.
2- Open app and download it. Close the app and check size (should be bigger, thats ok)
3- Push another changes again
4- Open app and download it. Close the app and check size (The sizes INCREASES AGAIN)
5- Keep repeating the process, the app keeps increasing when downloading the last update.

Seems like if there is a problem on what I download from the codepush server

### Additional Information

* cordova-plugin-code-push version: 1.11.11
* List of installed plugins: 
```
code-push 2.0.4 "CodePushAcquisition"
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-code-push 1.11.11 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.3.3 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"
phonegap-plugin-push 2.2.2 "PushPlugin"
```
* Cordova version: 8.0.0
* iOS/Android/Windows version: 7.1.2
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? physical devices

Any idea? ask for more details if needed

Thanks.

**Comment by alexandergoncharov** [comment]
Hi @geneoes ,
Thanks for reporting!

I'll investigate your issue a little bit later. Sorry for that long delay.

Thanks,
Alexander

**Comment by geneoes** [comment]
Thanks @alexandergoncharov 

Is it an intended functionallity that the app size increase overcoming even the initial app size? (App initial size: 20mb, App with updates: +80mb) Shouldn't the app size increase only what the bundle and assets sizes are?

**Comment by alexandergoncharov** [comment]
Hi @geneoes ,
Sorry for long delay.

I tested this case on `appcenter-cli` with and without image and didn't get this issue. There was near the same app size(Only after adding Image the size was incremented).
Docs for appcenter-cli: 
Could you please test it with `appcenter-cli` and please let me know if it was helpful for you or not?

Thanks
Alexander

**Comment by salemdomain** [comment]
@alexandergoncharov i have same problem.. i tried using appcenter-cli but no luck.

**Comment by geneoes** [comment]
The same with appcenter-cli. I think it might be a cordova plugin problem

**Comment by alexandergoncharov** [comment]
Hi @geneoes and @salemdomain,

I reproduced this issue only with Ionic app. For clear Cordova I don't have big increase app size.
Investigation issue in progress.

@geneoes, @salemdomain  Do you also use Ionic or Cordova/PhoneGap?

Thanks,
Alexander

**Comment by geneoes** [comment]
I'm using ionic 3!

**Comment by alexandergoncharov** [comment]
Hi @geneoes and @salemdomain ,
Sorry for this long delay.

Unfortunately this increasing of app size is just Ionic specification. Also, app keep the last one update on device for rollback case. Clear Cordova app also have this increasing but not so big because Ionic has additional structure of app and files.
I'm sorry to saying this but I think that we can't change this behaviour. =(

Please let me know if you have any questions.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi all,

I'm going to close this issue as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
