### ISSUE TITLE
codePush is undefined Vuetify Cordova boilerplate

### ISSUE THREAD

**Issue by JPaulMora** [Microsoft/cordova-plugin-code-push#418]
### Description

Hi, I'm using [Vuetify.js corodva](https://github.com/vuetifyjs/cordova) and would like to use codePush on my app. I just can't get it to recognize within my JS code on webpack (codePush is always undefined)

### Reproduction

After registering on CodePush, installing and following the steps on this repo:
````
#install
cordova plugin add cordova-plugin-code-push@latest 
#Add this
<platform name="ios">
    <preference name="CodePushDeploymentKey" value="MY-IOS-STAGING-KEY" />
</platform>
# Use all origins
<access origin="*" />
 # and confirming the plugin is there
cordova plugin ls
````

codePush itself seems to be working, detecting changes, pushing updates and all. My problem is inside my own code, I can't reach the `codePush` instance/object not even after doing
`import CodePush from 'code-push'` in App.vue

### Additional Information

* cordova-plugin-code-push version: 1.11.11
* List of installed plugins: 
```
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
* Cordova version: 8.0.0
* iOS/Android/Windows version: iOS 10.3.3
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

Thanks in advance

**Comment by alexandergoncharov** [comment]
Hi @JPaulMora,
Thanks for reporting!

Please check that you are trying to reach the correct name object. I see that you are importing `CodePush` (`C` is uppercase) and then you trying to reach `codePush` (`c` is lower case).
Please let me know if it was helpful or please provide test project with reproducing issue.

Thanks,
Alexander

**Comment by JPaulMora** [comment]
Thanks @alexandergoncharov for the response, sorry for the ambiguity, names are from different tests (tried **c**odePush as global variable/object, tried importing and using **C**odePush).

**Comment by alexandergoncharov** [comment]
@JPaulMora 
Got it. So, if issue isn't in naming could you please provide test project with reproducing issue?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @JPaulMora,

I'm going to close this issue because I haven't heard from you in a while.
Please feel free to reopen it if you'll have any questions or you'll provide test project with reproducing issue.

Thanks,
Alexander

**Comment by sobriver** [comment]
I also encountered this situation, how to solve it?
