### ISSUE TITLE
codePush sync SyncStatus before download function

### ISSUE THREAD

**Issue by joey91133** [Microsoft/cordova-plugin-code-push#42]
Can add a SyncStatus before download?
because if I click continue button for update alert.
I can do anything on this page and change another page.
but I want to show my loading function to limit user touch screem.

sorry my bad english.

**Comment by lostintangent** [comment]
We recently added support for tracking download progress, and we need to expose that functionality to the sync method. While we do that, we're planning to extend the sync status events as well so that the sync method provides more hooks to app devs, so they can display whichever custom UI they would like.

**Comment by dlebu** [comment]
Thanks for the feedback, @joey91133. When we implemented `SyncStatus` we thought about it as being a final status for the sync operation, not an intermediate one. That way, developers can rely on the fact that `syncCallback` is only called once at the end of the operation.

However, your scenario is very common, and we will add a download progress callback in the next version. It will be available for both `sync` and `download` as an extra parameter.

If you are blocked right now by this issue, you can manually invoke `checkForUpdate`, `download`, `apply` and control the UI between those calls. See the [advanced sample](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/advanced) for an example.

**Comment by joey91133** [comment]
Thanks.
I will wait download progress callback and update my app.
I like it code-push.

**Comment by dlebu** [comment]
Sounds good. I will keep this issue open until we publish the progress callback. Thanks again!

**Comment by dlebu** [comment]
@joey91133 We just released version [1.3.0-beta](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/1.3.0-beta) to GitHub and npm. This brings additional `SyncStatus`es for checking for update, downloading, installing. Also, we added a new callback for download progress. Please try it out and let us know if you have any feedback.

**Comment by joey91133** [comment]
Thanks.
I don't know where can I set UpdateDialogOptions,
Can make this Sample on Readme??

**Comment by dlebu** [comment]
@joey91133 We added a [new sample code snippet for sync](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/README.md#example-5) on how to use the `UpdateDialogOptions`. Please see the third sample for the sync operation. Thanks for the feedback.
