### ISSUE TITLE
Hot code push on iOS now outlawed by updated App Store guidelines?

### ISSUE THREAD

**Issue by dpa99c** [Microsoft/cordova-plugin-code-push#422]
Apple's updated App Store guidelines seem to prohibit hot pushing of code to iOS apps if it interacts with native APIs (e.g. via Cordova plugins):

http://www.appstorereviewguidelineshistory.com/articles/2018-06-04-wwdc2018/

> Apps may contain or run code that is not embedded in the binary (e.g. HTML5-based games, bots, etc.), as long as code distribution isn’t the main purpose of the app, the code is not offered in a store or store-like interface, and provided that the software (1) is free or purchased using in-app purchase; (2) <b>only uses capabilities available in a standard WebKit view (e.g. it must open and run natively in Safari without modifications or additional software); your app must use WebKit and JavaScript Core to run third party software and should not attempt to extend or expose native platform APIs to third party software;</b> (3) is offered by developers that have joined the Apple Developer Program and signed the Apple Developer Program License Agreement; and (4) adheres to the terms of these App Review Guidelines (e.g. does not include objectionable content).

This seems to imply that if the pushed code won't run natively in Safari (Cordova app code that uses Cordova plugins which access native APIs wouldn't) or exposes native platform APIs (Cordova plugins do) then it's not permitted.

Do you (Microsoft) or anyone else have any clarification on this, e.g. from Apple or apps being rejected due to hot push of code that interacts with Cordova plugins?

**Comment by Zakeelm** [comment]
Hey there!

We've been monitoring this closely and we're fully aware of the changes. We don't believe this to be an issue at all, as we haven't had any rejections or any other problems as a result of the changes. I'm going to go ahead and close this. We can re-open if something comes up in the future.
