### ISSUE TITLE
Why not update it in ios

### ISSUE THREAD

**Issue by duqianchen** [Microsoft/cordova-plugin-code-push#423]
In android, it can update normally, but in ios, it can detect and install updates normally, but the code has not changed, why?

**Comment by alexandergoncharov** [comment]
Hi @duqianchen ,
Thanks for reporting.

There can be many cases when it can be. Could you please provide us as much info as possible and fill it in template?
Also please check that you tested CodePush in release mode(NOT debug). As in Debug mode changes will be installed bot not applied as bundle will be downloaded from packager.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @duqianchen ,

I'm going to close this issue for as I haven't heard from you in a while but please feel free to reopen it if you have any questions.

Thanks,
Alexander
