### ISSUE TITLE
code-push deployment ls APP_NAME -k

### ISSUE THREAD

**Issue by pengzhiqiang110** [Microsoft/cordova-plugin-code-push#428]
code-push deployment ls APP_NAME -k finish later happen  -bash: code-push: command not found issures    in what directory run  code-push deployment ls HelloWord -k?

**Comment by alexandergoncharov** [comment]
Hi @pengzhiqiang110 ,

Unfortunately I'm going to close this issue as I haven't heard form you in a while.
Please feel free to reopen if you have any questions.

Thanks,
Alexander
