### ISSUE TITLE
code-push release-cordova MyApp-ios ios 

### ISSUE THREAD

**Issue by pengzhiqiang110** [Microsoft/cordova-plugin-code-push#429]
code-push release-cordova What does myapp-ios refer to for this command, I reported such error after execution  -bash: code-push: command not found . Looking forward to your reply.

**Comment by alexandergoncharov** [comment]
Hi @pengzhiqiang110 
Thanks for reporting!

You should run `code-push release-cordova` in root of your folder. This command automatically prepare your project and make release.
About your issue with `-bash: code-push: command not found` I describe in your other issue: https://github.com/Microsoft/cordova-plugin-code-push/issues/428

Please let me know if it was helpful for you or you have any question.

Thanks,
Alexander

**Comment by 1104931825** [comment]
The integration is now complete,The update to the codepush service shows success.But it won't be installed on the phone,this why

**Comment by alexandergoncharov** [comment]
@1104931825 , Could you pelase provide logs, setting for CodePush, you versions and other info which can help us to reproduce issue?

**Comment by NickToropov** [comment]
Hi all! Closing now. Feel free to reopen if you still facing this.
