### ISSUE TITLE
[Error]  No iOS simulators found. Re-run this command after starting one.

### ISSUE THREAD

**Issue by 1104931825** [Microsoft/cordova-plugin-code-push#431]
run  code-push debug ios ,At the wrong,this why

**Comment by alexandergoncharov** [comment]
Could you please fill issue template https://github.com/Microsoft/cordova-plugin-code-push/blob/master/.github/ISSUE_TEMPLATE.md and provide as much info as you can because it is really hard to understand your issue?

Thanks,
Alexander

**Comment by NickToropov** [comment]
Hi @1104931825. Closing now. Feel free to reopen if you still facing this.
Thanks!
