### ISSUE TITLE
Wrong type for parameter "path" of DirectoryEntry.getFile: Expected String, but got Undefined.

### ISSUE THREAD

**Issue by ButchMonkey** [Microsoft/cordova-plugin-code-push#436]
### Description
We noticed this coming up in our logging software.
Currently unable to replicate and not entirely sure when it occurs.

### Additional Information
* cordova-plugin-code-push version: **1.11.10**
* List of installed plugins:
> code-push 2.0.4 "CodePushAcquisition"
> cordova-plugin-actionsheet 2.3.3 "ActionSheet"
> cordova-plugin-appcenter-analytics 0.1.3 "App Center Analytics for Cordova"
> cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
> cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
> cordova-plugin-camera 4.0.1 "Camera"
> cordova-plugin-code-push 1.11.10 "CodePush"
> cordova-plugin-compat 1.2.0 "Compat"
> cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
> cordova-plugin-device 1.1.6 "Device"
> cordova-plugin-dialogs 1.3.3 "Notification"
> cordova-plugin-file 6.0.1 "File"
> cordova-plugin-file-transfer 1.7.1 "File Transfer"
> cordova-plugin-geolocation 2.4.3 "Geolocation"
> cordova-plugin-globalization 1.0.7 "Globalization"
> cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
> cordova-plugin-network-information 1.3.3 "Network Information"
> cordova-plugin-splashscreen 4.0.3 "Splashscreen"
> cordova-plugin-statusbar 2.2.3 "StatusBar"
> cordova-plugin-vibration 2.1.5 "Vibration"
> cordova-plugin-whitelist 1.3.2 "Whitelist"
> cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
> cordova-sqlite-storage 2.1.1 "Cordova sqlite storage plugin"
> ionic-plugin-keyboard 2.2.1 "Keyboard"
> phonegap-plugin-barcodescanner 7.0.1 "BarcodeScanner"
> uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"

* Cordova version: **7.1.0**
* iOS/Android/Windows version: **android 6.3.0**
* Does this reproduce on a debug build or release build? **Release**

**Comment by alexandergoncharov** [comment]
Hi @ButchMonkey ,
Thanks for reporting!

Unfortunately this is hard to understand the reason of issue by just one Error log. Do you have some other logs before this issue? I need it to understand in which state of CodePush this issue was occurred.

Also, would be great if you will provide CodePush configuration.

Please let me know if you have any questions.

Thanks,
Alexander

**Comment by ButchMonkey** [comment]
We currently haven't found a way to replicate the issue but will be looking into it this week.

**Comment by alexandergoncharov** [comment]
Good. Thanks. Please let me know when you have more info about this issue.

**Comment by alexandergoncharov** [comment]
Hi @ButchMonkey,

Just a friendly ping about info if you have. =)

**Comment by alexandergoncharov** [comment]
Hi @ButchMonkey ,

I'm going to close this issue as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
