### ISSUE TITLE
Differential updates not working

### ISSUE THREAD

**Issue by c-mendoza** [Microsoft/cordova-plugin-code-push#441]
### Description

I have a Cordova app that has about 300MB of sounds. Whenever I publish a CodePush release the app successfully updates, but it downloads the complete 300MB+ package every time, no matter if it was just a single js file that changed. Is this the expected behavior, or is the download only supposed to be the files that changed?

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

### Additional Information

* cordova-plugin-code-push version: latest
* List of installed plugins:
code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-code-push 1.11.12 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-exit 1.0.2 "Exit"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.41 "CDVBackgroundGeolocation"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

* Cordova version: 8.0.0
* iOS: 4.5.5 / 11.4.1
* Does this reproduce on a debug build or release build? Only tried on debug
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by alexandergoncharov** [comment]
Hi @c-mendoza ,
Thanks for reporting!

Yeah, first update have to be full because for now it isn't possible to merge CodePush update with binary files. But all other updates should be diff(download just changed files).
You said that your app download full update every time. It is strange.
Could you please share you logs for first and second updates?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @c-mendoza ,

I'm going to close this issue as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
