### ISSUE TITLE
[CodePush] An update is available, but it is being ignored due to have been previously rolled back. cordova.js:1732

### ISSUE THREAD

**Issue by peymancyb** [Microsoft/cordova-plugin-code-push#445]
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.]

I have followed the instruction and i am pretty sure that i did not lost any steps in the instruction. after releasing the new update , it says that application has been updated and it will be replaced after restarting the application , after restarting application i am getting a white screen after relaunching the app again i get this message which says `[CodePush] An update is available, but it is being ignored due to have been previously rolled back.`

**Comment by alexandergoncharov** [comment]
Hi @peymancyb ,
Thanks for reporting!

It is mean that you have some issue in release. In this case  CodePush make rollback. For more info please check 3rd paragraph of this docs: https://github.com/Microsoft/cordova-plugin-code-push#how-does-it-work

Could you please share additional info:
* Platform(Cordova/PhoneGap/Ionic)
* User platform(Android/Ios)
* Logs during update
* Installed plugins(`cordova plugin ls`)
* Dummy project with reproducing reprosteps

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @peymancyb ,

Could you please share your dummy project?
I would like to test it.

**Comment by peymancyb** [comment]
Yes sure
here is the link
[https://drive.google.com/drive/folders/1CumYFbr_cbk--JqoGbgxcVRP_l4KpbzI?usp=sharing](url)

**Comment by alexandergoncharov** [comment]
Hi @peymancyb,
Thanks for dummy project. But unfortunately I can't run it. I have this issue during run `cordova build ios`: 
![image](https://user-images.githubusercontent.com/13234108/45421715-9a9b0380-b696-11e8-8548-8b13ab6e5ece.png)

Could you please provide repro steps for your dummy project?

**Comment by alexandergoncharov** [comment]
Hi @peymancyb ,

Yeah, I added my team. Also here is error from Xcode when I try to run project: 
![image](https://user-images.githubusercontent.com/13234108/45561643-e4c7e480-b850-11e8-9d79-29e64e6789a7.png)

**Comment by alexandergoncharov** [comment]
Hi @peymancyb ,

Just a friendly ping. =)

**Comment by alexandergoncharov** [comment]
Hi @peymancyb ,

I'm going to close this issue as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by Cui-y** [comment]
> ### 描述
> [填写这个：解释你做了什么，你期望发生什么，以及实际发生了什么。此外，我们非常感谢精确的复制步骤和堆栈跟踪。]
> 
> 我遵循了指令，我很确定我没有丢失指令中的任何步骤。在发布新的更新之后，它说应用程序已经更新并且在重新启动应用程序后将被替换，重新启动应用程序后我再次重新启动应用程序后出现白屏我收到此消息说`[CodePush] An update is available, but it is being ignored due to have been previously rolled back.`

Excuse me, is the problem solved now?

**Comment by pawan-logiciel** [comment]
Hi @alexandergoncharov  I am getting this issue 

Case to reproduce
if a user has binary version 2.5.2 and I will send a code-push release then he will get that release fixes.
Now I have released a new version 2.5.3 on play store but the user didn't download it and after that, I will release another code push release for version 2.5.3 in this case 
Those users have binary version 2.5.2 they are getting rollback issue and they also did not get changes that would be pushed in code-push 2.5.2 release
