### ISSUE TITLE
Ionic/Cordova - Android - Could not get the package start page

### ISSUE THREAD

**Issue by davidemanske** [Microsoft/cordova-plugin-code-push#448]
Ionic-Cordova code push works on iOS but fails on Android with the following 'Could not get the package start page error'. The iOS app, as a separate app in the AppCenter, but same codebase, works, but the Android app fails with no start page. When I download the deployments for each OS and open as zip, it has the Android app nested in a www folder, not sure that's supposed to be nested.

[app-scripts] [10:45:33]  console.error: [CodePush] Preinstall failure. Could not get the package start page
[app-scripts] [10:45:33]  console.error: [CodePush] An error has occured while installing the package. Could not get the package start
[app-scripts]             page. StackTrace: Error: An error has occured while installing the package. Could not get the package start
[app-scripts]             page at preInstallFailure
[app-scripts]             (http://192.168.1.13:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41) at
[app-scripts]             Object.callbackFromNative (http://192.168.1.13:8100/cordova.js:293:52) at processMessage
[app-scripts]             (http://192.168.1.13:8100/cordova.js:1114:17) at processMessages
[app-scripts]             (http://192.168.1.13:8100/cordova.js:1137:9) at t.invoke
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:14976) at r.run
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:10143) at http://192.168.1.13:8100/build/polyfills.js:3:20242
[app-scripts]             at t.invokeTask (http://192.168.1.13:8100/build/polyfills.js:3:15660) at r.runTask
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:10834) at o
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:7894)
[app-scripts] [10:45:33]  console.error: [CodePush] An error occurred during sync. An error has occured while installing the package.
[app-scripts]             Could not get the package start page. StackTrace: Error: An error has occured while installing the package.
[app-scripts]             Could not get the package start page at preInstallFailure
[app-scripts]             (http://192.168.1.13:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41) at
[app-scripts]             Object.callbackFromNative (http://192.168.1.13:8100/cordova.js:293:52) at processMessage
[app-scripts]             (http://192.168.1.13:8100/cordova.js:1114:17) at processMessages
[app-scripts]             (http://192.168.1.13:8100/cordova.js:1137:9) at t.invoke
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:14976) at r.run
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:10143) at http://192.168.1.13:8100/build/polyfills.js:3:20242
[app-scripts]             at t.invokeTask (http://192.168.1.13:8100/build/polyfills.js:3:15660) at r.runTask
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:10834) at o
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:7894)
[app-scripts] [10:45:33]  console.error: Unhandled Promise rejection: An error has occured while installing the package. Could not get
[app-scripts]             the package start page ; Zone: <root> ; Task: Promise.then ; Value: [object Object] Error: An error has
[app-scripts]             occured while installing the package. Could not get the package start page at preInstallFailure
[app-scripts]             (http://192.168.1.13:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41) at
[app-scripts]             Object.callbackFromNative (http://192.168.1.13:8100/cordova.js:293:52) at processMessage
[app-scripts]             (http://192.168.1.13:8100/cordova.js:1114:17) at processMessages
[app-scripts]             (http://192.168.1.13:8100/cordova.js:1137:9) at t.invoke
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:14976) at r.run
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:10143) at http://192.168.1.13:8100/build/polyfills.js:3:20242
[app-scripts]             at t.invokeTask (http://192.168.1.13:8100/build/polyfills.js:3:15660) at r.runTask
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:10834) at o
[app-scripts]             (http://192.168.1.13:8100/build/polyfills.js:3:7894)
[app-scripts] [10:45:33]  console.log: Error in Error callbackId: CodePush1695529557 : Error: An error has occured while installing
[app-scripts]             the package. Could not get the package start page

### Reproduction

Release a new release build to the Android app setup in code push.
appcenter codepush release-cordova -a org/app -d Production -m

### Additional Information

This problem also occurs on the physical device as well as the simulator.
Ionic:

   ionic (Ionic CLI)  : 4.1.1 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 23 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.9.2 
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

**App Plugins**

code-push 2.0.6 "CodePushAcquisition"
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appcenter-analytics 0.1.8 "App Center Analytics for Cordova"
cordova-plugin-appcenter-push 0.1.8 "App Center Push for Cordova"
cordova-plugin-appcenter-shared 0.1.8 "App Center shared code for Cordova"
cordova-plugin-code-push 1.11.12 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-push 2.2.3 "PushPlugin"

** Update
I did get the deployments working when I changed from release-cordova to just release and specified the output directory of -c ./platforms/android/app/build/intermediates/assets/release/www

**Comment by alexandergoncharov** [comment]
Hi @davidemanske ,
Thanks for reporting!

As you fixed your issue with just `release` command(not `release-cordova`) it looks like cli issue. 
Unfortunately I can't reproduce your issue.
Could you please provide provide dummy project with repro steps? I would like to reproduce it and debug.

**Comment by alexandergoncharov** [comment]
Hi @davidemanske ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by gaurav112** [comment]
I have the same issue. the debug app updates perfectly, but the production app gives me this error. and no way to test on production
