### ISSUE TITLE
Any plans to support capacitor?

### ISSUE THREAD

**Issue by vially** [Microsoft/cordova-plugin-code-push#450]
### Description

I would like to start a discussion regarding the possibility to add `code-push` support to [capacitor](https://capacitor.ionicframework.com/)? I understand that this may not be the right place to ask this question because this repository is for `cordova`, but I think `capacitor` and `cordova` are similiar enough that it might make sense to start a discussion in here.

### Background

We're currently in the process of migrating an app from `cordova` to `capacitor` and the lack of support for `code-push` in `capacitor` is one of our blocking issues.

Our short-term plan is to fork `cordova-plugin-code-push` and replace all the `cordova` plugin calls with their `capacitor` equivalents. We [already started](https://github.com/areo/cordova-plugin-code-push/commit/77be71f2640a6e800a9559c7f02902c5eb3065c7) going down this path. But we've just got started and it's already obvious that our fork will diverge pretty quickly from upstream which will make it hard to keep our fork in sync (and will make it harder to try to upstream our work).

I would like to start a discussion about this and see if you guys have any interest in supporting `capacitor`, or do you think it would be better to leave this to the community to figure it out?

And if you do have any interest in supporting it, do you think it makes sense to have separate plugins (and repositories) for `cordova` and `capacitor`? Or would it be preferable to have one plugin which delegates the underlying platform calls to a library (which doesn't exist yet) which abstracts away the differences between `cordova` and `capacitor`?

Another approach could be to leverage the capacitor [support for cordova plugins](https://capacitor.ionicframework.com/docs/basics/cordova).

*We've tried this approach (on Android) and it didn't seem to work, but let's just suppose that it could be fixed.*

My main concern with this approach is that `code-push` relies on [cordova-plugin-file](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/) for filesystem access. And `cordova-plugin-file` overwrites the browser's `FileReader` in a backwards incompatible way which is causing all kinds of issues (related issues: [pannellum](https://github.com/mpetroff/pannellum/issues/284), [ionic-native](https://github.com/ionic-team/ionic-native/issues/505), [ionic2-app-base](https://github.com/ionic-team/ionic2-app-base/issues/126)).

So we'd really like to avoid having `cordova-plugin-file` as a dependency and that wouldn't be possible with this approach.

**Comment by Zakeelm** [comment]
Hey there! 

We're definitely keep an eye on Capacitor and will continue to do so. As of now, we don't currently have plans to support Capacitor. But, if we see this is something people are interested in we'll definitely further investigate the possibilities of supporting it in the future. 🙂

**Comment by NG-tylerholden** [comment]
@vially what did you guys end up doing? I'd like to know because I am in the same boat here wanting to make the switch to capacitor.

**Comment by vially** [comment]
@NG-tylerholden We [forked](https://github.com/areo/cordova-plugin-code-push/tree/capacitor) `cordova-plugin-code-push` and rewrote parts of it to make it compatible with capacitor, but we didn't actually finish the job as our priorities have shifted a bit in the meantime.

I would say it's around 75% done and we still plan on finishing it, we just haven't found the time to do it yet (_we could use some help for the community to finish the job though_ :wink:).

On a side note, we did migrate to capacitor and it's been a good experience so far compared to cordova. But unfortunately we lost `code-push` in the process, so we're back to old-school app store releases for now.

**Comment by richtoulouse** [comment]
@vially Are you still needing help on porting the Cordova code push plugin to Capacitor?

**Comment by vially** [comment]
Sure, any kind of help is more than welcome. We're still planning on finishing it (if someone else doesn't beat us to it), we just didn't have much time to work on it lately.

**Comment by petrtravnik** [comment]
Is there any working solution at the moment?

**Comment by digaus** [comment]
Yeah would really like to switch to capacitor foe easier including of custom native code. But currently code push is preventzing this.

**Comment by dylanvdmerwe** [comment]
Code push is also a blocker for us to move to Capacitor.

**Comment by jmellicker** [comment]
@vially I would also like to see hot code push working for Capacitor, happy to help move it forward, could you point me to your work so far?

**Comment by vially** [comment]
@jmellicker That's awesome! :+1: 

I haven't touched this code in almost a year now so I had to spend some time over the weekend to try to get up to speed on what the latest status is and what should be the next steps.

As a very high-level overview, the code-push cordova/capacitor plugin consists of three main parts:
- [1] the cross-platform javascript/typescript code
- [2] the native Android code
- [3] the native iOS code

So far, I've mostly focused on refactoring and rewriting [1] and [2]. The work on [3] hasn't been started yet.

*I think* the big chunk of work for refactoring [1] and [2] has already been done (but there are still a couple of parts missing which are *usually* marked with [TODO](https://github.com/areo/cordova-plugin-code-push/blob/cf1f0786f162abc884219508c221fd485b945d00/android/cordova-plugin-code-push/src/main/java/com/microsoft/cordova/CodePushReportingManager.java#L30) [comments](https://github.com/areo/cordova-plugin-code-push/blob/cf1f0786f162abc884219508c221fd485b945d00/www/fileUtil.ts#L70) [in](https://github.com/areo/cordova-plugin-code-push/blob/cf1f0786f162abc884219508c221fd485b945d00/www/fileUtil.ts#L75) [the](https://github.com/areo/cordova-plugin-code-push/blob/cf1f0786f162abc884219508c221fd485b945d00/www/localPackage.ts#L305) [code](https://github.com/areo/cordova-plugin-code-push/blob/cf1f0786f162abc884219508c221fd485b945d00/www/codePush.ts#L463)). So most of the remaining work is on filling these missing parts and refactoring [3] the native iOS code.

I've only taken a cursory look at the native iOS code, but I think most of the work involves rewriting [CodePush.m](https://github.com/areo/cordova-plugin-code-push/blob/cf1f0786f162abc884219508c221fd485b945d00/src/ios/CodePush.m) and [some parts](https://github.com/areo/cordova-plugin-code-push/blob/cf1f0786f162abc884219508c221fd485b945d00/src/ios/CodePushReportingManager.m#L35-L49) of [CodePushReportingManager.m](https://github.com/areo/cordova-plugin-code-push/blob/cf1f0786f162abc884219508c221fd485b945d00/src/ios/CodePushReportingManager.m) by getting rid of the Cordova calls and replacing them with their Capacitor equivalents.

However, most of the work I've mentioned so far only covers the *almost mechanical* work of refactoring the Cordova calls to Capacitor calls. Once these are done there might be some additional work required originating from underlying platform differences between Capacitor and Cordova. I'm not sure what those might be, so let's investigate once we see them.

I hope this should give you a rough overview of what the current status is. Feel free to reach out to me if you have any additional questions (either directly or by opening issues on our forked repository linked below).

Judging by the reactions in this thread and [other similar ones](https://github.com/microsoft/code-push/issues/615) it looks like there's definitely some demand for getting CodePush support in Capacitor. So I'd love if we could work together to ship this faster.


### Links to code repositories

- [cordova-plugin-code-push](https://github.com/areo/cordova-plugin-code-push/tree/capacitor)
- [capacitor-plugin-file-transfer](https://github.com/areo/capacitor-plugin-file-transfer) (Capacitor equivalent for [cordova-plugin-file-transfer](https://github.com/apache/cordova-plugin-file-transfer)). Only Android support has been implemented so far. But it looks like there's a new [capacitor-file-transfer](https://www.npmjs.com/package/capacitor-file-transfer) plugin. Maybe we could use that one instead?

**Comment by D34THWINGS** [comment]
Hey @vially! Where do you stand on your rewrite? Can we help?

**Comment by vially** [comment]
@D34THWINGS Sure, we'd love any help we can get. Unfortunately we haven't done any progress since the last update, so the last update I've posted here is still accurate.

Let me know if there's anything I can do to help you get started.

**Comment by D34THWINGS** [comment]
@vially great! Will look into it on Monday. I'll first check on the comments you left and try to work on them and if I got any questions I'll get back to you

**Comment by jmellicker** [comment]
Hi @vially I am so sorry I missed your reply here! 😭

But what is the current status? And how can we help?

**Comment by kodeine** [comment]
@vially any updates?

**Comment by TanJay** [comment]
Any updates?

**Comment by kapten96** [comment]
Does anyone know the preliminary date when this can done or any status ?

**Comment by darron1217** [comment]
@D34THWINGS  Any updates?

**Comment by sta55en** [comment]
No news?

**Comment by rizkyramadhan** [comment]
We should continue the discussion at https://github.com/microsoft/code-push/issues/615

**Comment by JishnuVinod** [comment]
@D34THWINGS  Is it possible to use Cordova code-push with capacitor? or is there any method  other than AppFlow to use code push for capacitor application. I got a docs mentioned below. but getting error when i tried( getting error when i add this 'codePush.sync()'). https://github.com/mapiacompany/capacitor-codepush#supported-capacitor-platforms
