### ISSUE TITLE
at ios 12, I install this plugin, app will close.

### ISSUE THREAD

**Issue by jevian-ma** [Microsoft/cordova-plugin-code-push#452]
My Iphone8 is ios12, I install this plugin and set config.xml
<pre>
    &nbsp; &nbsp; &lt;chcp&gt;
    &nbsp; &nbsp; &nbsp; &nbsp; &lt;auto-download enabled=&quot;true&quot; /&gt;
    &nbsp; &nbsp; &nbsp; &nbsp; &lt;auto-install enabled=&quot;true&quot; /&gt;
    &nbsp; &nbsp; &nbsp; &nbsp; &lt;config-file url=&quot;https://******/dist/chcp.json&quot; /&gt;
    &nbsp; &nbsp; &lt;/chcp&gt;
</pre>
and set cordova-hcp.json
<pre>
{
    "update": "now",
    "content_url": "https://******/dist"
}
</pre>
but ios can't work, open app then close, android is ok.

ios version 12
cordova version 8.0.0（ios prj version 4.5.5）
mac os version 10.13.6

**Comment by alexandergoncharov** [comment]
Hi @jevian-ma ,
Thanks for reporting!

Could you please logs during update and code-push configuration?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @jevian-ma ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
