### ISSUE TITLE
Noting return after CHECKING_FOR_UPDATE

### ISSUE THREAD

**Issue by coooooof** [Microsoft/cordova-plugin-code-push#455]
### Description

[FILL THIS OUT: the normal update process is : 1, CHECKING_FOR_UPDATE . 2, DOWNLOADING_PACKAGE,3,INSTALLING_UPDATE.
but the  situation I encountered was : I build an android and install it. then I do "code-push release-cordova testPush-Android android" .  the first time check update is fine. And I add some code like <p>test</p> in html file, build and release-cordova again. the console log only show CHECKING_FOR_UPDATE, then waiting for a long time but nothing continue.  I am sure I put the right deployment key and successfully released an update containing the "my directory\www"  directory to the "Staging" deployment of the "testPush-Android" app. 

![image](https://user-images.githubusercontent.com/10432597/46916391-97c06500-cfec-11e8-84d7-a950f8c2a97b.png)
]

### Reproduction

[FILL THIS OUT: Here is my code:
    window.codePush.sync(status => {
      console.log(" status .... " , status);
      switch (status) {
        case SyncStatus.CHECKING_FOR_UPDATE: 
          break;
        case SyncStatus.UP_TO_DATE: 
          break;
        case SyncStatus.DOWNLOADING_PACKAGE: 
          break;
        case SyncStatus.ERROR: 
          break;
      }
    }, { 
    installMode: InstallMode.IMMEDIATE,
    mandatoryInstallMode: InstallMode.IMMEDIATE
  });
    

### Additional Information

* cordova-plugin-code-push version:  1.11.13
* List of installed plugins:

![image](https://user-images.githubusercontent.com/10432597/46916442-980d3000-cfed-11e8-97ed-b0d884512f4d.png)

* Cordova version:8.1.1
* iOS/Android/Windows version: android 6.4.0
* Does this reproduce on a debug build or release build?  both debug build and release build has the save problem
* Does this reproduce on a simulator, or only on a physical device?  on a really android phone.

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @coooooof ,
Thanks for reporting!

`CHECKING_FOR_UPDATE` status can be stuck by bad connection. 
Could you please check your device connection?

If it was not helpful please provide dummy project with reproducing issue and detailed repro steps?

Thanks,
Alexander

**Comment by coooooof** [comment]
if it's because of network . won't be happen every time.
but in my project. the log show the same situation each time and I am sure device connection is fine. 
The first time when install my app, the log show code push precess fine.  
![image](https://user-images.githubusercontent.com/10432597/47265470-d4dfa680-d55a-11e8-86ed-c1de9158a111.png)

when downloading and isntalling update, the app will restart . then the log show "5" . for the correct situation, it will return 0 after 5. because it is the newest version. but in my situation, it return nothing. 
I can send files to you if you have time.  How to solve this problem puzzles me.
![image](https://user-images.githubusercontent.com/10432597/47265488-33a52000-d55b-11e8-9535-f00e29ac69a4.png)

**Comment by alexandergoncharov** [comment]
@coooooof, yeah, it would be great if you provide dummy project with reproducing issue and detailed reporsteps.

**Comment by coooooof** [comment]
Because of the whole project is too big to upload, so I delete most of the files and keep the key file .

please start a new project, and copy my project into your new project . then npm install module and add android@6.4.0 platform . 

replace the CodePushDeploymentKey in config.xml. 

please don't delete files in pages.  My project  has more documents .

when you can build success. and code-push release-cordova app android success . install the apk and check log. 
then change add something in home.html , after build and release , open app and check log again, you will see the console show  check updating but nothing return.

 
[MMEarnPro.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/2518111/MMEarnPro.zip)

**Comment by coooooof** [comment]
Hello. Is there any progress ？

**Comment by alexandergoncharov** [comment]
Hi @coooooof ,

Sorry for this delay but it is in queue because we have compatibility issue with new Ionic.
I'll keep you in touch.

**Comment by alexandergoncharov** [comment]
Hi @coooooof ,
Sorry for delay.

I downloaded your files, created new project with `ionic start testAppName blank`, replaced with your files, `npm install`, tried to build android with `ionic cordova build android` command but got next issue: 
![image](https://user-images.githubusercontent.com/13234108/48486864-b1dca580-e82d-11e8-80b2-4d17de0f125c.png)

How can I fix it or could you please provide other project? Possible just add repo with this code.

**Comment by coooooof** [comment]
log show out of memory.

try bellow:

node --max-old-space-size=4096 /usr/local/bin/ionic cordova build android --prod

or

sudo ionic cordova build android --aot --minifyjs --minifycss

or please search how to solve out of memory.  all solution I can find is chinese .

**Comment by alexandergoncharov** [comment]
Hi @coooooof ,
Sorry for delay.

I tried your approach but attempts were unsuccessful.
Do you have the same behaviour or you have  successfully build?

**Comment by alexandergoncharov** [comment]
Hi @coooooof,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions or resolve issue with build of your dummy project.

Thanks,
Alexander
