### ISSUE TITLE
Update not working if version contains no dots

### ISSUE THREAD

**Issue by Steffaan** [Microsoft/cordova-plugin-code-push#457]
### Description

The binary version of our app on iOS doesn't include any dots, which prevents the app from being updated. This is very annoying since codepush does show the versions correctly at the analytics page, but won't update the app. I am forced to use Target: * to update the apps now, which prevents me from targeting different versions of our app.

### Reproduction

**Case 1:** _(working)_
- Create App (either iOS or Android) with Binary version 1.0.0
- Publish update with codepush targeting 1.0.0 or higher
- Update works!

**Case 2:** _(NOT working)_
- Create App (either iOS or Android) with Binary version 100
- Publish update with codepush to target 100 or higher (^100)
- App ALWAYS says up-to-date, update not working.
- App never gets any updates, no matter how many times u try.

**Temporary fix we are using now for Case 2:**
- Change the target from codepush update to * instead of ^100
- App now correctly updates

### Additional Information

I understand it's a good habit to use semantic versioning, but since our app was published years ago under a binary version (112) in the App Store, it prevents us from changing it to 1.1.2 since 1 < 100.

**Comment by alexandergoncharov** [comment]
Hi @Steffaan ,
Thanks for reporting!

It is strange as `100` is valid version for semver. Could you please share your logs during update?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @Steffaan ,

I'm going to close this issue for now as I haven't heard form you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
