### ISSUE TITLE
Cannot compile modules unless the '--module' flag is provided

### ISSUE THREAD

**Issue by PatSul** [Microsoft/cordova-plugin-code-push#46]
Start a new project in visual studio with the Ionic Tabs App template.  Double-click the config.xml file, plugins tab, select Git and add the path for CodePush https://github.com/Microsoft/cordova-plugin-code-push.  Add the plug-in.  Try to run or build the project produces the following errors 

![image](https://cloud.githubusercontent.com/assets/821819/11551358/0c8b48b6-993e-11e5-94bc-70a51b8b5c2a.png)

**Comment by PatSul** [comment]
Resolved this issue by adding the following to the .jsproj file (added in both the Debug and Release sections.  <TypeScriptModuleKind>amd</TypeScriptModuleKind>

xml now reads:

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptCompileOnSaveEnabled>false</TypeScriptCompileOnSaveEnabled>
    <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
	<TypeScriptModuleKind>amd</TypeScriptModuleKind>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TypeScriptCompileOnSaveEnabled>false</TypeScriptCompileOnSaveEnabled>
    <TypeScriptRemoveComments>true</TypeScriptRemoveComments>
    <TypeScriptSourceMap>false</TypeScriptSourceMap>
	<TypeScriptModuleKind>amd</TypeScriptModuleKind>
  </PropertyGroup>

**Comment by dlebu** [comment]
@PatSul Thanks for the feedback and the fix. We are always looking into ways to improve our interoperability with developer tools. Please let us know if you have any other issues or suggestions for plugin.
