### ISSUE TITLE
How to update ionic 3 app using code push after changing ionic 3 resources (splash and icon) folder.

### ISSUE THREAD

**Issue by ismailcse11** [Microsoft/cordova-plugin-code-push#460]
### Description
How to update ionic 3 app using code push after changing ionic 3 resources (splash and icon) folder.

**Comment by alexandergoncharov** [comment]
Hi @ismailcse11 ,
Thanks for reporting!

Could you please clarify what exactly your issue with updating?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @ismailcse11 ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please fell free to reopen it if you have any questions.

Thanks,
Alexander
