### ISSUE TITLE
ionic 3: In debugging mode CodePush plugin is not installed 

### ISSUE THREAD

**Issue by ismailcse11** [Microsoft/cordova-plugin-code-push#461]
### Description

I have tried some time to install this plugin but when run "**ionic cordova run android --device -l -c**" then show below error.
**In terminal shows:** 
[app-scripts] [18:11:37]  console.warn: Ionic Native: tried calling CodePush.getCurrentPackage, but the CodePush plugin is not  installed.
[app-scripts] [18:11:37]  console.warn: Install the CodePush plugin: 'ionic cordova plugin add cordova-plugin-code-push'
[app-scripts] [18:11:37]  console.warn: Ionic Native: tried calling CodePush.checkForUpdate, but the CodePush plugin is not installed.
[app-scripts] [18:11:37]  console.warn: Install the CodePush plugin: 'ionic cordova plugin add cordova-plugin-code-push'

**in app show error:**

Runtime error
Uncaught (in promise): plugin_not_installed

### Additional Information

*** List of installed plugins:**
> cordova plugin ls
code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-advanced-http 2.0.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-code-push 1.11.13 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-googlemaps 2.4.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"

*** Cordova version:**
d:\ionic\btrc-event>ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.3.0 (C:\Users\ismail\AppData\Roaming\nvm\v8.9.4\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\ismail\AppData\Local\Android\Sdk)
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

*** Does this reproduce on a debug build or release build?** 
in my mobile android debugging mode using command "ionic cordova run android --device -l -c"
*** Does this reproduce on a simulator, or only on a physical device?** 
I am testing in real device in debugging mode.
**** in build mode using command "**ionic cordova build android --rollup --prod --release**" it's working fine.
(The more info the faster we will be able to address it!)
i am updating app to appcenter using **code-push release-cordova btrc-event-android android --targetBinaryVersion "*" -m -d "Staging" --description "Modified app"** command

**Comment by alexandergoncharov** [comment]
Hi @ismailcse11 ,
Thanks for reporting!

Could you please clarify what exactly your issue with updating?

Thanks,
Alexander

**Comment by kodeine** [comment]
when we run `ionic cordova run android -l` it listens for code changes and reloads app in device.
it says codepush not installed.

on regular without `-l` it works fine.

**Comment by kodeine** [comment]
can this be fixed?
