### ISSUE TITLE
[CodePush]  Could not unzip package-1.

### ISSUE THREAD

**Issue by Cui-y** [Microsoft/cordova-plugin-code-push#462]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description
After pushing the hot update server built by ourselves with code-push, the update prompt box pops up successfully on the client side, but when the user clicks the update button, the console reports an error：

### screenshoot
![image](https://user-images.githubusercontent.com/21211512/47967407-de5b2980-e097-11e8-8416-6c04970237e4.png)

### Additional Information

* cordova-plugin-code-push version: ^1.11.13
* List of installed plugins:
* Cordova version:8.1.2 (cordova-lib@8.1.1)
* iOS/Android/Windows version: 4.5.5/6.4.0/-

**Comment by Cui-y** [comment]
Please see that you can help me out.

**Comment by JoxC** [comment]
How you solved this ? I'm facing the same issue.

**Comment by Cui-y** [comment]
> How you solved this ? I'm facing the same issue.

Download URL has problems.
