### ISSUE TITLE
Code-Push breaks browser platform

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/cordova-plugin-code-push#463]
### Description

My app has three platforms: android, ios and browser (in browser, it's like a PWA). Same code base.
After installing and testing code-push plugin for android, I tried to build my browser version (it is only a `cordova build browser --release` and publish it to an Azure Web App).

The browser version fails to start:
```
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/localPackage.js net::ERR_ABORTED 404
exports.injectScript @ cordova.js:1535
injectIfNecessary @ cordova.js:1543
handlePluginsObject @ cordova.js:1596
(anonymous) @ cordova.js:1625
(anonymous) @ cordova.js:1545
load (async)
exports.injectScript @ cordova.js:1531
injectIfNecessary @ cordova.js:1543
exports.load @ cordova.js:1623
(anonymous) @ cordova.js:1143
setTimeout (async)
(anonymous) @ cordova.js:1142
build @ cordova.js:51
require @ cordova.js:66
(anonymous) @ cordova.js:1862
(anonymous) @ cordova.js:1864

cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/codePush.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/remotePackage.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/syncStatus.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/installMode.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/httpRequester.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/sdk.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/package.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/fileUtil.js net::ERR_ABORTED 404
cordova.js:1535 GET https://www.profixapp.com/app/plugins/cordova-plugin-code-push/bin/www/nativeAppInfo.js net::ERR_ABORTED 404
 ```

Finally, this is the final breaker:

```
cordova.js:1309 Uncaught Error: Module cordova-plugin-code-push.codePush does not exist.
    at addEntry (cordova.js:1309)
    at Object.exports.clobbers (cordova.js:1319)
    at onScriptLoadingComplete (cordova.js:1558)
    at scriptLoadedCallback (cordova.js:1591)
    at HTMLScriptElement.<anonymous> (cordova.js:1545)
```

The expected behavior is to ignore the browser platform (a common practice is to insert dummy scripts with a ```throw Error("Not implemented")```. 

My code is already ignoring codePush if ```cordova.platformId === "browser"```.

### Reproduction

Create any test project, add codepush, try to publish the browser plaftform to Azure.

### Additional Information

* cordova-plugin-code-push version: 2.0.6
* List of installed plugins:
```
code-push 2.0.6 "CodePushAcquisition"
cordova-background-geolocation 2.13.1 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-code-push 1.11.13 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 3.1.0 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"
```

* Cordova version: 8.1.2 (cordova-lib@8.1.1)
* iOS/Android/Windows version: Irrelevant
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Irrelevant

**Comment by JCKodel** [comment]
First, I create an Azure Publish Profile (it will create the .pubxml file).
Then, I add a task to it:
```
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="PreBuild.cmd" />
  </Target>
  <Target Name="PostBuild" AfterTargets="MSDeployPublish">
    <Exec Command="PostBuild.cmd" />
  </Target>
```
It's kinda hacky, but VS won't do any better =\

The PreBuild.cmd will erase the contents of my wwwroot, compile the cordova with `cordova build browser --release`, then copy the cordova's www folder into wwwroot\app.

The Visual Studio will then publish the contents of my backend along with a compiled cordova folder in the wwwroot.

The PostBuild.cmd will erase the wwwroot\app folder, so it won't be present in the project anymore.

It's kinda like a pipeline on VSTS, building and moving files along where they belong to, but done manually (for this personal project I don't have the money to pay for CI/CD, and works fine in every app I make. Except when using this plugin.

**And the problem is not really from this plugin: it's the bin folder used in the server. Contents inside a bin folder are served with a 404 in Azure. I've renamed the folder to bin2 and the JS came through.**

So, the fix, I guess, is to change the name of bin folder (app/plugins/cordova-plugin-code-push/**bin**/www/httpRequester.js)

Also, what exactly those scripts would do in a browser platform? I can't use appcenter for anything else on browser because it starts to ask for permission to use file storage, for example. This is unacceptable =\ The browser, in this case, should be transparent. Analytics and Error Logging should be non intrusive (definitely not asking for file storage quota).

With the ascension of Capacitor (the Ionic Cordova alternative, focused on PWA), it's more likely for you to encounter more and more hybrid projects (PWA + Cordova in one code-base).

My current solution is to use this tiny node script after I compile the cordova browser version:

```
const replace = require("replace-in-file");

const options =
{
	files: "./platforms/browser/www/cordova_plugins.js",
	from: /"cordova-plugin-code-push": "\d.\d\d.\d\d",/g,
	to: "",
};

const changes = replace.sync(options);

console.log("Modified files:", changes.join(", "));
```

It strips out the cordova-plugin-code-push from the cordova's plugin list, so it won't call those scripts neither try to execute the module (which does not exist).

**Comment by alexandergoncharov** [comment]
@JCKodel so, if renaming of bin folder helps you it defiantly means that issue isn't in CodePush plugin. About this you should ask in Azure support.

Yeah, CodePush require permissions for using storage as CodePush use it for keeping downloaded releases.

Unfortunately we don't support browsers as platform.

About Capacitor: Yeah, we are investigating and discussing about it. But I can't provide some accurate information for now unfortunately.

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by JCKodel** [comment]
@alexandergoncharov : 

> @JCKodel so, if renaming of bin folder helps you it defiantly means that issue isn't in CodePush plugin. 

Not exactly. There should NOT be any .js file for code-push in browser platform (the bin folder is just another issue - it's not about bug on azure, is about best-practice (and knowing that many web servers will block download from bin folders)).

Anyway, if browser platform is not supported, nothing has to be done (if someone uses browser platform for pwa, their bad).

My final solution was to stop using cordova for plugin management (now I'm using plugman - the behavior is similar to Capacitor), so my browser platform no longer have any AppCenter plugins installed.

**Comment by alexandergoncharov** [comment]
Yeah, I see, I see.
So, I'll mark browser supporting as feature request and discuss it with team.
Thanks for this.

It is sad but I understand your choice. Thanks for interesting AppCenter plugins!

So, I'm going to close this issue for now but please feel free to reopen it is you have any questions.

Thanks,
Alexander
