### ISSUE TITLE
Update error: "Could not unzip package" when not first time update

### ISSUE THREAD

**Issue by JoxC** [Microsoft/cordova-plugin-code-push#464]
### Description
When installing the downloaded package, the error "Could not unzip package ..."  always occurs except the first update after installation.

> [CodePush]  Could not unzip package-1. StackTrace: Error: Could not unzip package-1
>     at newPackageUnzipped (file:///data/data/com.xxx.xx/files/codepush/deploy/versions/60cfeeb5f29…4077819/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:49:50)
>     at fail (file:///data/data/com.xxx.xx/files/codepush/deploy/versions/60cfeeb5f29…01e26f90b31708a2294a83a4077819/www/plugins/cordova-plugin-zip/zip.js:24:13)
>     at Object.callbackFromNative (file:///data/data/com.xxx.xx/files/codepush/deploy/versions/60cfeeb5f2908a786678feaf22eb32cc0f01e26f90b31708a2294a83a4077819/www/cordova.js:296:52)
> 

After lots of digging, I found that the downloaded zip file stored at "cdvfile://localhost/files/codepush/download/update.zip" is a corrupted file which contains all the  downloaded data of every time update, meaning the last time update file is neither removed before the next update nor overwritten by the next downloaded update file. Every time the new downloaded update data is appended to the same file which cannot be unzipped correctly later.

### Additional Information

* cordova-plugin-code-push version: 1.11.13
* List of installed plugins:
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
...
* Cordova version: 8.0.0
* iOS/Android/Windows version: -/5.1.1/-
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by alexandergoncharov** [comment]
Hi @JoxC ,
Thanks for reporting!

It is strange issue.
Could you please provide dummy project with reproducing issue? I would like to debug it.

Thanks,
Alexander

**Comment by JoxC** [comment]
After I clear all the deployment and re-install the plugin, the issue no longer exists! Thanks for your concern. @alexandergoncharov

**Comment by alexandergoncharov** [comment]
Great! Thanks for keeping us in touch!
