### ISSUE TITLE
About rollback problem

### ISSUE THREAD

**Issue by Cui-y** [Microsoft/cordova-plugin-code-push#466]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description
The project is built on Cordova, and the hot update server is built by itself.

Now there is a strange problem. Under the Android platform, there is no problem with the application hot update, everything is normal.

Under the IOS platform, the simulator is normally hot update, but there are anomalies in the real machine: the first time the application enters, the update button is clicked, the progress bar is read, but the content remains unchanged. When the application closes and the second time the application opens, it is still prompted to update, but when the update button is clicked, the console will prompt the update to roll back and advance. The degree bar is not reading.

### Reproduction
Is it related to the secure domain name?

### Additional Information 

* cordova-plugin-code-push version:  @latest
* List of installed plugins:
     "code-push": "2.0.6",
    "cordova-android": "6.4.0",
    "cordova-ios": "4.5.5",
    "cordova-plugin-camera": "4.0.3",
    "cordova-plugin-code-push": "1.11.13",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-dialogs": "2.0.1",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-file-transfer": "^1.6.3",
    "cordova-plugin-image-picker": "1.1.3",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-wkwebview-engine": "1.1.4",
    "cordova-plugin-wkwebview-file-xhr": "2.1.1",
    "cordova-plugin-zip": "^3.1.0"
* Cordova version: 8.1.2
* iOS/Android/Windows version: 4.5.5/6.4.0/-
* Does this reproduce on a debug build or release build?release
* Does this reproduce on a simulator, or only on a physical device?physical device

**Comment by Cui-y** [comment]
First, declare that the front-end view is built by the Vue framework.

Not much to say, direct supplementary code.

First, call the `notify Application Ready'method during the mounted life cycle, and then check for new update information.

The code is as follows
```js
mounted() {
codePush.notifyApplicationReady()

codePush.checkForUpdate((update) => {
        console.log('-------' + update)
        // If there is an update, the update prompt box is prompted to prompt the user to update the app operation.
        if (update) {
          this.modalVisible = true
          let updateDescription = update.description
          if (updateDescription) {
            this.updateInfoList = updateDescription.split(',')
          }
          // Whether to force updates, temporarily unprocessed
          this.isMandatory = update.isMandatory
        }
      }, (err) => {
        alert(err)
      })
}

```

Then when an update is checked out, an update prompt box pops up to the user. When the user clicks the update button immediately, the `sync'method is triggered.

```js
methods: {
// Immediate update
    _immediateUpdate() {
      this.immediateUpdate = true
      // Start sync thermal update app
      codePush.sync(
        this.codePushStatusDidChange,
        {
          updateDialog: false,
          installMode: InstallMode.IMMEDIATE,
          mandatoryInstallMode: InstallMode.IMMEDIATE
        },
        this.downloadProgress
      )
    },

    // Download progress
    downloadProgress(downloadProgress) {
      if (this.immediateUpdate && downloadProgress) {
        let currProgress = parseFloat(downloadProgress.receivedBytes / downloadProgress.totalBytes).toFixed(2)
        if(currProgress >= 1) {
          // After the update is downloaded, restart the application.
          // codePush.restartApplication()
          this.modalVisible = false
        } else {
          // Schedule assignment
          this.currentPercentage = Math.ceil(currProgress * 100)
        }
      }
    }
}

```

Thank you first.

**Comment by alexandergoncharov** [comment]
Hi @Cui-y ,
Thanks for reporting!

Could you please also share logs during update?

**Comment by Cui-y** [comment]
@alexandergoncharov 
Thank you for your timely reply.

Sorry, wait a minute. I'm trying an old plug-in version @1.8.2-beta again. I'll post the log later.

**Comment by Cui-y** [comment]
Thank you for your timely reply.

Sorry, wait a minute. I'm trying an old plug-in version @1.8.2-beta again. I'll post the log later.

**Comment by Cui-y** [comment]
![image](https://user-images.githubusercontent.com/21211512/48252967-1e782e80-e441-11e8-8a04-36b928f71ede.png)

**Comment by alexandergoncharov** [comment]
Hi @Cui-y ,
Thanks for this history. But I don't see any rollbacks in your history.
Also, could you please clarify can you reproduce your rollback on your device?

**Comment by Cui-y** [comment]
Hello, thank you for your reply.

The real machine can be tested for rollback, and the simulator is updated normally.

Information on the real machine:
`An update is available, but it is being ignored due to having been previously rolled back`

I can give you a screenshot later.

**Comment by alexandergoncharov** [comment]
@Cui-y , Yeah, it is mean that update already rolled back and all other update should net get update as CodePush think that it is "broken" release.

So, could you please provide logs during update after which release is rolled back?

**Comment by Cui-y** [comment]
@alexandergoncharov  Hello,Thank you for your reply.
I don't quite understand the reason for rollback. Why is my version broken? To my surprise, my test on the simulator is updateable. I test on the real machine. When I first open the app, the content is not replaced by clicking on the update. But the console has shown that the download and installation is complete, but when I hit the second time. The update will still be prompted when app is opened, but the console will roll back and the page will be stuck at the rest of the scroll bar.

**Comment by Cui-y** [comment]
> @Cui-y , Yeah, it is mean that update already rolled back and all other update should net get update as CodePush think that it is "broken" release.
> 
> So, could you please provide logs during update after which release is rolled back?

Isn't this log the screenshot above?

**Comment by aiba** [comment]
@Cui-y You're using `cordova-plugin-wkwebview-engine` so I suspect your issue is caused by #424.  You could confirm this by seeing if your XCode logs contain a `kCFErrorDomainCFNetwork`.

**Comment by Cui-y** [comment]
@aiba  Thank you for your advice. I'm going to try it. Thank you very much.

**Comment by Cui-y** [comment]
@alexandergoncharov   Will it have anything to do with this?

Error：
![image](https://user-images.githubusercontent.com/21211512/48309170-2229c380-e5af-11e8-88a8-60e1b957f381.png)

**Comment by alexandergoncharov** [comment]
@Cui-y , Unfortunately I can't understand the reason of rollbacks by this info.
Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by alexandergoncharov** [comment]
Hi @Cui-y ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
