### ISSUE TITLE
iOS Problem : NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects

### ISSUE THREAD

**Issue by lcsdms** [Microsoft/cordova-plugin-code-push#469]
### Description
Hi! I have a project that is built using phonegap, and the development folder structure isn't in the cordova default layout, so we can't use the cordova prepare commands or specific code push cordova commands, since we don't even build it locally.

Since I can't build the project in the correct folder structure for the platforms locally, we use a custom built script that puts everything that's needed by phonegap on it's folder structure, and upload and build on phonegap, and it handles all the platform specific build configs.

After it's built, I download the .ipa and the .apk, unzip the files, and upload the folders to code push.

**The Problem**
On Android it seems to work correctly, but on iOS after the update, the app crashes, and I can't open it anymore. 

Here's the steps I'm using on each platform for updating the apps:
- js:
```
  document.addEventListener('resume', function(){
             window.codePush.sync(null, { updateDialog: true, installMode: window.InstallMode.IMMEDIATE });
         }, false);
```
- Android:
```bash
 mv app.apk app.zip
 unzip app.zip
 appcenter codepush release -a <owner>/<appName> -c assets/www/ -t '*' -d Developmen
```
After testing on the device it works without problems.

- IOS:
Here's where I think the problem is. I'm not sure of which folder I should upload here. The structure is very different from android.

```
unzip app.ipa
cd Payload/myApp.app/
appcenter codepush release -a <owner>/<appName> -c www/ -t '*' -d Development
```    
After uploading, the update is verified, downloaded , and seems to be installed. After that the app doesn't work anymore, and doesnt even rollback.

Here's the logs I was able to catch, since it seems to be a native problem, and the console from the safari is closed unexpectedly:

```
default	17:11:07.570617 -0200	My App	[CodePush] Installing update
default	17:11:13.518262 -0200	My App	[CodePush] Applying full update
default	17:11:13.689147 -0200	My App	CRASH: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[4] Stack Trace: (
	0   CoreFoundation                      0x1ce5fb55 <redacted> + 152
	1   libobjc.A.dylib                     0x1c0e7067 objc_exception_throw + 38
	2   CoreFoundation                      0x1cd728cf <redacted> + 306
	3   CoreFoundation                      0x1cd7ca01 <redacted> + 44
	4   My App                  			0x00136e21 My App + 220705
	5   My App                  			0x00135e95 My App + 216725
	6   libdispatch.dylib                   0x1c52d797 <redacted> + 10
	7   libdispatch.dylib                   0x1c53ab1d <redacted> + 536
	8   libdispatch.dylib                   0x1c53c1b5 <redacted> + 326
	9   libdispatch.dylib                   0x1c53c00f <redacted> + 106
	10  libsystem_pthread.dylib             0x1c6e287d _pthread_wqthread + 1040
	11  libsystem_pthread.dylib             0x1c6e245c start_wqthread + 8
)
default	17:11:13.739726 -0200	My App	*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[4]'
*** First throw call stack:
(0x1ce5fb3d 0x1c0e7067 0x1cd728cf 0x1cd7ca01 0x136e21 0x135e95 0x1c52d797 0x1c53ab1d 0x1c53c1b5 0x1c53c00f 0x1c6e287d 0x1c6e245c)
```

### Additional Information

* cordova-plugin-code-push version:  1.11.13
* List of installed plugins:
```
<plugin name="cordova-android-play-services-gradle-release" spec="2.0.0" />
<plugin name="cordova-android-support-gradle-release" spec="2.0.1" />
<plugin name="cordova-plugin-app-version" spec="0.1.9" />
<plugin name="cordova-plugin-buildinfo" spec="2.0.2" />
<plugin name="cordova-plugin-code-push" spec="1.11.13" />
<plugin name="cordova-plugin-customurlscheme" spec="4.3.0" />
<plugin name="cordova-plugin-device" spec="2.0.2" />
<plugin name="cordova-plugin-file" spec="6.0.1" />
<plugin name="cordova-plugin-file-transfer" spec="1.7.1" />
<plugin name="cordova-plugin-geolocation" spec="4.0.1" />
<plugin name="cordova-plugin-inappbrowser" spec="3.0.0" />
<plugin name="cordova-plugin-mauron85-background-geolocation" spec="3.0.0-alpha.47" />
<plugin name="cordova-plugin-network-information" spec="2.0.1" />
<plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
<plugin name="cordova-plugin-statusbar" spec="2.4.2" />
<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
<plugin name="cordova-plugin-zip" spec="3.1.0" />
<plugin name="cordova.plugins.diagnostic" spec="4.0.10" />
<plugin name="onesignal-cordova-plugin" spec="2.4.5" />
<plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" spec="4.2.2" />
```

* iOS/Android/Windows version:
- Android : 8.1.0
- iOS: 10
* Does this reproduce on a debug build or release build?
- Debug only, not tested on release yet.
* Does this reproduce on a simulator, or only on a physical device?
- Only tested on physical devices until now, if the procedures are correct will test on simulator as well.

**Comment by alexandergoncharov** [comment]
Hi @lcsdms ,
Thanks for reporting!

Interesting approach. I'm not sure that this approach should works correct but I'll test it.
Could you please clarify have you any chance to download build folder, not ipa/apk?

Thanks,
Alexander

**Comment by lcsdms** [comment]
Hi @alexandergoncharov , thanks for the response!

I can download the source files,but from the looks of it, it's the same that it's uploaded to the phonegap server.

It's in this folder structure:
```
  |-assets
   |---android
   |---ios
   |-res
   |---icons
   |-----android
   |-----ios
   |-----windows
   |-----wp8
   |---screens
   |-----android
   |-----ios
   |-----windows
   |-----wp8
   |-static
   |---css
   |---js
   |---media
   |-store
   |---icons
   |---screens
```

Other than that, I can only download the .apk or the .ipa.
I've checked the logs and phonegap takes this folder structure and builds it into the specific platform.
I've attached a example log here https://pastebin.com/HuRB9xbK

**Comment by alexandergoncharov** [comment]
Hi @lcsdms,
Sorry for delay.

Could you please share your `.ipa` downloaded from Phonegap and source files? I would like to investigate it more closer if it is possible to use for releasing CodePush update.

**Comment by lcsdms** [comment]
> Hi @lcsdms,
> Sorry for delay.
> 
> Could you please share your `.ipa` downloaded from Phonegap and source files? I would like to investigate it more closer if it is possible to use for releasing CodePush update.

Hi @alexandergoncharov, before submitting the files, I made some tests and ended up finding the cause of the problem.

Believe or not, it looks like it was a missing content tag, in my config.xml
https://cordova.apache.org/docs/en/latest/config_ref/#content

Here's what I've done to pinpoint the problem:

1. Created a new phonegap app with create phonegap app, and moved all my files to the same cordova / phonegap structure.
2. The problem persisted.
3. Created a new phonegap app from scratch without my code, and testing with code push worked.
4. Configured the cordova ios platform on Xcode and tried debugging, it showed the logs with the specific method name and line that triggered the exception.

The problem happened on the method getStartPageURLForLocalPackage:467 :
```NSArray* realLocationArray = @[libraryLocation, @"NoCloud", packageLocation, @"www", startPage];```

Looks the method getConfigLaunchUrl was returning a nil value because it couldn't find the tag in my project.

After putting the tag in my config.xml, the updates worked correctly:
```<content src="index.html" />```

Here's the logs with the error and xcode print screen:

https://drive.google.com/open?id=1Fj4eZkdGXaY0UE7AspUuOxyXXpAdgsTr

Thank you for your time !

**Comment by lcsdms** [comment]
Closed the issue by accident

**Comment by alexandergoncharov** [comment]
@lcsdms , Sorry for delay.

Oh, so, your issue fixed by adding content tag?

**Comment by alexandergoncharov** [comment]
Hi @lcsdms,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately. But it looks like your issue was fixed :)
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
