### ISSUE TITLE
codepush release - platform type parameter (Unknown arguments)

### ISSUE THREAD

**Issue by l3ender** [Microsoft/cordova-plugin-code-push#487]
### Description

Following the documentation in [this repo's readme](https://github.com/Microsoft/cordova-plugin-code-push/blob/79f3635a8711c767d6067ca18d8ca516df23e716/README.md#releasing-updates) and on [the Microsoft website](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#releasing-updates-cordova), it appears that the "platform parameter" part of the `release-cordova` command is incorrect and/or not applicable. When trying to use it, an error is thrown about "Unknown arguments".
```
-> appcenter codepush release-cordova -a myorg/myapp-android android

Error: Command 'codepush release-cordova -a myorg/myapp-android android' failed with exception "Unknown arguments: android"
```

However, running the same command without the `android` platform succeeds:
```
-> appcenter codepush release-cordova -a myorg/myapp-android
Running "cordova prepare" command:

No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform android
Android Studio project detected
Checking config.xml for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at /Users/ross/repos/myapp/platforms/android/app/src/main/res/xml/config.xml
Merging project's config.xml into platform-specific android config.xml
Merging and updating files from [www, platforms/android/platform_www] to platforms/android/app/src/main/assets/www
Wrote out android application name "myorg" to /Users/ross/repos/myapp/platforms/android/app/src/main/res/values/strings.xml
Wrote out Android package name "org.myorg.myapp" to /Users/ross/repos/myapp/platforms/android/app/src/main/java/org/myorg/myapp/MainActivity.java
Updating icons at platforms/android/app/src/main/res
Updating splash screens at platforms/android/app/src/main/res
This app does not have additional resource files defined
Prepared android project successfully
No scripts found for hook "after_prepare".

Releasing update contents to CodePush:

Successfully released an update containing the "/Users/ross/repos/myapp/platforms/android/app/src/main/assets/www" directory to the "Staging" deployment of the "myapp-android" app.
```

### Additional Information

* cordova-plugin-code-push version: 1.11.16
* List of installed plugins: 
```
<plugin name="cordova-plugin-whitelist" spec="~1.3.3" />
<plugin name="cordova-plugin-statusbar" spec="~2.4.2" />
<plugin name="cordova-plugin-device" spec="~2.0.2" />
<plugin name="cordova-plugin-splashscreen" spec="~5.0.2" />
<plugin name="cordova-plugin-ionic-webview" spec="^2.0.0" />
<plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
<plugin name="cordova-plugin-touch-id" spec="3.4.0">
    <variable name="FACEID_USAGE_DESCRIPTION" value=" " />
</plugin>
<plugin name="cordova-plugin-appcenter-analytics" spec="^0.2.2" />
<plugin name="cordova-plugin-appcenter-crashes" spec="^0.2.2" />
<plugin name="cordova-plugin-code-push" spec="1.11.16" />
<plugin name="cordova-plugin-file" spec="^6.0.1" />
<plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
<plugin name="cordova-plugin-zip" spec="^3.1.0" />
<plugin name="cordova-plugin-app-version" spec="0.1.9" />
```
* Cordova version: 8.1.2 (cordova-lib@8.1.1)
* iOS/Android/Windows version: 
```
<engine name="android" spec="7.1.4" />
<engine name="ios" spec="4.5.5" />
```
* Does this reproduce on a debug build or release build? n/a
* Does this reproduce on a simulator, or only on a physical device? n/a

**Comment by yuri-kulikov** [comment]
Hi @l3ender,
Thanks for reporting!

You're right, we don't need to specify the platform when we use `appcenter codepush release-cordova`. You can find the right way to use it on other pages, for example [here](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cordova#releasing-updates) and [here](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/#cordova). This is a mistake in our docs and we will fix it as soon as possible. We appreciate your help! I will close the issue as soon as the documents are corrected.

**Comment by alexandergoncharov** [comment]
Hi @l3ender,

Docs for `appcenter` cli on Microsoft site was updated. You can check it here: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#releasing-updates-cordova

About docs on Github: There are correct command as there is described `code-push` cli. This cli require platform type during release.
You can use any of this 2 CLIs but our recommendation is using `appcenter` cli.

So, as issue was resolved and incorrect documentation was fixed I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by alexhisen** [comment]
https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#platform-parameter-1 still mentions platform.
