### ISSUE TITLE
SyncStatus.ERROR not emitted when an error is thrown

### ISSUE THREAD

**Issue by Silvest89** [Microsoft/cordova-plugin-code-push#488]
As of currently the SyncStatus.ERROR is not being emitted. The sync process just stops after an error being thrown. No further emits after CheckForUpdate
Turn on plane mode and start a CodePush app.
 
<img width="251" alt="screenshot 2019-01-05 at 13 14 27" src="https://user-images.githubusercontent.com/2388338/50724327-faa53200-10eb-11e9-8b95-10282a38f900.png">

<img width="374" alt="screenshot 2019-01-05 at 13 22 59" src="https://user-images.githubusercontent.com/2388338/50724393-0c3b0980-10ed-11e9-93e7-690f1fc8e486.png">

**Comment by alexandergoncharov** [comment]
Hi @Silvest89 ,
Thanks for reporting!

If I understand correctly your issue is that `ERROR` sync status isn't set in case if CodePush can't download update due to network.

I tested this case(set device in airplane mode and tried to update) and found that this status is set. I set `console.log` on changing status like so:

```
function (syncStatus) {
                switch (syncStatus) {
                    // Result (final) statuses
                    case SyncStatus.UPDATE_INSTALLED:
                        console.log("---SyncStatus--- UPDATE_INSTALLED");
                        break;
                    case SyncStatus.UP_TO_DATE:
                        console.log("---SyncStatus--- UP_TO_DATE.");
                        break;
                    case SyncStatus.UPDATE_IGNORED:
                        console.log("---SyncStatus--- UPDATE_IGNORED.");
                        break;
                    case SyncStatus.ERROR:
                        console.log("---SyncStatus--- ERROR");
                        break;
                    
                    // Intermediate (non final) statuses
                    case SyncStatus.CHECKING_FOR_UPDATE:
                        console.log("---SyncStatus--- CHECKING_FOR_UPDATE.");
                        break;
                    case SyncStatus.AWAITING_USER_ACTION:
                        console.log("---SyncStatus--- AWAITING_USER_ACTION.");
                        break;
                    case SyncStatus.DOWNLOADING_PACKAGE:
                        console.log("---SyncStatus--- DOWNLOADING_PACKAGE.");
                        break;
                    case SyncStatus.INSTALLING_UPDATE:
                        console.log("---SyncStatus--- INSTALLING_UPDATE");
                        break;
                }
            },
```

And please check this screenshot:
![screenshot 2019-01-11 at 19 12 39](https://user-images.githubusercontent.com/13234108/51045683-4157c800-15d5-11e9-93d9-368d7ea941b2.png)

Please let me know if I missed something

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @Silvest89,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
