### ISSUE TITLE
ios update not working properly

### ISSUE THREAD

**Issue by gurindernarang** [Microsoft/cordova-plugin-code-push#49]
In case of iOS after adding code push plugin all the cordova plugins are working on minimizing the app. Working fine on android.

**Comment by lostintangent** [comment]
Thanks for reporting your issue! Could you elaborate a little bit on the exact problem you're experiencing? Are you having trouble after installing and configuring the plugin, or are you not seeing updates being discovered/installed?

**Comment by gurindernarang** [comment]
Hey thanks for responding back,

To elaborate, we have a demo app which gives an alert on $ionicPlatform.ready(). but after installing code-push plugin that alert box comes up when i minimize/switch the app (by double tapping home button) in iOS, while the same works fine in android build.

and to provide more insight... while having app on auto reload.. we get an error like this (in console)
" deviceready has not fired after 5 seconds.Channel not fired: onFileSystemPathsReady "

**Comment by lostintangent** [comment]
Hmm, that's really strange. Could you confirm that you're running the latest version of the plugin just so we can make sure we are testing the same bits as you? Could you also confirm that you simply added the plugin before seeing this behavior? You didn't add the deployment key to be config.xml or add a call to the CodePush API in your JS code?

Additionally, if you remove the CodePush plugin from your app does this issue go away? I haven't been able to repro it unfortunately, and it would just be useful to narrow down that the CodePush plugin is in fact causing this issue.

One other thing that might be worth trying it to remove and reads the iOS platform from your app, to force all of the plugins to be updated. Sometimes there can be conflicts between plugins, their dependencies and the version of the platforms, and we've seen folks get unblocked by simply reading a platform to their app.

We'll look into this further tomorrow, but in the meantime, it would be really helpful to get a little more detail about your setup. Thanks!

**Comment by dlebu** [comment]
@gurindernarang Could you also share the iOS platform version you are using and the list of public plugins you added to the application?

**Comment by dlebu** [comment]
@gurindernarang I tried to reproduce your issue today without success. I created an ionic application that displays a dialog on `ionicPlatform.ready`. The only case when the dialog was displayed on switching to the app was immediately after an update was installed using `InstallMode.ON_NEXT_RESUME`, which is expected. Is it possible that you are using `InstallMode.ON_NEXT_RESUME` instead of `InstallMode.ON_NEXT_RESTART`? I am closing the issue for now, please feel free to continue the conversation or to reopen it if you still think something is not right with the plugin behavior.

**Comment by gurindernarang** [comment]
Sorry for such a delayed response.

The plugin is working fine, its actually my bad, was missing "*gap:*(which
is required on iOS)" and "*data:*" inside 'Content-Security-Policy' meta
tag in index.html

Now it's working fine on iOS and Android. Thanks for your concern.

**Comment by dlebu** [comment]
I updated the CSP guidelines to avoid confusion in the future. Thanks for using CodePush and please keep the feedback coming.

**Comment by gurindernarang** [comment]
Thanks.
