### ISSUE TITLE
phonegap-plugin-push stop properly working after installing code-push

### ISSUE THREAD

**Issue by iliran11** [Microsoft/cordova-plugin-code-push#493]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I have added code-push to a cordova project and plugin `phonegap-plugin-push` stopped functioning properly.

### Reproduction

install `phonegap-plugin-push` and then install `cordova-plugin-code-push`

### Additional Information

* cordova-plugin-code-push version:  1.11.17
* phonegap-plugin-push version: 2.2.3
* List of installed plugins: 25
* Cordova version: 7.1.0
* android platform version: 6.3.0

* iOS/Android/Windows version: android 8
* Does this reproduce on a debug build or release build? debug build.
* Does this reproduce on a simulator, or only on a physical device? physical device.

Before installing code , when receiving push notification, the log for logcat looks as follows:

```
01-20 19:17:30.874  8292  8312 D Push_FCMService: onMessage - from: 696696535562
01-20 19:17:30.884  8292  8312 D Push_FCMService: normalize extras
01-20 19:17:30.885  8292  8312 D Push_FCMService: key = content-available
01-20 19:17:30.885  8292  8312 D Push_FCMService: replace key content-available with content-available
01-20 19:17:30.885  8292  8312 D Push_FCMService: key = summaryText
01-20 19:17:30.885  8292  8312 D Push_FCMService: replace key summaryText with summaryText
01-20 19:17:30.886  8292  8312 D Push_FCMService: no locale found for key = summaryText, error Value There of type java.lang.String cannot be converted to JSONObject
...
```

after installing code push, whenever recieving notification, the log related to FCMService stop after one line. and there is no error. push notification does not arrive either.

`01-20 19:24:34.329  9183  9202 D Push_FCMService: onMessage - from: 696696535562`

I will gladly supply more information if needed. Thanks for any help!

**Comment by alexandergoncharov** [comment]
Hi @iliran11,
Thanks for reporting!

Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by iliran11** [comment]
Sure. however it might take me 1-2 days as i need to do some re-production steps with a new project. if you have an idea for a quick way to connect a server to FCM it would be great. @alexandergoncharov

**Comment by iliran11** [comment]
i will close this ticket for now. it doesn't reproduce on dummy project - for now. thanks!!

**Comment by gaurav-chandra** [comment]
Phonegap Push Plugin working fine before installing code-push. After installing code-push the error starts. Probably there is some conflict with code-push as appcenter has push functionality also. 

Removing codepush makes phonegap push plugin works fine.

**Comment by gaurav-chandra** [comment]
spent 4 hours and solved it.

do:
```
cordova plugin add cordova-plugin-code-push
cordova plugin add cordova-android-play-services-gradle-release
cordova platform remove android
cordova plugin remove phonegap-plugin-push
cordova plugin add phonegap-plugin-push
cordova platform add android
```

**Comment by nguyendinhdoan** [comment]
I am getting the same issue. I did debug java code and found the Exception thrown by `PushPlugin.java`
```
senderID = getStringResourceByName(GCM_DEFAULT_SENDER_ID);
```
The `getStringResourceByName()` returned `null`.
Anyone fixed this bug?
