### ISSUE TITLE
 [CodePush] Could not get binary hash.Error: Could not get binary hash. 

### ISSUE THREAD

**Issue by teuassuri2** [microsoft/cordova-plugin-code-push#494]
### Description

I am using code-push with ionic3.
I am using the CLI to send an update to my application.
code-push release codepush-xxxx ./platforms/android/assets/www/ 0.3.0 --description "Test Fortunato" -d "Production"

But the following problem happens when I'm going to open the application

![image](https://user-images.githubusercontent.com/3892493/51489557-6f809900-1d87-11e9-9363-5e3a352df634.png)

### Additional Information
Android
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.13 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-push 2.1.0 "PushPlugin"

Problem happens in a physical device.

(The more we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @teuassuri2,
Thanks for reporting!

Could you please update `cordova-plugin-code-push` to latest version and check if it fix your issue?
If it was not helpful could you please provide some dummy project with reproducing reprosteps? I would like to debug it.

Thanks,
Alexander

**Comment by teuassuri2** [comment]
It was exactly what I did yesterday, I installed the latest version of the @last plugin and the problem continues.

You need the source code for my project, is that it?

**Comment by teuassuri2** [comment]
[app.component.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/2782839/app.component.zip)

Here is the codepush implementation file.

Before it worked and suddenly stopped...

**Comment by alexandergoncharov** [comment]
@teuassuri2, yeah, you are right :)

I checked your `app.component.ts` file. It looks like correct.
Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by teuassuri2** [comment]
I'm sending you the whole project. Missing only the resources folder.

[AppV3.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/2783573/AppV3.zip)

**Comment by teuassuri2** [comment]
Any news?

**Comment by alexandergoncharov** [comment]
Hi @teuassuri2,
Sorry for delay.

I checked your project and found only `src` and `www` folders. Could you please provide also "config" files? I would like to run and debug it.
By reviewing code it looks like correct.

**Comment by jp-uq** [comment]
I´m facing the same issue...
@teuassuri2 I had another question for you. I saw in your app.component that you are using the PushPlugin. Does it works for you with the new Xcode Build System. Apologies for the question, as it does not relate to the topic

**Comment by jp-uq** [comment]
I found a solution for this issue!
The problem is in build-extras.gradle. In this file the plugin wants to create the "cdvasset.manifest" File inside the postBuildExtras(). This will never be done cause there is a conflict with other plugins using the same method.
The solution is, to change `ext.postBuildExtras` with `ext.cdvPluginPostBuildExtras`. 

The problem, however, is that every time you add the platform, you would have to change that.
Until Microsoft solves the problem I write a plugin that takes care of creating the manifest file.
@teuassuri2 When I'm done, I'll upload it here so you can use it!

**Comment by jp-uq** [comment]
https://github.com/jp-uq/cordova-plugin-asset-manifest

This is the Plugin! Hope it works for you.

**Comment by teuassuri2** [comment]
This message appears @ jp-uq, but error

![image](https://user-images.githubusercontent.com/3892493/51780280-0c2a9a00-20ec-11e9-9ef1-b0bfc29d5d61.png)

**Comment by teuassuri2** [comment]
@alexandergoncharov , any news?

**Comment by jp-uq** [comment]
@teuassuri2 sorry, don´t know why you get this error. Seems there is an issue during the download process. In the File "remotePackage.js" in the cordova-plugin-code-push wrapper is the download method.  You could debug here, maybe this will help. Sorry I can't help you with that...

**Comment by alexandergoncharov** [comment]
Hi @teuassuri2 ,
Sorry for delay.

I tried to setup your project but got issue with adding platform: 
![image](https://user-images.githubusercontent.com/13234108/51831013-35bd0e80-2302-11e9-9d42-640df8195fac.png)


And after that I can't run android project:
![image](https://user-images.githubusercontent.com/13234108/51830997-2a69e300-2302-11e9-9b7f-ec755ebeb231.png)


Could you please try to setup your project and let me know if you have this issue and approach to fix it if you have.

Also, I see that @jp-uq opened PR for fixing this(Thanks @jp-uq 👍 ): https://github.com/Microsoft/cordova-plugin-code-push/pull/500
But at first I would like to reproduce this issue and ensure that the PR is really fix this issue.

**Comment by teuassuri2** [comment]
Just put the resources folder at the root of the project. We are waiting, because I have several applications. I need to know if this will disturb us or if we will stop using it and we will do everything manually.

thanks for the comprehension

[resources.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/2802940/resources.zip)

**Comment by alexstanbury** [comment]
I am also receiving this error.

**Comment by alexandergoncharov** [comment]
Hi @teuassuri2 !
Sorry for delay.

While I tried build your project, I faced with this failure.

![image](https://user-images.githubusercontent.com/13234108/56494094-d97d1b80-64f9-11e9-9d93-8ee17f9dba29.png)

Project which you send was without platform/android directory. Could you please send google-services.json or entire android folder? The second option would be better actually =)

**Comment by alexandergoncharov** [comment]
Hi @teuassuri2 ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen this issue if you have any questions or fix your demo project.

Thanks,
Alexander
