### ISSUE TITLE
[CodePush] An error occurred during sync. 404: Not found deployment, check deployment key is right

### ISSUE THREAD

**Issue by ervivek40** [Microsoft/cordova-plugin-code-push#495]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

Steps to Reproduce

I've cloned this repository.
Then i have added app in code push with name CodePushCordovaDemo.
I got keys staging and production.
Changed the keys in both config.xml file
Then run the application.
Changed version number in both the xml and some text in index.html in staging.
Then released.
Then closed and opened the app and i'm getting error [CodePush] An error occurred during sync.
debug in safari 404: Not found deployment, check deployment key is right.. StackTrace:
Expected Behavior

What you expected to happen?
Get And update alert even update there or not

Actual Behavior

What actually happens?
error :
[CodePush] An error occurred during sync. 404: Not found deployment, check deployment key is right.. StackTrace: #5

  STACK TRACE AND/OR SCREENSHOTS
https://drive.google.com/open?id=1gMWT7VqRgSHD2YNEz016qs4ATADDWRg4
https://drive.google.com/open?id=1VKEaymNmx2tiTZxztKVZUjNZCSqdu-gG
Reproducible Demo

Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From Examples folder run node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta command to generate plain CodePushified React Native app. Please see description on top of create-app.js file content if needed
If you can't reproduce the bug on it, provide us as much info as possible about your project
Environment

cordova-code-push version:4.2.1
iOS/Android/Windows version:12
Does this reproduce on a debug build or release build? debug
Does this reproduce on a simulator, or only on a physical device? simulator
(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @ervivek40,
Thanks for reporting!

Could you pleas ensure that you have correct deployment key?
You can check you keys with `appcenter codepush deployment list -a [ownerName]/[appName] -k` command. And check keys in `config.xml` file for app.

**Comment by ervivek40** [comment]
Yes Checked. It's same.

**Comment by ervivek40** [comment]
Please check the url below for better clarification
i've attched screenshots including deployment key

[https://drive.google.com/open?id=1kTA8APZq0hcvkD-2UtfhenYeEX2pEdB8](url)
