### ISSUE TITLE
Refused to connect to https://codepush.azurewebsites.net/updateCheck?

### ISSUE THREAD

**Issue by ervivek40** [Microsoft/cordova-plugin-code-push#496]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

Log  Stack Trace: 

[Error] Failed to load resource: The requested URL was not found on this server. (acquisition-sdk.js.map, line 0)
[Log] Received Event: deviceready (cordova.js, line 1732)
[Log] [CodePush] Checking for update. (cordova.js, line 1732)
[Error] Refused to connect to https://codepush.azurewebsites.net/updateCheck?deploymentKey=zouDOW2SlrBm7hsGFxdXFq4vqLnKHJjja4VmV&appVersion=2.0.0&packageHash=997cede8ea09f93c96e2157af0cc68472e824771ee0b59a8b583297a9e54bef4&isCompanion=false&label=&clientUniqueId=224387D9-0852-4EED-A305-E94A8E2AD3A6 because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.
[Error] [CodePush]  Couldn't send request to https://codepush.azurewebsites.net/updateCheck?deploymentKey=zouDOW2SlrBm7hsGFxdXFq4vqLnKHJjja4VmV&appVersion=2.0.0&packageHash=997cede8ea09f93c96e2157af0cc68472e824771ee0b59a8b583297a9e54bef4&isCompanion=false&label=&clientUniqueId=224387D9-0852-4EED-A305-E94A8E2AD3A6, xhr.statusCode = 0 was returned. One of the possible reasons for that might be connection problems. Please, check your internet connection.. StackTrace: file:///Users/vivekkumar/Library/Developer/CoreSimulator/Devices/47FF81FC-F793-4EE8-B1A0-F4248782FF57/data/Containers/Bundle/Application/9B35ECAB-1D46-4B0A-A6AA-AB2A5549FF39/mycodepushdemoapp.app/www/plugins/code-push/script/acquisition-sdk.js:50:35
onreadystatechange@file:///Users/vivekkumar/Library/Developer/CoreSimulator/Devices/47FF81FC-F793-4EE8-B1A0-F4248782FF57/data/Containers/Bundle/Application/9B35ECAB-1D46-4B0A-A6AA-AB2A5549FF39/mycodepushdemoapp.app/www/plugins/cordova-plugin-code-push/bin/www/httpRequester.js:30:51
	(anonymous function) (cordova.js:1732)
	logError (codePushUtil.js:41)
	invokeErrorCallback (codePushUtil.js:45)
	callback (codePush.js:90)
	(anonymous function) (acquisition-sdk.js:50)
	onreadystatechange (httpRequester.js:30)

### Reproduction
Steps to reproduce:
1.Clone https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic
2.get www and config files
3.create new project 
4.add code push
5.add platform 
6.paste www and config in project
7.create code push project
8. copy paste keys
9.release 
10. run
11.debug in safari

### Additional Information

* cordova-plugin-code-push version: latest
* List of installed plugins:
* Cordova version:
* iOS version:
* Does this reproduce on a debug build or release build? 
Debug
* Does this reproduce on a simulator, or only on a physical device?
Simulator
(The more info the faster we will be able to address it!)

**Comment by ervivek40** [comment]
Thanks For Help!

**Comment by bozhidarc** [comment]
Hi @ervivek40, can you tell me how you managed to resolve the issue? Thanks.

**Comment by ekrapfl** [comment]
Hi @vivek94, sounds like you were able to fix this issue somehow.  Would you mind explaining what happened that caused it?  I am seeing the same sort of thing while trying to implement CodePush in our existing Ionic/Cordova app.  I don't see it all of the time, just intermittently, but I know that my device does have a good internet connection when it happens.  Any insights for me?

Thanks!

**Comment by zhangbenfus** [comment]
me too

**Comment by ermik** [comment]
[`xhr.statusCode = 0`][mdnstatus] that you can see in the error message signifies that connection somehow failed. _Most likely explanation_ is, as noted in the error of this kind, is lack of connection itself: request could not be sent because device is offline. 

There could be other explanations, of course, but in the end the Domain for this error is **connectivity**.  Make sure to wrap your `code-push` code in `try...catch` and eagerly verify the status of network connections before invoking the SDK.

[mdnstatus]: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status
