### ISSUE TITLE
My ios app download last package and not install it

### ISSUE THREAD

**Issue by alpaygunes** [Microsoft/cordova-plugin-code-push#498]
Description
(sory for my english)
I'am using CodePush plugin. 
My ios app download last package but not install it. 

 Then when I close the application and open it again, I cannot see the update.
The process of updating codepush is being repeated

Reproduction

1 - install cordova-plugin-code-push
2 - build ipa and apk files
3 - install ipa file on test device
4 - change  app source code
5 - prepare for ios and release on  codepush server
6 - ios app not update. 

Additional Information
plugin name="cordova-plugin-whitelist" spec="1.3.3" 
    plugin name="cordova-plugin-statusbar" spec="2.4.2" 
    plugin name="cordova-plugin-device" spec="2.0.2" 
    plugin name="cordova-plugin-splashscreen" spec="5.0.2" 
    plugin name="cordova-plugin-ionic-webview" spec="^2.0.0" 
    plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" 
    plugin name="cordova-plugin-x-socialsharing" spec="5.4.1" 
    plugin name="onesignal-cordova-plugin" spec="2.4.5"
    plugin name="cordova-plugin-code-push" spec="1.11.17" 
    plugin name="cordova-plugin-file-transfer" spec="^1.7.1" 
    plugin name="cordova-plugin-file" spec="6.0.1" 
    engine name="android" spec="7.1.2" 
    engine name="ios" spec="4.5.5"

**Comment by gulullu** [comment]
same here with ionic 4.

**Comment by alexandergoncharov** [comment]
Hi @alpaygunes, @gulullu 
Thanks for reporting!

Could you please provide logs during update? You can grab it with XCode.

**Comment by gulullu** [comment]
@alexandergoncharov 

Hi, 
Here is my demo project: https://github.com/gulullu/MyApp.git.

And my environment info:

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 10 other plugins)

System:

   Android SDK Tools : 26.0.1 (/usr/local/opt/android-sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 5.0.11
   NodeJS            : v11.4.0 (/usr/local/Cellar/node/11.4.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

- Step 1
replace with your deploymentKey in 'tab1.page.ts'
- Step 2
`ionic cordova build ios --prod --release`
- Step 3
open MyApp.xcworkspace and run app on simulator or devices
- Step 4
change 'Update Label: 1' to 'Update Label: 2' in tab1.page.html with text editor
- Step 5
`ionic cordova build ios --prod --release`
- Step 6
`code-push release-cordova MyApp-ios ios --targetBinaryVersion 0.0.1`
- Step 7
check update and install it, the running app's text 'Update Label: 1' change to 'Update Label: 2'
- Step 8
kill the running app and reopen it, the label become to 'Update Label: 1'

**also a gif:**

![demo](https://i.imgur.com/H3FcMMM.gif)

**Comment by zanganeh** [comment]
I have the same problem and I downgraded to 1.1.15 and it works fine there seems the issue is here:

https://github.com/Microsoft/cordova-plugin-code-push/blob/4b533149a85539666f937b2b4e8dd2fc8153f1ab/src/ios/CDVWKWebViewEngine%2BCodePush.m#L18

the application downloads the zip file ..extract it .. set the root path for the ionic but finally the above line and revert the root path to old path! this is hapening when using "cordova-plugin-ionic-webview" this problem caused .. when using 'cordova-plugin-wkwebview-engine' it is fine!

**Comment by microadam** [comment]
having the same issue. We are also using `cordova-plugin-ionic-webview`. Can confirm that downgrading to 1.11.15 fixes the issue. Haven't tried swapping to `cordova-plugin-wkwebview-engine` as we rely on functionality from the ionic one

**Comment by alexandergoncharov** [comment]
Hi @zanganeh ,
Sorry for delay.

Yeah, I reproduced your issue. Sorry for this. Investigating how to fix it.

**Comment by zanganeh** [comment]
Appreciate it @alexandergoncharov

**Comment by NG-tylerholden** [comment]
Any update on this?

**Comment by zanganeh** [comment]
Any update ?

**Comment by alexandergoncharov** [comment]
Hi @zanganeh @NG-tylerholden ,

Sorry for this delay. I also involved in another repo and my investigation is still in progress. We should make fix which should be worked for Ionic4, ionic3, clear Cordova and Cordova with WKWebView plugin. This require more time unfortunately. I will keep you in touch about progress.

**Comment by marecektn** [comment]
I'd like to join the party :) 
I has been investigating this issue for quite a some time now.. 
after several hours I've noticed, that after app restart CodePush has issues of notifying that the app has deployed well. I see this line in console after restarting updated app:

`XMLHttpRequest cannot load https://codepush.azurewebsites.net/reportStatus/deploy due to access control checks.`

Here is my meta tag with Content Security Policy:
```
<meta http-equiv="Content-Security-Policy"
          content="default-src 'self' *.azurewebsites.net
          data: https://ssl.gstatic.com 'unsafe-inline' 'unsafe-eval';
          style-src 'self' 'unsafe-inline' http://fonts.googleapis.com ;
          script-src * 'unsafe-inline' 'unsafe-eval';
          font-src http://fonts.gstatic.com;
          connect-src *;
          media-src *;
          img-src 'self'
          content:;"/>
```

Here's the syncing code:

```
window.codePush.sync((status) => {
      console.log(status);
    }, { 
      installMode: InstallMode.ON_NEXT_RESUME,
      minimumBackgroundDuration: 0,
      mandatoryInstallMode: InstallMode.IMMEDIATE })
```

Cordova plugins that we are using:
```
code-push 2.0.6 "CodePushAcquisition"
cordova-android-support-gradle-release 1.4.7 "cordova-android-support-gradle-release"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-webview 4.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
sentry-cordova 0.13.1 "Sentry"
```

The behaviour currently looks like this. I build the app as mentioned in previous comments, but I have `InstallMode.ON_NEXT_RESUME` so once the app updates and installs, I put it in background.. then by putting on foreground I can see the new version is installed and served.

Once I kill the app and restart it, I get the `XMLHttpRequest cannot load https://codepush.azurewebsites.net/reportStatus/deploy due to access control checks.` console log which I think is the reason of rolling back to "bundled" code.

Speaking of bundled code.. I've also found out using iOS simulator, that the bundled code (that is distributed in AppStore) is physically still in `www` folder of installed application. Is this wanted behaviour? So CodePush stores all fetched versions into codepush directory and the original `www/index.html` of app is never replaced?

I am really willing to provide more info as I'd like to progress on this one and have it out of table. 

Thanks for any kind of help and looking forward to updates 👍

**Comment by marecektn** [comment]
Is any update about fix on the horizon? 🤸‍♂️

**Comment by zanganeh** [comment]
Any update on this @alexandergoncharov

**Comment by alexandergoncharov** [comment]
Hi all,

I'm so sorry for this delay but my investigation is still in progress. Looking for real reason of issue as it isn't rollback. Looks like there is some issue with setting new update for app.
I'll be keep you posted.

**Comment by davidellolio** [comment]
Any update ?

**Comment by alpaygunes** [comment]
I'm looking forward !

**Comment by 15019493655** [comment]
[CodePush] An error occurred during sync. Deployment key not found
Why is the key wrong for ios hot update？

**Comment by marecektn** [comment]
no pressure, is there any way how we can help to investigate with it? what's the current status please?

**Comment by mekery** [comment]
same problems, looking forward for updating.

**Comment by marecektn** [comment]
friendly ping, please any update on this. Our codebase is pretty much ready, it kind of start to affect our delivery. I am willing to consult in any way, but need to get forward :) Thanks

**Comment by taipeiwu** [comment]
Same problems, any update on this?

**Comment by l3ender** [comment]
@alexandergoncharov Any update? This is a pretty big issue and it's been a month and a half now.

If there are ways that others can contribute, please share those details, as people are waiting solely on you for a fix.

**Comment by alexandergoncharov** [comment]
Hi all,
I'm really sorry for this long delay.
My investigation is still in progress.

I just found that we should change handling request here: https://github.com/Microsoft/cordova-plugin-code-push/blob/master/src/ios/CDVWKWebViewEngine%2BCodePush.m as this prevent loading CodePush bundle correctly but I'm still investigation which exactly request we should handle by other way and exactly how. I compared logic with 1.11.15 version as this version works fine for this case.

If I found something else I'll post it here. I'll be keep you in touch.

**Comment by Mr-Anonymous** [comment]
I have code push version 1.11.10 and have the same issues for the past few weeks. It works fine in Android but all updates in iOS is getting rollbacked.
![Screenshot 2019-03-20 at 9 42 45 AM](https://user-images.githubusercontent.com/8770270/54658712-d0f98580-4af4-11e9-97de-da72b289407d.png)


```
code-push 2.0.4 "CodePushAcquisition"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-appcenter-analytics 0.1.4 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.10 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-mediapicker-dmcbig 2.3.8 "MediaPicker"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
```

My set-up:
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.5
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.3.0
    npm        : 5.7.1 
    OS         : macOS
    Xcode      : Xcode 10.1 Build version 10B61 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by marecektn** [comment]
2 months since reporting, we kind of really need to progress on this one.

**Comment by michaek** [comment]
@alexandergoncharov I'm reluctant to pile on the list of requests for an update on this issue, but it does seem like a long time for a showstopper bug to be in limbo. Any chance you can elaborate on your investigation into handling requests from your changes in https://github.com/Microsoft/cordova-plugin-code-push/commit/7057ce8807f14150b39c8da30750d1d643958ed1 ? Is the problem related to returning nil, or is that triggering some desired behavior?

I haven't tried to step through this code in Xcode yet, and I don't want to start digging into the plugin implementation if you're currently working on a fix. However, if you're not able to focus on this investigation now or in the near future, I'm sure the followers of the issue would appreciate some indication of where you think the problem is, so a solution from the community can be provided.

Thanks!

**Comment by marc-coll** [comment]
It still works with 1.11.15? 
`"cordova-plugin-code-push": "1.11.15",`

For me it's not working either. On app restart, the app is rollbacked and nothing upgraded.

**Comment by Mr-Anonymous** [comment]
@marc-coll It works for me in `cordova-plugin-code-push 1.11.15 "CodePush"`. Previously I had `v1.11.10` and it stopped working for the past few months. I then updated to version 1.11.15 and now its working. It appear updating to the latest version breaks it again so I am happy to stay with 1.11.15 for now.

**Comment by michaek** [comment]
I have tried installing version 1.11.15, but with `cordova-plugin-ionic-webview` (2.2.5) it seems to prevent any updates to web assets, requiring the app to be uninstalled and reinstalled to see changes. I don't know what interaction of components is triggering that, and I don't know if would happen in all cases, but it's been my experience that just using an earlier version is not feasible.

**Comment by marc-coll** [comment]
@Mr-Anonymous which version of `cordova-plugin-ionic-webview` are you using?

**Comment by arist0tl3** [comment]
I can also confirm that 1.11.15 always rolls back when using `cordova-plugin-wkwebview-engine` (1.1.4).

**Comment by coreysherman** [comment]
@alexandergoncharov We are also seeing this issue.  Is there any update as to a plan of attack on this?  Is there any other course of action other than rolling back to 1.11.15 and removing cordova-plugin-ionic-webview?

**Comment by marecektn** [comment]
Microsoft should hire Mr. Colombo for this one, since this investigation is stuck for way too long now 🙃

**Comment by matthewpavkov** [comment]
@coreysherman 1.11.15 works with `cordova-plugin-ionic-webview` version `^2.2.1` on iOS as of March 11, 2019 (as far as I can tell). I don't remember exactly what version of `webview` was installed, but I believe it should have been `2.4.0`.

**Comment by coreysherman** [comment]
Thank you, @matthewpavkov!  We did go ahead and roll back to `1.11.15` since we were only using `cordova-plugin-ionic-webview` version `2.0.0` any way and we're working for now.

**Comment by zanganeh** [comment]
Long time no see!

**Comment by Mr-Anonymous** [comment]
@marc-coll My apologies for the delay in my reply cuz I missed that one. I have `cordova-plugin-ionic-webview 2.3.1` installed along with `cordova-plugin-code-push 1.11.15`. Here is my plugins list:

```
> cordova plugin ls
code-push 2.0.6 "CodePushAcquisition"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-appcenter-analytics 0.1.4 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.15 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-mediapicker-dmcbig 2.3.8 "MediaPicker"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
```

**Comment by marc-coll** [comment]
@Mr-Anonymous Thanks!
just before your answer, I finally figured out how to make it work.

I'm using: 
```
<plugin name="cordova-plugin-code-push" spec="^1.11.0" />
<plugin name="cordova-plugin-ionic-webview" spec="^1.1.16" />
```

**Comment by jp-uq** [comment]
Regarding this [Post](https://ionic.zendesk.com/hc/en-us/articles/360015176994-2019-01-03-Security-Alert-for-cordova-plugin-ionic-webview?utm_campaign=Security%20Alert%20Native%20Plugins&utm_source=hs_email&utm_medium=email&utm_content=68797151&_hsenc=p2ANqtz-8iOdvXaA8choHoPEBn4tZOMoaaS_QUKfojauaJiRGSx7FNonfe56QaH7ym3zm-7W6YqFoIG8BrUxxVDx65zXsuVuAvQA&_hsmi=68797151) i can´t recommend to use a cordova-plugin-ionic-webview version under 2.3.1. Means that the cordova-plugin-code-push is currently not usable!

**Comment by l3ender** [comment]
Any update on this issue? We're using v4 of cordova-plugin-ionic-webview and falling back to previous versions is not workable because of the security issues in them.

If any advice could be given on this, it sounds like multiple people are willing to help. But we need some guidance from the team.

@alexandergoncharov

**Comment by alexandergoncharov** [comment]
Hi all, 
I'm really sorry for this delay and all this long active issue time.

Here is draft fix for this issue: https://github.com/Microsoft/cordova-plugin-code-push/pull/520
There is just logic for preventing loading binary bundle after installing CodePush bundle. Looks like all works correctly.

Could someone please test it additionally in some cases and let us know your results?
Also, please feel free to ask any questions or suggest any other approaches and notes.

Thanks,
Alexander

**Comment by gulullu** [comment]
> Hi all,
> I'm really sorry for this delay and all this long active issue time.
> 
> Here is draft fix for this issue: #520
> There is just logic for preventing loading binary bundle after installing CodePush bundle. Looks like all works correctly.
> 
> Could someone please test it additionally in some cases and let us know your results?
> Also, please feel free to ask any questions or suggest any other approaches and notes.
> 
> Thanks,
> Alexander

I had tested it, It works fine on both iOS & Android, great job, thanks.😄

**Comment by alexandergoncharov** [comment]
Hi all,

@gulullu Thanks for testing!

Fix already in Master and in new release: https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.11.18

Thanks for the great interest in CodePush and I'm sorry for this long delay!

So, I'm going to close this issue for now. Please feel free to reopen it if you have any questions or face this issue again.

Thanks,
Alexander

**Comment by marecektn** [comment]
seems to be working well! after all my pinging, I'd like to thank you @alexandergoncharov 👍

**Comment by alexandergoncharov** [comment]
That's great! Sorry for this delay and thanks for your waiting!  =)
