### ISSUE TITLE
Capacitor support please

### ISSUE THREAD

**Issue by NG-tylerholden** [Microsoft/cordova-plugin-code-push#499]
### Description

Cordova code push does not work with capacitor currently. Getting a build error: `'Cordova/CDVWebViewEngineProtocol.h' file not found`

### Reproduction

Latest cordova code push and ionic 4/capacitor

I have seen another issue closed by someone else requesting capacitor support but I want to reiterate that I think this should be bumped in priorities, please.

**Comment by alexandergoncharov** [comment]
Hi @NG-tylerholden,
Yeah, we don't support Capacitor for now unfortunately. Sorry for this.

Please check this issues about this:
https://github.com/Microsoft/cordova-plugin-code-push/issues/450
https://github.com/Microsoft/code-push/issues/615

So, I'm going to close this issue for now but please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by dylanvdmerwe** [comment]
https://github.com/Microsoft/code-push/issues/615
