### ISSUE TITLE
InstallMode under window.codePush instead global

### ISSUE THREAD

**Issue by zwacky** [Microsoft/cordova-plugin-code-push#50]
afaik this is how it's done in the react ms code push, too.
anything that speaks against it?

**Comment by dlebu** [comment]
We tried to keep the API familiar for Cordova developers. The core Cordova plugins add objects (types) globally and methods under `window` or `navigator`. Two good examples are the [geolocation plugin](https://github.com/apache/cordova-plugin-geolocation#methods) and the [device motion plugin](https://github.com/apache/cordova-plugin-device-motion#methods).

**Comment by zwacky** [comment]
alright. feels a bit bloaty but i understand.

**Comment by pke** [comment]
I'd think some cordova plugins (also those you mentioned) only use global namespace if there is an equivalent browser functionality available. But sometimes the plugin author just did not care and polluted the global namespace.
