### ISSUE TITLE
LocalStorage is not persistent on iOS

### ISSUE THREAD

**Issue by AMerkuri** [Microsoft/cordova-plugin-code-push#502]
### Description

I pushed new update via appcenter
`appcenter codepush release-cordova -a MyApp --description "0.1.1" --target-binary-version "~0.1.0" -d Testing`

I am saving data to localStorage and localForage (IndexedDB). On Android after code-push update localStorage is fine, everything is intact. On iOS other hand looks like localStorage and IndexedDB is no longer persistent and everything is wiped.

### Reproduction

This problem did not occur on `cordova-plugin-code-push` version: `1.11.15` (and `cordova-plugin-ionic-webview: 2.3.1`). Problem started to occur with combination of `cordova-plugin-code-push 1.11.17` and `cordova-plugin-ionic-webview 3.0.0`.

### Additional Information

* cordova-plugin-code-push version: 1.11.17
* List of installed plugins:
code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-appcenter-analytics 0.2.2 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.2.1 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.2.2 "App Center shared code for Cordova"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-smsreceiver 1.0.0 "Cordova SMS Receiver"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
* Cordova version: 8.1.2 (cordova-lib@8.1.1)
* iOS/Android/Windows version: 12.1.2
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? Tested on device

**Comment by alexandergoncharov** [comment]
Hi @AMerkuri,
Thanks for reporting!

Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by AMerkuri** [comment]
@alexandergoncharov 
Funny thing, I can't actually reproduce it. I am closing this issue and will try to figure out what is causing that.

@stutya Thanks. I'll look into that.

**Comment by alexandergoncharov** [comment]
@AMerkuri Sure, thanks for keeping us in touch!

**Comment by marcogrieco** [comment]
Hi, i have the same problem. Only on iOS (12.4 is the version of my testing device). Why? Any suggestion? Thanks in advance.

**Comment by Perh0rd** [comment]
Hi, same here.
