### ISSUE TITLE
Plugin doesn´t update iOS

### ISSUE THREAD

**Issue by jp-uq** [Microsoft/cordova-plugin-code-push#503]
### Description

i created an ionic 3 application and integrated the cordova-plugin-code-push. After publishing a new version to the appcenter the application detects the new version, download and install it. After restarting the app the new version is not visible.

### Reproduction

1. add cordova plugin
2. checkForUpdate in app.component.ts
3. sync with InstallMode.on_next_restart
4. publishing a new version to appcenter
5. restarting the app and wait till the update finished downloading
6. restart app

### Problem

I also detect what´s going wrong.
In your PR #491 you changed that every URL request uses the setServerBasePath method.
Through this fix the current flow is:
1. SetServerPath with update
2. SetServerPath with installed Version

--> Only the installed version is displayed and the updated version never gets the active one

### Additional Information

* cordova-plugin-code-push version: 1.11.17
* List of installed plugins:
com.liveperson.messagingSDK 1.0.0 "lpMessagingSDK"
cordova-android-firebase-gradle-release 2.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 2.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"
cordova-google-services-support 1.2.1 "cordova-google-services-support"
cordova-launch-review 3.1.1 "Launch Review"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-android-fingerprint-auth 1.5.0 "FingerprintAuth"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-asset-manifest 1.0.3 "cordova-plugin-asset-manifest"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-code-push 1.11.16 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.1.4 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.3 "cordova-plugin-ionic-webview"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
io-anyline-cordova 4.1.0 "AnylineSDK"
* ionic info:
Ionic:

   ionic (Ionic CLI)  : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5

System:

   Android SDK Tools : 26.1.1 (/Users/janpupeter/Library/Android/sdk/)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v11.8.0 (/usr/local/Cellar/node/11.8.0/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by alexandergoncharov** [comment]
Hi @jp-uq,
Thanks for reporting!

I'll investigate a bit later as soon as possible. Sorry for this delay.

**Comment by jp-uq** [comment]
@alexandergoncharov any news?

**Comment by alexandergoncharov** [comment]
Hi @jp-uq,
Sorry for delay.
Could you please check if this issue is the same as https://github.com/Microsoft/cordova-plugin-code-push/issues/498? It looks like the same behaviour.

**Comment by jp-uq** [comment]
@alexandergoncharov yes it´s the same issue!

**Comment by alexandergoncharov** [comment]
@jp-uq , so, I'm going to close this issue as duplicate. I'll post the progress to original issue. Let's continue our conversation there.
