### ISSUE TITLE
cordova app losing splashScreen plugin after CodePush installation

### ISSUE THREAD

**Issue by iliran11** [Microsoft/cordova-plugin-code-push#504]
### Description

Installing codePush update on iphone results in losing `splashScreen` property in `Navigator` object.
Before the codePush update installation, splashScreen worked OK.

version of `apache/cordova-plugin-splashscreen`: 5.0.2

this issue is not reproducible on dummy project, actually by compiling the project on my own personal mac - i don't see the problem. i have no idea what's the difference. i have xCode 9.4 and the problematic machine has xCode 9.2.

Beside that i actually need ideas what could be different and why this is happening.

## Additional Information

* cordova-plugin-code-push version: 1.1.17
* Cordova version: 7.1.0
* iOS/Android/Windows version: iOS 11.2.6
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? only physical device.

version list: 
```
code-push 2.0.6 "CodePushAcquisition"
cordova-clipboard 1.2.1 "Clipboard"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-android-volume 0.0.12 "Android Volume"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-downloadmanager 0.0.1 "DownloadManager"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-push 1.11.1 "PushPlugin"
```

thanks for any help.

**Comment by alexandergoncharov** [comment]
Hi @iliran11,
Thanks for reporting!

Could you please provide reprosteps for reproducing this issue? I would like to debug it.
