### ISSUE TITLE
why SuccessCallback<DownloadProgress>     totalBytes = 0

### ISSUE THREAD

**Issue by ricadro** [Microsoft/cordova-plugin-code-push#505]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.]

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

### Additional Information

* cordova-plugin-code-push version: 
* List of installed plugins:
* Cordova version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @ricadro,
Thanks for reporting!

Could you please provide more detailed information about your issue and how is it possible to reproduce it?
Also would be great if you provide some dummy project with reproducing issue and reprosteps.

**Comment by alexandergoncharov** [comment]
Hi @ricadro,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.
