### ISSUE TITLE
Move to AppCenter affect anything?

### ISSUE THREAD

**Issue by danicholls** [Microsoft/cordova-plugin-code-push#506]
We’re evaluating this plugin for a project and notice that the CodePush site linked in the readme now points to AppCenter. 

Will this move change anything for this plugin as-is? Will PhoneGap Build support still be here?

Thanks!

**Comment by alexandergoncharov** [comment]
Hi @danicholls,
Thanks for reporting!

No, moving CodePush to appcenter doesn't changing anything about plugin. Yeah, we still support Phonegap and we will continue doing it. :)

Please let me know if it was helpful or you have more questions.

**Comment by danicholls** [comment]
Great, that answers that!
