### ISSUE TITLE
White screen after add meta http-equiv

### ISSUE THREAD

**Issue by stephane-r** [Microsoft/cordova-plugin-code-push#507]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I wish to add code-push in a recent Cordova project. However, the ### meta step in the **index.html** returns me a white screen when I build the application : 

`<meta http-equiv="Content-Security-Policy" content="default-src 'self' https://codepush.azurewebsites.net/ data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">`

### Additional Information

* cordova-plugin-code-push version: latest
* List of installed plugins:
```
code-push 2.0.6 "CodePushAcquisition"
cordova-custom-config 5.0.3 "cordova-custom-config"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-networkinterface 2.0.0 "NetworkInterface"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-webserver 1.0.1 "Webserver for Cordova Apps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
es6-promise-plugin 4.1.0 "Promise"
wifiwizard2 3.1.0 "WifiWizard2"
```
* Cordova version: 8.1.2
* iOS/Android/Windows version: Android 8/9
* Does this reproduce on a debug build or release build?: build
* Does this reproduce on a simulator, or only on a physical device?: test on physical device only

Thank you community !

**Comment by alexandergoncharov** [comment]
Hi @stephane-r ,
Thanks for reporting!

Could you please try to use exactly meta line from from docs `<meta http-equiv="Content-Security-Policy" content="default-src https://codepush.azurewebsites.net 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *" /` ?

If this was not helpful for you could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by alexandergoncharov** [comment]
Hi @stephane-r,

I'm going to close this issue for now as I haven't heard form you in while unfortunately
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
