### ISSUE TITLE
Subscription needed for sync() observable?

### ISSUE THREAD

**Issue by l3ender** [Microsoft/cordova-plugin-code-push#509]
### Description

I am using `codePush.sync()` in my Ionic/Cordova application but it doesn't check for any updates unless I `subscribe()` to it.

I'm trying to figure out intended use of the plugin. Do I need to subscribe to the observable in order for the sync to take place?

### Reproduction

Normal usage of the sync method is like this. Calling the `sync()` method doesn't do any thing.
```js
constructor(
	private platform: Platform,
	private codePush: CodePush,
) { }

ngOnInit() {
	this.platform.ready().then(() => {
		console.log("normal update check");
		this.codePush.sync(); // THIS DOESN'T DO ANYTHING
	});
}
```

If I `subscribe()` to the sync method, I see the sync take place, and the application correctly updates.
```js
constructor(
	private platform: Platform,
	private codePush: CodePush,
) { }

ngOnInit() {
	this.platform.ready().then(() => {
		console.log("subscribe update check");
		this.codePush.sync().subscribe(); // THIS WORKS
	});
}
```

### Additional Information

It is happening on all devices: Android/iOS and simulator/real. Some of my dependencies:

```json
...
"@ionic-native/code-push": "^5.0.0",
"@ionic-native/core": "^5.0.0",
"@ionic/angular": "^4.0.0",
"code-push": "^2.0.6",
"cordova-android": "7.1.4",
"cordova-ios": "4.5.5",
"cordova-plugin-code-push": "^1.11.17",
...
```

Please advise. Thank you!

**Comment by alexandergoncharov** [comment]
Hi @l3ender,
Thanks for reporting!

No, you don't have to use `observable` method for `codepush.sync` method.  And it is strange that this works for you. Could you please share some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by alexandergoncharov** [comment]
Hi @l3ender,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
