### ISSUE TITLE
Ionic cordova_not_available after sync

### ISSUE THREAD

**Issue by HansKrywaa** [Microsoft/cordova-plugin-code-push#510]
### Description

i'm trying to implement Code-Push from AppCenter into my Ionic v4 App.

I'm stuck on the following Problem: I can update the App, but when i close the App after that and open again it is the old Version again and it says:

> Updade ignored, because it was rollbacked

So somehow the update is rolled back after i close the App. After searching for this problem i found that i have to run

`this.codePush.notifyApplicationReady()`

on application start. I added this to my code, but it doesn't work either. If i run the Application on a Android Emulator and open the Logs, AFTER the Update it says:

> cordova_not_available

So it makes sense that the notifyApplicationReady doesn't work, but why is cordova unavailable?

    initializeApp() {
        this.platform.ready().then(() => {
            this.statusBar.styleDefault();

            this.codePush.notifyApplicationReady().then(value => {
                console.log(value);
            });

            this.codePush.sync({
                deploymentKey: 'MY_KEY',
                installMode: InstallMode.IMMEDIATE
            }).subscribe(status => {
                console.log(status);
            });
            this.splashScreen.hide();
        });
    }

### Additional Information

* cordova-plugin-code-push version: 1.11.17
* List of installed plugins:
code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Trans
cordova-plugin-ionic-keyboard 2.1.3 "cordova-p
cordova-plugin-ionic-webview 3.1.2 "cordova-pl
cordova-plugin-splashscreen 5.0.2 "Splashscree
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? emulator

**Comment by alexandergoncharov** [comment]
Hi @HansKrywaa,
Thanks for reporting!

Unfortunately I can't reproduce your issue. Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by HansKrywaa** [comment]
Hey @alexandergoncharov,
we are already in email contact. Should we continue via email and just publish the result here? 😊

**Comment by alexandergoncharov** [comment]
oh. yeah, got it. I think that we should continue our conversation here as it can helps other guys which stuck with this issue. :)

**Comment by HansKrywaa** [comment]
Okay 😃 So here is my last E-Mail again:

i just create a repository and checked in my whole code :)
https://github.com/HansKrywaa/codePushTest

The whole thing happens in my app.component.ts - i delete the deployment key, but nothing else, so this code is not working for me...
 
I hope you can reproduce it, because otherwise i dont know whats happens here :D

**Comment by alexandergoncharov** [comment]
@HansKrywaa, Thanks for test project :)
I'll investigate it as soon as possible and let you know my results.

**Comment by HansKrywaa** [comment]
Okay solved it through this: https://stackoverflow.com/a/55043660/10908838

Usage "ionic cordova build android" instead of "ionic build" before the release works gor me 😊

**Comment by alexandergoncharov** [comment]
Hi @HansKrywaa,

Great! Thanks for keeping us in touch!
