### ISSUE TITLE
cdvCreateAssetManifest leftShift is deprecated from gradle 5.0

### ISSUE THREAD

**Issue by westenberg** [Microsoft/cordova-plugin-code-push#512]
### Description

Starting from gradle 5.0 the leftShift operator is deprecated. This operator is used in cdvCreateAssetManifest in the file build-extras.gradle. 

### Reproduction

Use the plugin in an android project with gradle 5.0 and compile. It will throw errors about the deprecated leftShift operator.

### Additional Information
Solution:
add doLast() function inside the cdvCreateAssetManifest function and remove the leftShift operator.

**Comment by alexandergoncharov** [comment]
Hi @westenberg,
Thanks for reporting!

Sorry for this delay but we will investigate it a bit later as soon as possible.

Thank,
Alexander

**Comment by jacobg** [comment]
The fix is simple. Just replace `<<` with `doLast`. Please push this fix to master! :-)

**Comment by alexandergoncharov** [comment]
Hi @westenberg  @jacobg 
Sorry for delay.

Thank you for helpful comments!

I opened [PR](https://github.com/Microsoft/cordova-plugin-code-push/pull/524) with the fix. Could you please test it and let me know if you have any issues?

**Comment by alexandergoncharov** [comment]
Hi @westenberg and @jacobg,

Fix already merged in master and will be in next release.
Thanks for good catch.
So, I'm going to close this issue for now as it was resolved. Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by jacobg** [comment]
Thank you @alexandergoncharov!

**Comment by westenberg** [comment]
when will this be released? v1.11.18 doesn't contain the adjustment.

**Comment by alexandergoncharov** [comment]
@westenberg This changes will be in new release. Unfortunately I can't provide any ETA but it will be soon. =)
Sorry for this delay.
