### ISSUE TITLE
Could not find start page in package

### ISSUE THREAD

**Issue by quantosapplications** [Microsoft/cordova-plugin-code-push#517]
Description

[app-scripts] [14:04:08] console.log: [CodePush] Checking for update.
[app-scripts] [14:04:09] console.log: registerId end - user id : 1 - onesignal id : bf1f0f7a-19fd-426d-9049-8e2007ec1e3c
[app-scripts] [14:04:14] console.log: [CodePush] Reported status:
[app-scripts] {"status":0,"appVersion":"2.0.23","deploymentKey":"XXXX"}
[app-scripts] [14:04:16] console.log: [CodePush] An update is available.
[app-scripts] {"appVersion":"2.0.23","deploymentKey":"XXXXX","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/y3-5r2_KinvpU51NBFV4sM75w1d6cb780a48-75f9-45f3-866c-ab4ece1c9e40","isMandatory":false,"label":"v2","packageHash":"4384382d0b96820ecd06766afa36ecaa5bd660d828ee16078171073e9d677409","packageSize":16276063,"failedInstall":false}
[app-scripts] [14:04:16] console.log: [CodePush] Downloading update
[app-scripts] [14:05:34] console.log: [CodePush] Package download success:
[app-scripts] {"deploymentKey":"VScIBCJpjwU0noxrd60UWrwaBDQ5rJbD7nWMKV","label":"v2","appVersion":"2.0.23","isMandatory":false,"packageHash":"4384382d0b96820ecd06766afa36ecaa5bd660d828ee16078171073e9d677409","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
[app-scripts] [14:05:34] console.log: [CodePush] Installing update
[app-scripts] [14:05:38] console.log: [CodePush] Applying full update
[app-scripts] [14:05:38] console.error: [CodePush] Preinstall failure. Could not get the package start page
[app-scripts] [14:05:38] console.error: [CodePush] An error has occured while installing the package. Could not get the package start
[app-scripts] page. StackTrace: Error: An error has occured while installing the package. Could not get the package start
[app-scripts] page at preInstallFailure
[app-scripts] (http://192.168.1.64:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41) at
[app-scripts] Object.callbackFromNative (http://192.168.1.64:8100/cordova.js:293:52) at processMessage
[app-scripts] (http://192.168.1.64:8100/cordova.js:1114:17) at processMessages
[app-scripts] (http://192.168.1.64:8100/cordova.js:1137:9) at t.invoke
[app-scripts] (http://192.168.1.64:8100/build/polyfills.js:3:14976) at r.run
[app-scripts] (http://192.168.1.64:8100/build/polyfills.js:3:10143) at http://192.168.1.64:8100/build/polyfills.js:3:20242
[app-scripts] at t.invokeTask (http://192.168.1.64:8100/build/polyfills.js:3:15660) at r.runTask
[app-scripts] (http://192.168.1.64:8100/build/polyfills.js:3:10834) at o
[app-scripts] (http://192.168.1.64:8100/build/polyfills.js:3:7894)

This happen both in iOS and Android, both emulator and device.

This issue is similar to https://github.com/Microsoft/cordova-plugin-code-push/issues/459#issue-375216271 but unfortunately that didn't solve mine.

I tried to install cordova-plugin-ionic-webview@1.2.1 but no luck.
I also tried to install version 1.1.12 / 1.1.16 / 2.4.1 / 3 of the same plugin but the error is the same for all of these.

this is the script I use to send updates
appcenter codepush release-cordova -a me/AppName-iOS -d Production
or
appcenter codepush release-cordova -a me/AppName-Android -d Production

Those are my dependencies:

"dependencies": {
"@angular/common": "^5.0.3",
"@angular/compiler": "^5.0.3",
"@angular/compiler-cli": "5.0.3",
"@angular/core": "5.0.3",
"@angular/forms": "5.0.3",
"@angular/http": "5.0.3",
"@angular/platform-browser": "5.0.3",
"@angular/platform-browser-dynamic": "5.0.3",
"@ionic-native/app-version": "^4.17.0",
"@ionic-native/base64-to-gallery": "^4.5.3",
"@ionic-native/camera": "^4.5.2",
"@ionic-native/clipboard": "^4.16.0",
"@ionic-native/code-push": "^4.20.0",
"@ionic-native/core": "4.4.0",
"@ionic-native/crop": "^4.16.0",
"@ionic-native/device": "^4.7.0",
"@ionic-native/email-composer": "^4.17.0",
"@ionic-native/facebook": "^4.15.0",
"@ionic-native/file": "^4.5.2",
"@ionic-native/file-chooser": "^4.5.2",
"@ionic-native/file-transfer": "^4.5.2",
"@ionic-native/globalization": "^4.12.2",
"@ionic-native/in-app-browser": "^4.16.0",
"@ionic-native/keyboard": "^4.5.2",
"@ionic-native/onesignal": "^4.5.3",
"@ionic-native/photo-library": "^4.11.0",
"@ionic-native/screen-orientation": "^4.7.0",
"@ionic-native/social-sharing": "^4.19.0",
"@ionic-native/splash-screen": "4.4.0",
"@ionic-native/status-bar": "4.4.0",
"@ionic/pro": "^1.0.20",
"@ionic/storage": "2.1.3",
"@stomp/ng2-stompjs": "^7.2.0",
"angular2-websocket": "^0.9.6",
"babel-core": "^6.26.3",
"babel-preset-es2015": "^6.24.1",
"babelify": "^8.0.0",
"code-push": "^2.0.6",
"cordova": "8.0.0",
"cordova-android": "7.0.0",
"cordova-base64-to-gallery": "^4.1.3",
"cordova-clipboard": "^1.2.1",
"cordova-ios": "4.5.5",
"cordova-plugin-add-swift-support": "^1.7.2",
"cordova-plugin-app-version": "^0.1.9",
"cordova-plugin-badge": "^0.8.7",
"cordova-plugin-camera": "^4.0.1",
"cordova-plugin-code-push": "^1.11.17",
"cordova-plugin-crop": "git+https://github.com/obeza/cordova-plugin-crop-with-ratio.git",
"cordova-plugin-customurlscheme": "^4.3.0",
"cordova-plugin-device": "^1.1.7",
"cordova-plugin-dialogs": "^2.0.1",
"cordova-plugin-email-composer": "^0.8.15",
"cordova-plugin-facebook4": "^3.1.0",
"cordova-plugin-file": "^5.0.0",
"cordova-plugin-file-transfer": "^1.7.0",
"cordova-plugin-filechooser": "^1.0.1",
"cordova-plugin-globalization": "^1.11.0",
"cordova-plugin-inappbrowser": "^3.0.0",
"cordova-plugin-ionic-keyboard": "^2.1.3",
"cordova-plugin-ionic-webview": "^1.2.1",
"cordova-plugin-photo-library": "^2.1.1",
"cordova-plugin-screen-orientation": "^3.0.1",
"cordova-plugin-splashscreen": "^5.0.2",
"cordova-plugin-statusbar": "^2.4.2",
"cordova-plugin-whitelist": "^1.3.3",
"cordova-plugin-x-socialsharing": "^5.4.4",
"cordova-plugin-zip": "^3.1.0",
"cordova-sqlite-storage": "^2.1.4",
"d3": "^5.8.0",
"es6-promise-plugin": "^4.2.2",
"font-awesome": "4.7.0",
"hammerjs": "^2.0.8",
"hermite-resize": "git+https://github.com/viliusle/Hermite-resize.git",
"i": "0.3.6",
"ionic-angular": "3.9.2",
"ionic-select-searchable": "^2.10.0",
"ionic2-super-tabs": "^5.0.2",
"ionicons": "3.0.0",
"ips": "2.1.3",
"ng2-pica": "^1.2.8",
"ng2-translate": "^5.0.0",
"onesignal-cordova-plugin": "^2.2.5",
"patch-package": "^6.0.5",
"pica": "^4.1.1",
"rxjs": "5.5.2",
"sentry-cordova": "^0.13.1",
"sockjs-client": "^1.3.0",
"sw-toolbox": "3.6.0",
"web-animations-js": "^2.3.1",
"zone.js": "0.8.18"
},

I'm new to CodePush but I have implemented it on a react native project and I had no problems, now on Ionic I don't know what else to do. I searched everywhere on google and this is the only place where this problem seem solved.

Thank you

**Comment by quantosapplications** [comment]
This is the same error thrown from iOS platform.

[app-scripts] [10:39:20]  console.log: [CodePush] Checking for update. 
[app-scripts] [10:39:21]  console.log: [CodePush] An update is available. 
[app-scripts]             {"appVersion":"2.0.27","deploymentKey":"XXXX","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/HjW8g6isLnKeinht0njq9Thea_Nwcb780a48-75f9-45f3-866c-ab4ece1c9e40","isMandatory":false,"label":"v14","packageHash":"813e890a6ed68a0e8a75daa4bfb727a32c0967291cd70e7698a830ef6befa9ee","packageSize":16287570,"failedInstall":false}
[app-scripts] [10:39:21]  console.log: DOWNLOADING_PACKAGE 
[app-scripts] [10:39:21]  console.log: [CodePush] Downloading update 
[app-scripts] [10:39:27]  console.log: [CodePush] Package download success: 
[app-scripts]             {"deploymentKey":"XXXX","label":"v14","appVersion":"2.0.27","isMandatory":false,"packageHash":"813e890a6ed68a0e8a75daa4bfb727a32c0967291cd70e7698a830ef6befa9ee","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/library-nosync/codepush/download/update.zip"}
[app-scripts] [10:39:27]  console.log: INSTALLING_UPDATE 
[app-scripts] [10:39:27]  console.log: [CodePush] Installing update 
[app-scripts] [10:39:28]  console.log: [CodePush] Applying full update 
[app-scripts] [10:39:28]  console.error: [CodePush] Preinstall failure. Could not find start page in package. 
[app-scripts] [10:39:28]  console.error: [CodePush] An error has occured while installing the package. Could not find start page in 
[app-scripts]             package.. StackTrace: 
[app-scripts]             preInstallFailure@http://192.168.1.64:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:50 
[app-scripts]             callbackFromNative@http://192.168.1.64:8100/cordova.js:293:57 
[app-scripts]             http://192.168.1.64:8100/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js:129:32 
[app-scripts]             wrapped@http://192.168.1.64:8100/build/vendor.js:110011:32 
[app-scripts]             runTask@http://192.168.1.64:8100/build/polyfills.js:3:10844 
[app-scripts]             invokeTask@http://192.168.1.64:8100/build/polyfills.js:3:16801 
[app-scripts]             n@http://192.168.1.64:8100/build/polyfills.js:3:66 
[app-scripts] [10:39:28]  console.error: [CodePush] An error occurred during sync. An error has occured while installing the package. 
[app-scripts]             Could not find start page in package.. StackTrace: 
[app-scripts]             preInstallFailure@http://192.168.1.64:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:50 
[app-scripts]             callbackFromNative@http://192.168.1.64:8100/cordova.js:293:57 
[app-scripts]             http://192.168.1.64:8100/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js:129:32 
[app-scripts]             wrapped@http://192.168.1.64:8100/build/vendor.js:110011:32 
[app-scripts]             runTask@http://192.168.1.64:8100/build/polyfills.js:3:10844 
[app-scripts]             invokeTask@http://192.168.1.64:8100/build/polyfills.js:3:16801 
[app-scripts]             n@http://192.168.1.64:8100/build/polyfills.js:3:66

**Comment by mbossX** [comment]
codepush not workd at dev mod. 
you just need release you app.

**Comment by alexandergoncharov** [comment]
Hi @quantosapplications,
Thanks for reporting!

It looks like you are using `--livereload` field for running app. @mbossX's note is correct. @quantosapplications could you please run app with release mode and let me know your results?

Please feel free to ask any questions.

**Comment by alexandergoncharov** [comment]
Hi @quantosapplications ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by jackie-d** [comment]
Same issued solved by testing it **without `--livereload`**.

related: https://github.com/microsoft/cordova-plugin-code-push/issues/459
