### ISSUE TITLE
On "deviceready" is never fired after 5 seconds after running Application.

### ISSUE THREAD

**Issue by jamesta696** [Microsoft/cordova-plugin-code-push#518]
![image](https://user-images.githubusercontent.com/14171094/55687813-452e8880-593f-11e9-8ca4-f70e6fcab2ae.png)

![image](https://user-images.githubusercontent.com/14171094/55687817-6c855580-593f-11e9-8a75-07abcabccc5f.png)

### Description

On Device Ready is never fired after 5 seconds after running Application.

### Additional Information

* cordova-plugin-code-push version: 1.11.17

* List of installed plugins:
code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-exclude-files 0.4.2 "Exclude Files"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

* Cordova version: 7.0.1
* iOS/Android/Windows version: 
Installed platforms:
  android 6.3.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  webos ~3.7.0
  windows ~5.0.0

* Does this reproduce on a debug build or release build?
Debug build gets this error of not receiving on "deviceready"

* Does this reproduce on a simulator, or only on a physical device?
Have not tried Simulator

**Comment by mbossX** [comment]
this is a cordova error, not about codepush, please search at cordova community.

**Comment by alexandergoncharov** [comment]
Hi @jamesta696,
Thanks for reporting and sorry for delay.

Yeah, @mbossX said correctly. It looks like Cordova issue. TO ensure it could you please try to remove `cordova-plugin-code-push` and test it again?

Please let me know your results or if you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @jamesta696 ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by ever-dev** [comment]
In my case, it worked fine after removing the code-push plugin.
Here's the list of plugins:
```
"devDependencies": {
    "code-push": "^3.0.1",
    "cordova-android": "^9.0.0",
    "cordova-ios": "^6.1.1",
    "cordova-plugin-advanced-http": "^3.1.0",
    "cordova-plugin-code-push": "^2.0.0",
    "cordova-plugin-deeplinks": "^1.1.1",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-zip": "^3.1.0"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-code-push": {},
      "cordova-plugin-deeplinks": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
```

Cordova version: 10
