### ISSUE TITLE
Failed to install 'cordova-plugin-media': CordovaError: Version of installed plugin: "cordova-plugin-file@4.3.3" does not satisfy dependency plugin requirement "cordova-plugin-file@^5.0.0".

### ISSUE THREAD

**Issue by crapthings** [microsoft/cordova-plugin-code-push#528]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

doesn't work with cordova-plugin-file new version ?

### Reproduction

cordova plugin add cordova-plugin-media or cordova-plugin-media-capture

these plugins require higher cordova-plugin-file version.

cordova-plugin-media
cordova-plugin-media-capture

**Comment by alexandergoncharov** [comment]
Hi @crapthings 
Thanks for reporting!

I'm sorry for delay and this error. 

Code-push plugin intently use 4.3.3 version of  cordova-plugin-file for compatibility for old versions of android.

I reproduced your error and update cordova-plugin-file manually. That resolved error and code-push continued to work :)

`cordova plugin remove cordova-plugin-file --force`
`cordova plugin add cordova-plugin-file@5.0.0`

Could you please test it and let me know your results.

**Comment by crapthings** [comment]
tried an empty cordova project, works. thanks~

**Comment by alexandergoncharov** [comment]
Glad to hear that.
Thanks for letting us know!
