### ISSUE TITLE
Reload fails after Webkit is terminated

### ISSUE THREAD

**Issue by alexhisen** [microsoft/cordova-plugin-code-push#529]
### Description

At least when using WkWebView, when app is running in the background and your code starts using more than 80% of CPU for more than 60s, iOS will terminate the Webkit.Webview process. There is code in Cordova that detects that the Webview has been terminated and it reloads the Webview.

However, if the app is loaded from a code-push update, then this reload fails with basically the same symptoms as in #424.

### Reproduction
You have to get iOS to terminate the Webkit.Webview process, then bring the app into foreground

### Additional Information
* cordova-plugin-code-push 1.11.17 
* cordova ios 5
* iOS 12
* definitely happens on debug build, probably release build as well
* physical device

**Comment by alexandergoncharov** [comment]
hi @alexhisen 
Thanks for reporting!

Sorry for delay.
I can't reproduce your issue. Could you please provide some dummy project with reproducing issue and reprosteps?

**Comment by alexhisen** [comment]
Are you not able to get Webview to get killed or for the reload to fail? I don't have any way to get Webview to be killed in a dummy app.
There are some unit tests in cordova-ios for checkAndReinitViewUrl that could perhaps be used. And there are some relevant discussions here:
https://github.com/apache/cordova-ios/pull/363
https://github.com/apache/cordova-ios/pull/418

**Comment by alexhisen** [comment]
Actually you should be able to crash the webview with the following line of javascript:
Array(1e8).fill('some string');
This will try to allocate an array with 100 million cells and memory will grow to 1GB+, at which point webview should crash. If for some reason not enough, can bump up to 1e9.

**Comment by alexandergoncharov** [comment]
Hi @alexhisen 
Sorry for delay. I tried the way what you proposed and also use infinity loop for overloading CPU. Unfortunately this wasn't influence on parameters of CPU and memory. So I can't terminate webview. 

Could you please specify what version of cordova-plugin-ionic-webview or cordova-plugin-wkwebview-engine you using?
Or could you please provide some dummy project with reproducing issue?

**Comment by alexhisen** [comment]
We are using wkwebview essentially at this commit point: https://github.com/apache/cordova-plugin-wkwebview-engine/commit/6f468f48735c5937f497e6a851901d4f68ce7da2 - it's slightly modified since the 1.1.4 release

And are you saying you can allocate 1Gb or 10GB of memory without WebView terminating?

**Comment by alexhisen** [comment]
@alexandergoncharov Are you saying you can allocate 1Gb or 10GB of memory without WebView terminating?

**Comment by alexandergoncharov** [comment]
Hi @alexhisen 
Sorry for delay!

I'm finally reproduced your issue and prepared draft fix:
https://github.com/microsoft/cordova-plugin-code-push/pull/538

Could you please test it?

**Comment by alexandergoncharov** [comment]
Hi @alexhisen 
I'm going to close this issue for now as I haven't heard from you in a while unfortunately and issue was fixed.
Please feel free to reopen it if you have any questions.

**Comment by alexhisen** [comment]
I can confirm that the Webview now reloads correctly after it crashes even when the app runs off a code-pushed update.

**Comment by alexandergoncharov** [comment]
@alexhisen , That's great! Thanks for letting us know.
