### ISSUE TITLE
IOS - App is ignoring new entries into code-push

### ISSUE THREAD

**Issue by dann95** [microsoft/cordova-plugin-code-push#530]
Hi guys!
### Description
Hi, i have a Cordova app that i use Code-push for update it, in the IOS version, i made a Code-push, but app never updates, looking for logs, i see that it prints "up to date" on IOS Console.

### Reproduction

Well, basically to sent the code-push, i did:

```bash
cordova platform add ios
``` 
Then set my distribution profile, and run:

```bash
code-push release-cordova <censured>-ios ios --deploymentName Production
```

in appcenter.ms site i can found the push in list:

![list-code-pushes](https://user-images.githubusercontent.com/9970959/57865735-820a5c80-77d4-11e9-9bf4-37c3a5ed54cc.png)

looking for the CodePushDeploymentKey of Production:
![deployment-keys](https://user-images.githubusercontent.com/9970959/57865781-99494a00-77d4-11e9-86a6-c9c312789eab.png)

And when inspecting app console output with IOS Console (http://lemonjar.com/iosconsole/), i see this:
![lemon](https://user-images.githubusercontent.com/9970959/57865857-b716af00-77d4-11e9-9d9b-f4a243aec6c1.png)

### Additional Information

* cordova-plugin-code-push version: ^1.11.18
* List of installed plugins: cordova-plugin-device, cordova-plugin-streaming-media, cordova-background-geolocation-lt, cordova-plugin-splashscreen, cordova-plugin-firebase, cordova-plugin-statusbar, cordova-plugin-local-notification, cordova-plugin-badge, cordova-plugin-customurlscheme, cordova-plugin-inappbrowser, cordova-plugin-network-information, cordova-plugin-file-transfer, cordova-plugin-zip, cordova.plugins.diagnostic, cordova-plugin-camera, cordova-plugin-vibration, cordova-plugin-audioinput, cordova-plugin-whitelist, cordova-plugin-splashscreen, cordova-plugin-file
* Cordova version: 8.1.2 (cordova-lib@8.1.1)
* iOS/Android/Windows version: IOS: ^5.0.1
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Physical device

**Comment by jacobg** [comment]
I'm also having this issue. It's been a few months since I did my last code push, and now I'm trying to do one on iOS, and checkForUpdate is not returning anything. I've check to see if I did something wrong, but it seems I'm doing everything right. Is there a code push service issue now?

**Comment by dann95** [comment]
Im having expected behaviour on Android, as i could investigate my app is using the right deployment key, and the release (code-push) exists on appcenter.ms, so i see no reasons why it dosn’t works, cause also with emulator and debug build, it works fine...

**Comment by dann95** [comment]
ping.....

**Comment by dann95** [comment]
ping @alexandergoncharov ...

**Comment by alexandergoncharov** [comment]
Hi @dann95 @jacobg 
Thanks for reporting!

I tried reproduce your issue but it works fine for me.
Could you please provide some dummy project with reproducing issue?

**Comment by alexandergoncharov** [comment]
Oh, yeah, We've been having some performance issues during peak hours (13:00 - 15:00 UTC+00) lately. We are working on resolving this situation but we have no ETA at the moment. Sorry for this issue.

**Comment by dann95** [comment]
@alexandergoncharov are u using a real app published on Apple Store, or are u using an emulator or debug provisioning build? Cause as i described above, on production published app, it dosn't works, but in emulator or debug provisioning build, works well..

**Comment by dann95** [comment]
I guess @jacobg app is production published app too..

**Comment by dann95** [comment]
@alexandergoncharov well, this is a bit hard to investigate, thinking with the premise that app must be production, and apple rules are boring to approve an app, isn't better if i give you my app name, you download it and on next release we can check all details?

**Comment by josecaodaglio** [comment]
Guys I am having this issue as well. It happens every time I tried so we could easily reproduce it. I would be more than happy one account credential so you could check it very quick. Any, any help is very welcomed.

**Comment by jacobg** [comment]
This is what the AppCenter support folks sent me. Interpret it as you wish:

Hi, we are currently working on the next version of CodePush (no breaking changes) that will fixes a bunch of the bugs people are seeing. We will come back and confirm this is fixed with the changes once we are done with that version.

**Comment by alexandergoncharov** [comment]
Hi all,

@dann95 , Could you please clarify it works correctly on local build(like with XCode)? If yes, could you please check that your deployment key and other settings configured correctly?

@josecaodaglio, could you please clarify your issue more detailed?

**Comment by dann95** [comment]
@alexandergoncharov 
> Could you please clarify it works correctly on local build(like with XCode)?

As i typed above, ON XCODE BUILD FOR DEBUG, it works fine, ON EMULATOR IN XCODE (there is no other) it works fine... on production build, it dosn't work.

>could you please check that your deployment key and other settings configured correctly?

As i show on first message, looking for output console, the keys matches with production keys, and the code-push release is at appcenter.ms

![image](https://user-images.githubusercontent.com/9970959/58661262-d269da00-82fd-11e9-88d1-0195a57f24d6.png)

![image](https://user-images.githubusercontent.com/9970959/58661272-d695f780-82fd-11e9-9442-a07b8a565ad8.png)

**Comment by alexandergoncharov** [comment]
I see, thanks for this info. It is strange that your release build can't update but your debug build can.
Could you please provide some dummy project with reproducing issue and reprosteps? I would like to reproduce it and debug.

**Comment by dann95** [comment]
@alexandergoncharov i guess we are not talking the same, if i give you a "sample" app, you still will not be able to test it. to reproduce the test, you must publish the app at Apple store, does it make sense for you?

**Comment by dann95** [comment]
Thats the Angular service used to update the app, when "deviceready" event from cordova is triggered, we call the method "onDeviceReady"
```typescript
import { getClock } from "@myapp/core/tools/utility";
import { Injectable } from '@angular/core';
import { BehaviorSubject } from "rxjs";
import {
    Window, IRemotePackage, DownloadProgress, ILocalPackage, InstallMode, CodePushCordovaPlugin
} from './cordova-plugins-definitions';

declare var window: Window;

@Injectable({
    providedIn: 'root'
})
export class UpdateService {

    private updated: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
    // State of notifyApplicationReady, run everytime app is opened first time.
    private released: boolean = false;

    constructor() {}

    onDeviceReady = async () => {
        this.releaseIfNeeded();
        this.checkForUpdate();
    };

    private releaseIfNeeded = () => {
        if (! this.released) {
            this.CodePush.notifyApplicationReady();
            this.released = true;
            console.log(`[COLMEIA-UPDATER] app ready`+getClock())
        }
    };

    private checkForUpdate = () => {
        console.log(`[COLMEIA-UPDATER] checking for updates`+getClock())
        this.CodePush.checkForUpdate(
            this.onUpdateCheck,
            this.onError
        );
    };

    private onUpdateCheck = (remotePackage?: IRemotePackage) => {

        if (! remotePackage) {
            console.log(`[COLMEIA-UPDATER] everything up to date..`+getClock())
            this.updated.next(true);
            return;
        }

        if (! remotePackage.failedInstall) {
            console.log(`[COLMEIA-UPDATER] update available with hash: ${remotePackage.packageHash}`+getClock())
            remotePackage.download(
                this.onPackageDownloaded,
                this.onError,
                this.downloadProgress
            )
        }

    };

    private downloadProgress = (progress: DownloadProgress) => {
        console.log(progress);
    };

    private onPackageDownloaded = (localPackage: ILocalPackage) => {
        localPackage.install(
            this.onInstallSuccess,
            this.onError,
            {
                installMode: (localPackage.isMandatory)
                    ? InstallMode.IMMEDIATE
                    : InstallMode.ON_NEXT_RESTART
            }
        );
        this.updated.next(true);
        console.log(`[COLMEIA-UPDATER] packaged downloaded... ${(localPackage.isMandatory) ? 'imediate install..' : 'install later..'}`)
    };

    private onInstallSuccess = () => {
        this.updated.next(true);
        console.log(`[COLMEIA-UPDATER] update success`+getClock())
    };

    private onError = (error) => {
        console.log(`[COLMEIA-UPDATER] update error, message: ${error}`+getClock())
    };

    private get CodePush(): CodePushCordovaPlugin {
        return window.codePush;
    }

    public subscribeToUpdateFinished(sub: (done: boolean) => void): void {
        this.updated.subscribe(sub);
    }
}
```

**Comment by dann95** [comment]
The code above is nothing so far from demonstrations of the plugin, and as i showed before, the releases occurred, and the deployment key is valid..

**Comment by josecaodaglio** [comment]
@alexandergoncharov My problem is basically the same what @jacobg described. 
- I release a code-push using production credentials (have checked this a lot)
- IOS SDK always states that there is no update no matter how many updates I made

I am more than available to give you my app password and you can check by yourself. 

Could we proceed this way?

Thanks a lot

**Comment by dann95** [comment]
ping @alexandergoncharov ...

**Comment by alexandergoncharov** [comment]
Hi @dann95 and @josecaodaglio.
Sorry for the delay.

It is a really strange issue. We had issues like this before but there were some other issues, which doesn't according to CodePush. Could you please try to make a new binary release to store? I'm not sure what reason for this issue can be for now.

@dann95, you said that I must to publish the app to App store to reproduce it but you also said that Prod build doesn't work. So, you can reproduce it on local production build?

Also, could you please provide your approaches to setup CodePush deployments? Is it just setup directly to `config.xml` file or there are some approaches with dynamically changing key according to build?

**Comment by josecaodaglio** [comment]
@alexandergoncharov 

I don't understand whether you are willing to solve the problem. I told you that I can reproduce the issue 100% of the times as long as you are willing to accept an user/pwd and see by yourself. I cannot see any simpler way to detected a problem other than accept this recommendation. It seems to me that you chose to ignore what I am proposing.

**Comment by alexandergoncharov** [comment]
@josecaodaglio I'm not ignoring your what you are proposing. I just would like to say that access to your binary version will not help me to investigate this issue unfortunately as It cannot provide me the source code of your app to debug.
Also, could you please provide your logs during update and have you tested it on release build?

**Comment by dann95** [comment]
Well, coming again to report.. Today we made another release.. 

after release code-push in cli, i repeated the instruction to release it again to check if appcenter mentions that release is identical to the last, and the result is:
![image](https://user-images.githubusercontent.com/9970959/59386437-0c46d180-8d3d-11e9-8ebd-6930370b30fd.png)

but, when querying from CLI to check the deployments, the result is:
![image](https://user-images.githubusercontent.com/9970959/59386478-22ed2880-8d3d-11e9-98f7-6963a04f094d.png)
the last release ocurred 12 days ago> As you can see this period matches with our conversations, but it shows no installation records..

```
Jun 12 17:41:56 iPhone-de-Dann MyAppName[464] <Notice>: [CodePush] Checking for update.
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_endpoint_flow_protocol_connected [C9.1 IPv4#4f93e676:443 in_progress channel-flow (satisfied)] Output protocol connected
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_connection_report_state_with_handler_locked [C9] reporting state ready
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Event [9:0x2801b8840]: 20, Pending(0)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TCP Conn Connected [9:0x2801b8840]: Err(16)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TCP Conn Event [9:0x2801b8840]: 1
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TCP Conn Event [9:0x2801b8840]: 8
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Handshake Complete [9:0x2801b8840]
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <720EB04F-9E71-4ED8-8ABF-E14CBDBF83D9>.<0> now using Connection 9
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_endpoint_flow_protocol_connected [C9.1 IPv4#4f93e676:443 ready channel-flow (satisfied)] Output protocol connected
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <720EB04F-9E71-4ED8-8ABF-E14CBDBF83D9>.<0> sent request, body D
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC Enabling TLS [11:0x2801bb300]
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TCP Conn Start [11:0x2801bb300]
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: [C11 Hostname#108234c8:443 tcp, url hash: 71499dfc, tls] start
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_connection_report_state_with_handler_locked [C11] reporting state preparing
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <CACB9290-1BE6-4209-A3E4-6726D4B7AF04>.<0> setting up Connection 11
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_endpoint_flow_protocol_connected [C11.1 IPv4#4f93e676:443 in_progress channel-flow (satisfied)] Transport protocol connected
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Event [11:0x2801bb300]: 1, Pending(0)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Event [11:0x2801bb300]: 2, Pending(0)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <720EB04F-9E71-4ED8-8ABF-E14CBDBF83D9>.<0> received response, status 200 content K
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <720EB04F-9E71-4ED8-8ABF-E14CBDBF83D9>.<0> response ended
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <720EB04F-9E71-4ED8-8ABF-E14CBDBF83D9>.<0> done using Connection 9
Jun 12 17:41:56 iPhone-de-Dann MyAppName[464] <Notice>: [CodePush] Reported status: {"status":0,"appVersion":"1.0.7","deploymentKey":"o1w86w9a_XXXXXXXXXXXXXXXXXXXXXXXXXX-d75ca83219ae","previousLabelOrAppVersion":null,"previousDeploymentKey":null}
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Event [11:0x2801bb300]: 11, Pending(0)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Event [11:0x2801bb300]: 14, Pending(0)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: System Trust Evaluation yielded status(0)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Trust Result [11:0x2801bb300]: 0
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <7FFDA2D6-D396-4ED7-9F18-1A5C2E3BD4E2>.<0> response ended
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <7FFDA2D6-D396-4ED7-9F18-1A5C2E3BD4E2>.<0> done using Connection 8
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_endpoint_flow_protocol_connected [C11.1 IPv4#4f93e676:443 in_progress channel-flow (satisfied)] Output protocol connected
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_connection_report_state_with_handler_locked [C11] reporting state ready
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Event [11:0x2801bb300]: 20, Pending(0)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TCP Conn Connected [11:0x2801bb300]: Err(16)
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TCP Conn Event [11:0x2801bb300]: 1
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TCP Conn Event [11:0x2801bb300]: 8
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TIC TLS Handshake Complete [11:0x2801bb300]
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <CACB9290-1BE6-4209-A3E4-6726D4B7AF04>.<0> now using Connection 11
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_endpoint_flow_protocol_connected [C11.1 IPv4#4f93e676:443 ready channel-flow (satisfied)] Output protocol connected
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <CACB9290-1BE6-4209-A3E4-6726D4B7AF04>.<0> sent request, body N
Jun 12 17:41:56 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: TCP Conn 0x2801bb840 canceled
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: [C10 Hostname#b18b1e17:5228 tcp, legacy-socket] cancel
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: [C10 Hostname#b18b1e17:5228 tcp, legacy-socket] cancelled
	[C10.1 <private> 192.168.137.11:49352<->IPv4#07639827:5228]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 1.061s, DNS @0.000s took 0.001s, TCP @0.002s took 0.109s
	bytes in/out: 366/465, packets in/out: 5/3, rtt: 0.093s, retransmitted packets: 0, out-of-order packets: 0
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.000s [C10 <private> Hostname#b18b1e17:5228 resolver] path:start
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.000s [C10 <private> Hostname#b18b1e17:5228 resolver] path:satisfied
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.000s [C10 <private> Hostname#b18b1e17:5228 resolver] resolver:start_dns
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.001s [C10 <private> Hostname#b18b1e17:5228 resolver] resolver:receive_dns
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.001s [C10.1 <private> 192.168.137.11:49352<->IPv4#07639827:5228 socket-flow] path:start
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.001s [C10.1 <private> 192.168.137.11:49352<->IPv4#07639827:5228 socket-flow] path:satisfied
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.002s [C10.1 <private> 192.168.137.11:49352<->IPv4#07639827:5228 socket-flow] flow:start_connect
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.110s [C10.1 <private> 192.168.137.11:49352<->IPv4#07639827:5228 socket-flow] flow:finish_connect
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.115s [C10 <private> Hostname#b18b1e17:5228 resolver] flow:finish_connect
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.115s [C10.1 <private> 192.168.137.11:49352<->IPv4#07639827:5228 socket-flow] flow:changed_viability
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 0.115s [C10 <private> Hostname#b18b1e17:5228 resolver] flow:changed_viability
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: 1.061s [C10] path:cancel
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_endpoint_flow_protocol_disconnected [C10.1 IPv4#07639827:5228 cancelled socket-flow (null)] Output protocol disconnected
Jun 12 17:41:56 iPhone-de-Dann MyAppName(libnetwork.dylib)[464] <Notice>: nw_connection_report_state_with_handler_locked [C10] reporting state cancelled
Jun 12 17:41:56 iPhone-de-Dann MyAppName[464] <Notice>: InitSystemService: Rehidratei o sistema e estou pronto
Jun 12 17:41:57 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <CACB9290-1BE6-4209-A3E4-6726D4B7AF04>.<0> received response, status 200 content K
Jun 12 17:41:57 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <CACB9290-1BE6-4209-A3E4-6726D4B7AF04>.<0> response ended
Jun 12 17:41:57 iPhone-de-Dann MyAppName(CFNetwork)[464] <Notice>: Task <CACB9290-1BE6-4209-A3E4-6726D4B7AF04>.<0> done using Connection 11
Jun 12 17:41:57 iPhone-de-Dann MyAppName[464] <Notice>: [CodePush] App is up to date.
```

Highlighting things about CodePush, we can see:
**Jun 12 17:41:56 iPhone-de-Dann MyAppName[464] <Notice>: [CodePush] Checking for update.
Jun 12 17:41:56 iPhone-de-Dann MyAppName[464] <Notice>: [CodePush] Reported status: {"status":0,"appVersion":"1.0.7","deploymentKey":"o1w86w9a_XXXXXXXXXXXXXXXXXXXXXXXXX-d75ca83219ae","previousLabelOrAppVersion":null,"previousDeploymentKey":null}
Jun 12 17:41:57 iPhone-de-Dann MyAppName[464] <Notice>: [CodePush] App is up to date.**
 

looking for our credentials in appcenter.ms:
![image](https://user-images.githubusercontent.com/9970959/59387293-34cfcb00-8d3f-11e9-9981-f31ea99118aa.png)

and to have no doubts about "am i using the right key?", i query deployments with deployment key in cli and:
![image](https://user-images.githubusercontent.com/9970959/59387808-74e37d80-8d40-11e9-8241-a5fd50cf5405.png)


I don't know what more do to help in the investigation, i just know we are facing this problem, and we depend of this service =/

**Comment by dann95** [comment]
and as you can see @alexandergoncharov in the last image, in Staging deployment, our device updates.. but on Production, no device updates =/

**Comment by dann95** [comment]
Querying Android app, in the CLI, we see normal behavior

![image](https://user-images.githubusercontent.com/9970959/59388081-3dc19c00-8d41-11e9-84c5-36087a6a1a6c.png)
both, staging and production releases are downloaded and updated in android devices...

So this problem occurs only in IOS and in Production (production key and applestore released app)..

**Comment by dann95** [comment]
repeating again , i could "update" the appcenter.ms version now it shows:
![image](https://user-images.githubusercontent.com/9970959/59389361-7fa01180-8d44-11e9-969b-c6ecbb1b976c.png)

but app still says "up to date"...

**Comment by alexandergoncharov** [comment]
Hi @dann95,
Thanks for this full info!

Could you please check your target-binary-version?
By your status reporting, you used `appVersion":"1.0.7"`. But target-binary-version of you update is `1.0.0`. It is semver expression that specifies the binary app version(s) this release is targeting.  Release with `1.0.0` target version can be installed on `1.0.7` binary version. It is implemented like so to Js code part all time will have the correct version of the native part. For more info please check this docs: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#target-binary-version-parameter

Could you please try to update this parameter and check if it fixes your issue?

**Comment by dann95** [comment]
Awesome, it solved the problem.. thats curious, cause even when app was released as 1.0.0 it didn't update.. thanks @alexandergoncharov

**Comment by dann95** [comment]
Hey @jacobg as u have the same problem of me, could u check your binary version, and your target version in config.xml and on code-push dashboard or cli-tool ?

**Comment by jacobg** [comment]
I haven't had a chance to check yet. It may be next week. But since they're talking about version numbers, I'm wondering:  My latest app that I had this issue on is version 2.10.0. I'm wondering if Code Push's version checking is semver-based or lexographical, and if it gets caught on the minor version 10? It's something I'll have to check.

**Comment by dann95** [comment]
@jacobg well, to have a safe update, im using:
```
code-push release-cordova appname-ios ios --deploymentName Production --targetBinaryVersion "*"
```
So i match every device, dosn't matter version, thats a problem only if you serve different versions, for different customers.. but to me solves my problem.

**Comment by jacobg** [comment]
I don't specify any version in the cli, which I think is supposed to just target the version in the build.

**Comment by dann95** [comment]
@jacobg i was doing the same, not specifying version, and that was the problem, so i started use:
```
--targetBinaryVersion "*"
```

**Comment by jacobg** [comment]
I never did that before. Was this a recent change of behavior?

**Comment by dann95** [comment]
dunno, i'm not from microsoft haha, and is not so old my app..

**Comment by josecaodaglio** [comment]
> @jacobg i was doing the same, not specifying version, and that was the problem, so i started use:
> 
> ```
> --targetBinaryVersion "*"
> ```

That solved my issues as well
