### ISSUE TITLE
BinaryHash is not equal to server packagehash

### ISSUE THREAD

**Issue by hzzcc** [microsoft/cordova-plugin-code-push#531]
### Description

Android first install will download full size update zip. 

Already run command `appcenter codepush release -a xxx/xxx -c platforms/android/app/src/main/assets/www -t ...`

Binary hash:
![image](https://user-images.githubusercontent.com/6861655/57913573-6e87f000-78bf-11e9-8eba-9c83766a123e.png)

Remote package hash:
![image](https://user-images.githubusercontent.com/6861655/57914172-bfe4af00-78c0-11e9-964f-e4d9d20f6c83.png)

BinaryHash is not equal to server packagehash, diff update is not work when first codepush

### Additional Information

* cordova-plugin-code-push version: 1.11.16
* List of installed plugins:
* Cordova version: 
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by hzzcc** [comment]
I figured out that my project static folder has .gitkeep file, and there are two postBuildExtras  because of imagepicker plugin.  So I removed .gitkeep, and add plugin "cordova-plugin-asset-manifest". These steps fix binary hash equals to remote package hash.

**Comment by hzzcc** [comment]
But the project still has problem,  when first upload my update to appcenter server,  I still got full size update zip. How the server diff remote package hash between binary hash ?

**Comment by alexandergoncharov** [comment]
Hi @hzzcc ,
Thanks for reporting!

About your last question: unfortunately, the first update will be downloaded fully because it isn't possible to make diff between CodePush releases and binary. It is possible to get diff between 2 CodePush releases. So, all nex update will be downloaded only changed part.

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by RascoApps** [comment]
I'm having the same issue. could it be caused by not having an update deployed yet?

**Comment by alexandergoncharov** [comment]
Hi @hzzcc,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
