### ISSUE TITLE
Update to cordova version 1.11.18

### ISSUE THREAD

**Issue by eternityBUG** [microsoft/cordova-plugin-code-push#533]
![image](https://user-images.githubusercontent.com/30195529/58367390-3319a100-7f11-11e9-88f4-a8cfc06d330f.png)

I need this version

**Comment by alexandergoncharov** [comment]
Hi @eternityBUG,
Thanks for reporting!

Could you please provide the link to this?

**Comment by eternityBUG** [comment]
[https://cordova.apache.org/plugins/?q=code-push](url)

thank you

**Comment by alexandergoncharov** [comment]
NPM already has `1.11.18` version of this plugin. You can add this with `cordova plugin add cordova-plugin-code-push` command. It adds the last version automatically.

Please let me know if it was helpful or you have any questions.

**Comment by eternityBUG** [comment]
Good thank you
