### ISSUE TITLE
Hot Code Push plugin is not installed. Doing nothing.

### ISSUE THREAD

**Issue by MTTTM** [microsoft/cordova-plugin-code-push#534]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

when  i  run  ‘code-push release-cordova test android -d "Staging" --des "描述"
’ at my cmd，it is  show message like:

Executing script found in plugin cordova-hot-code-push-local-dev-addon for hook "after_prepare": plugins\cordova-hot-code-push-local-dev-addon\scripts\afterPrepareHook.js
CHCP Local Development Add-on:
    Hot Code Push plugin is not installed. Doing nothing.

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "D:\forPerson\shop-mall-app\src-cordova\platforms\android\app\src\main\assets\www" directory to the "Staging" deployment of the "test" app.

**my  html5 code  likes:**

window.codePush.checkForUpdate(onUpdateCheck, onError);
 function onUpdateCheck(remotePackage) {
                if (!remotePackage) {
                    console.log("The application is up to date.");
                } else {
                    if (!remotePackage.failedInstall) {
                        console.log("There is an update available. Remote package:" + JSON.stringify(remotePackage));
                        console.log("A CodePush update is available. Package hash: " + remotePackage.packageHash);
                        remotePackage.download(onPackageDownloaded, onError, onProgress);
                    } else {
                        console.log("The available update was attempted before and failed.");
                    }
                }
            };

the  code  'The available update was attempted before and failed.' is  wolk  and  show  ant  my  crome  devTools  after i run my  debug  app  at my  android device.

**so,why  it  show  'Hot Code Push plugin is not installed. Doing nothing.' at my cmd**
**why  i  app  upload  fail.**

### Additional Information

* cordova-plugin-code-push version: 1.11.18
* List of installed plugins:
code-push 2.0.6 "CodePushAcquisition"
cordova-hot-code-push-local-dev-addon 0.4.2 "Hot Code Push Local Development Addon"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-code-push 1.11.18 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
* Cordova version:9.0.0

**Comment by alexandergoncharov** [comment]
Hi @MTTTM,
Thanks for reporting!

`cordova-hot-code-push-local-dev-addon` already depricated and we don't support any custom implementation of CodePush. My recommendation is asking the author of https://github.com/nordnet/cordova-hot-code-push-local-dev-addon or start using our official CodePish plugin for Cordova.  https://github.com/microsoft/cordova-plugin-code-push

Please feel free to ask any questions regarding `cordova-plugin-code-push` plugin.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @MTTTM,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
