### ISSUE TITLE
Ionic app not working properly after Code Push update

### ISSUE THREAD

**Issue by l3ender** [microsoft/cordova-plugin-code-push#536]
### Description

After pushing a Code Push update, the startup code in `AppComponent` is not running.

Our startup code contains logic to check for CodePush updates (among other things) and after a device gets an update, this code is no longer firing.

### Reproduction

I have created a sample app that shows the issue and put it [here](https://github.com/l3ender/code-push-issues). Follow the simple steps in README.md to set up the project and run/test. The issue is happened for both iOS and Android but my steps are for iOS. On Mac you can use the Console app to see output from app to confirm that startup code is not running.

Once the update happens, you will see that the startup logging is not showing any Code Push checks, in addition to any other logic being performed in `AppComponent`.

Also if you click the link in the sample app to "View App Details" you will see Cordova errors as it is not loading correctly.

### Additional Information

* cordova-plugin-code-push version: **1.11.18**
* List of installed plugins:
```
-> cordova plugin ls
code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-code-push 1.11.18 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-fingerprint-aio 1.7.0 "FingerprintAllInOne"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-secure-storage 3.0.2 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
```
* Cordova version:
```
"cordova-android": "8.0.0"
"cordova-browser": "6.0.0"
"cordova-ios": "5.0.1"
```
* iOS/Android/Windows version: **Latest (iOS 12.2)**
* Does this reproduce on a debug build or release build? **Both**
* Does this reproduce on a simulator, or only on a physical device? **Both**

Please take a look and advise. Thanks!

**Comment by alexandergoncharov** [comment]
Hi @l3ender 
Thank you for reporting and sample app!

I tried to reproduce your issue but the app still checks for new updates after other update has been applied. In other words `initializeApp` method in `app.component` is executed after updates.

Here is screenshot from my "View app details":

![UNADJUSTEDNONRAW_thumb_1](https://user-images.githubusercontent.com/13234108/58698084-3eeae480-83a3-11e9-9817-f0f36a404796.jpg)

Could you please provide Cordova errors from your "View app details"?

**Comment by l3ender** [comment]
Thanks for the reply. Can you share what steps you took to rebuild the app after you made a change? I'm wondering if my step of doing `ionic build` is not correct.

**Comment by alexandergoncharov** [comment]
Actually I just:

- Disable section for ios in build.json
- `ionic cordova build ios --buildFlag="-UseModernBuildSystem=0"`

   for build app and subsequent run it at xCode
- Change caption on `username-password.component`
 - `appcenter codepush release-cordova -a userName/appName -d deploymentName`

   for release update
- Re-run app for checking update
- Re-run app again after installing update

**Comment by l3ender** [comment]
After you changed the caption in the component, did you perform any other build step to regenerate web assets before doing `appcenter codepush` command?

**Comment by alexandergoncharov** [comment]
Hi @
Sorry for delay!

Oh, yeah, missed it. Sorry. After change js code and before executing `appcenter codepush release-cordova` command you have to prepare your platform folders, at least for Ionic apps. A codepush release will be taken from there. For this you need to build again your app
`ionic cordova build ios --buildFlag="-UseModernBuildSystem=0"`
or just run
`ionic cordova prepare ios`.

**Comment by l3ender** [comment]
Perfect, thanks!
