### ISSUE TITLE
[Question]: when running cordova prepare, is it prepared for release/production?

### ISSUE THREAD

**Issue by gaurav-chandra** [microsoft/cordova-plugin-code-push#545]
When running ```cordova prepare```, is it prepared for release/production? When we release for production, lot of files are uglified. Want to know if this is what is happening.

**Comment by alexandergoncharov** [comment]
Hi @gaurav-chandra,
Thanks for reporting!

From docs: 
```
Transforms config.xml metadata to platform-specific manifest files, copies icons & splashscreens, copies plugin files for specified platforms so that the project is ready to build with each native SDK.
```
Source: https://cordova.apache.org/docs/en/latest/reference/cordova-cli/#cordova-prepare-command

So, there is no build for an app. Prepare command can't be `release` or `production`. It just copies necessary files to a specific folder.

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by gaurav-chandra** [comment]
Hey @alexandergoncharov I saw the docs in more detail later and figured out that it will only prepare. The reason was that the code was not being compiled properly. I had to do other things for building. Thanks.

**Comment by alexandergoncharov** [comment]
@gaurav-chandra Perfect. Thanks for letting us know!
