### ISSUE TITLE
android studio simulator can check for updates but not download update files, update failed

### ISSUE THREAD

**Issue by liuxi198991** [microsoft/cordova-plugin-code-push#550]
### Description

android studio simulator can check for updates but not download update files, update failed.
if physical device is ok

### Additional Information

* cordova-plugin-code-push version: v1.11.20
* List of installed plugins:
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "code-push": "^2.0.7",
    "cordova-android": "^8.0.0",
    "cordova-plugin-code-push": "^1.11.20",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-file-transfer": "^1.6.3",
    "cordova-plugin-zip": "^3.1.0",

* Cordova version:
    "cordova": "9.0.0",
* iOS/Android/Windows version:
    Android 4.4
    Android 7.0
    Android 7.1.1
    Android 8.1
* Does this reproduce on a debug build or release build?
   All
* Does this reproduce on a simulator, or only on a physical device?
   android studio simulator update failed,physical device is ok

**Comment by ermik** [comment]
Android Studio enforces newer gradle versions which don’t support the project configurations that Cordova generates. Avoid opening Cordova projects in AS.

**Comment by liuxi198991** [comment]
> Android Studio enforces newer gradle versions which don’t support the project configurations that Cordova generates. Avoid opening Cordova projects in AS.

I just use the Android Studio simulator , use ionic cordova build android command Build APK，the Build APK run the Android Studio simulator，the Android Studio simulator can check for updates but not download update files，the APK run physical device is right
