### ISSUE TITLE
Unknown arguments: updateContents

### ISSUE THREAD

**Issue by alexcroox** [microsoft/cordova-plugin-code-push#559]
`
Error: Command 'codepush release-cordova -a Company/appname-ios updateContents 1.x.x -d Staging' failed with exception "Unknown arguments: updateContents 1.x.x"
`

This is taken straight from the documentation is it correct? Shouldn't an argument have a dash (-) before it?

**Comment by szh** [comment]
I believe the updateContentsPath argument is not used when using release-cordova

**Comment by alexcroox** [comment]
How do I specify a target version then? Or can it only be done via the web UI for Cordova applications?

**Comment by alexcroox** [comment]
Just found it in other docs 

--targetBinaryVersion
