### ISSUE TITLE
CodePush servers slow and unstable

### ISSUE THREAD

**Issue by ekrapfl** [microsoft/cordova-plugin-code-push#562]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

As described in several other bugs ([App Center #814](https://github.com/microsoft/appcenter/issues/814) and [React Native Code Push #1641](https://github.com/microsoft/react-native-code-push/issues/1641)) ,the CodePush servers are currently extremely slow and returning server errors randomly, breaking the app start up for many workflows.

I'm opening this issue here, because to make sure it is being tracked for the Cordova version as well, as it is definitely affected.

### Reproduction

See issues above.

### Additional Information

This is a server side problem.

**Comment by alexandergoncharov** [comment]
Hi @ekrapfl ,
Thanks for reporting and sorry for the delay!

Yeah, we had some server changes in that period. Right now all should work correctly.
So, I'm going to close this issue for now. Please feel free to reopen it if you have any questions or face this issue again.
