### ISSUE TITLE
Couldn't Send Request Error - Server Issue?

### ISSUE THREAD

**Issue by DrCorduroy** [microsoft/cordova-plugin-code-push#572]
Is there a sever issue for codepush? I received this from my bug tracker (clearly it connects to the internet and I've replaced the variables with placeholders below. ) This as working a few days ago.

An error occurred. Error: Couldn't send request to https://codepush.azurewebsites.net/updateCheck?deploymentKey=${deploymentKey}&appVersion=${appVersion}&packageHash=${packageHash}&isCompanion=${isCompanion}&label=${label}&clientUniqueId=${clientUniqueId}, xhr.statusCode = 0 was returned. One of the possible reasons for that might be connection problems. Please, check your internet connection

**Comment by digital-tcbs** [comment]
Same here! pls support

**Comment by apascual-pl** [comment]
same here

**Comment by brassier** [comment]
We are noticing the same.  We are getting 500 or 503 errors when checking for a code push update.  I sure hope someone from CodePush looks into this.  The App Center support seems very delayed.  The status page says everything is operational, which is not the case obviously.

**Comment by raphjutras** [comment]
Same here, code push not working anymore..! What is happening?

**Comment by dandouglas** [comment]
I have the same issue

**Comment by brassier** [comment]
I reached out to them via app center support.  Looks like they are aware of this issue now, which is good.
https://status.appcenter.ms/

**Comment by DrCorduroy** [comment]
The issue has been fixed.
