### ISSUE TITLE
An update is available, but it is being ignored due to have been previously rolled back.

### ISSUE THREAD

**Issue by iamtarun1993** [microsoft/cordova-plugin-code-push#585]
On first run the new updated code is running properly in an ionic app. 
but If I clear the android app from background and open the app again, I can't see the latest update. It is showing me the old code. Please reply how to fix ASAP.

**Comment by pawan-logiciel** [comment]
any update on this I am getting the same issue

**Comment by iamtarun1993** [comment]
This is resolved.
In `deviceready` you need to run `codePush.notifyApplicationReady();`
Ref: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cordova#installoptions

**Comment by pawan-logiciel** [comment]
Thanks @iamtarun1993  this works for me
