### ISSUE TITLE
UIWebView - Apple warning

### ISSUE THREAD

**Issue by bbialas** [microsoft/cordova-plugin-code-push#586]
### Description

Apple Store initial review process is sending a warning after submitting the app to Apple Connect.

> Dear Developer,
> We identified one or more issues with a recent delivery for your app, "XXXX". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

The reason is, that in Code-Push code there are still references to **UIWebView**.

Would be great to be able to decide, which view engine to use on the compile level.
Other cordova plugins are already working on that, for example cordova-plugin-inappbrowser:
https://github.com/apache/cordova-plugin-inappbrowser/pull/584/files

### Reproduction

Build iOS app and submit to Apple Store.

### Additional Information

* cordova-plugin-code-push version: 1.12.0
* Cordova version: 9.0.0
* Does this reproduce on a debug build or release build? All.

**Comment by EmeryGuillaume** [comment]
Hello,

I've got the same issue.

The cordova-ios 5.1.0 platform introduced a flag (WK_WEB_VIEW_ONLY) in order to be able to output a wkwebview instead of a uiwebview at compilation time (as I understand it).
Some plugins are likely to move to this behavior (there is a pending PR on the inappbrowser repository)

It would be great if the code-push code can also use this flag.

**Comment by bbialas** [comment]
@code-push-team, any updates on this one?

**Comment by bbialas** [comment]
Refresh... anyone?

**Comment by ludufre** [comment]
Looks like the project is abandoned ...

**Comment by ludufre** [comment]
https://github.com/microsoft/cordova-plugin-code-push/pull/588

**Comment by l3ender** [comment]
This is a serious issue that needs input from the Microsoft team. It looks like there is a PR with the fix (https://github.com/microsoft/cordova-plugin-code-push/pull/588); can someone from the Microsoft team please review, merge, and publish?

**Comment by zvihersh** [comment]
same issue here. any progress on this?

**Comment by brassier** [comment]
Looks like this issue may start causing iOS app submissions to be rejected in April ( 8 days)?
https://developer.apple.com/news/?id=12232019b

**Comment by sinnkirou** [comment]
Have the same issue, is there any progress in this?

**Comment by brassier** [comment]
Looking like [the fix for this ](https://github.com/microsoft/cordova-plugin-code-push/pull/588)got merged in.  Such good news!

**Comment by l3ender** [comment]
We referenced 1.12.1 with the fix and are no longer receiving the issue when uploading to App Store Connect. Thank you for taking care of this.

**Comment by ermik** [comment]
This has been resolved.

@alexandergoncharov please close.

**Comment by alexandergoncharov** [comment]
Cool, Thanks @ermik!
