### ISSUE TITLE
IOS The update contents failed the data integrity check

### ISSUE THREAD

**Issue by sefasaid** [microsoft/cordova-plugin-code-push#587]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I have success on android. But in ios platform I'm getting error: The update contents failed the data integrity check

First i run app in emulator and codepush runs success and update app success. After second codepush release it gives this error. 

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

### Additional Information

* cordova-plugin-code-push version: 
cordova-plugin-code-push 1.12.0 "CodePush"
* List of installed plugins:
code-push 3.0.1 "CodePushAcquisition"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.0 "cordova-android-support-gradle-release"
cordova-base64-to-gallery 4.1.3 "base64ToGallery"
cordova-clipboard 1.3.0 "Clipboard"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-code-push 1.12.0 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-document-viewer 0.9.11 "SitewaertsDocumentViewer"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-facebook4 5.0.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.5 "cordova-plugin-filepath"
cordova-plugin-filepicker 1.1.6 "File Picker"
cordova-plugin-fingerprint-aio-keychain 1.7.0 "FingerprintAllInOne"
cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-keychain-touch-id 3.2.1 "TouchID and Keychain"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.2 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.3.1 "cordova-support-google-services"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
* Cordova version:
9.0.0 (cordova-lib@9.0.1)
* ionic version
5.4.6 
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
both builds
* Does this reproduce on a simulator, or only on a physical device?
simulator

(The more info the faster we will be able to address it!)

I checked downloaded sum
shasum -a 256 /Users/sefasaid/Library/Developer/CoreSimulator/Devices/4B47DAE7-CECC-4156-91B2-D1C25F2B8ABF/data/Containers/Data/Application/F3DC4626-8F03-4C64-8841-D981F3A76676/Library/NoCloud/codepush/download/update.zip 
5497f82541959af34cacbcf5c602e5a1568d37f966ab0d16b8fdab5428a1b23f  /Users/sefasaid/Library/Developer/CoreSimulator/Devices/4B47DAE7-CECC-4156-91B2-D1C25F2B8ABF/data/Containers/Data/Application/F3DC4626-8F03-4C64-8841-D981F3A76676/Library/NoCloud/codepush/download/update.zip

it was wrong with 
{"appVersion":"1.3.140","deploymentKey":"xxx","description":"hata testi 2","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/sEVQP0ggLYwUI_ylV2UAOPyJGMfPe6d4e62a-46b8-44e3-82a2-494b3daf842b","isMandatory":false,"label":"v14","packageHash":"014b06d95b89c087a0f09390447d9fa5feb11d2ac15506c2ca109a1ce6a2ed9b","packageSize":830132,"failedInstall":false

**Comment by sefasaid** [comment]
when i run again with xcode codepush does full update and it is success
but when i deploy new udpate from codepush it fails again

**Comment by sefasaid** [comment]
[this](https://github.com/microsoft/cordova-plugin-code-push/pull/584) pull request solves the problem

**Comment by sefasaid** [comment]
when the cannel is change it won't work again

**Comment by mastersmind** [comment]
Did you found any solution?

**Comment by alexandergoncharov** [comment]
Hi @sefasaid ,
Thanks for reporting and sorry for the delay.

I merged this PR https://github.com/microsoft/cordova-plugin-code-push/pull/584 that fix your issue. 
Could you please test your app with the latest code-push plugin version?

@mastersmind , that PR should fix this issue.

So, as PR was merged I'm going to close this issue for now. Please feel free to reopen it if you have any questions or if you faced this issue again.

Thanks,
Alexander
