### ISSUE TITLE
existing code push update download fails and crashes on android app install

### ISSUE THREAD

**Issue by dwolner** [microsoft/cordova-plugin-code-push#597]
### Description

As of this month, my cordova android app installs fine when there is no update to download. Then when I upload a code push (with just a visual string change), this app downloads and installs the code push no problem, I see the change. But when I reinstall the app when an update already exists, the app tries to download the update on initial launch and crashes. It then refreshes and tries again to download upload and crashes back to the home screen.

Anyone seen something like this or have any ideas on how I can pin down this issue? Thanks o/

### Reproduction

Install app on android device, no code push update released.
App executes, no problems.
Release code push update.
Reopen app and is downloads and installs code push, no problems.
Delete app from device.
Reinstall app, tries to download code push update, restarts, tries again and crashes.

### Additional Information

* cordova-plugin-code-push version: 1.12.0
* List of installed plugins:
cordova-plugin-spinner
cordova-plugin-statusbar
cordova-plugin-file
cordova-plugin-file-transfer
cordova-plugin-zip
cordova-plugin-camera
cordova-plugin-code-push
cordova-plugin-inappbrowser
cordova-plugin-network-information
cordova-plugin-splashscreen
nl.x-services.plugins.backgroundaudio
cordova-plugin-background-download
com.mutatefile.plugin
cordova-plugin-document-viewer
cordova-plugin-file-opener2
cordova-plugin-facebook4
cordova-plugin-googleplus
ionic-plugin-deeplinks
cordova-plugin-purchase
cordova-plugin-smartlook

* Cordova version: 9.0.0
* Cordova-android version: ^8.0.0
* Android version on device: 7.0
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Physical device

One final note, I have a custom handler for code push updates installMode and a loader which may be related to the issue:
```
var storage = window.localStorage
        var isAppUpdated = storage.getItem('isAppUpdated')
        var spinner = false

        function syncStatusCallback(syncStatus, cb) {
            k('syncStatusCallback: ', syncStatus)

            if (syncStatus === SyncStatus.UPDATE_INSTALLED) {
                storage.setItem('isAppUpdated', 'true')
                spinner = false
                if (SpinnerPlugin) SpinnerPlugin.activityStop()
                window.codePush.restartApplication()
            } else if ([SyncStatus.UP_TO_DATE, SyncStatus.ERROR, SyncStatus.UPDATE_IGNORED].indexOf(syncStatus) > -1) {
                if (spinner) {
                    if (SpinnerPlugin) SpinnerPlugin.activityStop()
                }
                cb()
            }
        }

        function checkForUpdate(cb) {
            k('checking for codepush update: ', isAppUpdated)

            k('spinner? ', spinner)
            if (!spinner) {
                spinner = true
                k('SpinnerPlugin: ', SpinnerPlugin)
                if (SpinnerPlugin) SpinnerPlugin.activityStart("Loading...", {
                    dimBackground: true
                })
            }

            if (!isAppUpdated) {
                window.codePush.sync((status) => {
                    syncStatusCallback(status, () => {
                        cb()
                    })
                }, {
                    installMode: InstallMode.IMMEDIATE
                })
            } else {
                window.codePush.sync((status) => {
                    syncStatusCallback(status, () => {
                        cb()
                    })
                })
            }
        }
```

**Comment by Krasavinigor** [comment]
Hi @dwolner! 
Sorry for the delay, and thank you for reporting!  

Could you please test the plugin without custom modification? Is it still work?

**Comment by Krasavinigor** [comment]
Hi @dwolner! 

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Igor
