### ISSUE TITLE
Cordova WKWebview Support

### ISSUE THREAD

**Issue by tropperstyle** [Microsoft/cordova-plugin-code-push#60]
I am pulling out my hair trying to find a Cordova solution that will allow for hot code updates, as well as take advantage of the vastly more performant WKWebview. I have tried the following plugins without much luck. I realize since each of these plugins alter the way the application code is loaded, compatibility may not be so trivial. Has there been any experimental setups? Any insight or at least nudges in the right direction would be much appreciated!

https://github.com/Telerik-Verified-Plugins/WKWebView
https://github.com/apache/cordova-plugin-wkwebview-engine
https://github.com/apache/cordova-plugins/tree/master/wkwebview-engine-localhost

Not sure if this helps, but here is a related issue with a similar plugin to code push https://github.com/nordnet/cordova-hot-code-push/issues/42

**Comment by lostintangent** [comment]
Hey @tropperstyle! Unfortunately, we haven't tested CodePush with either of these plugins, so I couldn't offer any immediate insights, but I can definitely take a look at it on Monday and see what kind of issues exist and what workarounds we could prescribe. We definitely need this scenario to work.

Stay tuned and sorry for the inconvenience!

**Comment by tropperstyle** [comment]
Any update on this? Looks like `cordova-plugin-wkwebview-engine` is a core plugin now so hopefully that makes hooking in a bit easier

**Comment by lostintangent** [comment]
I ended up having to look into a few other issues today unfortunately. I'll definitely get to this in the next day or two.

**Comment by tropperstyle** [comment]
Thanks for the update. I appreciate the time and effort!

**Comment by tropperstyle** [comment]
Sorry to nag, but any movement on this? I can attempt to hack it together but I don't have much experience on the native side.

**Comment by lostintangent** [comment]
I started looking at it today and will hopefully finish up the analysis tomorrow of what we'll need to change in our plugin to support it. It doesn't look too difficult so far.

**Comment by dozoisch** [comment]
Any update on this :)? I was thinking about migrating to wkwebview too!

**Comment by lostintangent** [comment]
@dozoisch We've got this work scheduled for the upcoming week. We did the analysis to figure out what was necessary to support this, so we'll try to get a plugin update published within the week and we'll ping you when it's out.

**Comment by tropperstyle** [comment]
Looking forward to this! This is currently a blocker for my app. I rely heavily on native scrolling via `webkit-overflow-scrolling: touch;` and UIWebView has very buggy behavior that disables all scroll functionality. But under WKWebView, it scrolls without flaw.

**Comment by lostintangent** [comment]
@tropperstyle Ok thanks for letting us know this is a blocker for you. That helps us up the priority of getting this done. Thanks for the patience!

**Comment by lostintangent** [comment]
@tropperstyle @dozoisch #69 was just sent out to enable the use of the WKWebView. Just to clarify, are you both looking to use https://github.com/apache/cordova-plugin-wkwebview-engine, or are you using one of the other plugins?

**Comment by tropperstyle** [comment]
Sweeet! Correct, I am using latest cordova (6.0.0) with the official cordova-plugin-wkwebview-engine plugin

**Comment by dozoisch** [comment]
@lostintangent I was looking to use that exact plugin :)!

**Comment by lostintangent** [comment]
@dozoisch Perfect, thanks for confirming!

**Comment by lostintangent** [comment]
This issue has been resolved in the `1.5.1-beta` release which we just tagged on this repo, and we're about to publish to NPM. Let us know if you run into any issues with it. Thanks for your patience @tropperstyle @dozoisch!

**Comment by dozoisch** [comment]
Awesome :)!

**Comment by kenvunz** [comment]
@lostintangent Any chance that `code-push` can support the `wkwebview-engine-localhost` also? My app relies on it to provide WKWebView support for iOS 8

This is the errros I got from the log:
```

Cheers

**Comment by lostintangent** [comment]
@kenvunz We haven't investigated that plugin yet, but we can definitely look into it! From the logs you mentioned, I'm guessing that the plugin modifies the start page in the config.xml to point at a something like http://localhost/index.html, which confuses CodePush. I'll take a look at this tonight and see what it would look like for us to support it. Stay tuned!

**Comment by kenvunz** [comment]
legend 👍

**Comment by lostintangent** [comment]
@kenvunz So I investigated this, and I understand the limitations here (it's what I had suspected before), but I need to evaluate the best fix for this. I'm going to open up a new issue to track this, and we'll hopefully be able to get to it next week. Thanks for sending out the feedback!
