### ISSUE TITLE
[Android] Update prompt should be modal/non-dismissable by touch

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/cordova-plugin-code-push#61]
I'm not an Android user so I can't say whether this behavior is idiomatic or not across apps. But, it's a little odd that the update prompt isn't actually modal, and can be dismissed by touching anywhere outside of the prompt, as opposed to requiring the end-user to actually touch the accept or ignore buttons. I could kind of see this behavior making sense in the optional-update scenario, where dismissing the dialog is effectively an alternative way of ignoring the update, but in the case of a mandatory update, it seems like the prompt should be modal since you have no choice but to continue. Would an end-user ever expect to dismiss a non-modal dialog, only to have it actually force the behavior as if they accepted the prompt?

We had received feedback about this behavior on the React Native plugin, and ended up making the dialog modal/non-dismissable, so the end-user needed to click a button when an update prompt is displayed. Personally, I like this behavior, and its consistent with how we behave on iOS.

**Comment by dlebu** [comment]
@lostintangent I agree that for mandatory updates the dialog should not be dismiss-able. For the React implementation, what happens when the user presses the back button? Is the dialog dismissed?

**Comment by lostintangent** [comment]
Nope, I believe the back button is "disabled" until you touch one of the dialog's buttons.

**Comment by lostintangent** [comment]
The Cordova dialog plugin doesn't appear to have a way to customize this, and I don't think it's a high pri issue, so I'm going to close this for now. We also haven't heard any customer complaints, plus we're de-emphasizing the use of the update dialog anyways (since Apple doesn't allow it), so I'm comfortable closing this until we hear a customer request for a fix.
