### ISSUE TITLE
Adding cordova-plugin-file-transfer on plugin dependency

### ISSUE THREAD

**Issue by darron1217** [microsoft/cordova-plugin-code-push#630]
This plugin uses `cordova-plugin-file-transfer` plugin, but this is not specified on dependency.

**Comment by ermik** [comment]
`cordova-plugin-file-transfer` is deprecated since Cordova 5.0 and will be removed in #513.

**Comment by alexandergoncharov** [comment]
Hi @darron1217,
Thanks for reporting!

Yeah, thanks @ermik. We already merged https://github.com/microsoft/cordova-plugin-code-push/pull/513.
So, `cordova-plugin-file-transfer` removed from `cordova-plugin-code-push`.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by darron1217** [comment]
Great! Thanks :)
