### ISSUE TITLE
cordova.js not found

### ISSUE THREAD

**Issue by export-mike** [Microsoft/cordova-plugin-code-push#67]
Hi I'm finding that after running: 
```code-push release app-android build/www/ 0.11.1 --deploymentName Staging```

I get the following error:
file:///data/data/bundle.app.name.id/files/codepush/deploy/versions/8sds645e6325b1bfcac0181c396d377a21946f764526cd7cd0480c6c2a47d9a/www/cordova.js Failed to load resource: net::ERR_FILE_NOT_FOUND

cordova.js seems to be requested from the codepush path, how do I fix this? do I need to set cordova.js path to ../../../../../www/cordova.js ?

**Comment by export-mike** [comment]
version: 1.5.0-beta

**Comment by lostintangent** [comment]
@export-mike Arw you attempting to release your app's root www folder? If so, then that wouldn't contain the Cordova.js file. If you take a look at the [docs](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/README.md#releasing-updates), we show examples of the exact command you need to run to release to CodePush. Specifically, you need to make sure to be releasing the "prepares" Android and/or iOS specific www folder, which would include the Cordova.js file.

Let us know how that goes!

**Comment by export-mike** [comment]
I see! that makes sense, we have a custom gulp command that controls this so it appears to be this thats not doing prepare correctly. so you're saying platforms/android/platform_www is the directory we need to be publishing?

**Comment by export-mike** [comment]
I see, looking at wrong folder: changed to platforms/android/assets/www/ thanks. :+1:

**Comment by lostintangent** [comment]
Awesome, thanks for confirming!
