### ISSUE TITLE
[CodePush]  Could not access local package. Stage:undefinedError code: undefined

### ISSUE THREAD

**Issue by PatrickGunawan** [Microsoft/cordova-plugin-code-push#675]
### Description

Hi all, I'm facing a strange issue.

We have been using cordova code push without issue on a project for over 1 year now.

Yesterday, I tried releasing a new minor fix via code push and suddenly it is no longer working. The error message is below.

Has anyone faced this before or maybe knows what might be causing it?

### Reproduction

Couldn't reproduce the bug in other projects.

### Additional Information

1. Error Message: `[CodePush]  Could not access local package. Stage:undefinedError code: undefined`
2. `"@ionic-native/code-push": "^5.26.0",`
3. `"cordova-plugin-code-push": "^1.12.4",`

**Comment by ludufre** [comment]
Update to cordova-plugin-code-push 2.0.0 to see if works.

**Comment by PatrickGunawan** [comment]
This fixed it!
