### ISSUE TITLE
CrossWalk WebView support

### ISSUE THREAD

**Issue by tropperstyle** [Microsoft/cordova-plugin-code-push#75]
First of all, thank you so much for [adding WKWebView support](https://github.com/Microsoft/cordova-plugin-code-push/pull/69) which bumps iOS modern specs. This is a ticket for achieving the same thing for the Android platform. I am trying to get this working with [Crosswalk Project](https://crosswalk-project.org/) and the specifically the [cordova webview plugin](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview).

**Comment by lostintangent** [comment]
@tropperstyle Good call! Thanks for creating the issue to track this. We'll try to get to this within the next few days. The fix for iOS ended up being pretty simply, so hopefully the same will be true for Android. I'll update this issue with more details as we have them.

**Comment by qianjun22** [comment]
@tropperstyle I have verified that the [Crosswalk WebView Cordova Plugin](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) works with Code Push Cordova Plugin without any changes required. Please reopen this issue if you run into integration problems.
