### ISSUE TITLE
The remote package does not contain a download URL. 

### ISSUE THREAD

**Issue by gregor-srdic** [Microsoft/cordova-plugin-code-push#80]
If I create and install a new version of my application with Ionic for android including cordova-plugin-code-push 1.5.1-beta "CodePush", 
**BEFORE ** I release any updates via code-push, I get the following error when client invokes  window.codePush.sync():

`Checking for update.`
`[CodePush] An update is available. {"failedInstall":false}`
`Downloading package.`
`[CodePush] Downloading update package`
`[CodePush]  The remote package does not contain a download URL.`
`[CodePush] An error occurred during sync.`
`An error occured while checking for updates `

It should return SyncStatus.UP_TO_DATE. When I release an update, it updates, and then it works normal, even if there are no new updates.

**Comment by lostintangent** [comment]
@gregor-srdic You mention that you're using 1.5.1-beta of the plugin, but the logs you included seem to indicate that you're using the latest bits from GitHub. Could you help clarify which version of CodePush you're using so that I can try to repro this issue? Thanks!

**Comment by lostintangent** [comment]
@gregor-srdic Could you try re-installing the CodePush plugin by running the following commands in your project's directory?

1. `cordova plugin rm cordova-plugin-code-push` 
2. `cordova plugin add cordova-plugin-code-push`

We had a dependency issue that I believe we just fixed and should resolve this issue.

**Comment by lostintangent** [comment]
I'm going to close this issue for now since I believe it has been fixed using the above recommendation, but please re-open it if you continue experiencing problems. Thanks!

**Comment by gregor-srdic** [comment]
@lostintangent thanks for your reply. Ionic plugin list displays `cordova-plugin-code-push 1.5.1-beta "CodePush"` and this is also written in plugin.xml. I installed it using `ionic plugin add cordova-plugin-code-push`. 

I believe removing and readding the plugin did in fact fix the issue, thanks!

**Comment by veti-io** [comment]
This is showing up again with code push ^1.9.0-beta and cordova-plugin-code-push version ^1.9.4-beta with Ionic v3.10.2, Angular 4.1.2.

**Comment by sergey-akhalkov** [comment]
Hi @veti-io, thanks for reaching us. Would you have a chance please to create [new issue ](https://github.com/Microsoft/cordova-plugin-code-push/issues/new) and provide us much info as possible so we would able to investigate it and help you?

**Comment by leobudima** [comment]
@veti-io I'm getting the same, but see that no new issue has been reported - were you able to solve this somehow?

**Comment by kinggolf** [comment]
@leobudima I ran into same exact issue today with cordova-plugin-code-push ^1.9.5-beta. This is on an Ionic project that I was upgrading from 2.x to 3.x. I removed node_modules, platforms, and plugins folders and reinstalled/added from scratch, including individual plugins one-by-one, and re-ran. Now error is gone and getting "App is up to date". Thanks Cordova team!
