### ISSUE TITLE
sample application

### ISSUE THREAD

**Issue by sowsan** [Microsoft/cordova-plugin-code-push#82]
Hello I'm trying the sample application and testing it with VS Android simulator. First, can we use simulator for testing the codepush ?

My app identifies that there is an update when I click update button then its error out. I can see that file is getting downloaded by debugging the Index.JS

function (downloadProgress) {
                console.log("Downloading " + downloadProgress.receivedBytes + " of " + downloadProgress.totalBytes + " bytes.");
            });

Error is captured here

     case SyncStatus.ERROR:
                        app.displayMessage("An error occured while checking for updates");
                        break;

Thanks for your help !

Regards,
Sowmyan

**Comment by dlebu** [comment]
Hi @sowsan. You can definitely test the sample application using the VS Android emulator. Can you attach a debugger (chrome, for example) to the Android emulator and look at the logs? We should be able to get more information from there.

**Comment by sowsan** [comment]
Thanks for your prompt response. I'm using VS 2015 and does it automatically attach the debugger to the emulator ? I can step in the JS code. Thanks for your help !

**Comment by dlebu** [comment]
Perfect, if you can step in the JS code you are already debugging. If you open up the debugging console, you should see the more details before the `An error occurred while checking for updates` message.

**Comment by sowsan** [comment]
great. Thanks for the pointer dlebu :) 

Here is what I'm seeing in the JS console. Any idea what could be going wrong with unzipping ?

[CodePush] Installing update package ...
codePushUtil.js (37,17)

[CodePush]  Could not unzip package. -1
codePushUtil.js (41,17)

**Comment by sowsan** [comment]
I can also see that download was success before that unzipping error message. Here is the complete details.

Checking for update.
index.js (58,33)
Uncaught TypeError: Cannot call method 'querySelector' of null
index.js (84,0)
[CodePush] An update is available. {"appVersion":"1.1.0","deploymentKey":"oz1KwJ04pTtGT1WSiAt6n-8v8b1SVJp1B9WRl","description":"","downloadUrl":"https://codepush.blob.core.windows.net/storagev2/2b6T6urxSm3JWwNxFX1TcjMQxyUQVJp1B9WRl","isMandatory":false,"label":"v2","packageHash":"db20c0aab2b57de6c81a293584a39890d5af36f6a59567971201805c4c883b66","packageSize":1121,"failedInstall":false}
codePushUtil.js (37,17)
Alerting user.
index.js (61,33)
Current window: file:///android_asset/www/index.html
Downloading package.
index.js (64,33)
[CodePush] Downloading update package ...
codePushUtil.js (37,17)
Downloading 1068 of 1121 bytes.
index.js (75,25)
Downloading 1121 of 1121 bytes.
index.js (75,25)
[CodePush] Package download success: {"deploymentKey":"oz1KwJ04pTtGT1WSiAt6n-8v8b1SVJp1B9WRl","description":"","label":"v2","appVersion":"1.1.0","isMandatory":false,"packageHash":"db20c0aab2b57de6c81a293584a39890d5af36f6a59567971201805c4c883b66","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
codePushUtil.js (37,17)
Installing update
index.js (67,33)
[CodePush] Installing update package ...
codePushUtil.js (37,17)
[CodePush]  Could not unzip package. -1
codePushUtil.js (41,17)
[CodePush] An error occurred during sync.
codePushUtil.js (41,17)

**Comment by dlebu** [comment]
What tool did you use to zip up the file? You should not manually zip it, as the code push CLI does this automatically for you. I took a look at your zip (the url is in the logs) and it seems like it is zipped twice. [Here](https://github.com/Microsoft/cordova-plugin-code-push#releasing-updates) are the details on how to release an update using the CLI.

**Comment by sowsan** [comment]
I'm pretty new to this space :) . I have used the below method for pushing only changes in my index.html file
code-push release CordovaCodePush index.html "*" -d Production

That link doesn't have some eg: which is making me confused :) , thanks for your help !

**Comment by dlebu** [comment]
First, make sure you run `cordova prepare` after your changes.
Then, you should point it to the platforms `www` folder after like this:

`code-push release CordovaCodePush ./CordovaCodePushProject/platforms/android/assets/www 1.0.0 --deploymentName Production`

**Comment by sowsan** [comment]
Thanks , I have ran it and was following the same article. If you are suspecting more than one update files, anyway to clean it out and keep only one ?

**Comment by sowsan** [comment]
I have done it once again for testing not sure if that also going to be an issue. 

C:\Users\sowmyans\Documents\Visual Studio 2015\Projects\CordovaCodePush>code-push release CordovaCodePush ./CordovaCodePush/platforms/android/assets/www 1.1.0
Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "./CordovaCodePush/platforms/android/assets/www" directory to the "Staging" deployment of the "CordovaCodePush" app.

**Comment by dlebu** [comment]
@sowsan We do expect multiple files. The command will zip the whole `/platforms/android/assets/www` folder. All files are needed, so no cleaning necessary.

**Comment by sowsan** [comment]
Thank you so much. Did a complete new packaging to Staging this time instead of Production and it works fine. Thank you !

**Comment by dlebu** [comment]
Glad it worked out, thanks for using CodePush!
