### ISSUE TITLE
Deps not installed with no platforms

### ISSUE THREAD

**Issue by dylanvdmerwe** [Microsoft/cordova-plugin-code-push#91]
When running
> cordova plugin add cordova-plugin-code-push

No dependencies (code-push, cordova-plugin-file-transfer, etc.) are installed if there are no platforms added to the cordova project. 

```
ionic plugin add cordova-plugin-code-push
Fetching plugin "cordova-plugin-code-push" via npm
Running command: "C:\Program Files\nodejs\node.exe" c:\Users\dylan.vdmerwe\Projects\GraduateApp\hooks\after_plugin_add\010_register_plugin.js c:\Users\dylan.vdmerwe\Projects\GraduateApp
Saving plugin to package.json file
```

The plugins are installed when a platform is added. But I believe the deps should be installed regardless of any platform being added.

Remove plugin process should work the same way.

**Comment by geof90** [comment]
I think this has to do with the way the Cordova plugin acquisition system works, not with CodePush. I'm interested to know what your use case is for this though. What would be the impact of not having the deps installed if no platforms are added to the project yet and therefore you can't run it?

**Comment by dylanvdmerwe** [comment]
For source control:
1. Checkout an existing project. Platform folder are normally not committed. 
2. Do some work.
3. Install code-push plugin.
4. Commit. 

I would expect all plugins to be installed at this point so that they are committed.

Developer 2:
1. Pulls latest version
2. Does some work. 
3. Adds a platform.
4. Commits after testing. 

Developer 2's changelog now includes all the code-push deps that were installed on adding the platform. This can also cause conflicts and issues for developer 3 if they happened to do the same thing.

**Comment by geof90** [comment]
I see. Note that this issue is already tracked on Cordova CLI's JIRA: https://issues.apache.org/jira/browse/CB-4922?jql=project%20%3D%20CB%20AND%20text%20~%20%22dependencies%20no%20platform%22

**Comment by geof90** [comment]
I'm closing this for now since it is not actionable for us. Feel free to reopen if you have any better suggestions on how we can workaround this problem!
