### ISSUE TITLE
Build instead of Prepare

### ISSUE THREAD

**Issue by dylanvdmerwe** [Microsoft/cordova-plugin-code-push#92]
Normally `cordova prepare` would be enough however, for example, Ionic 2 requires a compilation step to compile (using gulp) TypeScript and SCSS to create the www directory. 

When using the `code-push release-cordova` command it runs `cordova prepare` for you, however with Ionic 2 no new changes would be compiled into the platform's www directory. 

Maybe think about running a complete `cordova build` step in order to ensure all scripts and everything is ready for the appropriate platform for the release-cordova command?

**Comment by geof90** [comment]
That makes sense. I guess one way we could get it to work could be a CLI flag eg. `code-push release-cordova --build`, if `--build` is provided, it runs `cordova build` instead of `cordova prepare`?

**Comment by dylanvdmerwe** [comment]
Sounds good to me!

**Comment by lostintangent** [comment]
So does Ionic 2 add before/after build hooks to Cordova which trigger your Gulp scripts? If so, it definitely seems like a great solution for us to allow triggering `cordova build` instead of `cordova prepare` in the `release-cordova` command.

**Comment by dylanvdmerwe** [comment]
Yes, ionic 2 only triggers an update of the platform's www folder on `build` not `prepare`.

**Comment by lostintangent** [comment]
OK cool, we'll take care of this change this week. Apologies for the inconvenience!
