### ISSUE TITLE
[CodePush] 400: An update check must include a deployment key and provide a semver-compliant app version.

### ISSUE THREAD

**Issue by candidodmv** [Microsoft/cordova-plugin-code-push#95]
I followed the steps described on the project site, and I'm getting this error, what this means?

**Comment by dtivel** [comment]
What is the version of your app (not the update)?  If the app version is not [semver-compliant](http://semver.org/), you'll get that error.

Also, did you put your deployment key in your app?  Is your app using Cordova or React Native?

For Cordova apps instructions are [here](https://github.com/Microsoft/cordova-plugin-code-push#getting-started).  For React Native apps instructions are [here](https://github.com/Microsoft/react-native-code-push#getting-started).

**Comment by dtivel** [comment]
Sorry, I missed that your app is using Cordova.  I saw your original post on the code-push repo and it didn't register until now that reposting here meant it's a Cordova app.

**Comment by candidodmv** [comment]
Thanks @dtivel, problem was the version number

**Comment by dtivel** [comment]
No problem.  Glad I could help.  Thanks.
